### ISSUE TITLE
you need more reasons than the single one you have

### ISSUE THREAD

**Issue by connaryscott** [circleci/circleci-docs#1002]
This issue is about <https://circleci.com/docs/1.0/cant-follow/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/cant-follow.md>)

I cannot follow a project however your single reason is not my reason and this job is a snowflake in behavior that needs another explanation.

**Comment by ryanwohara** [comment]
I recommend reaching out to support in that case.
