### ISSUE TITLE
What should the permissions be for step 1?

### ISSUE THREAD

**Issue by kidbrax** [circleci/circleci-docs#1003]
This issue is about <https://circleci.com/docs/enterprise/docker-builder-config/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_ccie/docker-builder-config.md>)

What should the permissions be for step 1?

**Comment by ryanwohara** [comment]
Any user with sudo access as per the source of the script:

```
	sh_c='sh -c'
	if [ "$user" != 'root' ]; then
		if command_exists sudo; then
			sh_c='sudo -E sh -c'
		elif command_exists su; then
			sh_c='su -c'
		else
			cat >&2 <<-'EOF'
			Error: this installer needs the ability to run commands as root.
			We are unable to find either "sudo" or "su" available to make this happen.
			EOF
			exit 1
		fi
	fi
```
