### ISSUE TITLE
Unclear working_directory reference.  No mention of build environment variables.

### ISSUE THREAD

**Issue by gorzell** [circleci/circleci-docs#1012]
This issue is about <https://circleci.com/docs/2.0/local-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-jobs.md>)

It's unclear what the reference to `working_directory` was to.  Eventually I figured out it was in the circle config.

Also there is no mention of how to set or use build environment variables, these are require for my build to run and seem like an import part of the circle environment that is missing for local execution.

**Comment by michelle-luna** [comment]
Hi,

Thanks for this feedback, sorry for the late reply, the answer for env vars is the following:

https://discuss.circleci.com/t/how-to-set-env-vars-for-local-builds-using-circleci-2-0/12714

"We don't yet have an ideal solution for that, but there is a workaround. Define which vars you want to export in a file within your repository (don't commit it - just have it in the directory) and set BASH_ENV to that filename in your config.yml. The file will be automatically sourced on each command as long as BASH_ENV is correct."

I have added this workaround and committed a change to make the working_directory reference more clear in the local-builds doc.

Regards,
Michelle
