### ISSUE TITLE
Missing Flag for Google Compute Engine deployment 

### ISSUE THREAD

**Issue by JulienMalige** [circleci/circleci-docs#1018]
This issue is about <https://circleci.com/docs/1.0/google-cloud-platform/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/google-cloud-platform.md>)

To deploy on Google Compute Engine, the `gcloud compute copy-files` will try to generate a ssh key but will lock on `Enter passphrase (empty for no passphrase): `.

**the `--quiet` flag seems to solve the issue**.

> This command ensures that the user's public SSH key is present in the project's metadata. If the user does not have a public SSH key, one is generated using ssh-keygen(1) (if the --quiet flag is given, the generated key will have an empty passphrase).

(https://cloud.google.com/sdk/gcloud/reference/compute/copy-files)

Im not the only one concerned:
http://stackoverflow.com/questions/43305517/how-to-deploy-from-circleci-to-google-compute-engine/43698612#43698612

Thanks

**Comment by sha1sum** [comment]
FYI: Documentation has been PR'd for 2.0 GKE deployment. I did also include the `--quiet` flags for each `config set` command.

#1073

**Comment by michelle-luna** [comment]
Hi,

Thanks for this feedback, much appreciated, I have approved merge of #1073
For the 1.0 document, if the change still needs to be made, let me know exactly where to add the flag and I will update it (but I see --quiet in the file already, so maybe it is already fixed?)

Regards,
Michelle
