### ISSUE TITLE
Mention that volumes can't be used with docker-compose

### ISSUE THREAD

**Issue by Psykar** [circleci/circleci-docs#1019]
This issue is about <https://circleci.com/docs/2.0/docker-compose/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/docker-compose.md>)

As per https://discuss.circleci.com/t/docker-compose-yml-and-volume-mounts/10043/8
Some more info: https://discuss.circleci.com/t/using-docker-compose-in-2-0/9492/10

**Comment by michelle-luna** [comment]
Thanks for opening this issue, I assume from the thread we should also mention about port forwarding? If you agree, I'll add a note to the docker-compose article about these limitations for now and try to put some more details around them in future revisions.

**Comment by Psykar** [comment]
Haven't tested port forwarding myself, but it does look as though it's not possible. 

The two possible workarounds are using the `executorType: machine` as mentioned, but for volumes at least you can just copy data in to the docker instance manually. using `docker cp`
