### ISSUE TITLE
Executable Permissions for sh scripts using Continuous Deployment

### ISSUE THREAD

**Issue by audiolion** [circleci/circleci-docs#1020]
This issue is about <https://circleci.com/docs/1.0/introduction-to-continuous-deployment/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/introduction-to-continuous-deployment.md>)

I was following this guide and ran into a `permission denied exit code 126` when I followed the doc exactly and had a `./my-script.sh` under the command. I had to run `- chmod -x my-script.sh` before I could run it.

**Comment by michelle-luna** [comment]
Thanks for this feedback, I will add a note about this exit code and mention chmod -x of the files before the example if you agree.

**Comment by audiolion** [comment]
👍 sounds good to me.

**Comment by ryanwohara** [comment]
Alternatively you can prefix it with `bash`, i.e., `bash ./my-script.sh`

**Comment by audiolion** [comment]
also `+x` not `-x`, but I think `bash ./my-script.sh` is the right answer here
