### ISSUE TITLE
Incorrect Yarn Docs

### ISSUE THREAD

**Issue by mgartner** [circleci/circleci-docs#1024]
All the OS versions say `n/a` but `yarn` is supported in Ubuntu 14.04.

https://circleci.com/docs/1.0/yarn/

**Comment by felicianotech** [comment]
This is the problem: https://github.com/circleci/circleci-docs/commit/900897fef1b1ecd691a7dd407026e66c2a0ad959#diff-992354a1328175b1b05dfe6ae0d2f285

@mgartner Thank you for pointing this out. Fix coming shortly.
