### ISSUE TITLE
Step was canceled

### ISSUE THREAD

**Issue by senterright** [circleci/circleci-docs#1037]
This issue is about <https://circleci.com/docs/2.0/language-go/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-go.md>)

I have followed the docs pretty closely but I am getting a "Step was canceled" step in my "Start service" 
```
      - run:
          name: Start service
          command: server
          background: true
```
 Here's the output from the build step:
```
#!/bin/bash -eo pipefail
server
Running server on port 3000...
/go/src/github.com/senterright/timeframer
Step was canceled
```

it's a server and here's the snippet of startup:
```
// Startup starts the webserver, right now it's both for rest and UI navigation
func Startup(mode string) {
	session := db.NewSession("localhost")
	database := session.DB("timeframer")
	appdb, _ := db.NewTFDBM(session, database)

	fmt.Println("Running server on port 3000...")
	// get gorilla/mux router for UI
	r := mux.NewRouter()
	setHandlers(r, appdb)
	l, _ := net.Listen("tcp", ":3000")
	// Run on port 3000 declare port and pass in the router
	if !strings.Contains(mode, "test") {
		http.Serve(l, handlers.LoggingHandler(os.Stdout, r))
	}
}
```
Here's the build if you guys want to snoop around: https://circleci.com/gh/senterright/timeframer/16

**Comment by keybits** [comment]
Thanks for reporting this. The best place to get help with issues not directly related to docs is on our community forums: https://discuss.circleci.com/

I took a quick look at this but I'm not sure what the cause is.

**Comment by kiramclean** [comment]
Did you ever figure out what the problem was? I have a similar issue.. I need to spin up a server to run in the background for tests but it gets killed sometimes.

**Comment by kirillgroshkov** [comment]
similar problem!

**Comment by ccopto** [comment]
similar problem here!!

**Comment by renaudguerin** [comment]
Same here with the Google Cloud Pub/Sub simulator

**Comment by jcoyne** [comment]
I'm also having the same problem.

**Comment by awatson1978** [comment]
Please reopen.  Community forums keep closing these threads because users are unable to diagnose and resolve.

**Comment by soundofjw** [comment]
Same hosting ES server. :/

**Comment by MockArch** [comment]
```- sleep 5```   did you guys get a change to add sleep command when your running background process

**Comment by bjm88** [comment]
we are also seeing this, its marked background,  a build step that takes a little time, 1-2min happens first and then the server run command, but seems like this step canceld comes later...no other information....any ideas?
