### ISSUE TITLE
The Java image doesn't seem to exist and the link returns a 404.

### ISSUE THREAD

**Issue by gorzell** [circleci/circleci-docs#1057]
This issue is about <https://circleci.com/docs/2.0/circleci-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/circleci-images.md>)

**Comment by keybits** [comment]
Thanks for reporting this. The link is now fixed and the images are available from the 'tags' page. (We'll update the description soon)
