### ISSUE TITLE
RE: jekyll/_docs/docker.md

### ISSUE THREAD

**Issue by cjmurphy42** [circleci/circleci-docs#107]
The instructions for attaching no longer work.

This did
https://jpetazzo.github.io/2014/03/23/lxc-attach-nsinit-nsenter-docker-0-9/

but it seems like overkill.

**Comment by felicianotech** [comment]
Can you provide the instructions/steps that you are already using?

**Comment by felicianotech** [comment]
Hi @cjmurphy42,

Any response? Have you tried the command in Docs with our recent images? The Ubuntu 14.04 container image has been updated twice since this Issue has been opened.

**Comment by cjmurphy42** [comment]
I tried using 
sudo lxc-attach -n "$(docker inspect --format '{{.Id}}' $MY_CONTAINER_NAME)" -- bash -c $MY_COMMAND

to bash into a running container but I was unable to get it to work.

**Comment by keybits** [comment]
Sorry we never got back to you about this. We've been working hard on CircleCI 2.0, now in private Beta (https://circleci.com/beta-access/), which has much more complete Docker integration. The CircleCI1.0 Docker support and docs won't be updated as we're encouraging all customers using Docker to try out 2.0.
