### ISSUE TITLE
Documentation on running jobs locally does not mention version requirement for Docker

### ISSUE THREAD

**Issue by devurandom** [circleci/circleci-docs#1071]
A friend of mine uses Ubuntu 17.04, which comes with `Docker version 1.12.6, build 78d1802`. Trying to run `circleci build` results in `Error response from daemon: client is newer than server (client API version: 1.30, server API version: 1.24)`.

My assumption is that the Picard image contains a Docker client which is too new for this host. However, the [documentation on running jobs locally](https://circleci.com/docs/2.0/local-jobs/) does not mention a version requirement and the `circleci` script does not complain about the version of the Docker daemon, either.

it would be nice if the documentation would mention version requirements and the `circleci` script would check them, before beginning the build. Alternatively, the the Docker client in the Picard image could be downgraded to a more compatible version.

See-Also: https://discuss.circleci.com/t/circleci-picard-image-contains-too-recent-docker-client/12750

**Comment by michelle-luna** [comment]
Hi,

Thanks for this post, I looked at the discuss thread and I'm not sure if there is still a change needed in the docs that would have helped you or if this was a separate issue that is now fixed, let me know and I will add some info to cover this if it is appropriate.

Thanks,
Michelle

**Comment by smart-alek** [comment]
@michelle-luna I also read through the discuss thread, and it looks like this issue can be safely closed. @devurandom do let us know if you think the docs could be clearer on this point, and we'll be happy to reopen. :)
