### ISSUE TITLE
macOS image appears to be out of date

### ISSUE THREAD

**Issue by daveanderson** [circleci/circleci-docs#1083]
This issue is about <https://circleci.com/docs/1.0/build-image-macos/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/build-image-macos.md>)

The fact that Xcode 8.3.1 is installed on the macOS image is otherwise documented but it is _not_ clear what version of ruby or other tools are installed by default on the latest macOS image as the above file has not been updated.

**Comment by michelle-luna** [comment]
Hi,

Thanks for this feedback, are you saying that the 1.0/build-image-macos page should have this information added or that the content of the manifest (https://circleci.github.io/macos-image-tests/) is out of date? 

Thanks,
Michelle

**Comment by michelle-luna** [comment]
this is fixed
