### ISSUE TITLE
No example for cache usage

### ISSUE THREAD

**Issue by web-bert** [circleci/circleci-docs#1102]
There seems to be clear lack of examples in the docs. How about showing how a restore_cache works with a save_cache?

This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

**Comment by michelle-luna** [comment]
Hi,

Thanks for this comment on the beta caching doc, below is a config from a discuss post that uses save and restore with some comments, in case it helps you. Let me know and I'll add it to the doc.

-M

version: 2

jobs:
  build:
    working_directory: /home/circleci/ytb

    docker:
      - image: yourtradebase/ruby:2.3-node-phantomjs-0.0.1
        environment:
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/mysql:5.6

    steps:
      - checkout
      - run: cp config/{database_circleci,database}.yml

      # Run bundler
      # Load installed gems from cache if possible, bundle install then save cache
      # Multiple caches are used to increase the chance of a cache hit
      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ .Branch }}
            - gem-cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache-{{ .Branch }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache
          paths:
            - vendor/bundle

      - run: bundle exec rubocop
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rake factory_girl:lint

      # Precompile assets
      # Load assets from cache if possible, precompile assets then save cache
      # Multiple caches are used to increase the chance of a cache hit
      - restore_cache:
          keys:
            - asset-cache-{{ .Branch }}-{{ checksum "VERSION" }}
            - asset-cache-{{ .Branch }}
            - asset-cache
      - run: bundle exec rake assets:precompile
      - save_cache:
          key: asset-cache-{{ .Branch }}-{{ checksum "VERSION" }}
          paths:
            - public/assets
            - tmp/cache/assets/sprockets
      - save_cache:
          key: asset-cache-{{ .Branch }}
          paths:
            - public/assets
            - tmp/cache/assets/sprockets
      - save_cache:
          key: asset-cache
          paths:
            - public/assets
            - tmp/cache/assets/sprockets


      - run: bundle exec rspec
      - run: bundle exec cucumber

**Comment by michelle-luna** [comment]
I've updated the caching document and added the full example.

**Comment by web-bert** [comment]
👍

**Comment by simoniong** [comment]
Hi, all, i just wonder if any one could tell me where is the "VERSION" file, how could i generate the "VERSION" file so that I could make the proper cache in asset precompile
