### ISSUE TITLE
Is docker-layer-caching.md used anymore?

### ISSUE THREAD

**Issue by lag13** [circleci/circleci-docs#1105]
I stopped looking at the docs for a little while and when I came back I noticed that I couldn't find reference to the `reusable` option attached to the `setup_remote_docker` command:

```
- setup_remote_docker:
    reusable: true
```

That is documented in https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/docker-layer-caching.md. Is this no longer supported? Or is it just hard to find and I'm not seeing it?

Thanks.

**Comment by michelle-luna** [comment]
Hi,

I assume this is supported for 2.0 beta (I made an unrelated change to docker-layer-caching.md recently and there was no indication that reusable: true had been removed), reusable: false is the default. Let me know if I'm misunderstanding your comment.

Thanks,
Michelle

**Comment by lag13** [comment]
Hey, I guess my main question is what links to this file? Since I couldn't seem to find it anymore in the docs. If I do a `grep -r docker-layer-caching *` I don't see any hits.

**Comment by lag13** [comment]
So is there a link pointing to this file anywhere in the docs?

**Comment by lag13** [comment]
nevermind about this. I think at this point the docs have changed around so much that this is no longer relevant.
