### ISSUE TITLE
Git conflict artifact on 2.0 ruby page

### ISSUE THREAD

**Issue by etki** [circleci/circleci-docs#1113]
Hi.  
It seems that there is unresolved conflict somehow committed on [2.0 page for ruby](https://circleci.com/docs/2.0/language-ruby/). You can search for HEAD to find it on the HTML page, but sadly i couldn't find where 2.0 docs are in the repository.

**Comment by michelle-luna** [comment]
I found it, thank you for letting us know. FYI 2.0 doc files are in the ../jekyll/cci2 directory in the repo.

Regards,
Michelle

**Comment by michelle-luna** [comment]
fixed.
