### ISSUE TITLE
Docker Storage Driver Configs

### ISSUE THREAD

**Issue by stutefish** [circleci/circleci-docs#1120]
This issue is about <https://circleci.com/docs/enterprise/docker-install/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_ccie/docker-install.md>)

`
sudo sed -i 's/docker daemon/docker daemon --storage-driver=overlay/' \
   /usr/lib/systemd/system/docker.service \
`

That file does not exist. There are copies of *docker.service* at */etc/system/multi-user.target.wants/* and */lib/systemd/system/*, but neither of these have a  `docker daemon` directive to be modified.

What is CircleCI's current recommendation for setting a Docker storage driver when provisioning Docker builders?

**Comment by felicianotech** [comment]
@bellkev @GERey Do either of you know the solution to this?

**Comment by GERey** [comment]
Hi @stutefish , Thanks for your patience. Iirc, you might need to create that file, but anyways we recommend following the instructions at https://docs.docker.com/storage/storagedriver/overlayfs-driver/ . We included the sed line to have an easy way to change the storage driver, but it doesn't matter how you change the storage drive to us. We'll look at revising these docs soon.
