### ISSUE TITLE
Cassandra CircleCI Image Not Listed

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1121]
The Cassandra CircleCI Docker image is not listed in [CircleCI Images](https://circleci.com/docs/2.0/circleci-images/).

This was pointed out by a customer [in CircleCI Discuss](https://discuss.circleci.com/t/using-official-docker-images/13196/3?u=felicianotech).

**Comment by ryanwohara** [comment]
It's actually not a convenience image and that's why it is undocumented
We published a single version 7 months ago and I don't recall why https://hub.docker.com/r/circleci/cassandra/tags/
