### ISSUE TITLE
circleci v2 error when installing dependencies with node:8

### ISSUE THREAD

**Issue by doxiaodong** [circleci/circleci-docs#1122]
https://circleci.com/gh/doxiaodong/darlin-react/77?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by felicianotech** [comment]
Hi,

If you're having issues, I would suggest posting about it in [CircleCI Discuss](https://discuss.circleci.com/). If you think there's a bug, you can use the `Bug Reports` category.

GitHub Issues for this repo is issues specifically with the Docs website.

**Comment by briangonzalez** [comment]
Here's a link where you can find the discussion:

https://discuss.circleci.com/t/npm-install-error-that-isnt-reproducing-in-a-local-docker-container/13085/10
