### ISSUE TITLE
How can I do this in CircleCI 2.0?

### ISSUE THREAD

**Issue by henrich-m** [circleci/circleci-docs#1138]
This issue is about <https://circleci.com/docs/1.0/ssh-between-build-containers/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/ssh-between-build-containers.md>)

This "feature" is available in version 1.0 but isn't available in 2.0 and this is the main reason for us to not upgrade. When it will be available?

**Comment by ryanwohara** [comment]
This is not supported in 2.0 and is not on the roadmap (to the best of my knowledge). The solution is to use Workflows and Workspaces to aggregate your artifacts.
