### ISSUE TITLE
Ubuntu 14 Window Manager

### ISSUE THREAD

**Issue by eric-simonton-sama** [circleci/circleci-docs#1146]
This issue is about <https://circleci.com/docs/1.0/browser-debugging/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/browser-debugging.md>)

Until recently I was using the Ubuntu 12 image and the instructions for `Interact with the browser over VNC` worked well. However, on Ubuntu 14 it harder because there doesn't seem to be any way to move, close, or resize windows. They are drawn without any decorations. Is there some trick to get a usable window manager? (And if so, that could be helpful to include in this documentation.)

**Comment by ryanwohara** [comment]
That's really good feedback. I'll include my 2.0 solution here for reference before we update any docs:

```
ssh -p PORT ubuntu@IP_ADDRESS -L 5902:localhost:5901 # To connect via SSH
sudo apt install vnc4server metacity
vnc4server -geometry 1280x1024 -depth 24
export DISPLAY=:1.0
metacity &
firefox &
```
