### ISSUE TITLE
"persist_to_workspace" is not written in configuration-reference

### ISSUE THREAD

**Issue by MulticolorWorld** [circleci/circleci-docs#1154]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>

"persist_to_workspace" field in workflows reference isn't written in configuration-reference

**Comment by michelle-luna** [comment]
Thank you, I have a PR up for this https://github.com/circleci/circleci-docs/pull/1170

-Michelle

**Comment by MulticolorWorld** [comment]
Your pull request about this issue is merged.  Are you planning on closing this issue?

**Comment by michelle-luna** [comment]
Yes, it can be closed, you reopened it, so I thought I should leave it to you to close.

Thanks,
Michelle

**Comment by MulticolorWorld** [comment]
I closed this issue by mistake 5 days ago. But I think it should be closed by you, so I reopen issue.
Sorry.
