### ISSUE TITLE
Java language guide is misleading about which Ubuntu versions have Play Framework

### ISSUE THREAD

**Issue by tsleyson** [circleci/circleci-docs#1155]
This issue is about <https://circleci.com/docs/1.0/language-java/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/language-java.md>).

It seems that Play Framework is not actually installed on Ubuntu 14.04 instances, only on 12.04 instances. This is not mentioned anywhere on the page. The text above the chart at the bottom says "CircleCI supports Apache Ant, Play Framework, Gradle, and Apache Maven out of the box", which makes it sound like it's supported on both 12.04 and 14.04. There is no mention anywhere on the page that the available tools are different between the two build images. 

While it would be nice if the chart itself were updated to make it clear which tools are available on which version, at the very least a warning along the lines of "Available tools might differ between build image versions" would be appreciated. I could have saved two hours trying to figure out why Play wasn't installed on my build image.

**Comment by michelle-luna** [comment]
Thanks for taking time to let us know, sorry about that. I have a PR for the note about play framework on 14.04 and the general warning with a link.

**Comment by tsleyson** [comment]
@michelle-luna I appreciate it! Cheers.
