### ISSUE TITLE
CircleCI 2.0 escapes dollar sign characters ('$') in environment values (undocumented change in behavior).

### ISSUE THREAD

**Issue by jfreidin** [circleci/circleci-docs#1159]
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>)

When I use CircleCI 1.0 I have to escape ('\\') any dollar sign characters ('$') in the environment variable value it order to avoid variable substitution (documented).
When I use CircleCI 2.0 if I use \\$, then I get \\$ in the environment variable value and it breaks.
Unfortunately I'm in transition and some branches have a CIrcleCI 1.0 yml file and others have a CircleCI 2.0 yml file.
I see no way to make it work for both branches.

**Comment by ndintenfass** [comment]
This sounds like it might be a bug rather than a documentation issue - I filed a ticket in our internal system for the bug, and I'm going to close this issue in the docs repo. I put a link to this issue in the ticket, so it should get updated when it's fixed..
