### ISSUE TITLE
Visibility for documentation around Docker image order, executor 

### ISSUE THREAD

**Issue by JadedEvan** [circleci/circleci-docs#1176]
This issue is about <https://circleci.com/docs/2.0/glossary/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/glossary.html>)

I think there needs to be more discussion in the examples and documentations of the "Primary Container" section on this page. We were spinning our wheels trying to figure out why the new 2.0 build was not working - only to discover that the build runs on the first image specified in the list. 

I don't think that this is abundantly clear and don't recall seeing that in other spots of the documentation. I imagine this may be a big roadblock for others - anything you can do to increase the visibility around this condition would be helpful!

**Comment by michelle-luna** [comment]
Thanks for this feedback I have PR #1178 for this.

**Comment by michelle-luna** [comment]
This content was added to several docs to make it more clear.
