### ISSUE TITLE
RE: jekyll/_docs/test-metadata.md - Add Node section

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#119]
Brought up by Kunal.

**Comment by drazisil** [comment]
See https://github.com/circleci/circleci-docs/pull/180, but I would be happy to play with and do write ups for other node test runners if you have requests.

**Comment by drazisil** [comment]
@felicianotech  was this resolved by https://github.com/circleci/circleci-docs/pull/180, or did you still want/need more?
