### ISSUE TITLE
Missing link to building-docker-images in the navigation docs menu

### ISSUE THREAD

**Issue by elpddev** [circleci/circleci-docs#1198]
This issue is about <https://circleci.com/docs/2.0/building-docker-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/building-docker-images.md>)

I can't seems to find a link. I got to the document only from the glossary page:

> Remote Docker
> Feature that enables building, running and pushing images to Docker registries from within a Docker executor job. Learn more.

**Comment by michelle-luna** [comment]
Ah, it is under Deployment in the menu. I will move that category up, to make it connected to the other sections. Thanks for this feedback.
