### ISSUE TITLE
Unable to start Elasticsearch server after installing specific version

### ISSUE THREAD

**Issue by artspool-nyc** [circleci/circleci-docs#1200]
This issue is about <https://circleci.com/docs/1.0/installing-elasticsearch/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/installing-elasticsearch.md>)

I've been following your instructions for installing a specific version of Elasticsearch (5.4.1) as outlined in your documentation, and everything goes fine until the final step of checking to make sure that elasticsearch is running. After running `sleep 10 && wget --waitretry=5 --retry-connrefused -v http://127.0.0.1:9200/`, I'm getting:

```
--2017-06-27 20:55:26--  http://127.0.0.1:9200/
Connecting to 127.0.0.1:9200... failed: Connection refused.
Retrying.
```

This retries 20 times before giving up with `exit code 4`. Do you know how I can get the elasticsearch server running so I can run my tests?

**Comment by jsmecham** [comment]
You need to update your configuration to point to Java 8, as Elasticsearch 5 requires it. See https://discuss.circleci.com/t/using-openjdk-8/68/5 for the necessary configuration options.
