### ISSUE TITLE
Refer to user-defined env vars

### ISSUE THREAD

**Issue by binkley** [circleci/circleci-docs#1205]
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>)

Hi, it would be nice to refer to user-defined env vars on this page.  Presently it discusses CircleCI ones.  This could be as simple as a link to the page on Build Setting env vars.

Likewise for env vars defined in `config.yml`.

**Comment by michelle-luna** [comment]
Thanks for this feedback! I have added this to the doc and will get a PR up today.

**Comment by michelle-luna** [comment]
ok, got this info updated today, thanks!

**Comment by binkley** [comment]
Much nicer, thanks!
