### ISSUE TITLE
Hello world example does not work with CircleCI CLI 

### ISSUE THREAD

**Issue by kurtwheeler** [circleci/circleci-docs#1207]
This issue is about <https://circleci.com/docs/2.0/hello-world/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/hello-world.md>)

I used the example config.yml provided in the tutorial and replaced `<project root directory>` with `data_refinery`, `<language>` with `python`, and `<version TAG>` with `3.6`. After installing the circleci CLI tool and running `circleci build` I got the following output:

```
====>> Spin up Environment
Build-agent version 0.0.3409-42d3981 (2017-06-28T00:09:26+0000)
Starting container circleci/python:3.6
Error:   error starting container circleci/python:3.6: Error response from daemon: invalid bind mount spec "/home/kurt/Development/data_refinery:~/data_refinery": invalid volume specification: '/home/kurt/Development/data_refinery:~/data_refinery': invalid mount config for type "bind": invalid mount path: '~/data_refinery' mount path must be absolute

Error: Unexpected environment preparation error: Error response from daemon: invalid bind mount spec "/home/kurt/Development/data_refinery:~/data_refinery": invalid volume specification: '/home/kurt/Development/data_refinery:~/data_refinery': invalid mount config for type "bind": invalid mount path: '~/data_refinery' mount path must be absolute

Step failed
Task failed
Error: Error response from daemon: invalid bind mount spec "/home/kurt/Development/data_refinery:~/data_refinery": invalid volume specification: '/home/kurt/Development/data_refinery:~/data_refinery': invalid mount config for type "bind": invalid mount path: '~/data_refinery' mount path must be absolute
```

(Note that I also created a [feedback item on the Discuss forum](https://discuss.circleci.com/t/hello-world-example-does-not-work-with-circleci-cli/13827) because I saw that before I noticed I could do this, which seems better.)

**Comment by michelle-luna** [comment]
Hi,
Correct, there are a number of limitations when running build with the CLI on your local machine, see https://circleci.com/docs/2.0/local-jobs/#limitations

I can add a note about these to the Hello World doc if you think that would have helped you.

Thanks!
Michelle

**Comment by kurtwheeler** [comment]
That might be helpful for future users, however I would suggest a better way to correct the documentation would be to just use a full path in the example rather than a relative one. Specifically change `~/<project root directory>` to `/home/user/<project root directory>`. Then your Hello World example will Just Work whether it is run locally or remotely.

**Comment by kurtwheeler** [comment]
Well I thought that had worked but it doesn't. It seems like unless I use a relative path the remote execution of my build throws a `mkdir: cannot create directory ‘<my path>’: Permission denied` exception. What is the path that is generated when I use `~/<my project name?` remotely? I'd really like to find one way to do this so that I can test it locally and then push it remotely and have it work the same so I don't have to change my config. (It really reduces the usefulness of the CLI tool if you can't use the config you create using it without modifications.)

**Comment by kurtwheeler** [comment]
Ah I got it, the user on CircleCI's docker images is named `circleci`. Therefore if you change `~/<project root directory>` to `/home/circleci/<project root directory>` then the hello world example will work no matter how it is used.

**Comment by michelle-luna** [comment]
thanks for this feedback, this requirement for working directory has been removed, based on user feedback, so closing this issue, but feel free to re-open if you have other suggestions.
