### ISSUE TITLE
"Run rspec in parallel" but not set to run in parallel on 2.0

### ISSUE THREAD

**Issue by keybits** [circleci/circleci-docs#1225]
This issue is about <https://circleci.com/docs/2.0/language-ruby/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-ruby.md>)

The sample config has a comment with  `Run rspec in parallel` but we're not setting `parallelism` on this example. Perhaps remove this comment? Or create a config / example that does test in parallel on CircleCI 2.0?

**Comment by naofumi-fujii** [comment]
i made a issue & pull request about this.
https://github.com/CircleCI-Public/circleci-demo-ruby-rails/issues/6
