### ISSUE TITLE
Pre launch of simulator fails with asking for a template to launch instrument

### ISSUE THREAD

**Issue by elangogit** [circleci/circleci-docs#1229]
This issue is about <https://circleci.com/docs/1.0/troubleshooting-ios-and-OSX/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/troubleshooting-ios-and-OSX.md>)

xcrun instruments -w "iPhone 7 (10.3.1) [" || true
Waiting for device to boot...
Instruments Usage Error: No template (-t) specified
instruments, version 8.3.3 (62125)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

**Comment by smart-alek** [comment]
@elangogit Thanks for submitting this issue, and apologies for the delay!

With the EOL of 1.0 in August, we're focusing on ensuring 2.0 docs quality. Have you had any luck with CircleCI 2.0? If so, have you encountered this error there?

**Comment by smart-alek** [comment]
Closing this since we've got much more exhaustive (updated) 2.0 docs in this area. @elangogit feel free to comment if you're having problems on 2.0! :)

**Comment by saikrishnareddykarri** [comment]
yes am still facing it
