### ISSUE TITLE
Apache and PHP examples do not work when specifying PHP version

### ISSUE THREAD

**Issue by mikeschinkel** [circleci/circleci-docs#1232]
This issue is about <https://circleci.com/docs/1.0/language-php/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/language-php.md>)

See https://discuss.circleci.com/t/very-simple-circle-yml-fails-to-start-apache/13919 for all details.

**Comment by smart-alek** [comment]
#1233 and #655 are almost certainly related.

**Comment by felicianotech** [comment]
@smart-alek CircleCI 2.0 is the solution IMO.

**Comment by smart-alek** [comment]
@mikeschinkel Apologies for the delay and your troubles!

I know that the last thing you'd probably want to be doing is setting up CircleCI again after this Apache situation, but have you tried CircleCI 2.0 yet? I want to make sure these little wrinkles didn't follow us into 2.0 land.

Let us know!

**Comment by mikeschinkel** [comment]
@smart-alek Not yet.  It took so long to get `1.0` working that I don't know when I can reserve the time to move to `2.0` _(but I guess I will have to within 6 months.)_

BTW, I make heavy use of setting bash environment vars and **then using them to create new vars** within `circle.yml` and I read that `2.0` does not support that (yet?)  Is that still true?

**Comment by smart-alek** [comment]
@mikeschinkel Unfortunately, that's still the case with the environment variables, but we've got people piling onto the idea [here](https://circleci.com/ideas/?idea=CCI-I-67). We'll definitely have to address that before 1.0 EOL arrives in August.

Definitely let us know if you try to set up on 2.0 and run into issues there: that's the future, so we're highly motivated to keep that working! :)

**Comment by mikeschinkel** [comment]
@smart-alek Without that feature, I pretty much cannot move forward.  

I have set up an open-source solution I call [WP DevOps](/wplib/wp-devops) specifically for managing WordPress sites although it is not yet v1.0 and as such does not yet have an example `circle.yml` file.  

Given WP DevOps architecture it would be utterly impossible to move it to `2.0` without that the [environment vars feature](https://circleci.com/ideas/?idea=CCI-I-67) which makes @felicianotech's assertion that `2.0` is the solution incorrect, at least for my use-cases.
