### ISSUE TITLE
Apache returns permission denied with specified configuration

### ISSUE THREAD

**Issue by mikeschinkel** [circleci/circleci-docs#1233]
This issue is about <https://circleci.com/docs/1.0/language-php/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/language-php.md>)

Apache returns permission denied with specified configuration. After googling StackOverflow I found this solution, although I do not know if it is optimal.  Add this inside of the `<VirtualHost>` directive:

      <Directory /home/ubuntu/MY-PROJECT/server-root>
        Require all granted
        Options FollowSymLinks
      </Directory>

**Comment by felicianotech** [comment]
@smart-alek I don't think it's worth "fixing" this at this point The correct fix should be using CircleCI 2.0.

**Comment by smart-alek** [comment]
Fair enough! My only concern with that approach is that we've got to be sure that there is a 2.0 path. I think we do in this case, but that concern applies more generally.

**Comment by smart-alek** [comment]
@mikeschinkel I tagged you in another (related) issue, but I'll reiterate what I wrote there, which is:

We're hyper-focused on making the 2.0 docs for CircleCI the definitive version. Since we're sunsetting 1.0 in August, our whole team is thinking less and less about 1.0. Moving to 2.0 _should_ solve your problems, but definitely let us know if it doesn't! :)

**Comment by mikeschinkel** [comment]
I commented on issue #1232 and asked if it is yet possible to define environment vars in the config file using other environment vars.  When I first looked that did not work in `2.0`, and switching to `2.0` is certainly not a trivial task.

**Comment by smart-alek** [comment]
Hey @mikeschinkel: responded to the env var issue in the other thread. While there _is_ a workaround, we recognize that baked-in support for env var interpolation is still on many people's wishlists. Thanks for your patience as we work out the final kinks before August. :)

**Comment by mikeschinkel** [comment]
@smart-alek What is the workaround?

I hope you don't fix this in August and then give me 5 minutes to switch over...

**Comment by smart-alek** [comment]
Gross, I hope we don't do that, either. I'm going to be doing some investigative work this week with the responsible parties here — you're definitely not alone!

I *think* the workaround is in that thread. If you scroll up, people seem to be using `export` at the command level to specify env vars. Annoying but supposedly functional.

**Comment by mikeschinkel** [comment]
@smart-alek I will check into the workaround as soon as I can look into it.
