### ISSUE TITLE
Sample Config is not a valid config file

### ISSUE THREAD

**Issue by isaacpovey** [circleci/circleci-docs#1235]
This issue is about <https://circleci.com/docs/2.0/sample-config/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/sample-config.md>)

Testing the sample config using `circleci config validate` throws the error message:
```
Error: 1 error occurred:
* 1 error occurred:
* In job 'test': 3 errors occurred:
* missing executor type
*  is not supported executor type
* no working_directory
```

**Comment by michelle-luna** [comment]
Thank you! I broke this sample config the other day when I split out the test job and added the workflow config...fixing now.
