### ISSUE TITLE
Substitutions are stripped from the CircleCI 2.0 caching example

### ISSUE THREAD

**Issue by sfackler** [circleci/circleci-docs#1239]
It looks like the substitutions (e.g. `{{ .Branch }}`) were stripped from the caching example [here](https://circleci.com/docs/2.0/caching/#full-example-of-saving-and-restoring-cache) added in #1196, which leaves the cache names as `gem-cache--`, `gem-cache-`, and `gem-cache`. There presumably needs to be some escaping performed on the braces?

**Comment by michelle-luna** [comment]
good catch, thank you

**Comment by michelle-luna** [comment]
got this fixed today, thanks!

**Comment by sfackler** [comment]
Awesome, thanks!
