### ISSUE TITLE
RE: jekyll/_docs/continuous-deployment-with-google-container-engine.md

### ISSUE THREAD

**Issue by devonbarrett** [circleci/circleci-docs#124]
Should use the same GCP credentials envar as https://circleci.com/docs/google-auth/ 

This page refers to it as `$ACCT_AUTH` and the other page refers to it as `$CLIENT_SECRET`

**Comment by felicianotech** [comment]
The environment variable can be called whatever you'd like, as long as you use it correctly in `circle.yml` or your script.

That being said, consistent variable names in the doc make following along easier. I agree this should get changed.

**Comment by felicianotech** [comment]
Hi @devonbarrett,

Your Issue has been addressed in the referenced PR. Once that PR is merged, this Issue will be closed. Thank you so much for bringing this to our attention.
