### ISSUE TITLE
Cache keys are rendered incorrectly in the sample

### ISSUE THREAD

**Issue by quantus** [circleci/circleci-docs#1248]
This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

The full example has following cache keys:
```
  - restore_cache:
      keys:
        - gem-cache--
        - gem-cache-
        - gem-cache
```

It most likely should look like this:
```
  - restore_cache:
      keys:
        - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-{{ .Branch }}
        - gem-cache
```

**Comment by michelle-luna** [comment]
I fixed this, thank you!
