### ISSUE TITLE
Make configuration steps more consistent

### ISSUE THREAD

**Issue by quantus** [circleci/circleci-docs#1269]
This issue is about <https://circleci.com/docs/2.0/postgres-config/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/postgres-config.md>)

The page contains several configurations examples that have `steps` written in different ways, but still achieve the same thing (I think so). At least for me that is confusing, as I start to wonder if there is some difference in the different ways of writing the commands.

## Things to do

 - Remove unneeded `type` from steps, example:
```
    steps:
      - type: checkout
```
should rather be:
```
    steps:
      - checkout
```

 - Convert `type: shell` to `run` steps, example:
```
      - type: shell
        name: Install Ruby Dependencies
        command: bundle install
```
should rather be:
```
      - run:
          name: Install Ruby Dependencies
          command: bundle install
```

Most likely there are other pages with similar inconsistency issues, and those should be changed as well.

**Comment by marcomorain** [comment]
thanks for noticing this @quantus
