### ISSUE TITLE
Run PSQL Init Command to Initialize Database

### ISSUE THREAD

**Issue by base698** [circleci/circleci-docs#1273]
Can't figure out how to initialize our db by reading this: https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/postgres-config.md

Our repo has an init file that's run for tests.

**Comment by felicianotech** [comment]
Is this related to your CircleCI Discuss post? I'm assuming this was resolved there (where it should be) so I'm closing this. Let me know if I'm wrong.

**Comment by base698** [comment]
Yeah, but would nice to update the docs on how to run scripts to initialize
a database.  Something not done with rake.
