### ISSUE TITLE
Document working_directory

### ISSUE THREAD

**Issue by dzhus** [circleci/circleci-docs#1276]
This issue is about <https://circleci.com/docs/2.0/migrating-from-1-2/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/migrating-from-1-2.md>)

There's no mention of `working_directory` which seems essential for a working build:

```
Build-agent version 0.0.3558-7abfc35 (2017-07-11T15:25:49+0000)
Configuration errors: 1 error occurred:

* 1 error occurred:

* In job 'build': 1 error occurred:

* no working_directory
```

There's no explanation of what this option means, how to use it, how does it relate to the checkout directory and why is it even required.

**Comment by michelle-luna** [comment]
Correct, I've added this in https://github.com/circleci/circleci-docs/pull/1278

**Comment by michelle-luna** [comment]
Working directory was also changed after this post in two ways: first, it is no longer required for each job; second, it has a default of `~/project`.
