### ISSUE TITLE
Mention checkout is a required step

### ISSUE THREAD

**Issue by dzhus** [circleci/circleci-docs#1277]
This issue is about <https://circleci.com/docs/2.0/migrating-from-1-2/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/migrating-from-1-2.md>)

There's been no
```
checkout:
    post:
```
section in my CircleCI configuration for 1.0, yet building on 2.0 fails due to my app sources not being present unless I add `- checkout` as a step. If it's not done by default for some reason then the documentation should mention that you *must* have a `checkout` step in your `steps:` section.

**Comment by michelle-luna** [comment]
Thank you! I have https://github.com/circleci/circleci-docs/pull/1278 ready for this.
