### ISSUE TITLE
CIRCLE_TAG documentation links to 1.0 docs

### ISSUE THREAD

**Issue by tvainika** [circleci/circleci-docs#1279]
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>)

Under CIRCLE_TAG documentation the 2.0 docs link to 1.0 docs, which I found very confusing.

**Comment by michelle-luna** [comment]
thanks for this feedback, I have added qualifying text to make this more clear here https://github.com/circleci/circleci-docs/pull/1281
