### ISSUE TITLE
Make Minitest Parallel Docs more Explicit (_cc1/configuration.md)

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#130]
We write: 

> By default, when testing in parallel, CircleCI runs all tests in the test/unit, test/integration, and test/functional directories. You can add minitest_globs to replace the standard directories with your own. This is needed only when you have additional or non-standard test directories and you are testing in parallel with MiniTest.

However, it is important to note that running parallel will _only_ run tests in those directories. If you do not specify other directories than it will appear that we are skipping tests during the build.

**Comment by smart-alek** [comment]
Closing as we transition to 2.0.
