### ISSUE TITLE
Requiring "GNU tar" when using 'attach_workspace' is not written

### ISSUE THREAD

**Issue by MulticolorWorld** [circleci/circleci-docs#1300]
When use 'attach_workspace', CI require 'GNU tar' to extract persisted workspace. But this requirement not written anywhere. 'GNU tar' is not included in alpine linux by default. So error occur sometimes when use image based from it (especially docker https://hub.docker.com/_/docker/).
I suggest to write about them somewhere in document.

**Comment by michelle-luna** [comment]
Actually, the dependency on GNU tar for attach_workspace has been removed in the code, thanks again for the report.
