### ISSUE TITLE
private-images page's example code is broken

### ISSUE THREAD

**Issue by inuscript** [circleci/circleci-docs#1322]
https://circleci.com/docs/2.0/private-images
I found broken code syntax on private images docs.
![using_private_images_-_circleci](https://user-images.githubusercontent.com/13282103/28424626-0982183e-6da9-11e7-99bd-5c0bfc3a9bde.png)

and I check source markdown file, but can't find some errors.

https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/private-images.md

**Comment by michelle-luna** [comment]
thank you, this was fixed in https://github.com/circleci/circleci-docs/pull/1329
