### ISSUE TITLE
Permission denied error when attempting docker-compose installation 

### ISSUE THREAD

**Issue by MisterGlass** [circleci/circleci-docs#1323]
This issue is about <https://circleci.com/docs/2.0/docker-compose/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/docker-compose.md>)

Following the example in this doc, I received an error `/bin/bash: line 1: /usr/local/bin/docker-compose: Permission denied`. After some googling, I found the following advice, which seems to install docker-compose properly:
https://github.com/docker/machine/issues/652#issuecomment-243215931

I would open a PR to update the doc but I am not sure this method is desirable.

**Comment by levlaz** [comment]
I install latest docker-compose with pip and I have never had this issue. How are you installing it?

i.e. `pip install docker-compose`

**Comment by MisterGlass** [comment]
@levlaz with CURL as described in the beginning of the documentation

**Comment by levlaz** [comment]
Thanks. I'll figure out why we're recommending that method. :)

**Comment by sysradium** [comment]
@levlaz I guess because of this:
```
Successfully built PyYAML docopt texttable dockerpty
Installing collected packages: PyYAML, colorama, docopt, texttable, requests, six, websocket-client, docker-pycreds, docker, jsonschema, dockerpty, cached-property, docker-compose
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/_yaml.cpython-36m-x86_64-linux-gnu.so'
Exited with code 2
```

**Comment by kwent** [comment]
Same permission denied here with the curl method.

**Comment by kwent** [comment]
This fixes it for me:

```bash
 curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
chmod +x ~/docker-compose
sudo mv ~/docker-compose /usr/local/bin/docker-compose
docker-compose run test
```

**Comment by leojh** [comment]
The above works, docs at https://circleci.com/docs/2.0/docker-compose/ should be updated to have the above if it's decided to be the right solution

**Comment by CrashyBang** [comment]
Ran into same issue today, solution provided by @kwent fixed the issue.

**Comment by anandwana001** [comment]
> This fixes it for me:
> 
> ```shell
> curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
> chmod +x ~/docker-compose
> sudo mv ~/docker-compose /usr/local/bin/docker-compose
> docker-compose run test
> ```

@kwent I am doing the same for `bufbuild` but it is not showing the output of the command.

```
curl -sSLO
https://github.com/bufbuild/buf/releases/download/v$BUFVERSION/buf-Linux-x86_64 > ~/buf
chmod +x ~/buf
sudo mv ~/buf /usr/local/bin/buf
buf check lint
```

**Comment by anandwana001** [comment]
> > This fixes it for me:
> > ```shell
> > curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
> > chmod +x ~/docker-compose
> > sudo mv ~/docker-compose /usr/local/bin/docker-compose
> > docker-compose run test
> > ```
> 
> @kwent I am doing the same for `bufbuild` but it is not showing the output of the command.
> 
> ```
> curl -sSLO
> https://github.com/bufbuild/buf/releases/download/$BUFVERSION/buf-Linux-x86_64 > ~/buf
> chmod +x ~/buf
> sudo mv ~/buf /usr/local/bin/buf
> buf check lint
> ```
> 
> nor `buf --help` is showing the output

Resolved - https://github.com/bufbuild/buf-example/issues/3#issuecomment-636601534

**Comment by ultrox** [comment]
What really helped me is that I took ownership of the file. Many of the solution took the same route, but with extra steps. When you download docker-compose with the current user it's owned by that user.


   chown {{user}} {{path/to/file_or_directory}}
