### ISSUE TITLE
It's not clear whether a failure during Heroku deploy rolls back

### ISSUE THREAD

**Issue by dbalatero** [circleci/circleci-docs#1324]
The docs at a glance don't make it clear whether `heroku rollback` is run if the deploy steps fail.

https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-heroku.md

Still trying to figure it out, but maybe it should be updated with a bit of text information about this topic?

**Comment by michelle-luna** [comment]
Thank you for this feedback, I am mostly working on v2.0 docs at this point, but will try to cover this in that set of docs if you think it would be useful there as well.

**Comment by michelle-luna** [comment]
https://circleci.com/docs/2.0/deployment-integrations/#heroku the new way to deploy to Heroku is documented for 2.0 (it is manual).
