### ISSUE TITLE
RE: jekyll/_docs/language-php.md

### ISSUE THREAD

**Issue by yatsyukv** [circleci/circleci-docs#133]
```
dependencies:
  pre:
    - echo "memory_limit = 64M" > ~/.phpenv/versions/$(phpenv global)/etc/conf.d/memory.ini
```

This way of adding custom configuration to PHP just doesn't work. No such directories in user's home and from everything it looks like it's not the correct way to add .ini configurations anymore.

Please advice/fix.

Tnx

**Comment by felicianotech** [comment]
Thanks, this is true. The way some of the languages are being installed is changing with the next Ubuntu 14.04 image so we'll hold this issue until then, then see how we can improve this.

**Comment by felicianotech** [comment]
This is being handled in the following PR: https://github.com/circleci/circleci-docs/pull/153
