### ISSUE TITLE
Guide is missing information about Python test runner

### ISSUE THREAD

**Issue by mitar** [circleci/circleci-docs#1334]
In [project walkthrough](https://circleci.com/docs/2.0/project-walkthrough/) it is unclear which Python unit test runner do I have to use, if any, and how or if I have to configure it. I suspect we should use [unittest-xml-reporting](https://github.com/xmlrunner/unittest-xml-reporting), but this is not mentioned anywhere.

**Comment by michelle-luna** [comment]
Thanks for this feedback, I will try to get this added to the doc as an option (I assume you can use any one that you want).

**Comment by smart-alek** [comment]
Hey @mitar! Thanks for the feedback.

Your suspicion is correct! If you pop over to the [requirements/dev.txt file in the project's repository](https://github.com/CircleCI-Public/circleci-demo-python-flask/blob/master/requirements/dev.txt), you'll see `unittest-xml-reporting` is specified there.

In the case of this walkthrough, there's no special configuration — it's just using the standard `unittest` module that's baked into Python.

I'll add a sentence around this to the guide so this is less confusing for others.
