### ISSUE TITLE
Sample circle.yml doesn't lint

### ISSUE THREAD

**Issue by prnewman** [circleci/circleci-docs#134]
The sample circle.yml doesn't lint: http://www.yamllint.com/

Error: "mapping values are not allowed in this context at line 31 column 15"

If you remove the following line, the sample lints:

branch: master

**Comment by prnewman** [comment]
The solution is removing the extra indentation of commands:

deployment:
  beta_distribution: # just a label, can be anything
    branch: master
    commands:
        # this will build the ipa file
        - gym --scheme "App" --workspace "App.xcworkspace"
        - ipa distribute:crashlytics
            --crashlytics_path Crashlytics.framework
            --api_token    "$CRASHLYTICS_API_KEY"
            --build_secret "$CRASHLYTICS_SECRET"

**Comment by felicianotech** [comment]
Lints correctly now. Thanks.
