### ISSUE TITLE
Machine base image information is outdated

### ISSUE THREAD

**Issue by sebastianseitz** [circleci/circleci-docs#1340]
The <https://circleci.com/docs/2.0/configuration-reference/#docker--machine-executor> (Writing Jobs Documentation) clearly states that the machine executor uses ubuntu 17.x, which can be chosen via the `circleci/classic` image. The executor types page states that it will run ubuntu 14.04, please clarify which version is used in any case.

This issue is about <https://circleci.com/docs/2.0/executor-types/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/executor-types.md>)

**Comment by michelle-luna** [comment]
I have clarified the version in this PR https://github.com/circleci/circleci-docs/pull/1357
