### ISSUE TITLE
Missing caveat about Workflows

### ISSUE THREAD

**Issue by myabc** [circleci/circleci-docs#1346]
This issue is about <https://circleci.com/docs/2.0/local-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-jobs.md>)

As far as I can tell, workflows are not currently supported by the CLI.

**Comment by michelle-luna** [comment]
correct, I have added a note in https://github.com/circleci/circleci-docs/pull/1354, thanks!
