### ISSUE TITLE
Can't understand what is this page saying....

### ISSUE THREAD

**Issue by PureWhiteWu** [circleci/circleci-docs#1347]
This issue is about <https://circleci.com/docs/2.0/parallelism-faster-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/parallelism-faster-jobs.md>)

**Comment by michelle-luna** [comment]
Hi,

Thanks for this feedback, can you be more specific about what is confusing or which part should be clarified?
