### ISSUE TITLE
PyOpenSSL is missing for the dependency to use glcoud RE: jekyll/_docs/google-cloud-test-lab.md

### ISSUE THREAD

**Issue by thagikura** [circleci/circleci-docs#135]
PyOpenSSL is missing for using the gcloud command, otherwise you wil get the error like in this [build](https://circleci.com/gh/google/flexbox-layout/33)

Also after I installed the PyOpenSSL via "sudo apt-get install python-openssl" I started seeing the following error in this [build](https://circleci.com/gh/google/flexbox-layout/36#tests) even the `CLOUDSDK_PYTHON_SITEPACKAGES` environment variable is set to 1 in the circle.yml.
Couldn't figure out why that didn't work, but as a workaround, I ended up removing the preinstalled gcloud and re-installing a new one like discussed in this forum thread.

https://discuss.circleci.com/t/deployment-to-appengine-fails-pyopenssl-not-available/2154

**Comment by thagikura** [comment]
Any update on this?

**Comment by thagikura** [comment]
Looks like this is happening anymore. Verified the built-in gcloud worked.

**Comment by felicianotech** [comment]
I'm no sure which image you were referring to but GCloud on Ubuntu 14.04 was updated in October (https://github.com/circleci/circleci-docs/blame/master/jekyll/_data/trusty/versions.json#L138).

Thank you for following up here.
