### ISSUE TITLE
2.0: `type: approval` missing in workflows reference

### ISSUE THREAD

**Issue by Dominik-K** [circleci/circleci-docs#1352]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/#workflows> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>). `type: approval` is missing.

The `type: approval` can be also set on a build job, right? Then the example and description in [Holding a Workflow for a Manual Approval](https://circleci.com/docs/2.0/workflows/#holding-a-workflow-for-a-manual-approval) is misleading.

**Comment by michelle-luna** [comment]
Yes, you are correct, I will be adding some info to both of these files today and tomorrow and will add an example or clarify that build job can be type: approval. Thanks!

**Comment by michelle-luna** [comment]
PR is  https://github.com/circleci/circleci-docs/pull/1360

**Comment by Dominik-K** [comment]
@michelle-luna It seems that it's not intended/possible to use `type: approval` on a job defined in `jobs`. If so, the job gets immediately green after approval, but does not run the job `steps` neither gets a build number or shows up in the `builds`. See [my forum post](https://discuss.circleci.com/t/non-accessible-workflow-job-gets-no-build-number/16421?u=dominikgm).
