### ISSUE TITLE
RE: jekyll/_docs/language-java.md

### ISSUE THREAD

**Issue by danielcompton** [circleci/circleci-docs#136]
The docs here don't say which versions of Java are installed, or how to refer to them in the circle.yml doc.

**Comment by felicianotech** [comment]
Hi @danielcompton, seems to me like it does. The doc starts with links to the Ubuntu 12.04 and Ubuntu 14.04 images. Right under that it shows how to add that to `circle.yml`. Is there a specific part that is unclear to you?

Taking a look at the Ubuntu 12.04 Java section, it looks like the formating could be improved there (JSON is showing for some reason). I made a new Issue (#139) to get that fixed.

**Comment by danielcompton** [comment]
Ah, gotcha, sorry I didn't think to look at the build image docs. My mistake sorry.

**Comment by felicianotech** [comment]
Not at all. This Issue led to #139 so you helped out anyway. Thank you!
