### ISSUE TITLE
Please show me how I can test my app on Python 2.7, 3.4, and 3.6

### ISSUE THREAD

**Issue by cclauss** [circleci/circleci-docs#1380]
This issue is about <https://circleci.com/docs/2.0/project-walkthrough/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/project-walkthrough.md>)

It would be best if these three tests could run __in parallel__.

**Comment by smart-alek** [comment]
@cclauss This is an incredibly late response (sorry!), but you should be able to get this done with Workflows using parallel jobs. Here's an [example in Ruby](https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml).
