### ISSUE TITLE
Provide detailed information about API response

### ISSUE THREAD

**Issue by edouard-lopez** [circleci/circleci-docs#1394]
Hi guys,
could you provide more details about your API response (e.g. [new-build-branch](https://circleci.com/docs/api/v1-reference/#new-build-branch)) as the value of the attributes are puzzling:
```
{
   "failed": null, ← what are the possible values here ?
   "canceled": false,
}
```

**Comment by felicianotech** [comment]
Hey @edouard-lopez, could you clarify what you'd like to see? Perhaps an example?

**Comment by edouard-lopez** [comment]
@felicianotech I would like to know what are the possible value for that attribute, is it a boolean a string, etc.?

**Comment by smart-alek** [comment]
@edouard-lopez Could you take a look at the above PR and see if that resolves your issue?

Specifically: is `"failed"` the only attribute that was confusing, or was it a general lack of information about the possible values of **all** attributes in a response?
