### ISSUE TITLE
Mechanism to clear docker cache

### ISSUE THREAD

**Issue by tedgoddard** [circleci/circleci-docs#1410]
"Rebuild without cache" still uses the Docker cache. Is there an admin mechanism for forcibly clear the docker cache?

This issue is about <https://circleci.com/docs/2.0/docker-layer-caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/docker-layer-caching.md>)

**Comment by michelle-luna** [comment]
Hi,

Thanks for this question, is this the same issue as ENOSPC and no space left on device errors?
If so, use the following config to clean up unused images and report image size in your build for debugging:
```
- run:    
  command: |      
    docker prune      
    docker images
```

If not, let me know and I will check about this question and get something added to the doc.

**Comment by ryanwohara** [comment]
@tedgoddard Can you include this in your config?

```
docker images --no-trunc --format '{{.ID}} {{.CreatedSince}}' \
    | grep ' months' | awk '{ print $1 }' \
    | xargs --no-run-if-empty docker rmi
```

**Comment by tedgoddard** [comment]
I'm not sure these would have the same effect -- the goal I had was to clear the docker cache just in the case when it seemed to be corrupted, not on every build. These commands do look useful for removing unused data from the cache, though.

**Comment by smart-alek** [comment]
Hey @tedgoddard, if this is still an issue for you, can you pop over to the [Ideas](https://circleci.com/ideas/) page to file an official request for this? Something similar came up recently, and we want to make sure everyone who cares about this can show that through a vote. Thanks!
