### ISSUE TITLE
Clarify difference in service availability between Precise & Trusty (_cc1/configuration.md)

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#142]
At the [top of the services section](https://circleci.com/docs/configuration/#services), we have:

> CircleCI supports a large number of databases and other services. Most popular ones are running by default on our build machines (bound to localhost), including Postgres, MySQL, Redis and MongoDB.

This is true on the Precise container, but not on the Trusty container.  I believe we defaulted most services to not running to save ram for Android builds.

Is it better to move this snippet into the Precise doc?  Should there be a page for "changes to be aware of switching from Precise to Trusty"?

**Comment by felicianotech** [comment]
@eric-hu,

The dbs mentioned do indeed autostart on Ubuntu 14.04 (I found this out the hard way myself). Also, we do have a guide for differences between the two images. Do you think this issue is still relevant?

**Comment by eric-hu** [comment]
This is true for Postgres and MySQL, but specifically not Redis, and I think other services like Cassandra.

I think it's still relevant.  It was a somewhat regular "hey, this is broken because I upgraded to Trusty" support ticket, when it was necessary to add Redis or Cassandra to the circle.yml services section.

**Comment by smart-alek** [comment]
Closing in favor of 2.0 docs.
