### ISSUE TITLE
RE: jekyll/_docs/configuration.md

### ISSUE THREAD

**Issue by zenspider** [circleci/circleci-docs#143]
Actually this is about ALL the docs pages. The search bar doesn't do a damn thing in safari or chrome. Return doesn't seem to post. There is no JS running dynamically afaict. Just... a box with words I typed.

**Comment by felicianotech** [comment]
What are you trying to search? The search box searches doc titles and categories as you type. There isn't a separate search results page. Everything is done right there.

We have been comparing the current behavior to having a dedicated search page as well. I assume that is something that you would prefer?

The other route is to simply get full-text support, which docs currently doesn't  have. That would provide much more results when searching.

**Comment by ndintenfass** [comment]
Fixed by https://github.com/circleci/circleci-docs/pull/161
