### ISSUE TITLE
Clarify Whether or Not 2.0 Cache is Immutable

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1435]
This issue was reported via [CircleCI Discuss](https://discuss.circleci.com/t/documentation-claims-caching-is-both-mutable-and-immutable/15300).

The gist of it is:

> However, caching is immutable. I have tried to run jobs with new definitions for the cache, namely adding more folders to cache, for a given key, but it seems that CCI does not ever update the cache.

> Is there clarification for what behavior to expect? Which part of the documentation is accurate? What is the behavior that is intended here?

**Comment by michelle-luna** [comment]
Thanks Ricardo, I don't know what change to make to the docs based on this thread, can you suggest a change or addition?

**Comment by felicianotech** [comment]
I don't have the time right now but if no one gets to this, I can revisit next week.

**Comment by smart-alek** [comment]
This issue is for sure related: https://github.com/circleci/circleci-docs/issues/997

**Comment by felicianotech** [comment]
This issue was fixed here: https://github.com/circleci/circleci-docs/commit/ef0fb2fc6d5533d48a311d92f2e84a0c00f64e22
