### ISSUE TITLE
More Information on Public Projects and Open-Source

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1441]
> Also, it would be nice to just have a section about public repo/projects clearly outlining best practices here. I wish to use CircleCI in place of TravisCI, but finding out how to keep deployment config private and what's visible to non-contributors has been difficult.

> Here is a list of things that I've not been able to find or wish to be more clear:

> - public repo = public project
> - env-vars are shared in forks unless turned off
> - Web GUI settings are accessible only by contributors? Therefore, env-vars set in the GUI are hidden from the public.
> - Build-logs are visible, so don't print sensitive information in them.

This falls in line with a blog post on CircleCI and FOSS I wrote but wasn't published awhile back as well. @smart-alek Remember that? Any ideas?

@michelle-luna If you have some ideas of structure and where this might live, I wouldn't mind writing this information.

via: https://discuss.circleci.com/t/circleci-2-0-private-environment-keys-for-public-repos/15259/5

**Comment by smart-alek** [comment]
@michelle-luna has final say, but here are my thoughts:

- public repo = public project --> note in [Hello World](https://circleci.com/docs/2.0/hello-world/)
- env-vars are shared in forks unless turned off --> [Env Vars](https://circleci.com/docs/2.0/env-vars/)
- Web GUI settings accessible only by contributors --> [Env Vars](https://circleci.com/docs/2.0/env-vars/)
- Build-logs are visible --> Not sure about this one. Makes me think we need an article that specifically addresses FOSS

**Comment by zzak** [comment]
I'd love to see a general guide for OSS authors onboarding to CircleCI.

**Comment by jthegedus** [comment]
@zzak That was my initial thought too. If there was a small, single page that collated the docs relevant to OSS projects it would really help with the onboarding.

**Comment by felicianotech** [comment]
I am working on this as part of my Q1 goals. This will be done. :)

**Comment by jthegedus** [comment]
@smart-alek I respect the decision but do disagree. From my understanding, other than the `.circleci/config.yml` there are generally two desire settings setups; public (OSS) or private. Personally, I feel the benefit of having a simple guide for each outlining the aforementioned settings outweighs any amount of duplication from these other pages. And singling these settings out only highlights their importance, because they're extremely important.

btw, I'm happy to contribute feedback/help to the whatever docs come out of this, regardless of their structure :smiley:

**Comment by smart-alek** [comment]
Hey @jthegedus! Thanks for keeping the feedback coming — good stuff. :)

But maybe we're actually aligned here! You wanted a simple guide for OSS setups, and I think we want that, too! When I said "link to other articles", I really meant linking to the bulkier, more thorough docs without copying their contents wholesale. You're completely right that the pros of collecting OSS info outweigh the cons of duplicate information.
