### ISSUE TITLE
CLI does not support piping from stdin on OSX

### ISSUE THREAD

**Issue by willryan** [circleci/circleci-docs#1448]
This issue is about <https://circleci.com/docs/2.0/local-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-jobs.md>)

I installed the CLI on OSX based on the instructions on this page.  However when I tried to follow the examples on https://circleci.com/docs/2.0/parallelism-faster-jobs/ I kept having issues.  So for example, it would error out when I tried `circleci tests glob test/**/*.java | circleci tests split`.

Turns out that two of the Splitting Pattern cases ("piping" and "stdin redirection") fail because /usr/local/bin/circleci specifies that docker should run with `-it`.  The `-t` part allocates a pseudo TTY, which causes the piping to fail with:  "the input device is not a TTY".

Based on the available set of commands for circleci, I can't see where you would need the `-t`.  I removed it locally (keeping `-i`) and the piping to `circleci tests` works as expected.  Can you change this in the circleci script that installs?

Thanks.

**Comment by felicianotech** [comment]
This issue is with the Local CLI/build-agent. I've reported this issue to that team. This isn't an issue with Docs itself so I will close this.
