### ISSUE TITLE
discuss how split tests actually get run?

### ISSUE THREAD

**Issue by aleemstreak** [circleci/circleci-docs#1471]
This issue is about <https://circleci.com/docs/2.0/parallelism-faster-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/parallelism-faster-jobs.md>)

This page talks about how to split tests but it doesn't really talk about how those split tests get run? Does each group of test get run in its own container? Or are each group run on the same container but in parallel?

**Comment by ryanwohara** [comment]
TESTFILES=$(circleci tests glob "specs/**/**_spec.rb" | circleci tests split --split-by=timings)
mkdir -p test/reports
echo ${TESTFILES}
bundle exec rspec --format progress \
  --format RspecJunitFormatter \
  -o test/reports/rspec.xml \
  -- ${TESTFILES}

The TESTFILES var will have a different value in each container, based on $CIRCLE_NODE_INDEX and $CIRCLE_NODE_TOTAL

And don't forget to store your test timings afterwards.

**Comment by smart-alek** [comment]
@aleemstreak Just following up with a prose explanation:

Groups of tests are spread across a number of containers. The actual number of containers is defined by the `parallelism` key in the job running the tests.

I'll get this added to our documentation sometime this week.
