### ISSUE TITLE
Show how to make this work with AWS ECR private docker repo

### ISSUE THREAD

**Issue by rberger** [circleci/circleci-docs#1475]
This issue is about <https://circleci.com/docs/2.0/private-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/private-images.md>)

Its not clear how you can get use a private docker repo if its ECR which needs to run something like
```
eval $( aws ecr get-login --region us-west-2 --profile staging)
```
to login to the repo.
The username / password can't be put in environment variables

**Comment by felicianotech** [comment]
This issue was resolved here: https://github.com/circleci/circleci-docs/commit/d419cbc6050863de6629c48a60311c550085929d
