### ISSUE TITLE
Document limits on Build Artifacts size, retention, etc

### ISSUE THREAD

**Issue by laughinghan** [circleci/circleci-docs#148]
RE: jekyll/_docs/build-artifacts.md

https://circleci.com/docs/build-artifacts/ doesn't mention any limits on the sizes of build artifacts (I see #122 mentions a 3GB size limit on individual artifacts; what about total size per build, or per project?), nor how long Circle promises to host the artifacts (e.g. only 3 months like (random example) [Ghost Inspector](https://ghostinspector.com/pricing/), or indefinitely but promise 6 months warning if you're gonna start taking them down, etc).

For my case I'm not actually worried about the size limit (though I would love to see it documented), just retention, especially since the filepaths are all `.../tmp/circle-artifacts.AvvFajf/...`, which isn't exactly resounding with permanence. Can I hotlink them, or should I be uploading them somewhere else? (Imgur probably)

There may be other limits worth documenting, too. (Rate limits on downloads? That's probably high enough not to be worth documenting.)

**Comment by janpaul123** [comment]
+1 on retention information!

**Comment by keybits** [comment]
Thanks for your questions about this. We are working internally on making a public retention policy and it will be published on the main website when ready. I don't have an ETA for when this will be as at the moment we're focusing on launching CircleCI 2.0.

Artifacts are stored on S3. The 3GB limit is related to what `curl` can upload. Artifacts are designed to be useful around the time of the build, but we don't recommend relying on them as a software distribution mechanism with long term future guarantees.

Closing this for now. Please [subscribe to our Announcements](https://discuss.circleci.com/t/how-to-subscribe-to-announcements-and-notifications-from-circleci-email-rss-json/5616) to be notified  when updates are published.

**Comment by caipivara** [comment]
@keybits any update on retention docs for 2.0? I dont see any of it on 2.0
