### ISSUE TITLE
No android emulator available

### ISSUE THREAD

**Issue by albertovelazmoliner** [circleci/circleci-docs#1483]
This issue is about <https://circleci.com/docs/2.0/language-android/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-android.md>)
You should put in the first line of Android Guide the next message:
<h1>WE HAVE NO ANDROID EMULATORS IN DOCKER IMAGES, SO DON'T WASTE YOUR TIME IF YOU NEED AN ANDROID EMULATOR</h1>

I think this will avoid a lot of android developers wasting their time.
Thanks

**Comment by afolson** [comment]
Looks like this image is installing a specific version of the SDK (which you specify) and then installing a bunch of other tools including the emulator: https://github.com/circleci/circleci-images/blob/master/android/Dockerfile.m4#L40

What specifically are you trying to do with this image? If you're trying to do UI tests it may require a few extra steps depending on your toolchain.

**Comment by albertovelazmoliner** [comment]
I'd like to run my testsuite of unittests of my android app.
I can not find any clue about how to do that in your current documentation.
If you can give me a link with the instructions for running my unit test I'll really appreciate it.
Today was a disaster. 7 hours with not help, no documentation, except  - Marc O'Morain‏ @atmarc -, who was not able to run my tests after several hours trying to do it.
One of circleci team in the community forum said there wasn't any docker image with android emulator.
Any help will be appreciate.
Thanks

**Comment by michelle-luna** [comment]
Thanks for the feedback, we will get something added to the android 2.0 doc.
