### ISSUE TITLE
Not Able to deploy to the google compute engine Instance 

### ISSUE THREAD

**Issue by cstrd** [circleci/circleci-docs#1504]
Hi I want to integrate, Circle CI, with Google compute engine, for node js language I am having problem in deploy job, I am not able to deploy to compute engine giving some error message like" command not found " in circle CI 
![circle_google_cloud-error](https://user-images.githubusercontent.com/11487982/30030720-3b1796e0-91ac-11e7-8a3a-91bc8ae53795.png)

please help how to fix that.  below is my .yml file 

version: 2
jobs:
  build:
    working_directory: ~/circle_ci_demo_project
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
      steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
      - deploy:
          name: Deploy Master to Gcloud
          command: echo $GCLOUD_SERVICE_KEY 
          command: echo $GCLOUD_INSTANCE_ZONE
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
          command: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
          command: sudo /opt/google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT_ID
          command: sudo /opt/google-cloud-sdk/bin/gcloud compute copy-files ./dist 725459838767-compute@circle-ci:/circle_demo --zone $GCLOUD_INSTANCE_ZONE

**Comment by michelle-luna** [comment]
I can't see where you have deploy.sh in your .yml, maybe you can get some help with this on the community discussion at https://discuss.circleci.com?

Thank you,
Michelle
