### ISSUE TITLE
How do you specify a specific yarn version?

### ISSUE THREAD

**Issue by AlastairTaft** [circleci/circleci-docs#1507]
This issue is about <https://circleci.com/docs/1.0/yarn/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/yarn.md>)

**Comment by felicianotech** [comment]
On CircleCI 1.0 you don't. That's why there's a specified version for the build image: https://circleci.com/docs/1.0/yarn/#version-support

You need to install your own version on top of the one included, or with CircleCI 2.0, use an image with your specified version.
