### ISSUE TITLE
Issue with the setup-heroku.sh script in the Heroku deployment guide with  respect to Heroku CLI

### ISSUE THREAD

**Issue by kyrcha** [circleci/circleci-docs#1521]
This issue is about <https://circleci.com/docs/2.0/deployment_integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment_integrations.md>)

Perhaps in some images the proposed way is not working: #1413 and [here](https://discuss.circleci.com/t/unable-to-install-heroku-cli-under-2-0/15733)

**Comment by keybits** [comment]
Thanks for reporting this. It can be fixed by using `sudo` - this PR fixes the doc: https://github.com/circleci/circleci-docs/pull/1523
