### ISSUE TITLE
GCR documentation is inaccurate

### ISSUE THREAD

**Issue by ryanwohara** [circleci/circleci-docs#1534]
Discuss post with both the problem and the solution:

https://discuss.circleci.com/t/impossible-to-use-a-private-gcr-io-base-image-on-circle-2-0/15965

**Comment by michelle-luna** [comment]
Thanks, also cc'ing @sha1sum who developed this doc.

**Comment by michelle-luna** [comment]
https://github.com/circleci/circleci-docs/pull/1542

**Comment by michelle-luna** [comment]
fixed, finally!

**Comment by kunal-relan** [comment]
does somebody have a working example config file for using json key with GCR
