### ISSUE TITLE
Provide an example for Google Container Registry

### ISSUE THREAD

**Issue by suranap** [circleci/circleci-docs#1535]
This issue is about <https://circleci.com/docs/2.0/private-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/private-images.md>)

The only way I could make this work is using a JSON key file, described at [the bottom of this page](https://cloud.google.com/container-registry/docs/advanced-authentication). Is there a better way?

**Comment by michelle-luna** [comment]
This seems to be the way that others are using it, but the doc need some work, here is a PR for an update based on a discuss thread from yesterday, feel free to comment https://github.com/circleci/circleci-docs/pull/1542

**Comment by michelle-luna** [comment]
fixed (to use correct commands for json file), thank you!
