### ISSUE TITLE
Improve Workflow Tags Information

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1553]
These are two related issues:

- [ ] There isn't an explanation of how tag filters truly work. Clearly, they're regex. What kind of regex? What are the full rules for tag matching.
- [ ] Better tag examples. Most of the tag examples use `/^config-test.*/`. That's not a real world example for most people. A typical use case would be for Semantic Versioning (SemVer) tagged releases.

**Comment by smart-alek** [comment]
@felicianotech What doc are you referring to here? The configuration reference? Or the workflows doc?

**Comment by felicianotech** [comment]
I believe it's anywhere this is referenced but maining the main Workflows doc.

**Comment by smart-alek** [comment]
So perhaps adding links to [this section on tags](https://circleci.com/docs/2.0/configuration-reference/#tags) to the Workflows doc?

**Comment by felicianotech** [comment]
That's still not enough information. For example, do we support Perl-like regex? JavaScript-like regex?

How would we match the common use case of a SemVar version?

This information also applies to branch names as well, not just tags. Wherever we use regex (which those are the only two I can think of).

**Comment by smart-alek** [comment]
I'm hearing the need for a full-blown doc on how we consume Regex in the Reference section, yeah? Regex is a cross-feature thing so should exist on its own.
