### ISSUE TITLE
Improve `persist_to_workspace` and `attach_workspace` documentation

### ISSUE THREAD

**Issue by lswith** [circleci/circleci-docs#1563]
There is no documentation for what the dependencies are for the `persist_to_workspace` and the `attach_workspace` command and no way of figuring it out other than trial and error. My container uses ubuntu:16.04 and it seems that it doesn't have the appropriate dependencies for these command.

**Comment by iynere** [comment]
thanks, this is helpful ! working on it now

**Comment by michelle-luna** [comment]
Hi,
I fixed some missing info in this documentation in January to make the required keys for persist and attach clear, as follows:
https://github.com/circleci/circleci-docs/pull/1980/files

https://github.com/circleci/circleci-docs/pull/1976/files
Thanks for filing this request, apologies for the extreme delay in getting it fixed!
-Michelle

**Comment by iynere** [comment]
awesome !!!!!!!
 
looks like i assigned it to myself & then didn't follow through, so thank you for picking it up :3
