### ISSUE TITLE
$ANDROID_NDK is not exported (and the NDK is apparently not installed)

### ISSUE THREAD

**Issue by xknight** [circleci/circleci-docs#157]
The documentation (https://circleci.com/docs/android/) suggests that the Android NDK is available, but it does not appear to be (at least in Ubuntu 14.04).

**Comment by felicianotech** [comment]
Thank you for reporting this. It's not installed and will be removed from the docs.

**Comment by PaulWoitaschek** [comment]
Why is this not installed? This is the standard.
