### ISSUE TITLE
Images for C/C++ environment not documented

### ISSUE THREAD

**Issue by mloskot** [circleci/circleci-docs#1576]
This issue is about <https://circleci.com/docs/2.0/circleci-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/circleci-images.md>)

------

There is no mention of what images are recommended for C/C++ environment.

For example, some projects out there in the wild use `image: gcc:latest`, but it is not documented anywhere.

**Comment by ryanwohara** [comment]
We do not presently offer a C/C++ image. This doc is only for images we are extending/building.

https://github.com/circleci/circleci-images

You can use any arbitrary image with the proper packages installed.

**Comment by mloskot** [comment]
@ryanwohara Clear. A sentence, in the docs, clarifying that would be sweet.

**Comment by sas** [comment]
FWIW, I'm setting up my C++ project with CircleCI currently, and I was wondering which image to use. The first "documentation" I found was this PR, so some documentation for C/C++ projects might be helpful.
