### ISSUE TITLE
Using Private Images

### ISSUE THREAD

**Issue by AlbertShamsiyan** [circleci/circleci-docs#1577]
This issue is about <https://circleci.com/docs/2.0/private-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/private-images.md>)

No JFROG ArtifactoryServer integration? When I try to use the following section: 

> docker: 
> - image: containers.MyCompany.com/My-team/nodejs/amazonlinux:v6.10.2
> auth:
> username: MyUserName
> password: MyPassword 

The following error is being raised 
> Error parsing config file: yaml: line 7: mapping values are not allowed in this context
> Cannot find a job named build to run in the jobs: section of your configuration file.
> This can happen if you have no workflows defined, or a typo in your 'workflows:' config.

note build is properly working when using:
> - image: circleci/node:7,

**Comment by iynere** [comment]
hi Albert, sounds like you have an issue in your YML file—try running it through something like http://yamllint.com
