### ISSUE TITLE
Add link to (_cc1/environment-variables.md) from both 12.04 and 14.04 & remove env vars from 12.04

### ISSUE THREAD

**Issue by brycefisher** [circleci/circleci-docs#158]
Currently there are three environment documentation pages:
- The [landing page](https://circleci.com/docs/environment/)
- Ubuntu 12.04 page
- Ubuntu 14.04 page

However, only the Ubuntu 12.04 lists the environment variables available during a build inside the container. So, its unclear to me whether the environment variables are the same regardless of environment, or if there are differences in which environment variables exposed. (Let's ignore build parameters from the build API, since I'm only discussing CircleCI provided environment variables.)

Here's my proposal:
- If the environments are the same in Ubuntu 12.04 and 14.04, then move the environment variables to the [landing page](https://circleci.com/docs/environment/) and off the ubuntu 12.04 page
- If there are differences between the two build environments, list all of the CircleCI provided environment variables on each page.

**Comment by felicianotech** [comment]
Hi @brycefisher, thank you so much for pointing this out. I've looked at those pages several times recently and somehow didn't notice that. I'm leaning towards your first suggestion. That makes a lot of sense.

**Comment by brycefisher** [comment]
Awesome thanks!

**Comment by keybits** [comment]
This appears to be fixed: https://circleci.com/docs/1.0/environment/

@felicianotech can we close?

**Comment by smart-alek** [comment]
@keybits that link just goes to separate 12.04 and 14.04 pages. But I think [this article](https://circleci.com/docs/1.0/environment-variables/) is what @brycefisher was looking for.

**Comment by brycefisher** [comment]
@smart-alek yes! That article is definitely the content I was looking for. IMHO, it would make sense to remove the environment vars from the 12.04 page and add a link to https://circleci.com/docs/1.0/environment-variables/ from both image pages.

**Comment by smart-alek** [comment]
Great suggestion, @brycefisher! I'll reopen and rename this one to incorporate that.

**Comment by smart-alek** [comment]
@brycefisher thanks for your help on this! We're closing out most of our 1.0 issues involving edits in favor of focusing on 2.0 docs. Just didn't want you to wonder what happened to this, though. :)

**Comment by brycefisher** [comment]
No worries at all! Thanks for looping me in.
