### ISSUE TITLE
Confusing section

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#1580]
This issue is about <https://circleci.com/docs/2.0/google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/google-container-engine.md>)

A customer tried to use the password Base64 encryption scheme on this page for pulling from Google Container Registry.  I think it's confusing that this page is listed under "containerization", when the code snippets are for deployment to GCE.

**Comment by smart-alek** [comment]
@eric-hu While the document could probably be more clearly called out, does having it linked in the "Deploy" section help at all? https://circleci.com/docs/2.0/deployment_integrations#google-cloud

**Comment by eric-hu** [comment]
@smart-alek Yeah, that helps.  I think changing the title to "Deploying to Google Container Engine" would make it a lot clearer too.
