### ISSUE TITLE
CircleCI 2.0 Postgresql Doc Has Incorrect Info

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1583]
> The default user, port, test database for PostgreSQL 9.6 are as follows:

 >postgres://ubuntu:@127.0.0.1:5432/circle_test

> Note: For version 9.5, the default port is 5433 instead of 5432. To specify a different port, change the $DATABASE_URL and all invocations of psql.

This is incorrect. I'm assuming that this might have been accidently carried over from the 1.0 Doc? The Postgres defaults, if we want to mention that, in this case are specific to the Docker Library version since this is where we're basing our images off of too. https://hub.docker.com/_/postgres/

**Comment by michelle-luna** [comment]
thanks, I replaced this with the link to docker hub and added it as a description where we specify it in the example.
