### ISSUE TITLE
Seemingly contradictory statements about cache changes

### ISSUE THREAD

**Issue by tejohnso** [circleci/circleci-docs#1584]
This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

First we have:

> Cache is written in chronological order. Consider a workflow of Job1 -> Job2 -> Job3. If Job1 and Job3 write to the same cache key, a rerun of Job2 may use the changes written by Job3 because Job2 ran last. That is, any job that runs inside a project will always use the latest write. 

This indicates that cache under a particular key will be modified by Job1 and then modified by Job3.

But then we have:

> Tip: Caches are immutable so it is useful to start all your cache keys with a version prefix...

This states that caches are immutable, contradicting the above scenario where Job3 modifies a cache after Job1.

Seeking clarification.

**Comment by iynere** [comment]
thanks, this should be fixed now !
