### ISSUE TITLE
The Ruby Language Guide on official website is outdated

### ISSUE THREAD

**Issue by number5** [circleci/circleci-docs#1589]
This issue is about <https://circleci.com/docs/2.0/language-ruby/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-ruby.md>)

There are few bugs fixed in the github but not on the website.

Particularly, 
```
--format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
```
https://github.com/circleci/circleci-docs/blame/master/jekyll/_cci2/language-ruby.md#L73

**Comment by ryanwohara** [comment]
@number5 Can you clarify what the problem is?

**Comment by number5** [comment]
@ryanwohara what I meant was the docs on https://circleci.com/docs/2.0/language-ruby/ is out-of-sync of the github version.

But it solved now. thanks
