### ISSUE TITLE
Missing Redis container for docker

### ISSUE THREAD

**Issue by liesislukas** [circleci/circleci-docs#1592]
This issue is about <https://circleci.com/docs/2.0/circleci-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/circleci-images.md>)

Not sure if that's technically possible but can we just use any public docker image as a dependency? e.g. `redis` or whatever else.

If not, please add redis to the list.

**Comment by ryanwohara** [comment]
We do not intend to customize the Redis images. If you experience a flakey version, I recommend `redis:2.8.19`.
