### ISSUE TITLE
Small detail in AWS - EC2 integration article

### ISSUE THREAD

**Issue by picandocodigo** [circleci/circleci-docs#1607]
This issue is about <https://circleci.com/docs/1.0/continuous-deployment-with-aws-ec2-container-service/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-aws-ec2-container-service.md>)

>*Service* - A “service” handles the logic of running task on the cluster.

Should this say "running task**s**"?

**Comment by iynere** [comment]
yup, thanks !!!!!!!
