### ISSUE TITLE
Confusion over restore_cache, save_cache

### ISSUE THREAD

**Issue by jamesleejiacheng** [circleci/circleci-docs#1632]
This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

A question in regards to https://circleci.com/docs/2.0/caching/#full-example-of-saving-and-restoring-cache. 

The documentation mentioned `restore_cache` using 3 different keys, however `save_cache` section will always fill the cache with a key having the prefix of `gem-cache-*`. Does CircleCI automatically creates a cache with the key `gem-cache`?

![image](https://user-images.githubusercontent.com/7088256/31003462-6a5e29bc-a522-11e7-88dd-61bdcdbcfd1d.png)

**Comment by smart-alek** [comment]
@jamesleejiacheng Sorry for the late response!

CircleCI does *not* automatically create a cache with the key `gem-cache`. The three keys listed under the `restore_cache` section are just varying levels of specificity to catch the more recently saved caches.

If you pop up to the [Restoring Cache](https://circleci.com/docs/2.0/caching/#restoring-cache) section in that doc, you'll see that explained better. Hope that helps! :)
