### ISSUE TITLE
Update PHP Example to use composer.lock 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1635]
From a Zendesk ticket. 

For your circle 2.0 system you have an example for PHP that uses a cache key based on the checksum of composer.json.

This must be composer.lock.

You can change your vendor dependencies by running composer update and it will update the lock file but won't change the composer.json.

**Comment by deviantintegral** [comment]
I think this depends on if you are building a library or an application.

If you are building a library, you won't be committing composer.lock. If you don't touch your composer.json, then caching on it is OK, though you won't automatically pick up any upstream dependencies that have upgraded.

If you're building an application, then you should probably key on both composer.json and composer.lock. That way, you will ensure dependencies are locked to the right versions, and any config or extra keys in composer.json are picked up too.

**Comment by felicianotech** [comment]
cc @ryanwohara

**Comment by Potherca** [comment]
Although @deviantintegral is correct when stating 

> If you are building a library, you won't be committing composer.lock.

I don't agree with

> If you're building an application, then you should probably key on both composer.json and composer.lock. That way, you will ensure dependencies are locked to the right versions, and any config or extra keys in composer.json are picked up too.

It would be better to add a step to `composer validate`.

Regardless, I would strongly advise to change the example to use the `composer.lock` file, for the simple reason that the overwhelming majority of developers are _not_ working on a library (or package) but on applications.

Those that _are_ working on packages (and not committing their `composer.lock` files) will most likely simply substitute the lock with the regular file, as they are already less focussed on the lock file.

Worst case, a comment could be added explaining this (i.e. "unless you have not committed your `composer.lock` file, in which case the `composer.json` file should be used to calculate the checksum)".

**Comment by ryanwohara** [comment]
Oh this has been a thing for a long time
https://github.com/CircleCI-Public/circleci-demo-php-laravel/blob/circleci-2.0/.circleci/config.yml#L15
