### ISSUE TITLE
language-go: Print out the whole file at some point

### ISSUE THREAD

**Issue by kevinburke** [circleci/circleci-docs#1649]
This issue is about <https://circleci.com/docs/2.0/language-go/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-go.md>)

It's hard to get a sense for the correct level of indentation for each of the keys, without being able to see the whole file. Even if it was printed at the end, that would be helpful.

**Comment by felicianotech** [comment]
Even with the link to the full config file a the top of the doc?

**Comment by smart-alek** [comment]
@kevinburke We're actually going to be turning all of these language guides into commented `config.yml` files eventually. You can see the [Elixir guide](https://circleci.com/docs/2.0/language-elixir/) for a preview of what that might look like.

But for now! @felicianotech's recommendation of just checking out the GitHub repo is your best bet. :)
