### ISSUE TITLE
Android connected test on Circle 2

### ISSUE THREAD

**Issue by alexandru-calinoiu** [circleci/circleci-docs#1655]
In this article https://circleci.com/docs/1.0/android/ targeted for circle 1.0 looks like is possible to run android connected tests, any idea on how to do this on circle 2?

**Comment by DanToml** [comment]
@alexandru-calinoiu Hey :wave: - On 2.0 we recommend using [Firebase Test Lab](https://firebase.google.com/docs/test-lab/) with [this gradle plugin](https://github.com/gildor/gradle-firebase-test-lab-plugin) to get the best possible results for connected tests.

**Comment by alexandru-calinoiu** [comment]
Got it, thank you.

**Comment by halfhp** [comment]
@DanToml That plugin appears to be dead, or at least no longer available from plugins.gradle.org :(
