### ISSUE TITLE
`filters` parent unclear

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#1660]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>)

I was wondering if `filters` in the workflow section can be a child of a `<workflow name>` or only a `<job name>` within a workflow.  Examples on other pages only point to the latter.

It seems tedious to have to add the same filters for each job in a workflow, but that's not a docs issue.

**Comment by smart-alek** [comment]
@eric-hu I checked in with the workflows team on this one. Did the formatting of this article make it confusing as to which parent `filters` was attached to? I agree that it would be helpful to be able to specify filters at the workflow level, but I _also_ agree that it's not a docs issue. :)

**Comment by eric-hu** [comment]
@smart-alek The formatting is clear to me today.  I'm not sure if the formatting changed much between now and then, or if I was just having a slow brain day :)  I did confirm that one can't set filters on a workflow currently, though.  The docs could be clearer if they call that out.

**Comment by smart-alek** [comment]
SUPERB.
