### ISSUE TITLE
Handling tox in version 2.0

### ISSUE THREAD

**Issue by djrtwo** [circleci/circleci-docs#1665]
This issue is about <https://circleci.com/docs/2.0/language-python/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-python.md>)

It is not clear how to use tox.ini in the new version of circleci config files.

Get the following error when using tox.ini without a config.yml
```
ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError("Failed to get version_info for python3.5: pyenv: python3.5: command not found\n\nThe `python3.5' command exists in these Python versions:\n  3.5.1\n  3.5.2\n  3.5.3\n\n",)
```

**Comment by smart-alek** [comment]
Hey @djrtwo, this is somewhat late, but hello! Thanks for the feedback!

First: did you figure out your problem? If not, have you checked out this [Discuss thread](https://discuss.circleci.com/t/testing-in-different-environments/450/13). The small `config.yml` at the bottom of the thread seems like it handles your situation quite nicely.
