### ISSUE TITLE
Unable to find instructions for Bitbucket

### ISSUE THREAD

**Issue by musikele** [circleci/circleci-docs#1667]
This issue is about <https://circleci.com/docs/2.0/gh-bb-integration/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/gh-bb-integration.md>)

Instructions are about Github and CircleCI, what if I have to push to a bitbucket repository?

**Comment by smart-alek** [comment]
Hey @musikele! Thanks for the feedback.

Can you take a look at #2133 and see if that's in the same ballpark as your issue? I'm narrowing some of the work that needs to be done on this document, and I'm fairly sure these are related.

**Comment by musikele** [comment]
Hi there, I confirm those two are the same thing
