### ISSUE TITLE
Setting Up a Job Step to Decode Credentials is confusing

### ISSUE THREAD

**Issue by dhagge** [circleci/circleci-docs#1670]
This issue is about <https://circleci.com/docs/2.0/google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/google-container-engine.md>)

The section "Selecting a Base Image" references using `google/cloud-sdk` and the "Setting Up a Job Step to Decode Credentials" section references a custom docker container hosted out of the GCP container registry with auth username/password specified.

I found this quite confusing as in the example I changed `- image: gcr.io/project/image-name` to be `- image: google/cloud-sdk` which fails on build with the error `Error response from daemon: Get https://registry-1.docker.io/v2/google/cloud-sdk/manifests/latest: unauthorized: incorrect username or password`.

After some digging I figured out the issue was that specifying auth fails since `google/cloud-sdk` is a public docker image, but I think this should be drawn out better in the docs.

**Comment by arekkas** [comment]
I stumbled on this as well! Thank you!

**Comment by ssinhas** [comment]
I have the same issue. Documents is really vague and not very  helpful. 
Github links takes to repo which is nothing to  do  google cloud.
