### ISSUE TITLE
Add best practices for running Tox w/ CircleCI (_cci1/language-python.md)

### ISSUE THREAD

**Issue by sfermigier** [circleci/circleci-docs#168]
Tox is a fairly standard test runner for Python. Having some comments on best practices for running tox tests under circle would be a useful addition to this document.

**Comment by smart-alek** [comment]
@sfermigier thanks for raising this! We'll keep an eye on the test runners we include in our 2.0 documentation. [Check it out](https://circleci.com/beta-access/) if you haven't already! :)
