### ISSUE TITLE
yarn version

### ISSUE THREAD

**Issue by ForbesLindesay** [circleci/circleci-docs#1692]
This issue is about <https://circleci.com/docs/1.0/yarn/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/yarn.md>)

How do I set the yarn version? These instructions seem to result in a very old version of yarn.

**Comment by felicianotech** [comment]
You don't. That page list the version of Yarn available within the image. There isn't instructions to install it.

To use a newer version of Yarn, you have the following options:

1. Wait until the Ubuntu 14.04 image in CircleCI 1 gets updated. This should happen very soon.
2. Install a newer version of Yarn yourself.
3. Use CircleCI 2.0, with an image that has the version of Yarn that you want.

**Comment by ForbesLindesay** [comment]
There does not appear to be any documentation for how to use yarn with CircleCI 2.0

**Comment by felicianotech** [comment]
The only documentation would be what's available on Yarn's website. As far as CircleCI is concerned, you'd need to use a Docker image that has Yarn included. [Our NodeJS image](https://hub.docker.com/r/circleci/node/) includes it, the [Docker Library image](https://hub.docker.com/_/node/) includes it, and many other images do as well.

If you're building your own, then you should install Yarn according to the instructions here: https://yarnpkg.com/en/docs/install
