### ISSUE TITLE
.circleci/config.yml  Minimum Requirements for Docker Better Explanation

### ISSUE THREAD

**Issue by pgensler** [circleci/circleci-docs#1699]
I am a little bit concered about this piece of documentation:

This issue is about <https://circleci.com/docs/2.0/custom-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/custom-images.md>)

Let's say I just want to see if my container RUNS on Circle CI. If I use that config.yml file supplied on that webpage above, and try to validate it using the CLI, I get the following error:

![image](https://user-images.githubusercontent.com/7308115/32025219-f22d6d44-b9a4-11e7-8425-8267fab32ec8.png)

So according to this, this is clearly invalid. My question is, what is the minimum requirements for me to have in my config.yml spec to run a container?? Do I need:

test:
    - docker run -ti -v $(pwd):/tmp -w /tmp rocker/verse ./tests.sh

Thanks.

**Comment by felicianotech** [comment]
This shows you how to do it: https://circleci.com/docs/2.0/custom-images/#using-your-image-on-circleci

That runs your Docker Image as the build environment.

If you want to actually build your image, then you can use this: https://circleci.com/docs/2.0/building-docker-images/

If you have follow up questions, please use [CircleCI Discuss](https://discuss.circleci.com).
