### ISSUE TITLE
Add Example to POST /user/heroku-key

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1706]
The following method shows up the API summary. 

```
POST: /user/heroku-key
    Adds your Heroku API key to CircleCI, takes apikey as form param name.
```

But there is no example of it in the detailed documentation.

**Comment by felicianotech** [comment]
@levlaz This is for the API doc correct?

**Comment by levlaz** [comment]
Yes that is correct.

**Comment by iynere** [comment]
looks like it's there now : https://circleci.com/docs/api/v1-reference/#heroku-keys
