### ISSUE TITLE
Php versions not up to date 

### ISSUE THREAD

**Issue by Petrucheqa** [circleci/circleci-docs#1714]
This issue is about <https://circleci.com/docs/1.0/build-image-trusty/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/build-image-trusty.md>)

I tried to deploy with PHP version 7.1.0 and get this error message 

Sorry, we don't support the version of php you specified. Check our list of supported versions and contact us if we should support your version.

**Comment by dgallegos** [comment]
Another PHP version out of date
https://circleci.com/docs/1.0/language-php/

Pull request to fix
https://github.com/circleci/circleci-docs/pull/1719

**Comment by felicianotech** [comment]
This was fixed in #1717.
