### ISSUE TITLE
Scripts in .circleci folder

### ISSUE THREAD

**Issue by Rauno56** [circleci/circleci-docs#1722]
This issue is about <https://circleci.com/docs/2.0/deployment_integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment_integrations.md>)

The documentation leaves an impression that it's possible to share deployment scripts(example of Heroku in the doc) through `.circleci` folder. It's seems that it actually does not work that way.

How should sharing such scripts be done then?

**Comment by felicianotech** [comment]
What do you mean by share deployment scripts?

**Comment by Rauno56** [comment]
I mean the case of `.circleci/setup-heroku.sh` in the referenced documentation page.
