### ISSUE TITLE
Please add mysql configuration example too, as I didn't manage to get mysql running

### ISSUE THREAD

**Issue by tangorboyz** [circleci/circleci-docs#1730]
This issue is about <https://circleci.com/docs/2.0/postgres-config/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/postgres-config.md>)

**Comment by smart-alek** [comment]
@tangorboyz hello! My apologies for the delayed response!

Can you help me flesh out your issues with the doc? Was the article so Postgres-focused that you couldn't apply the same principles to MySQL? What sort of bugs were you running into as you were trying to set up MySQL?

What I'm hearing is that there should probably a generalized "Configuring Databases" article that discusses shared behavior. Beneath that, we could have documents that are DB-specific (for those little wrinkles).
