### ISSUE TITLE
store_artifacts will not work without certs e.g. ca-certificates

### ISSUE THREAD

**Issue by tupev** [circleci/circleci-docs#1740]
This issue is about <https://circleci.com/docs/2.0/artifacts/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/artifacts.md>)

Using custom alpine docker image and tried to store_artifacts after test run:

```
Uploading /tmp/reports to tmp/reports
Failed uploading file /tmp/reports/load_test_report
Error RequestError: send request failed
caused by: Put https://circle-production-customer-artifacts.s3.amazonaws.com/picard/...-build/artifacts/tmp/reports/load_test_report: x509: failed to load system roots and no roots provided
Failed uploading file /tmp/reports/load_test_report.html
Error RequestError: send request failed
caused by: Put https://circle-production-customer-artifacts.s3.amazonaws.com/picard/...-build/artifacts/tmp/reports/load_test_report.html: x509: failed to load system roots and no roots provided
```

I was able to solve this by installing ca-certificates to the Docker alpine image. However, this dependency should be mentioned in the artifacts documentation page.

**Comment by felicianotech** [comment]
This is mentioned here: https://circleci.com/docs/2.0/custom-images/#adding-required-and-custom-tools-or-files

Is that enough? Do you think a paragraph should be added to the artifacts doc? Or, how about a link in the artifacts doc to the section link I provided?

**Comment by iynere** [comment]
added txt to the custom images section explicitly noting that various CCI services (artifacts, test results, etc.) will not work w/o the listed mandatory tools—feel free to close this issue when the PR is merged
