### ISSUE TITLE
Please add v2 docs for "Continuous Deployment with npm"

### ISSUE THREAD

**Issue by callumlocke** [circleci/circleci-docs#1742]
v1 docs are here: https://circleci.com/docs/1.0/npm-continuous-deployment/

I can't find a v2 equivalent.

**Comment by smart-alek** [comment]
@callumlocke thanks for this! 2.0 definitely has a few gaps, and we're working to fill those in. I'll add "publishing packages to the NPM registry" to the list.

But! In the meantime (and I realize you wrote this in November), did you fix your issue or are you still trying to do this?
