### ISSUE TITLE
The badge I'm offered from my project page show red even though the build succeeded

### ISSUE THREAD

**Issue by retorquere** [circleci/circleci-docs#1757]
This issue is about <https://circleci.com/docs/1.0/status-badges/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/status-badges.md>)

I am offered this badge code:

```
[![CircleCI](https://circleci.com/gh/retorquere/zotero-better-bibtex/tree/master.svg?style=svg)](https://circleci.com/gh/retorquere/zotero-better-bibtex/tree/master)
```

but the badge is always red regardless of build status.

**Comment by iynere** [comment]
hi there, please open a support ticket if you're having trouble getting your status badge to work—thanks !!
