### ISSUE TITLE
That's so vague and confusing

### ISSUE THREAD

**Issue by berardo** [circleci/circleci-docs#1758]
This issue is about <https://circleci.com/docs/2.0/google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/google-container-engine.md>)

In 1.0 docs, this section used to be so well written, but now there's not even a complete example or an explanation that kind of make more sense.

Seriously, I'm having a hard time putting this to work :(

**Comment by levlaz** [comment]
Thanks for the feedback, will work on improving this.

**Comment by smart-alek** [comment]
For reference: some others have found some issues with the same article: https://github.com/circleci/circleci-docs/issues/1670

Any overlaps with your particular concerns?

**Comment by smart-alek** [comment]
Closing this in favor of more specific issues! Feel free to comment if you've got something more concrete for us @berardo!
