### ISSUE TITLE
Add warning that only things in the home folder can be cached (_cci1/how-cache-works.md)

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#176]
RE: jekyll/_docs/how-cache-works.md

Right now only things in the home folder (owned by the `ubuntu` user) may be cached. To reduce confusion we should make this explicit in the doc. 

If someone needs to cache something that is not owned by the ubuntu user they can either: 
1. install the dependencies into the home folder rather than the standard location 
2. Change the ownership of the directory outside of home to be owned by the ubuntu user

**Comment by felicianotech** [comment]
Hey so to be clear, the rule isn't that something needs to be in `$HOME` to be cached but rather needs to be owned by the `ubuntu` user correct? Does the group matter at all?

**Comment by levlaz** [comment]
That is right, just things owned by ubuntu. However you need to be careful.
For example if you `chown -R ubunut:ubuntu /` and try to cache root it will
not work (and even if it did it would be a 60+GB cache that would take two
hours to restore.)

This is why to be safe we just tell people to install things into $HOME and
then on a case by case basis chown the file if you absolutely must cache
it.

**Comment by eric-hu** [comment]
@levlaz out of curiosity, are there other reasons that taking ownership of `/` would fail besides size limitations?

**Comment by levlaz** [comment]
Yes, there are some files and directories that you cannot actually own as
the `ubuntu` user even if you chown them, so this will cause a failure.

**Comment by smart-alek** [comment]
More context [here](https://discuss.circleci.com/t/circle-bug-error-restoring-cache/422).

**Comment by smart-alek** [comment]
This might still be applicable to 2.0, but closing for now unless I hear otherwise from @eric-hu or @levlaz.
