### ISSUE TITLE
1.48.5 (latest version of 1.0 is required) in order to do the db upgrades. 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1766]
This issue is about <https://circleci.com/docs/2.0/upgrading/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/upgrading.md>)

In order to run the upgrade scripts, you must be running 1.48.5 (latest version of 1.0), we should make this more explicit.

**Comment by iynere** [comment]
thanks !!

**Comment by iynere** [comment]
feel free to close this once the PR is merged
