### ISSUE TITLE
Tags section example, contains examples of filtering in base of branch.

### ISSUE THREAD

**Issue by vaukalak** [circleci/circleci-docs#1769]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/#tags/> (source file: <https://circleci.com/docs/2.0/configuration-reference/#tags>). All examples under this section show how to filter in base of branch. But no one show how to filter in base of tag.

**Comment by iynere** [comment]
hi there, you can see an example of tag filtering on the Workflows page — https://circleci.com/docs/2.0/workflows/#git-tag-job-execution — which is already linked to here: https://circleci.com/docs/2.0/configuration-reference/#filters-1
