### ISSUE TITLE
Historical tests timing is not automatically available

### ISSUE THREAD

**Issue by axelson** [circleci/circleci-docs#1771]
This issue is about <https://circleci.com/docs/2.0/parallelism-faster-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/parallelism-faster-jobs.md>)

> CircleCI automatically makes timing data from previous successful runs available inside your container in a default location so the CLI tool can discover them ($CIRCLE_INTERNAL_TASK_DATA/circle-test-results).

The snippet above is incorrect. You have to manually specify `store_test_results` in your jobs:

https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by iynere** [comment]
> CircleCI automatically makes timing data from previous successful runs available inside your container in a default location so the CLI tool can discover them ($CIRCLE_INTERNAL_TASK_DATA/circle-test-results).
this is actually true. `store_test_results` is simply how you add your current run's test results to the aggregate timing data. however, https://circleci.com/docs/2.0/parallelism-faster-jobs should definitely mention `store_test_results` at some point, so i will add that in. thank you !

**Comment by iynere** [comment]
feel free to close this once this PR is merged: https://github.com/circleci/circleci-docs/pull/1841

**Comment by bf4** [comment]
Are there any examples of anyone using timing data via CIRCLE_INTERNAL_TASK_DATA?  I've searched the discuss, the github, the web, and cannot find nary a one. Just a few mentions.  (I also commented in #1598)
