### ISSUE TITLE
Detail lifespan of caches

### ISSUE THREAD

**Issue by steprescott** [circleci/circleci-docs#1781]
If would be good to document the cacheing strategy that CircleCI use when deeming if a cache should be deleted or how long they last.

This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

**Comment by iynere** [comment]
hi there, we don't delete caches—they are immutable (see https://circleci.com/docs/2.0/caching/#clearing-cache)
