### ISSUE TITLE
Bad assumption

### ISSUE THREAD

**Issue by oneandoneis2** [circleci/circleci-docs#1786]
This issue is about <https://circleci.com/docs/2.0/high-uid-error/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/high-uid-error.md>)

I hit the error yesterday and whilst the page was very helpful in explaining the problem, it didn't get me to where I could fix it.

Neither the find command suggested, nor any other approach, could find me any file with a too-high UID.

In the end, I discovered that it was one of the interim steps in building the container that was creating the bad file, but that file was gone by the time the final image was generated.

To fix it, I had to modify the "RUN" step in the Dockerfile, adding "&& chown -R root:root /root" to the problem step. This meant that the problem file was created and fixed all in one step and thus didn't create a bad interim.

The assumption in the docs is that the bad file will still exist in the image when it's run, but this is clearly not necessarily the case. Updating to explain that a bad file can be created, removed, and still cause a problem; and how to debug & fix this, would be very helpful.

**Comment by smart-alek** [comment]
Hey @oneandoneis2, thanks for the feedback! You're not the only one who wants additional clarification around this (#1639). We're actually going to be pulling this page out of documentation and into a place that collects Known Issues (and their workarounds).

Will keep you in the loop!
