### ISSUE TITLE
How to do test coverage badge?

### ISSUE THREAD

**Issue by cbare** [circleci/circleci-docs#1802]
This issue is about <https://circleci.com/docs/1.0/status-badges/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/status-badges.md>)

**Comment by iynere** [comment]
hi there, https://circleci.com/docs/1.0/status-badges explains how to use our status badges—we don't provide test coverage badges. if you're having issues using our status badges, feel free to open a support ticket.

**Comment by andrew-synapse** [comment]
+1 for test coverage badge

**Comment by tylim88** [comment]
+1 for test coverage badge

**Comment by phamquiluan** [comment]
+1 for test coverage badge

**Comment by romansorochak** [comment]
+1 for test coverage badge
