### ISSUE TITLE
Add contents of `deploy.sh` inline to _cc1/continuous-deployment-with-aws-ec2-container-service.md

### ISSUE THREAD

**Issue by jimmycuadra** [circleci/circleci-docs#182]
This document describes what the `deploy.sh` script does, but doesn't actually display it, nor does it have a direct link to it on an external page. There is a link at the very top of the article to the sample project (https://github.com/circleci/go-ecs-ecr) that contains this script, but I think it'd be easier to follow the document if it included the relevant code inline with the explanations, or there was a direct link to the file you could bring up in another tab without having to dig through links to find the code.

**Comment by felicianotech** [comment]
Familiar with GitHub Gists? Do you think having a Gist of the file embedded would help or would you rather direct, discrete snippets?

**Comment by jimmycuadra** [comment]
Anything that makes the code appear inline on that document would be an improvement from the reader's perspective, I think. Using a Gist might be annoying to maintain, though, since it'd be a duplicate of the code in the go-ecs-ecr repository.

**Comment by smart-alek** [comment]
@felicianotech unless you have `deploy.sh` on hand, I'm closing this in favor of 2.0 docs.

@jimmycuadra we'll be sure to drop shell scripts into docs where we can in 2.0. Thanks for calling this out! :)
