### ISSUE TITLE
Please document Android NDK best practice 

### ISSUE THREAD

**Issue by joebowbeer** [circleci/circleci-docs#1876]
This issue is about <https://circleci.com/docs/2.0/language-android/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-android.md>)

The NDK *was* installed but now it isn't, and neither `ANDROID_NDK` nor `ANDROID_NDK_HOME` is exported now, right?

Can you document the preferred approach for configuring the NDK?

A sample configuration file/project that used NDK would be helpful, too.

**Comment by levlaz** [comment]
Thanks for the note. I added a new issue in the images repo to see if we can bake the ndk into the image. https://github.com/circleci/circleci-images/issues/138 

For now, the best way to do this would be to bake your own image that sets all of these envvars. You could also use an existing image, there are a ton of them out there. https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=android-ndk&starCount=0

**Comment by smart-alek** [comment]
@joebowbeer @levlaz #1907 updates the wording to stress that our provided image doesn't necessarily include everything you might need for development. Closing this issue in favor of [linked issue](https://github.com/circleci/circleci-images/issues/73) in the images repo

**Comment by joebowbeer** [comment]
Currently, there is no NDK installed and there are no directions on how to install one. (I don't think #1907 is going to help anyone who is looking for an NDK.) This represents a regression from the previous state, and the [issue](https://github.com/circleci/circleci-images/issues/73) to add NDK images has been open since August. I would prefer to keep this issue open until the NDK images have been added.

**Comment by smart-alek** [comment]
@joebowbeer I hear you. :) What I've done is added a line specific to NDK with the advice that @levlaz gave above. I realize It's only a stopgap, but it accurately reflects our recommended solution until the NDK-specific images have been added.

Let me know if this improves anything!
