### ISSUE TITLE
Missing region

### ISSUE THREAD

**Issue by bruce-hartley** [circleci/circleci-docs#1878]
This issue is about <https://circleci.com/docs/2.0/single-box/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/single-box.md>)

Please can you add an ami for the uk region eu-west-2
Also, can self-hosting circleci be used with a self-hosted bitbucket or gitlab?

thanks
Bruce

**Comment by levlaz** [comment]
Hey bruce, 

> Please can you add an ami for the uk region eu-west-2
Looking into this, thanks! 

> Also, can self-hosting circleci be used with a self-hosted bitbucket or gitlab?
No, we only support Github Enterprise, github.com and bitbucket.com at this time.

**Comment by smart-alek** [comment]
@bruce-hartley I followed up on that region for you, and it looks like the docs show all the regions we currently support. Once our provisioning team adds that AMI, we'll update the docs accordingly!
