### ISSUE TITLE
There is no details about how the output of a build job gets into a deploy job.

### ISSUE THREAD

**Issue by agrabren** [circleci/circleci-docs#1879]
This issue is about <https://circleci.com/docs/2.0/deployment_integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment_integrations.md>)

Documentation about how data is passed between build and deploy is non-existent. Am I supposed to rebuild the artifacts in the deploy job? Does it magically copy some stuff? Which stuff?

A better sample would be to have a build step create a sample file (via an echo statement) and a deploy step upload that or even just view it. That way, we can see how it is supposed to work.

**Comment by levlaz** [comment]
Hey! Thanks for the note. 

The document you linked to links to the workflows documentation which includes a section on [workspaces](https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs) this is the officially supported method for sharing data between jobs.

**Comment by agrabren** [comment]
I had finally found that. It feels like it could be called out a bit clearer.
A great sample for the entire system would be to have two build jobs, each which generates a simple text file via echo statements. Then, a packaging step which takes those and creates a concatenation of them, and finally a test/deploy step which verifies that output and dumps it to the output.
This would give a great sample of parallelism, workspaces, and the deploy section, all with something that is extremely language agnostic so it could be applied to any project. The samples are a bit sparse and could use a single "master" sample that does a bit of "everything".
    On Saturday, December 30, 2017, 2:38:53 PM MST, Lev Lazinskiy <notifications@github.com> wrote:  
 
 
Hey! Thanks for the note.

The document you linked to links to the workflows documentation which includes a section on workspaces this is the officially supported method for sharing data between jobs.

**Comment by smart-alek** [comment]
@agrabren Thanks for the feedback! I've gone ahead and added a couple of links: one to workflow job filtering, and the other for sharing data between jobs. You can see the changes in #1903.

I've also added your suggested example to our backlog. A "master" sample that combines a smattering of features and best practices is definitely needed! Thanks again for the ideas! 👍
