### ISSUE TITLE
Xcode version 9.2.0 is supported

### ISSUE THREAD

**Issue by LukasAuerbeck** [circleci/circleci-docs#1885]
This issue is about <https://circleci.com/docs/1.0/build-image-macos/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/build-image-macos.md>). I was able to start a new build on an Xcode 9.2.0 machine and ran tests with an iPhone 6 and iOS 11.2.

**Comment by smart-alek** [comment]
Thanks for catching this! Xcode 9.2.0 is the last version of macOS we'll be supporting for CircleCI 1.0 — all future support will only be for our CircleCI 2.0 platform.

I'll go ahead and update the documentation for accuracy's sake. See #1901 for details!
