### ISSUE TITLE
Improve Documentation on How Regex Matching works 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1886]
There has been a little bit of confusion around this. 

> it seems that the regex has to fully match the tag name, rather than just match a substring inside the tag name (as if there is an implicit ^ and $ around the provided regex).

**Comment by smart-alek** [comment]
@levlaz Are you quoting yourself here? 😄

**Comment by smart-alek** [comment]
@levlaz see if #1896 works for you

**Comment by levlaz** [comment]
Haha. No that was a quote from a ticket that came in. #1896 looks perfect thank you!
