### ISSUE TITLE
Sequential Workflow link/page not found/working

### ISSUE THREAD

**Issue by stonehz** [circleci/circleci-docs#1887]
This issue is about <https://circleci.com/docs/2.0/tutorials/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/tutorials.md>)

**Comment by stonehz** [comment]
https://github.com/CircleCI-Public/circleci-demo-workflows/issues/13 linked.

**Comment by zzak** [comment]
Whoops, should be fixed now.

Thanks for your report!
