### ISSUE TITLE
How to store test results for workflows?

### ISSUE THREAD

**Issue by binkley** [circleci/circleci-docs#1889]
This issue is about <https://circleci.com/docs/2.0/collect-test-data/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/collect-test-data.md>)

The docs say storing test results is not supported for workflows.  What is the approach for them?

**Comment by michelle-luna** [comment]
Thanks, we have a PR to update this content which is out for engineering review, so you can follow it here https://github.com/circleci/circleci-docs/pull/1849

**Comment by smart-alek** [comment]
Closing this in light of recent merge of #1849. 🎉
