### ISSUE TITLE
Is it possible that slack notification contents defined by user?

### ISSUE THREAD

**Issue by chenlifeihub** [circleci/circleci-docs#1898]
This issue is about <https://circleci.com/docs/2.0/notifications/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/notifications.md>)

**Comment by smart-alek** [comment]
Hi @chenlifeihub! We currently don't support user-defined content for Slack notifications. But you're  [not alone](https://discuss.circleci.com/t/notification-enhancement/1328) in wanting this!

If you have any future questions, drop by our [Discuss forum](https://discuss.circleci.com/); it's usually a good spot to find answers. :)

**Comment by chenlifeihub** [comment]
Thanks!
