### ISSUE TITLE
Workflow docs need improvement

### ISSUE THREAD

**Issue by mikhail** [circleci/circleci-docs#1933]
https://circleci.com/docs/2.0/workflows/ jumps into examples before providing a clear documentation of reserved keywords and expected behavior.

It is unclear whether the first keys inside the `workflows` dictionary have a specific meaning, what that meaning is, and what all the available keys are. One key `btd`, presumably acronym for "build test deploy" is used in an example without any documentation.

Suggestion: Before the "Workflows Configuration Examples" section, add a full spec of expected keywords, allowed values and defaults.

**Comment by smart-alek** [comment]
Hey @mikhail, thanks for the feedback!

So what I'm hearing here is that you'd rather see something like our [Workflows Reference](https://circleci.com/docs/2.0/configuration-reference/#workflows) before jumping into examples, yeah?

**Comment by mikhail** [comment]
Yes! thanks!

When a workflow is not configured CCI presents the following message:

> To orchestrate multiple jobs, add the workflows key to your config.yml file.
> See the [workflows documentation](https://circleci.com/docs/2.0/workflows/) for examples and instructions.

So that was my starting point. A link to the "Workflows Reference" as you've provided would suffice. I see now that the link is available under See Also, but as important as this documentation is - this should be linked earlier and "louder" so to speak.
