### ISSUE TITLE
Make this page consistent 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1936]
There are a handful of inconsistencies (specifically 9.5 vs 9.6) that is causing some confusion for users. We should pick one version and stick with it. 

This issue is about <https://circleci.com/docs/2.0/postgres-config/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/postgres-config.md>)

**Comment by levlaz** [comment]
Also some sections use apt without `sudo`. This should be fixed.

**Comment by michelle-luna** [comment]
Thanks Lev, I will work on this one since this doc is my fault ;)
