### ISSUE TITLE
The android sample app is not a sample app :) 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1937]
This issue is about <https://circleci.com/docs/2.0/demo-apps/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/demo-apps.md>)

**Comment by smart-alek** [comment]
@levlaz Are you saying this is because it's using React Native?

Arguably, we should delete either the "React Native" or "Android" category since they are both pointing to the same repository.

**Comment by levlaz** [comment]
No, check the first link. It goes to the android image instead of an app.

**Comment by smart-alek** [comment]
Got it, Lev — check that linked PR; it should be better now. 😸
