### ISSUE TITLE
Document gcloud for 2.0 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#1938]
This issue is about <https://circleci.com/docs/1.0/google-auth/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/google-auth.md>)

We started recommending that folks use [gcloud firebase](https://support.circleci.com/hc/en-us/articles/360000028928) for using the android emulator. The most complex part of this might be the auth. It would be worth adding a similar section from our 1.0 docs to the 2.0 docs.

**Comment by smart-alek** [comment]
@levlaz is this related at all to #1758?
