### ISSUE TITLE
Can we remove this page?

### ISSUE THREAD

**Issue by sararead** [circleci/circleci-docs#1942]
This issue is about <https://circleci.com/docs/enterprise/ios/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_ccie/ios.md>)

This is no longer relevant, as new users are not being added to the Enterprise 1.0 iOS beta.

**Comment by smart-alek** [comment]
Nice catch @sararead! I'm all for cleanup as long as @michelle-luna approves. I'll make a PR that removes this article.
