### ISSUE TITLE
mv step for docker times out due to a prompt or fails due to permission if you force "mv -f"

### ISSUE THREAD

**Issue by jsmith-phoenix** [circleci/circleci-docs#1945]
This issue is about <https://circleci.com/docs/2.0/building-docker-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/building-docker-images.md>)

![image](https://user-images.githubusercontent.com/24377680/35300396-440781ac-0056-11e8-98f1-d9f588250d0b.png)

**Comment by smart-alek** [comment]
Hey @jsmith-phoenix!

The linked document actually omits the `-f` flag; are you still having problems if you remove that?

**Comment by jsmith-phoenix** [comment]
I'm all set. I added "sudo" and "-f" to the mv call and it works fine. Thanks for following up!

**Comment by smart-alek** [comment]
@jsmith-phoenix Great to hear!

But! Just to close the docs loop: did `mv /tmp/docker/* /usr/bin` fail for you and lead you to add the `-f` flag? I'm wondering if we need to change that last line to `sudo mv -f /tmp/docker/* /usr/bin`.

**Comment by smart-alek** [comment]
Just checked the `mv /tmp/docker/* /usr/bin` step, and it seems to be working, so I'm going to close this issue @jsmith-phoenix. Happy building!
