### ISSUE TITLE
Should this text be updated for the 2.0 documentation?

### ISSUE THREAD

**Issue by pcrews** [circleci/circleci-docs#1955]
This issue is about <https://circleci.com/docs/1.0/migrating-from-jenkins/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/migrating-from-jenkins.md>)

I have a number of suggested edits for this page, but since it is related to 1.0, I am unsure if it is worth submitting a patch. The 2.0 docs contain far less text: https://circleci.com/docs/2.0/faq/#how-do-i-migrate-from-jenkins-to-circleci-20

Would like some guidance on if we want to bolster the 2.0 docs and/or if the 1.0 docs will be irrelevant before long.

**Comment by smart-alek** [comment]
Hey @pcrews! Thanks for the excellent question.

The 1.0 version of that doc is performing quite a few roles — one of which is a comparison of CircleCI's and Jenkins' features. The actual instructions on how to migrate to Jenkins are similar sizes in both the 1.0 and 2.0.

But! All current documentation efforts are focused on 2.0, and we're trying to gently guide people away from 1.0. So, if you'd like to help (and we hope you do!), bolstering the 2.0 docs will be a much better use of your time.

**Comment by smart-alek** [comment]
@pcrews Closing this issue for now, but feel free to submit a patch or PR for our 2.0 docs as a new issue. Thanks!
