### ISSUE TITLE
Docker tags on CircleCI Images Page are out of date

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1974]
The image tags displayed in https://circleci.com/docs/2.0/circleci-images/ ( or jekyll/_cci2/circleci-images.md) are out of date.

This is technically not an issue within this repo but using this as a public tracker. The issue is with the JSON file we're pulling in via _config.yml from S3 being out of date.

Tracking that down.

**Comment by felicianotech** [comment]
I'm going to solve this problem within this repo instead, making the data more accurate. PR coming soon.

**Comment by smart-alek** [comment]
@felicianotech Rather than try to keep a reference document synchronized with other repositories, perhaps we should just link to the repos and/or DockerHub for a listing of pre-build images?

In other words, should this document even exist?

**Comment by felicianotech** [comment]
Good question that I asked myself as well. I wasn't sure but I asked a few people and they thought it would be valuable to have them on the page.
