### ISSUE TITLE
There's Empty Whitespace At The Bottom of Every Page

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1978]
Under every page, after the CircleCI footer, there's a strip of whitespace. This looks to be unintentional.

**Comment by smart-alek** [comment]
@trevor-circleci mind taking a look?

**Comment by smart-alek** [comment]
@felicianotech there's a tracking pixel added by Google that's added post-CSS. It's shoving the footer around, but @trevor-circleci can't affect that. We'll need to figure out who controls that tracking pixel and remove it if possible.

**Comment by felicianotech** [comment]
That's not true. Opening a PR now.

**Comment by smart-alek** [comment]
@felicianotech it's not true that there is no tracking pixel pushing things around? Or it's not true that you can't affect it?

Either way, going to add @trevor-circleci to the PR.

**Comment by felicianotech** [comment]
That it can't be fixed. I fixed it.

**Comment by felicianotech** [comment]
The tracking pixel itself is a different issue which is always a back and forth, but that would be handled in Google Tag Manager, if ever.

**Comment by smart-alek** [comment]
Cool, I'll make an investigation ticket for that. Thanks for fixing this, @felicianotech!
