### ISSUE TITLE
Missing artifacts explanation

### ISSUE THREAD

**Issue by hamczu** [circleci/circleci-docs#1985]
This issue is about <https://circleci.com/docs/2.0/deployment-integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment-integrations.md>)

In the setup described in the docs "deploy" job doesn't have access to any files created in "build" job. There section about artifacts and passing them between the jobs is missing.

**Comment by hamczu** [comment]
Oh, I see - I should be using "workspaces" but still the setup mentioned in the docs simply doesn't work.

**Comment by smart-alek** [comment]
Hey @hamczu, glad you stumbled on the workspaces bit, but I'm going to reopen this as an issue because that example should **also** be using them.

Thanks for bringing this up!
