### ISSUE TITLE
XQuartz and VNC fail for Circle debugging after a period of time

### ISSUE THREAD

**Issue by marcysutton** [circleci/circleci-docs#1993]
Following this document, it either needs updating or appending with more troubleshooting steps: https://circleci.com/docs/1.0/browser-debugging/

I tried multiple methods on that page and they both failed in the same place: `Gtk: cannot open display`. It sounds like an X11 Forwarding issue from what I've read, but I don't know how to fix it as a Circle user.

I've gotten the XQuartz method to work before, but now it fails with the "cannot open display: localhost:10.0". This occurs when I try to open Chrome, and even when I try running `xclock`. I read somewhere that the permissions for `-X` might change/degrade over time for security reasons. Is there a way to fix this on the ubuntu test boxes somehow? 

I also tried using VNC to debug. I got the display to open, but it fails in the same place when I try to open Chrome with `/opt/google/chrome/chrome`: `Gtk: cannot open display :1.0`

My local machine is running OSX High Sierra, which changed since the last time I used SSH to debug Circle tests. But I'm not sure if that matters since I'm SSH'ing into an Ubuntu environment. 
Circle-specific debugging tips for this issue would be fantastic. Thank you!

**Comment by smart-alek** [comment]
Hi @marcysutton, and thanks for the comments!

Bad news first! This document (and 1.0 docs more generally) is almost certainly out of date. So your troubles do not surprise me. The end of 1.0 is also on the horizon, so we're no longer updating 1.0 documentation. But! Have you popped into [Discuss](https://discuss.circleci.com/) to see if there's anything more current related to VNC debugging?

Now the good news! We're actively moving troubleshooting "documentation" like this over to our [Support Center](https://support.circleci.com/hc/en-us). So I'm going to ping some support folks to add this to their list.
