### ISSUE TITLE
If I leave the hostname blank, the ssh key disappeared.

### ISSUE THREAD

**Issue by LeiZeng** [circleci/circleci-docs#1995]
This issue is about <https://circleci.com/docs/1.0/permissions-and-access-during-deployment/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/permissions-and-access-during-deployment.md>)

Hi, I tried to use blank hostname for the ssh key, but I can't find the key, could you please help me to sort it out?

Thanks.

**Comment by smart-alek** [comment]
Hi @LeiZeng! Do you mean that you already generated an SSH key, and it disappeared when you entered a blank hostname?

**Comment by LeiZeng** [comment]
Sorry I have resolved this one, I have forgot to use the add_ssh_key annotation...
