### ISSUE TITLE
What does the --delete option do?

### ISSUE THREAD

**Issue by bmansheim** [circleci/circleci-docs#1996]
This issue is about <https://circleci.com/docs/1.0/continuous-deployment-with-amazon-s3/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-amazon-s3.md>)

It would be helpful to have more explanation for what the --delete option does. Does it delete all of the files before the deploy begins or does it delete all of the files that were not updated during the deploy?

**Comment by smart-alek** [comment]
Hi @bmansheim!

`--delete` will delete files that exist in the destination but not in the source. This is actually a flag for the [sync command](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) of the AWS CLI.
