### ISSUE TITLE
What is the difference between browsers and stretch-browsers

### ISSUE THREAD

**Issue by toddself** [circleci/circleci-docs#2009]
The list of docker images is helpful, but like, the lack of any sort of description of what the differences are is beguiling.

This issue is about <https://circleci.com/docs/2.0/circleci-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/circleci-images.md>)

**Comment by smart-alek** [comment]
Hello @toddself! You are absolutely correct, and all beguilement was unintentional!

What we're in the middle of doing is making it more clear what's in each available image, along with how the variants are attached to the "base" image name. In this case, `stretch-browsers` would be the official Docker `stretch` image, along with browsers and libraries normally used for windowing. The more dashes, the more extra stuff you get!

But all this will become clearer, and I'll attach the PR once we've got it ready.

**Comment by toddself** [comment]
Hi!

So the biggest frustration I experienced this morning was that this is mentioned no where in the example node config. The node:6 image has xvfb and xlib, but not enough other stuff installed to actually, like, run x apps (namely electron which requires gtk2 installed.). 

So the fact that there is no indication as to what each container contains (and that the base one actually has Xvfb, but not enough other stuff to be useful for this). 

All of my experiences with version 2 so far feel very half-baked and its disppointing that you are forcing it on paying customers.

**Comment by smart-alek** [comment]
@toddself thanks for the details!

So, I'm hearing that you want more context around what each image has in it **when** you're actually using the image. Can you point me to the example node config you were using to set up? @felicianotech also opened #2012 to get some improved info into this doc.

As for the half-baked bits... I hear you! Customers who _have_ been able to get up and running are enjoying the speed, but I get that there's room for improvement — especially in how we communicate new formats and abstractions. But hearing feedback from you and others is the only way we get better, so thanks for taking the time to give it to us! :)

**Comment by felicianotech** [comment]
@jasonworden Yes. These questions are best asked in [CircleCI Discuss](https://discuss.circleci.com).

**Comment by philihp** [comment]
Debian Stretch as opposed to what?

@felicianotech this thread comes up higher in google search relevance than a thread in CircleCI's forums. Could you link to a specific thread, or perhaps explain [here](https://circleci.com/docs/2.0/circleci-images/#language-image-variants)?

**Comment by felicianotech** [comment]
This is mostly controlled by upstream projects. We don't control what tags they use and their meanings. In this specific case yes `stretch` means the Debian Stretch release of Debian. Problem is, that doesn't mean a different image can't use that name to mean something else.

I wouldn't know the best place to document this information or even how. @smart-alek thoughts?

**Comment by smart-alek** [comment]
@felicianotech I think we can (and should) add this caveat to the top of [this document](https://circleci.com/docs/2.0/circleci-images/). That should help stave off any confusion about the naming schema (or lack thereof!).
