### ISSUE TITLE
RE: jekyll/_docs/language-php.md

### ISSUE THREAD

**Issue by mpscholten** [circleci/circleci-docs#202]
The xdebug section says `sed -i 's/^;//' /opt/circleci/php/$(phpenv global)/etc/conf.d/xdebug.ini` enables xdebug. This does not work (tried with php 7.0.4 and php 5.5.9). Changing it to `sed -i 's/^;//' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini` worked.

**Comment by felicianotech** [comment]
Which build image are you using? Note the following at the top of the guide: 

> The examples here referring to PHP filepaths are for the Ubuntu 14.04 and newer images. This image is not default but can be choosen in Project Settings -> Build Environment. For Ubuntu 12.04, replace /opt/circleci/php with ~/.phpenv/versions in the examples.

If you are using Ubuntu 12.04 then this is expected. Otherwise, there's a problem we need to look into.

**Comment by mpscholten** [comment]
Ok, that's it. Thanks for pointing out :)
