### ISSUE TITLE
DLC is confusing

### ISSUE THREAD

**Issue by ryanwohara** [circleci/circleci-docs#2027]
https://circleci.com/docs/2.0/docker-layer-caching/

A given end user with absolutely no Docker experience are being mislead to believe DLC will help them cache an image with the Docker executor. We should include references to `docker build` at the top of the doc.

**Comment by michelle-luna** [comment]
sorry, I did this before I checked the assignment :)

**Comment by ryanwohara** [comment]
The feedback on the new doc has been very positive. Thanks @michelle-luna!
