### ISSUE TITLE
RE: jekyll/_docs/background-process.md

### ISSUE THREAD

**Issue by leon-wu** [circleci/circleci-docs#203]
I used background: true to start the web server for testing. But it is error saying 'mapping values are not allowed here'

test:
  post:
    - npm run server
        background: true
    - npm run e2e

**Comment by felicianotech** [comment]
@leon-wu 

Two issues here.

1. The line that you are modifying (the line above background: true) needs to end in a colon `:`.
2. `background: true` needs to be indented 4 spaces from the start of the command (6 spaces from the start of the dash).

Try that out and let me know if it works out.
