### ISSUE TITLE
Unclear how to test a particular branch

### ISSUE THREAD

**Issue by LoveIsGrief** [circleci/circleci-docs#2033]
Starting out with CircleCI it took me a while to find out how to start a build on a particular branch. I'm not sure if this is a workaround, but here's where I went to trigger a build on a branch:

![spectacle tj4597](https://user-images.githubusercontent.com/2829538/36345354-0197397a-1429-11e8-9bb7-688e6df6d28f.png)

I couldn't find this anywhere in the documentation and it would be nice to have it.

Cheers!

**Comment by michelle-luna** [comment]
Hi,
Thanks for taking time to make this suggestion. I think this may be a 1.0 feature. Do you know if you are using a circle.yml file or a config.yml file (or if one doesn't appear in the Config tab of the builds page)? This will help me know where to put this info (v1.0 or 2.0).

Regards,
Michelle

**Comment by LoveIsGrief** [comment]
Hi @michelle-luna 

It's a [config.yml](https://github.com/LoveIsGrief/videojs-externals/blob/14_-_Stabilize_tests/.circleci/config.yml)

Cheers

**Comment by michelle-luna** [comment]
Ok thanks for this additional info. In v2.0 the way to do this is by using workflows and branches, have you tried them using this doc?
https://circleci.com/docs/2.0/workflows/#branch-level-job-execution
