### ISSUE TITLE
Wrong config path in Workflows Doc

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#2054]
Here: https://circleci.com/docs/2.0/#using-the-workflows-functionality

The config file is referred to as `.circle/config.yml` instead of `.circleci/config.yml`.

Reported on Twitter: https://twitter.com/mazgi/status/966949376575746048

**Comment by michelle-luna** [comment]
thanks for reporting, this is fixed https://github.com/circleci/circleci-docs/pull/2059
