### ISSUE TITLE
Documentation update request - PaaS business

### ISSUE THREAD

**Issue by dhlavaty** [circleci/circleci-docs#2058]
This issue is about <https://circleci.com/docs/1.0/language-nodejs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/language-nodejs.md>)

Are you sure that sentense "We can deploy to Nodejitsu and other PaaSes as well as to physical servers under your control." is correct ? Nodejitsu announced in February 2015 that they are exiting the PaaS business.

**Comment by smart-alek** [comment]
This is definitely not correct! Thanks for the catch.
