### ISSUE TITLE
node.js project is suspended

### ISSUE THREAD

**Issue by eczajk1** [circleci/circleci-docs#207]
I am trying to run test on a node project, but the tests aren't running because it says:

"We did not test this push because the project has been suspended. Please contact us if you think this is a mistake."

I've tried on repo's that are in my personal account and an organizational account.  Any documentation on what is meant by "suspended"?

![image](https://cloud.githubusercontent.com/assets/2584923/16275234/2a7ebf8c-3877-11e6-8b2a-4ee64b7c3049.png)

**Comment by gordonsyme** [comment]
Hi, we briefly had some over-zealous fraudulent account detection deployed which accidentally swept up your account. It's been rolled back and all blocks removed. Apologies for the inconvenience and thank you for bearing with us.

We don't monitor GitHub issues as closely as we monitor our support channels, you'll generally get a faster response if you go through the contact or support links.

**Comment by gordonsyme** [comment]
Hi @kiner-tang I would suggest you get in contact with CircleCI support. They are best placed to help, but don't monitor GitHub issues on our docs repo.

**Comment by kiner-tang** [comment]
> Hi @kiner-tang I would suggest you get in contact with CircleCI support. They are best placed to help, but don't monitor GitHub issues on our docs repo.

👌🏻!
