### ISSUE TITLE
Heroku Deploy Doc Bug

### ISSUE THREAD

**Issue by AnthonyNahas** [circleci/circleci-docs#2077]
This issue is about <https://circleci.com/docs/2.0/deployment-integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment-integrations.md>)

`command: |  # this command is framework-dependent and may vary
            heroku git:remote -a HEROKU_APP_NAME`

--> when I run this command I got : `  Couldn't find that app.
Exited with code 1`

HEROKU_APP_NAME should be enhanced with $ to be referenced to a env variable 

--> 

`command: |  # this command is framework-dependent and may vary
            heroku git:remote -a $HEROKU_APP_NAME`

**Comment by smart-alek** [comment]
Sharp eye @AnthonyNahas! Thanks for spotting that. I'll cook up a PR and serve it to you posthaste. 🍔
