### ISSUE TITLE
Add example: Skip a Git tag 

### ISSUE THREAD

**Issue by steurt** [circleci/circleci-docs#2078]
This issue is about <https://circleci.com/docs/1.0/skip-a-build/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/skip-a-build.md>).

This document shows the log results of a git commit/tag with [ci skip], but it doesn't show how to create it. An example of git commit might be unnecessary, but with regard to item [4 - Skip a Git tag release](https://circleci.com/docs/1.0/skip-a-build/#4-skip-a-git-tag-release) it does seem relevant.

It states that it's possible to skip building a Git tag by including [ci skip] in the tag description. But creating a tag with `git tag -a v1.1 -m "Release v1.1 [ci skip]"` does not actually work. Either it's a bug or this documentation should state how to create a tag that's able to skip a build.

**Comment by smart-alek** [comment]
Hey @steurt, thanks for the feedback! Couple questions for you:

1. Are you creating this tag on a forked PR?
2. I agree that `[ci skip]` should be processed properly in the tag message, but perhaps it wouldn't hurt to try adding that to the tag _name_ instead.

If either of those fail, then congratulations, you've found a bug!

**Comment by steurt** [comment]
@smart-alek I've checked your suggestions:

1. I am not creating this tag on a forked PR. I'm creating it on the master branch of the main repository.
2. I've tried adding it to the tag _name_ but a tag name can't contain spaces nor brackets. So any tag name containing `[ci skip]` is an invalid tag name and thus cannot be created.

So I guess it really seems to be a bug.

**Comment by michelle-luna** [comment]
Hi Stuart, 

Adding to Alek's questions for a second, are you using 1.0 or 2.0? I suspect this is different in 2.0 and we haven't documented it yet. If you are using 2.0, have you looked into doing it with workflows tag filtering? I think that is probably the way to go forward, but let me know if I'm misunderstanding https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

Thanks,
Michelle

**Comment by lewang** [comment]
@michelle-luna We never supported skipping builds based on tag description.  The doc change introduced in 8760257df is inaccurate.

Thanks for the report @steurt .
