### ISSUE TITLE
confused about how to use with node.js

### ISSUE THREAD

**Issue by sourcevault** [circleci/circleci-docs#2080]
This issue is about <https://circleci.com/docs/2.0/language-javascript/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-javascript.md>)

-------------
FAN OF PODCAST ... TRIED CIRCLE CI .... DOCS CONFUSING ... !
-------------
could you improve the docs to make is simpler ... for example my `.travis.yml` file looks like this. ..  I have zero knowledge on docker and have zero interest in learning it.

```
language: node_js
node_js:
  - "lts/*"
```
cheers !

**Comment by smart-alek** [comment]
Hey @sourcevault, glad you're liking the podcast! "To Be Continuous", right?

We are (continuously!) improving the docs and are always happy to receive feedback. In this case, though, the docs are a reflection of the product — which does indeed use Docker.

So what I'm hearing is that you want a simpler _product_. But if you'd like simpler docs, just tell us what's confusing you, and we can take a look.

**Comment by sourcevault** [comment]
Whats the simplest `config.yaml` for `nodejs` projects ? 

The tutorial page for `js` seems like a tutorial on docker :( 

Anyway it seems circleCI is for power users for CI that have specific needs, it makes sense to concentrate on them rather than more inexperienced CI folks.  

Good Luck !

**Comment by smart-alek** [comment]
Hey @sourcevault!

Don't let the Docker integration scare you off! While it's true that CircleCI _can_ be pretty powerful, it doesn't require deep knowledge of Docker to set up. Docker is really just used as a way of bundling dependencies and providing a starting point. You _could_ go deeper into that Docker world, but it's definitely not required.

You can pop over to our example Node app using the Express framework and [check out the configuration](https://github.com/CircleCI-Public/circleci-demo-javascript-express/blob/master/.circleci/config.yml). It's not necessarily the _simplest_ configuration, but it's certainly a thorough one. And if you haven't gone through our initial tutorials, I definitely recommend those as well.

Hope that's helpful!
