### ISSUE TITLE
Environment Variables in the 2.0 YML: no mention in the docs

### ISSUE THREAD

**Issue by s-paquette** [circleci/circleci-docs#2085]
This issue is about <https://circleci.com/docs/2.0/migrating-from-1-2/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/migrating-from-1-2.md>)

There's no mention of environment variables in any of the 2.0 documentation for the YML conversion. Does this mean they can't be used? If they can, in what circumstances? A glance at the support forums indicates there are numerous problems, none of which are addressed here.

**Comment by smart-alek** [comment]
Hello @s-paquette! Thanks for the feedback.

Environment variables are still important, should be used, and so on and so forth. They are so crucial, in fact, that we have an [entire article devoted to them](https://circleci.com/docs/2.0/env-vars/).

A cursory scan of the migration doc didn't show any links to this document. Did you feel like environment variables weren't called out clearly enough in this article? Would be happy to add a more obvious shoutout if that's the case.

**Comment by s-paquette** [comment]
Yes, the migration doc should explicitly mention them, particularly because interpolation of env vars isn't currently supported in 2.0 (nor, apparently, can we expect it to be before the drop dead date in [August](https://discuss.circleci.com/t/reference-an-environment-variable-in-environment-yaml-map/10792)), so workarounds for that specific case should be a part of the migration documentation.

**Comment by s-paquette** [comment]
Added note: working_directory also doesn't support env var expansion, which should probably be noted since it used to default to the same value as CIRCLE_PROJECT_REPONAME, and now that the default has diverged users might think to try and use that variable, except they can't.

**Comment by smart-alek** [comment]
Ahoy @s-paquette!

So in #2090, I dug into the migration document and tried to make the changes to env vars a little clearer. I didn't add anything explicit about `working_directory`; I felt like the general statement about interpolation being unsupported was enough. Let me know what you think about those changes!

**Comment by s-paquette** [comment]
@smart-alek Thank you, this is a significant improvement and really helps clarify things.
