### ISSUE TITLE
Add 'Skipping a build' documentation to 2.0 docs

### ISSUE THREAD

**Issue by steurt** [circleci/circleci-docs#2095]
This issue is about <https://circleci.com/docs/1.0/skip-a-build/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/skip-a-build.md>).

The documentation regarding 'Skipping a build' is only available in the documentation for CircleCI 1.0. It's supported by 2.0 so shouldn't it be part of the 2.0 docs as well?

**Comment by smart-alek** [comment]
@steurt Indeed it should! If you spot any other gaps like that, definitely let us know. 👍
