### ISSUE TITLE
Status Badges links incorrect

### ISSUE THREAD

**Issue by jpotter** [circleci/circleci-docs#2097]
This issue is about <https://circleci.com/docs/2.0/status-badges/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/status-badges.md>)

Hello! It looks like the URLs to the status badges are outdated -- the image URLs are 404.

**Comment by smart-alek** [comment]
Aha, you are correct @jpotter! Thanks for the catch. :)

**Comment by smart-alek** [comment]
@jpotter do you mean the URLs for the status badges _in the doc_, or the generated URLs for your own status badges?

**Comment by jpotter** [comment]
@smart-alek The URLs for the status badges _in the doc_ :)

**Comment by smart-alek** [comment]
@jpotter SPLENDID. The linked PR destroys them both. ;)
