### ISSUE TITLE
RE: jekyll/_docs/language-java.md

### ISSUE THREAD

**Issue by lhazlewood** [circleci/circleci-docs#210]
What versions of Java are available?

I need to know which ones are available so I can choose one.

Also, how do we ensure that the JCE Unlimited Strength cryptography policy files are installed in the JDK installation?

**Comment by felicianotech** [comment]
The Version section of the doc has two links. https://circleci.com/docs/language-java/#version

Click the environment that you are using, Ubuntu 12.04 (default) or Ubuntu 14.04. That will show you the versions of Java that are preinstalled.

As for your second question, I'm not sure. How do you normally do that? You can run Bash commands from `circle.yml` so if it's not installed you can install it the usual, terminal way.
