### ISSUE TITLE
Is the 'login to heroku' section  repeated in setup-heroku.sh? 

### ISSUE THREAD

**Issue by Jackclarify** [circleci/circleci-docs#2117]
https://github.com/circleci/circleci-docs/blob/b127cf15a58369de7555444a03f456c22fc2d1b0/jekyll/_cci2/project-walkthrough.md
the section of login to heroku at the end of the article
```
  machine api.heroku.com
    login $HEROKU_LOGIN
    password $HEROKU_API_KEY
  machine git.heroku.com
    login $HEROKU_LOGIN
    password $HEROKU_API_KEY
```
Is it repeated?

**Comment by smart-alek** [comment]
Hey @Jackclarify! Great question, but it [doesn't appear so](https://devcenter.heroku.com/articles/authentication#usage-examples). Thanks for asking, though! :)
