### ISSUE TITLE
Can store_artifacts path be a regex?

### ISSUE THREAD

**Issue by benwicks** [circleci/circleci-docs#2125]
This issue is about <https://circleci.com/docs/2.0/artifacts/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/artifacts.md>)

I am building a multi-module project. I have artifacts that I want to store that follow this pattern: "*/build/reports" where * would be "module1", "module2", etc.

Does the store_artifacts path allow a regex to support that? Or is there any other way to shorten the syntax so I don't have to repeatedly specify multiple lines to store artifacts from all modules?

Thanks for considering.

**Comment by smart-alek** [comment]
Hey @benwicks! Thanks for the question.

That is actually a great idea, but [my research](https://circleci.com/docs/2.0/configuration-reference/#store_artifacts) reveals that it's not something that's currently supported. Your reasoning for wanting support for patterns makes sense, though, so you should pop over to our [Ideas page](https://circleci.com/ideas/) and get people voting on it.

Thanks!

**Comment by EvanHerman** [comment]
This was available to us in v1 and should have been ported over to v2 😞
