### ISSUE TITLE
Missing software manifest for Xcode version 9.2.0.

### ISSUE THREAD

**Issue by acrookston** [circleci/circleci-docs#2126]
Missing software manifest for Xcode version 9.2.0.

This issue is about <https://circleci.com/docs/1.0/build-image-macos/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/build-image-macos.md>)

**Comment by smart-alek** [comment]
Thanks for this @acrookston! Looking into it.

**Comment by marcomorain** [comment]
The link is here: https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-298/index.html

We've got it in the 2.0 docs, not the 1.0 docs. PR incoming.
