### ISSUE TITLE
Local CLI build pretends to support parallism but doesn't

### ISSUE THREAD

**Issue by nroose** [circleci/circleci-docs#2129]
This issue is about <https://circleci.com/docs/2.0/local-cli/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-cli.md>)

If I do
`circleci help build`
it has
`--parallelism int       parallelism level (default 1)`
as one of the options, but it does not seem to work.

**Comment by smart-alek** [comment]
@nroose can you give me some more details on what isn't working?

**Comment by nroose** [comment]
Is it supposed to work? I have `parallelism: 2` in my .circleci/config.yml file, and if I do `circleci build --parallelism 2` it does just one of the 2 nodes, running just half of the specs.

**Comment by smart-alek** [comment]
@nroose I've gotten confirmation that the message is indeed confusing!

A better message would be: `--parallelism M --index N`. This doesn't mimic a fully parallelized build; it mimics a run of the **Nth node** in an **M-parallelized** job.

I'll work on getting this updated in the tool itself, but let me know if that answers your question!

**Comment by nroose** [comment]
Oh. OK. Thanks.

**Comment by smart-alek** [comment]
@nroose I can't tell if you're disappointed or satisfied, but I'm going to close this issue anyway!
