### ISSUE TITLE
Docs don't tell how to add write-keys to Bitbucket

### ISSUE THREAD

**Issue by rask** [circleci/circleci-docs#2133]
This issue is about <https://circleci.com/docs/2.0/gh-bb-integration/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/gh-bb-integration.md>)

Bitbucket does not have write-capable deployment keys from what I understand. The docs only outline how to create RW keys for GitHub. How would one create a write-capable and CircleCI compatible deployment key for a (private) Bitbucket project? What about Gitlab?

**Comment by smart-alek** [comment]
Related: #1667

**Comment by rask** [comment]
Thanks @smart-alek, the change in documentation makes it clearer. I will have to see how it works and I can create a new issue in case the change needs more changes in my opinion. ;)
