### ISSUE TITLE
GAE setup instructions are confusing

### ISSUE THREAD

**Issue by travis** [circleci/circleci-docs#2134]
- "Paste this into a new environment variable’s “Value” field" <- not clear whether "this" is the contents of the JSON key or something else
- not clear which parts of the config.yml are necessary
- I think GCR_CREDS and GOOGLE_AUTH are both used to refer to the same environment variable (GOOGLE_AUTH in most places, GCR_CREDS in the comment in the sample config.yml)
- this document doesn't specify which roles the Service Account needs to have to work properly with CircleCI

This issue is about <https://circleci.com/docs/2.0/google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/google-container-engine.md>)

**Comment by smart-alek** [comment]
Hey @travis, good to see you!

I've actually already got a full revision of that document in the works, so I'll go ahead and incorporate some of your suggestions there. In the meantime, glance at this doc and see if you fare any better (it's more specific and recent): https://circleci.com/docs/2.0/google-auth/
