### ISSUE TITLE
configuration reference does not mention `docker_layer_caching` for `machine` executor

### ISSUE THREAD

**Issue by marcomorain** [circleci/circleci-docs#2144]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>)

We allow the user to specify `docker_layer_caching` for `machine` builds - https://circleci.com/docs/2.0/docker-layer-caching/#docker-layer-caching-in-machine-executor - this might be a new feature.

This was never added to the [configuration reference](https://circleci.com/docs/2.0/configuration-reference/#machine) docs, or the [Executor Types](https://circleci.com/docs/2.0/executor-types/#using-machine) docs.

**Comment by michelle-luna** [comment]
Thanks, I will take this one since I made the changes with Anton when we enabled the feature.
