### ISSUE TITLE
Yarn documentation migration to 2.0

### ISSUE THREAD

**Issue by sampsakuronen** [circleci/circleci-docs#2154]
This page is linked from `yarn` homepage. It references CircleCI version `1.0` which might confuse some new users. 

Should the page be migrated to `2.0`?

Linked from: https://yarnpkg.com/en/docs/install-ci

This issue is about <https://circleci.com/docs/1.0/yarn/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/yarn.md>)

**Comment by smart-alek** [comment]
@sampsakuronen thanks for the catch!

@felicianotech wrote the first version of that Yarn documentation. How much work do you think it would be to migrate that to 2.0 config?

**Comment by felicianotech** [comment]
My thought is that this shouldn't be carried over to 2.0 docs. 99% of what was preinstalled in CircleCI 1.0 aren't in 2.0, Yarn being in the 99%.

I'm thinking a PR over at the Yarn docs specifically the previous instructions (which I wrote) as for 1.0 and to use `-node` variant images for 2.0.

Thoughts? I'll stew on this a bit and ge back to this during the week. If you agree with what I said Alek, then feel free to assign this Issue to me.

**Comment by michelle-luna** [comment]
Agreed, and just add to what Ricardo says above in case it helps, we have a number of customers who get confused about this in 2.0 because we don't preinstall yarn. So, we need to make it clear that we don't do this anymore in 2.0 and exactly what users need to do in 2.0 (install it and/or pick an image variant that has it). We've had multiple issues about this filed and a top search term is always yarn for the 2.0 docs collection.

**Comment by Gaurav0** [comment]
What image variants have yarn?

**Comment by felicianotech** [comment]
@Gaurav0 The CircleCI NodeJS images (`circleci/node`) and the `-node` and `-browsers` variants.

**Comment by Gaurav0** [comment]
@felicianotech I get `yarn not found` errors in those branches.

**Comment by felicianotech** [comment]
@Gaurav0 This is getting out of the scope of a GitHub Issue. Can you please open a [CircleCI Discuss](https://discuss.circleci.com) post and mention me (`FelicianoTech`) in it?

**Comment by felicianotech** [comment]
Due to the amount of searches Michelle says we get for Yarn on 2.0 docs, I'll make an updated doc for it and then a PR over the Yarn website to point to the new one.

**Comment by felicianotech** [comment]
Opened Yarn PR here: https://github.com/yarnpkg/website/pull/795
