### ISSUE TITLE
New trial install getting "Unknown error authenticating via GitHub. Try again, or contact us."

### ISSUE THREAD

**Issue by el-psycho** [circleci/circleci-docs#2155]
I got a trial license key and followed this guide to deploy a self hosted circle ci: https://circleci.com/docs/2.0/single-box/

After the setup is complete and I try to log in I get the error "Unknown error authenticating via GitHub. Try again, or contact us.". Clicking the "contact us" link on that error doesn't work either, it just shows a 404 page with the text "Something doesn't look right ... You may have been logged out."

**Comment by GERey** [comment]
Hi @el-psycho , we generally try to keep the circleci-docs limited to documentation issues. This seems more like a tech issue. Would you mind reaching out to trial-support@circleci.com with a support bundle (in the top right hand corner in the management console under `support`) and a description of the error?  Thanks!

**Comment by el-psycho** [comment]
Hi, I actually managed to resolve this by using http (not https) for the GitHub OAuth `Homepage URL` and `Authorization callback URL`. From the documentation it's not clear when one should use http vs https. I was using a self signed certificate for this circle ci trial if that makes a difference.

**Comment by michelle-luna** [comment]
Hi,

Thanks for this additional feedback on the docs, glad you got it sorted out! I've re-opened this issue.

**Comment by felicianotech** [comment]
Self-signed certificates are still TLS (SSL) certificates so I think HTTPS would still be used. @GERey is that accurate?
