### ISSUE TITLE
There is no documentation outline/index for the 2.0 docs

### ISSUE THREAD

**Issue by istepaniuk** [circleci/circleci-docs#2167]
The document outline/index (on the left side bar) does not expand/show any of the lower level entries.

For example: In the document outline there is a "Reference" entry, and going to that page reveals that "Pre-Built CircleCI Docker Images" is in underneath "Reference" in the document hierarchy.

For the 1.0 docs, the outline is expandable and that makes it easy to navigate the documentation.

**Comment by michelle-luna** [comment]
Hi @istepaniuk ,

Thanks for this feedback, this is on purpose to keep the left nav simple and have room for the admin docs as well. (but, I recognize it is not perfect!) Do you think the Pre-Built Docker Images should be in a different category other than Reference? Which category make more sense to you? 

Regards,
Michelle

**Comment by smart-alek** [comment]
@istepaniuk Thanks for that feedback! This was done intentionally so the docs wouldn't be as overwhelming as 1.0 — you can scroll for days in that version of the docs!

We do have future redesign plans where we might expandable lower-level entries, but those will be handled in the related tickets. So closing this one!
