### ISSUE TITLE
The docs are missing a lot of important information about Code Signing

### ISSUE THREAD

**Issue by azrosen92** [circleci/circleci-docs#2169]
This issue is about <https://circleci.com/docs/2.0/ios-codesigning/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/ios-codesigning.md>)

It seems like there is a lot of documentation about setting up Code Signing in the [v1.0 docs](https://circleci.com/docs/1.0/ios-code-signing/). Are these no longer relevant in v2.0? What needs to be carried over?

**Comment by michelle-luna** [comment]
Hi @azrosen92 ,

Thanks for filing this issue, code signing is different in 2.0 and the new document reflects the new setup (all in config, not in the CircleCI app). We carried over everything that still applies. Maybe we can add a note to the document stating this to make it more clear?

-Michelle

**Comment by azrosen92** [comment]
@michelle-luna thanks for the quick response! A note about that would be helpful.
