### ISSUE TITLE
Make DB credential information clear

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#217]
Currently, the Ubuntu 12.04 build doc has it, 14.04 doesn't. Might not be good to include this info in either since it shouldn't be container specific.

**Comment by smart-alek** [comment]
@felicianotech It seems like there are 2 things you're suggesting:

1. make information more clear by adding it to 14.04
2. make information more clear by removing it from 12.04

Can you give me some more context on this?

**Comment by felicianotech** [comment]
This is referring to the default username/passwords for the databases that we have pre-installed. Either, this information needs to be available in both build image docs, or in neither, and perhaps moved to the (huge) configuration doc, in the database section.

**Comment by smart-alek** [comment]
Closing this in favor of 2.0 docs.
