### ISSUE TITLE
Running gcloud --quiet components update as suggested causes error

### ISSUE THREAD

**Issue by jamesmbourne** [circleci/circleci-docs#2174]
This issue is about <https://circleci.com/docs/2.0/google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/google-container-engine.md>)

The recommended command to configure `gcloud` includes `gcloud --quiet components update`. However, this causes the following error which fails the build:

```
ERROR: (gcloud.components.update) 
You cannot perform this action because the Cloud SDK component manager 
is disabled for this installation. You can run the following command 
to achieve the same result for this installation: 

sudo apt-get update && sudo apt-get --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java


Exited with code 1
```

**Comment by smart-alek** [comment]
Hey @jamesmbourne, thanks for the feedback!

Did that suggested command work for you, or did this bring your development to a screeching halt?

**Comment by smart-alek** [comment]
@jamesmbourne just following up on this. Do you remember how you installed the SDK?
