### ISSUE TITLE
Fix for Code 13; Exit code 65

### ISSUE THREAD

**Issue by gauravagarwalr** [circleci/circleci-docs#2183]
This issue is about <https://circleci.com/docs/2.0/testing-ios/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/testing-ios.md>)

It seems pre-starting the simulator and running UITests before Tests completely solves the issue. Please add this to the docs for any future developers. This is useful.

https://stackoverflow.com/questions/44361446/ios-uitests-failed-idetestoperationsobservererrordomain-code-13/48299184#48299184

**Comment by smart-alek** [comment]
@gauravagarwalr thanks for the feedback!

Can you tell me where in this document you bumped into Code 13? Was it in the [Resolving Common Simulator Issues](https://circleci.com/docs/2.0/testing-ios/#resolving-common-simulator-issues) section?

**Comment by gauravagarwalr** [comment]
I am talking in relation to this issue.

https://circleci.com/blog/xcodebuild-exit-code-65-what-it-is-and-how-to-solve-for-ios-and-macos-builds/

It already suggests pre-starting the simulator. For which you have a session in the new docs.
I am saying, add a new section or a side note somewhere that reordering the ios tests, as mentioned in the stackoverflow link, fixes the exit code 65 completely.

**Comment by smart-alek** [comment]
Got it, thanks @gauravagarwalr!
