### ISSUE TITLE
(fix): Adding the HOME env variable description

### ISSUE THREAD

**Issue by Guikingone** [circleci/circleci-docs#2184]
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>)

Hi everyone, 

As I discovered earlier this day, CircleCI allows using the `${HOME}` env variables during builds, this variable contains the folder which contains the current project during the build. 

Here's my thought on this variable: 

HOME: 
The current folder (with an additional `/project` folder in front) where is located your project during the build, this variable is different from the `CIRCLE_WORKING_DIRECTORY` one which returns the folder where the job is actually triggered.

I know that this seems strange to detail this variable but I was looking for this one since 2-3 months and I discover it via this page: https://circleci.com/docs/2.0/google-auth/ which is clearly not related to the CI phase. 

PS: Sorry for the broken English.

**Comment by smart-alek** [comment]
@Guikingone hello and thanks for the feedback!

Sorry you had to look so long to find that env variable. Here's a question that might help us put in the right spot: do you have a document (or list of documents) where you **expected** to find information about `${HOME}` but didn't?
