### ISSUE TITLE
Server: HA PostgreSQL database list is incomplete

### ISSUE THREAD

**Issue by bluekeyes** [circleci/circleci-docs#2185]
The [High Availability setup page](https://circleci.com/docs/2.0/high-availability/#setting-up-postgresql-hosts) currently lists 5 databases that must exist on an external PostgreSQL instance. However, when configuring this for a clean install of version 2.7.0, I had to create 3 additional databases that are not listed on that page:

- `permissions`
- `federations`
- `domain`

While things seem to be working, it would be best to have an official list of required databases, including required extensions.

**Comment by smart-alek** [comment]
Excellent @bluekeyes!

When you say that "things seem to be working", I assume that was _after_ you created those 3 additional databases, yes?

**Comment by bluekeyes** [comment]
Correct, after creating those three databases (mentioned in the error logs of various migration containers), all service containers started and I haven't found any broken functionality yet.

**Comment by smart-alek** [comment]
Great! I'll get this updated this week.
