### ISSUE TITLE
Add guide for managing GitHub settings (_cc1/github-privacy.md)

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#219]
A customer ran into [an issue](https://circleci.zendesk.com/agent/tickets/7426) with their project not receiving Github status updates.  It doesn't look like it's documented anywhere, so they didn't think to look for the setting.

The customer requested this be documented, and I think I agree.  One would have to discover the setting to disable status updates.  But, it's possible that one person on a team does this and the rest of a team is unaware.

Perhaps this should be it's own page and linked to on the Github Integration page (inaccurately named github-privacy).  Thoughts?

**Comment by smart-alek** [comment]
I think this is probably still relevant for 2.0, so I'm going to leave this open and create a JIRA ticket.

**Comment by smart-alek** [comment]
Left a comment re: this issue in [this ticket](https://circleci.atlassian.net/browse/CIRCLE-3355).

**Comment by ndintenfass** [comment]
Closing this, as discussion JIRA will catch it, and there are changes afoot on this front....
