### ISSUE TITLE
incorrect artifacts download command

### ISSUE THREAD

**Issue by gusdecool** [circleci/circleci-docs#2202]
This issue is about <https://circleci.com/docs/2.0/artifacts/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/artifacts.md>)

The last command to download the artifacts should be

```sh
<artifacts.txt xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
```

note that it require prefix `?circle-token=`

**Comment by smart-alek** [comment]
Hey @gusdecool! Thanks for the feedback. I'm not sure I'm seeing where you'd like to correct this, though, since the code snippet at the bottom has that last command exactly.

Can you be a bit more specific about where you think this should be changed?

**Comment by gusdecool** [comment]
Hi @smart-alek , strange. I'm remember the page on https://circleci.com/docs/2.0/artifacts/ didn't have `?circle-token=` before. That's why i got error 404 when copy paste the code 😭 

But anyway, since now it do have  `?circle-token=`, i guess the issue resolved.
I will close this issue 🙏 

Thanks @smart-alek 👍
