### ISSUE TITLE
RE: jekyll/_docs/ruby-debugger-problems.md

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#221]
I vote to kill this page and references to it.  Ruby-debugger was a gem that never made it past Ruby 1.9.3.  Both Ruby 1.9 and 2.0 are [EOL](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/).

**Comment by smart-alek** [comment]
All right with me! :)
