### ISSUE TITLE
Add potential fix to failing schema load (_cci1/ruby-exception-during-schema-load.md)

### ISSUE THREAD

**Issue by mmccarthy15** [circleci/circleci-docs#224]
New to the CircleCI community, but wanted to add some feedback.  I ran into a schema load issue when ramping up our system, and while this doc was helpful - the solution was this:

http://stackoverflow.com/questions/32077666/why-factory-girl-initialized-during-rake-dbschemaload

I have to imagine I'm not the only one who has run into this.

Thx,
Mike

**Comment by smart-alek** [comment]
Great @mmccarthy15! It's easy enough to add this as another potential fix. :)

**Comment by smart-alek** [comment]
@mmccarthy15 thanks for filing this ticket! We're cleaning up our issues in favor of 2.0 documentation. If you haven't already, go ahead and [check it out](https://circleci.com/beta-access/)!
