### ISSUE TITLE
it allows a backdoor

### ISSUE THREAD

**Issue by ru40** [circleci/circleci-docs#2246]
This issue is about <https://circleci.com/docs/2.0/hello-world/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/hello-world.md>)

**Comment by smart-alek** [comment]
Hello @ru40!

Our GitHub Issues are for issues related specifically to the documents themselves. If you've got a security concern, please send details to security@circleci.com and follow the guidelines presented in our [security policy](https://circleci.com/security/).

Thanks!
