### ISSUE TITLE
gitsubmodules are not cloning by checkout

### ISSUE THREAD

**Issue by Rutulpatel7077** [circleci/circleci-docs#2253]
This issue is about <https://circleci.com/docs/1.0/external-resources/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/external-resources.md>)
I tried 

```
checkout:
  post:
    - git submodule sync
    - git submodule update --init
```

but even nothing showing in checkout log about submodules and at last repo not found error.

**Comment by smart-alek** [comment]
Hi @Rutulpatel7077, thanks for the question. Support for 1.0 is on the wane — have you tried running this on CircleCI 2.0 yet? If not, [this configuration document](https://circleci.com/docs/2.0/configuration-reference/#checkout) might have what you need.

**Comment by smart-alek** [comment]
We hit the three day cooldown @Rutulpatel7077, so closing this issue until I hear if the 2.0 configuration reference on git submodules worked for you. :)
