### ISSUE TITLE
RE: jekyll/_docs/language-java.md

### ISSUE THREAD

**Issue by dmitriid** [circleci/circleci-docs#226]
Docs:

> We have several versions of JDK pre-installed on Ubuntu 12.04 and Ubuntu 14.04 build images.
> ```
machine:
  java:
    version: openjdk7
```

The link to images points to https://circleci.com/docs/build-image-trusty/#java

> Java
> Default: 1.8.0_40
> Pre-installed versions:
> java-7-openjdk-amd64
> java-8-openjdk-amd64
> jdk1.8.0

Trying to specify this:

```
machine:
  java:
    version: jdk1.8.0
```

Build fails:

```
unknown java version
```

Please clarify documentation on how to properly specify Java versions

**Comment by felicianotech** [comment]
@kimh Any insight?

**Comment by kimh** [comment]
@dmitriid Sorry for the late response. This is indeed not correct. You can specify `oraclejdk8` and it should use `/usr/lib/jvm/jdk1.8.0`. I'll fix the document.

Thanks for bringing this out.

**Comment by dmitriid** [comment]
Thanks!
