### ISSUE TITLE
Key `name` for `save_cache` and `restore_cache`

### ISSUE THREAD

**Issue by Librazy** [circleci/circleci-docs#2296]
Per reference, key `name` is only available in `run` declaration. And neither [save_cache](https://circleci.com/docs/2.0/configuration-reference/#save_cache) nor [restore_cache](https://circleci.com/docs/2.0/configuration-reference/#restore_cache) support it. But actually [we can use `name`](https://github.com/yarnpkg/yarn/blob/master/.circleci/config.yml#L22) in these two to define its title. It is by accident and may be removed, or it is a feature not documented yet?

**Comment by smart-alek** [comment]
Hey @Librazy! Congratulations, you've discovered a secret!! ;)

In all seriousness, this is something that works and fell through the cracks of the configuration reference. But thanks to you... that will change soon enough!
