### ISSUE TITLE
Add warning to use Environment Variables in scripts

### ISSUE THREAD

**Issue by gregorwolf** [circleci/circleci-docs#2314]
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>). 

I would suggest to add a warning that when you call a script defined in a command in .circleci/config.yml that then the content of the Environment Variables will be logged in clear text. For critical values like passwords or API Keys only the command in .circleci/config.yml should be used. Then the Environment Variables is only shown with it's variable name.

**Comment by smart-alek** [comment]
Hey @gregorwolf, thanks for submitting an issue. Since this really more of a suggestion and not a change to docs, please submit this to our [public Ideas board](https://circleci.com/ideas/).

Thanks!

**Comment by gregorwolf** [comment]
My suggestion is to improve the documentation. The documentation at https://gitlab.com/help/ci/variables/README#secret-variables is much clearer on this topic.

**Comment by smart-alek** [comment]
Apologies @gregorwolf! I see what you mean now, and it looks like my colleague @michelle-luna already reopened the issue for resolution. Thanks for bringing this up!

**Comment by smart-alek** [comment]
@gregorwolf Some digging has revealed [this note](https://circleci.com/docs/2.0/env-vars/#declaring-environment-variables) in the environment variables document. I think what I'll do here is promote this to the Overview and expand it with your suggestions. Thanks!
