### ISSUE TITLE
RE: jekyll/_docs/faq.md

### ISSUE THREAD

**Issue by scole-scea** [circleci/circleci-docs#232]
Hey there. I was looking at the FAQ today, searching for the state of Docker 1.9 on Circle, and noticed the FAQ is talking about docker 1.5 "coming soon". Since Circle is running 1.8.2, this seems sadly out-of-date...

**Comment by felicianotech** [comment]
Thank you for pointing this out. There was actual a few things outdated there. Fix to remove the cruft coming in shortly.
