### ISSUE TITLE
document API scopes

### ISSUE THREAD

**Issue by afeld** [circleci/circleci-docs#2325]
The UI gives the option to create an API token and specify the scope, but doesn't explain what the different scopes mean.

<img width="350" alt="screen shot 2018-05-11 at 10 25 57 am" src="https://user-images.githubusercontent.com/86842/39937815-ce1773b2-5505-11e8-92b5-1c431e2bf521.png">

Specific questions:

* Which scopes gives read access, vs. read-write?
* Does `Status` give any permissions beyond being able to see the status badge?

**Comment by smart-alek** [comment]
Hey @afeld! Thanks for submitting this issue.

While I think this could definitely use some new documentation, I believe that **some** of your questions might be answered in [this article](https://circleci.com/docs/2.0/status-badges/) on embedding build status badges.

The article here implies that the `Status` scope is read-only and used only for status badges. But! I do not know the answers to your other questions and will respond with an actual document. Thanks!

**Comment by afeld** [comment]
Looks great, thanks!
