### ISSUE TITLE
RE: jekyll/_docs/build-artifacts.md Artifact Authentication?

### ISSUE THREAD

**Issue by theronic** [circleci/circleci-docs#233]
Is there any authentication involved in pulling artifacts?

When CircleCI completes my Clojure project build, I want to pull the uberjar onto my DO deployment box. How do I authenticate with Circle, or does the URL contain a secret token?

**Comment by keybits** [comment]
Hi there, sorry for the very late reply. Authentication is required. The API requires a token to access the artifact URL. Here's a post about downloading artifacts for a build that might be helpful: https://discuss.circleci.com/t/download-all-artifacts-for-a-build-on-circleci/7217

The best place to ask questions about CircleCI is on https://discuss.circleci.com/
