### ISSUE TITLE
Heroku deployment example seems to be missing configuration

### ISSUE THREAD

**Issue by arsduo** [circleci/circleci-docs#2347]
Hi! I was following the instructions for the Heroku deployment example on <https://circleci.com/docs/2.0/deployment-integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment-integrations.md>) and (using a slightly modified version of the example) ran into an error:

```
 deploy:
   steps:
     - checkout
     - run:
         name: Authenticate to Heroku
         command: docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com

     - run:
         name : Deploy to Heroku
         command: heroku container:push web --app $HEROKU_APP_NAME
```

I got the following error:

```
Build-agent version 0.0.5706-58f0e71 (2018-05-14T22:35:09+0000)
Configuration errors: 1 error occurred:

* 1 error occurred:

* In job 'deploy': 1 error occurred:

* The job has no executor type specified. The job should have one of the following keys specified: "machine", "docker", "macos"
```

It looks like the example is missing some configuration. 
 
Thanks!

**Comment by smart-alek** [comment]
Hey @arsduo, thanks for the catch! You are absolutely right — we should be picking an executor and nesting that within the `deploy` job. You can most likely get away with specifying a Docker image for your `deploy` job, but I'll get that updated in the docs today. Thanks!
