### ISSUE TITLE
RE: jekyll/_docs/build-artifacts.md

### ISSUE THREAD

**Issue by SethDavenport** [circleci/circleci-docs#235]
The example link appears to be incorrect:

https://circleci.com/api/v1/project/circleci/mongofinil/latest/artifacts/0/$CIRCLE_ARTIFACTS/cherry-pie.png?branch=master&filter=failed

```
{
  "message" : "Artifact not found"
}
```

**Comment by felicianotech** [comment]
Thank you for pointing this out.
