### ISSUE TITLE
RE: jekyll/_docs/build-image-trusty.md

### ISSUE THREAD

**Issue by pschord** [circleci/circleci-docs#236]
I'm looking for CouchDB support for my builds. It is not mentioned in the Databases section, but it is shown in the `dpkg -l` section:

```
couchdb1.6.1-0ubuntu5
couchdb-bin1.6.1-0ubuntu5
couchdb-common1.6.1-0ubuntu5
```

Is CouchDB officially supported?

**Comment by surawutperth** [comment]
...klp

**Comment by felicianotech** [comment]
This sadly fell through. For the Ubuntu 14.04 image (default), we have the packages pre-installed listed [here](https://circleci.com/docs/build-image-trusty/). For Ubuntu 12.04, [here](https://circleci.com/docs/build-image-precise/).

Most software, including CouchDB, "support" from CircleCI simply entails having it pre-installed. Using full Linux images means you can always run the software you need with limited exceptions (security and networking related).
