### ISSUE TITLE
Getting Rspec rrelated error while doing build

### ISSUE THREAD

**Issue by rabendrasharma** [circleci/circleci-docs#2386]
Getting Rspec related error while doing build. I have created one new file for mailer and also created one method on model. And when pushing the code circle ci giving error.Please help me I am unable to resolve it.

Thanks on advance.

**Comment by smart-alek** [comment]
Hi @rabendrasharma! This repository is for filing issues related to CircleCI documentation. If you need help debugging an error, please visit our [support center](https://support.circleci.com/hc/en-us) or[community forum](https://discuss.circleci.com/). Thanks!
