### ISSUE TITLE
Removing Docker version 17.11.0-ce from guide to building docker images

### ISSUE THREAD

**Issue by janoulle** [circleci/circleci-docs#2387]
This issue is about <https://circleci.com/docs/2.0/building-docker-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/building-docker-images.md>)

When following [this guide](https://circleci.com/docs/2.0/building-docker-images/), I saw `17.11.0-ce` was listed as a supported version. However, upon using that tag in my curl command, I got an error in my logs:
```#!/bin/bash -eo pipefail
set -x
VER="17.11.0-ce"
curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
tar -xz -C /tmp -f /tmp/docker-$VER.tgz
mv /tmp/docker/* /usr/bin
+ VER=17.11.0-ce
+ curl -L -o /tmp/docker-17.11.0-ce.tgz https://download.docker.com/linux/static/stable/x86_64/docker-17.11.0-ce.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100   576  100   576    0     0   2620      0 --:--:-- --:--:-- --:--:--  2630
+ tar -xz -C /tmp -f /tmp/docker-17.11.0-ce.tgz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Exited with code 2
```

Browsing https://download.docker.com/linux/static/stable/x86_64/ shows there's no 17.11.0-ce of docker. A proposed edit would be to remove this version from the documentation since it's no longer available publically.

**Comment by smart-alek** [comment]
Hey @janoulle! Thanks for the feedback — we've actually kicked off a larger discussion around how to automate the list of supported Docker version tags. In the meantime, though, I'll make a quick PR to remove this version from the list. :)

**Comment by smart-alek** [comment]
I just did a bit of investigation — it looks like 17.11.0-ce **is** actually supported, but you're right that it's not one of the stable releases. It's actually one of the [edge releases](https://download.docker.com/linux/static/edge/x86_64/).

So, if you were following the instructions in the document, I could see that being confusing. What I'll do  is divide our supported Docker CE releases into **Stable** and **Edge** groups. 👍

**Comment by janoulle** [comment]
thanks for the quick response, @smart-alek! I'm happy with the current course of action.
