### ISSUE TITLE
Caching Documentation ambiguities

### ISSUE THREAD

**Issue by s-paquette** [circleci/circleci-docs#2415]
This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

I had to go through figuring out how to use this today, and the documentation has some gaps:

- **Restoring Cache** reads, "CircleCI restores caches in the order of keys listed in the restore_cache step. Each cache key is namespaced to the project, and retrieval is prefix-matched. The cache will be restored from the first matching key. If there are multiple matches, the most recent match will be used." What does 'most recent match' mean? The most recently generated cache that matches? The last match made in the matching process, which might or might not be related to the most recent cache (it's not mentioned anywhere else if it is)?
- {{ .BuildNumber }} indicates it's the 'CircleCI build number for this build', except I am receiving a new build number for each **job** in a workflow build right now. So what value is this giving me--the 'build numbers' I see in the UI? If so, those are really 'job' numbers; it would be easy to assume this template value would persist between 2 jobs in a workflow, and so something cached in job #1 could be retrieved in job #2, but this won't be the case if the numbers I see in the UI are used. 
- paths don't support Glob in caching, but they do in persist_to_workspace, which is very easy to trip over as a user trying to work out which of these methods to use; it might be worth a callout

**Comment by smart-alek** [comment]
Hey @s-paquette! Thanks for these — very specific and very helpful. 👍 You should see a PR up in the next 1-2 days. Thanks for taking the time to write these down for us!
