### ISSUE TITLE
Tell us how to specify region for AWS ECR

### ISSUE THREAD

**Issue by steadysupply** [circleci/circleci-docs#2458]
# Document
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/private-images.md

# Problem Details
```
Build-agent version 0.0.6918-3a2a4e2 (2018-06-22T13:50:16+0000)

error authentication with ECR: MissingRegion: could not find region configuration
```

## Undocumented
- What are you looking for?
How to specify region
- Where have you already looked?
I googled it and found https://discuss.circleci.com/t/you-must-specify-a-region-you-can-also-configure-your-region-by-running-aws-configure-exited-with-code-255/14392

Cheers!

**Comment by smart-alek** [comment]
Hey @steadysupply, thanks for filing an issue — and humoring us by filling out that template. :)

Here's a couple of other spots that might give you some answers:
- In our [Configuration Reference](https://circleci.com/docs/2.0/configuration-reference/#docker), there's a key called `aws_auth` under the `docker` key that might be what you need. If you scroll down a bit, it looks like the region is specified in the image's title.
- Also check out the [AWS deploy section](https://circleci.com/docs/2.0/deployment-integrations/#aws).

Just so I have a little more context, could you attach your `config.yml` to this issue? Thanks!

**Comment by steadysupply** [comment]
It was actually my mistake, I'm new to ECR. You're correct that the region
is implicitly specified in the image name, it's a slightly misleading error
message from AWS.

Feel free to close this issue.

Ben

**Comment by smart-alek** [comment]
Glad to hear it @steadysupply! Happy building. :)
