### ISSUE TITLE
Limitation "can't use relative paths using local cli" has been removed

### ISSUE THREAD

**Issue by zlrth** [circleci/circleci-docs#2466]
This issue is about <https://circleci.com/docs/2.0/local-cli/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-cli.md>)

I believe the limitation here:
https://circleci.com/docs/2.0/local-cli/#relative-path-for-working_directory

has been removed. I'm using CircleCI locally. The relevant line from my config.yml file is:
```
    working_directory: ~/repo
```

Thank you for removing the limitation! I'm enjoying using CircleCI.

**Comment by smart-alek** [comment]
Hey @zlrth thanks for the catch and your patience! :)
