### ISSUE TITLE
Add information about how to use Haskell on 14.04 (_cci1/language-haskell.md)

### ISSUE THREAD

**Issue by newhoggy** [circleci/circleci-docs#247]
`language-haskell.md` should include all the documentation necessary to work with Haskell on CircleCI, but it doesn't.  In particular, information about how to use Haskell on trusty is absent.

**Comment by smart-alek** [comment]
@newhoggy thanks for the heads up on the lack of Haskell context!

We're closing issues for 1.0 docs edits/drafts in favor of our [2.0 docs](https://circleci.com/docs/2.0/). While those don't have a lot of info about Haskell either (yet), our goal is to make those cleaner and more complete than 1.0. Stay tuned! :)
