### ISSUE TITLE
Download Artifacts Steps unclear

### ISSUE THREAD

**Issue by egucciar** [circleci/circleci-docs#2472]
This issue is about <https://circleci.com/docs/2.0/artifacts/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/artifacts.md>)

Hi, 

I followed the steps above to try to grab the images. Artificats txt looked like this:

```
https://developer.github.com/v3/repos/#get\

```

something tells me this isnt right. Why cant we just have a button that makes it easy to download the content?

**Comment by levlaz** [comment]
Can you provide a link to the build where you ran into this issue?

> Why cant we just have a button that makes it easy to download the content?

This would be a great feature, could you make a feature request on our public ideas board: https://circleci.com/ideas/

**Comment by smart-alek** [comment]
Hey @egucciar, I double-checked the docs on this and was able to get everything working. Couple questions for you:

- Are you storing artifacts properly in your `config.yml`?
- What's the exact URL you are passing to `curl`?

In the meantime, I'll clean up the steps in the documentation to ensure there's no ambiguity there. Thanks for your patience!
