### ISSUE TITLE
Git deploy instruction for Heroku is incorrect

### ISSUE THREAD

**Issue by smart-alek** [circleci/circleci-docs#2485]
(copied from [this comment](https://github.com/CircleCI-Public/circleci-demo-workflows/pull/20/files#r202156520))

# Locations
The `config.yml` example in the [Heroku section of the Deployment Integrations document](https://circleci.com/docs/2.0/deployment-integrations/#heroku).

# Details
User claims that they need to replace the `heroku` username with the user login tied to the `HEROKU_API_KEY`. Was captured in `$HEROKU_LOGIN` before the most recent change.

**Comment by m90** [comment]
Hey @smart-alek, thanks for making an issue out of this.

I've done further reading on the topic and found [this part of the Heroku docs](https://devcenter.heroku.com/articles/git#http-git-authentication) which clearly states:

> The Heroku HTTP Git endpoint only accepts API-key based HTTP Basic authentication. A username is not required and any value passed for username is ignored.

so I guess I must be doing something else wrong here (I still can repro what described though) and the PR was correct to remove the need for the username in the `.netrc` file.

If you want to, you can close this issue, or we'll keep it open and I can post what I found out for others to access.

**Comment by smart-alek** [comment]
Hey @m90! Thanks for doing a little bit of docs digging — that's a good find. :)

I'm getting a strong [Discuss](https://discuss.circleci.com/) vibe from this issue. Rather than capture the conversation in a thread locked to this repo, let's move it over to our forum so other users can search for it there. If you'd be so kind as to repost this and any other findings there, then I think we'll be in good shape!
