### ISSUE TITLE
Add examples to env-vars.md

### ISSUE THREAD

**Issue by klahnakoski** [circleci/circleci-docs#2510]
# Missing Information
Specific use examples using CIRCLE_* environment variables

Maybe using environment variables is obvious to everyone else, but I am not sure how to use them. Specifically, how to use the `CIRCLE.*` vars.

How do I use `CIRCLE_TAG`? in the `enviroment` section of config.yml file?  How to use `CIRCLE_TAG` in a run command in config.yml?  How do I use `CIRCLE_TAG` in my dockerfile?

* `$CIRCLE_TAG`
* `${CIRCLE_TAG}`
* `{{Environment.CIRCLE_TAG}}`

Right now I must perform an exhaustive search because there are not enough examples to know what level of quotation I am supposed to use.  Still trying to figure out which one, or if there are others.

**Comment by smart-alek** [comment]
Hey @klahnakoski, thanks for submitting an issue!

Like custom environment variables, CircleCI environment variables can be referenced by prefixing a dollar sign. So, using your example of `CIRCLE_TAG`, you would use it in a `bash` script by typing `$CIRCLE_TAG`.

CircleCI 2.0 does not support interpolation of environment variables while defining other environment variables. So you actually can't use a built-in environment variable in any `environment` section. [This open PR](https://github.com/circleci/circleci-docs/pull/2512) is actually trying to make that more clear.

You **can**, however, use it in a run command to define another environment variable that depends on information stored in another environment variable. That behavior is also documented in the same PR.

As for the Dockerfile route, CircleCI built-in environment variables are only accessible in the context of a CircleCI build, which means only in `config.yml`. The Dockerfile contains details on how to create a specific image, so won't know that those CircleCI variables exist.

I'll take a look at the Environment Variables document to see how we can some of this clearer. Thanks again for filing this! :)
