### ISSUE TITLE
The parents jobs must allow `filters.tags`

### ISSUE THREAD

**Issue by klahnakoski** [circleci/circleci-docs#2511]
# Location
https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

# Explanation
Instead of "... and all its transitively dependent jobs must also have a filters tags section" say "... and all its job dependencies must also have a filters tags section."  The former reads as if all children jobs must have `filters.tags`, while in fact all parent jobs require `filters.tags`.

**Comment by smart-alek** [comment]
Hey @klahnakoski! I definitely see the confusion here: I believe transitively dependent is _supposed_ to  imply the **required jobs** of another job. "Parent job" might seem synonymous, but it's a bit misleading to talk about a parent/child relationship for jobs.

What I'll do is use some simpler language around this requirement to clear up this confusion. Thanks for submitting this issue!
