### ISSUE TITLE
MIgrate Internal/Root CA docs to 2.0

### ISSUE THREAD

**Issue by eddiewebb** [circleci/circleci-docs#2523]
# Missing Information
The use of internally signed or custom Certificate AUthority certs is supported but undocumented.  1.0 docs reference invalid procedure.

# Already Looked
Closest is https://circleci.com/docs/enterprise/custom-ca/  but wrong

# Potential Locations
https://circleci.com/docs/2.0/certificates/ is currently focused on adding SSL certs to ELBs, but could be broken up, otherwise a new https://circleci.com/docs/2.0/certificate-authorities page in the server section.

**Comment by eddiewebb** [comment]
I'll start drafting this as I have working steps in https://github.com/circleci/customer-eng/wiki/Installing-CA-Certificates-to-trust-self-signed-or-internal-certs and Daimler is asking for it for their trial

**Comment by smart-alek** [comment]
@eddiewebb what's the status on this one? Anything I can do to help get it over the line?

**Comment by michelle-luna** [comment]
Hi Alek,

We are waiting for June to review and approve this.

Thanks!
Michelle
