### ISSUE TITLE
2.0 Docs For Using Firebase Test Lab for Android Devices

### ISSUE THREAD

**Issue by MatthewTighe** [circleci/circleci-docs#2525]
# Missing Information
I'd like to be able to set up instrumented testing for my Android application. There is a guide in the 1.0 docs but not in the 2.0.

# Already Looked
https://circleci.com/docs/2.0/language-android/
https://circleci.com/docs/2.0/tutorials/
https://circleci.com/docs/2.0/sample-config/
https://circleci.com/docs/2.0/test/

https://circleci.com/docs/1.0/android/

# Potential Locations
I would expect it to be a part of https://circleci.com/docs/2.0/language-android/ or to have a link on that page.

**Comment by smart-alek** [comment]
Hey @MatthewTighe, thanks for submitting an issue!

It is _likely_ that the 1.0 guide should work for you on 2.0. And if not, this document is actually part of a [larger effort](https://github.com/circleci/circleci-docs/projects/3#card-10969130) to migrate 1.0 docs to 2.0.

Regardless, I'm in conversations with the language experts themselves, and I've bumped this migration project up in the priority list. Thanks for submitting!
