### ISSUE TITLE
Android image now includes NDK?

### ISSUE THREAD

**Issue by ahxxm** [circleci/circleci-docs#2529]
# Locations

(Android Image Docs)[https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-android.md]
(Android Image)[https://hub.docker.com/r/circleci/android/tags/]

# Conflict Description

I found NDK under `/opt/android/ndk/android-ndk-r17b`(:api-28-alpha), although `ANDROID_NDK_HOME` was still `/opt/android/ndk`.

**Comment by smart-alek** [comment]
Hey @ahxxm, thanks for submitting an issue!

I took a look at the Dockerfile for `api-28-alpha`, and it does indeed look like we're installing the NDK. I'll get the docs updated for that posthaste.

Question for you re: the conflict description — were you expecting to find `ANDROID_NDK_HOME` somewhere else other than `/opt/android/ndk`?
