### ISSUE TITLE
RE: jekyll/_docs/docker-btrfs-error.md

### ISSUE THREAD

**Issue by ThomasWo** [circleci/circleci-docs#253]
Unfortunately, the referenced issue (below) on this page is a blocker for my builds (occuring on every build) and the only suggested work-around is accessing btrfs directly, which is impossible in the CircleCI environment.  Is there a work-around that will work in CircleCI?

`Error removing intermediate container 9988070f8621: Cannot destroy container 9988070f8621135d7af41973b9e20a9kdk9178795c0fa1371b0ff111238a4e76a: Driver btrfs failed to remove root filesystem 9988070f8621135d7af41973b9e20a9kdk9178795c0fa1371b0ff111238a4e76a: Failed to destroy btrfs snapshot: operation not permitted`

**Comment by keybits** [comment]
Sorry we never got back to you about this. We've been working hard on CircleCI 2.0, now in private Beta (https://circleci.com/beta-access/), which has much more complete Docker integration. The CircleCI 1.0 Docker support and docs won't be updated as we're encouraging all customers using Docker to try out 2.0.
