### ISSUE TITLE
jest deprecated testresultsprocessor in you guide for /collect-test-data/#jest

### ISSUE THREAD

**Issue by janat08** [circleci/circleci-docs#2539]
# Missing Information
 https://github.com/jest-community/jest-junit#usage:

# Already Looked
https://circleci.com/docs/2.0/collect-test-data/#jest

# Potential Locations

**Comment by janat08** [comment]
their docs point out that for CI the usage is: jest --ci --testResultsProcessor="jest-junit".

**Comment by janat08** [comment]
their docs are also conflicting with the warning

**Comment by neo35** [comment]
Hatte Unfall mus kurz erholen Sorry

zhan ishzhanov <notifications@github.com> schrieb am Do., 2. Aug. 2018,
13:50:

**Comment by smart-alek** [comment]
@janat08 can you say more about what you mean here? Which warning?

**Comment by janat08** [comment]
when you run commands specified in docs warning appears about usage of testprocessor option.
