### ISSUE TITLE
Incorrect job name

### ISSUE THREAD

**Issue by gwynhowell** [circleci/circleci-docs#2545]
# Locations
https://circleci.com/docs/2.0/config-intro/

# Details
The documentation  refers to a job called "Run-In-A-Container", but the job is actually called "Run-With-Node"

**Comment by michelle-luna** [comment]
Hi @gwynhowell thanks for this catch. I have a PR to fix it. This doc is totally new, so if you have any other feedback, I'd love to hear what you thought/if this helped you/what else could be improved. Appreciate your time!
