### ISSUE TITLE
postgresql-client install tries to start server

### ISSUE THREAD

**Issue by cthorner** [circleci/circleci-docs#2548]
# Description
- run: sudo apt install postgresql-client

should be:
- run: sudo apt install -y postgresql-client || true

to avoid error when the apt installation tries to starting the server

# Location
- run: sudo apt install postgresql-client

# Steps to Reproduce
on Ubuntu 14.04 Trusty
run the build job

**Comment by smart-alek** [comment]
Hey @cthorner, thanks for filing this!

Which document did you find this information in?

**Comment by smart-alek** [comment]
Is it https://circleci.com/docs/2.0/postgres-config/ ?
