### ISSUE TITLE
Ruby Guide: Which images are recomended?

### ISSUE THREAD

**Issue by drazisil** [circleci/circleci-docs#2558]
# Locations
Add a link to the document (or documents)
with the conflicting documentation.

https://circleci.com/docs/2.0/language-ruby/

# Conflict Description
Describe the conflicting documentation.
```
The official Ruby images are tagged to use the latest patch-level version of 2.4 and with additional packages installed for NodeJS.

The official Postgres image is specified for use as the database container.
```

The above wording says the official images are used, but the examples use CircleCI images. This is confusing to me.

**Comment by drazisil** [comment]
Also, `Check out our Job page to see how this looks when building on CircleCI.` is very confusing language as I initially read it as go check out our open jobs page.

**Comment by smart-alek** [comment]
Nice catch @drazisil, I'll get these squared away this week. :)
