### ISSUE TITLE
Missing ordering information

### ISSUE THREAD

**Issue by pankopiotr** [circleci/circleci-docs#2562]
# Missing Information
For endpoints that return lists of objects, sometimes ordering information is missing.
E.g. https://circleci.com/docs/api/v1-reference/#recent-builds-project-branch does not say whether returned result is ordered in some way and if so, by which attribute.

# Already Looked
https://circleci.com/docs/api/v1-reference/

# Potential Locations
In endpoint description.

**Comment by smart-alek** [comment]
Hey @pankopiotr, thanks for filing an issue.

So, for this particular example: `steps` is a list inside the response for "recent builds for a project branch". You're curious how that list is ordered. Is it by name? Or number of actions? And this question would apply to other endpoints, like [List Checkout Keys](https://circleci.com/docs/api/v1-reference/#list-checkout-keys).

Let me know if I've got that right, and I'll get this taken care of! :)

**Comment by pankopiotr** [comment]
No, I am curious how whole list (so in my case, list of all recent builds) is ordered. Is it by `stop_time`, `start_time`, `queued_time` or whatever else. For example endpoint `Recent Builds Across All Projects` description says 'Build summary for each of the last 30 recent builds, *ordered by build_num*.'  I think this info should be included for every endpoint that returns more then 1 build.
