### ISSUE TITLE
gh-bb-integration/#machine-user-keys could use some clarification

### ISSUE THREAD

**Issue by ucbjrl** [circleci/circleci-docs#2568]
# Location
https://circleci.com/docs/2.0/gh-bb-integration/#machine-user-keys

# Explanation
```
2. Go to https://circleci.com and log in. GitHub will ask you to authorize CircleCI to access the machine user’s
account, so click on the Authorize application button.
```

Log in as who? The machine user? I have machine user accounts on GitHub and CircleCI.
I'd like to add additional repositories (to which the machine user has access) to CircleCI projects.
Presumably, one reason to use machine user keys is to reduce the privileges required in order to checkout code and run tests.
Requiring the machine user to have admin writes on all the repo's it's going to be testing seems diametrically opposed to the idea of a machine user.

Is it the case that all CircleCI projects have to use the GitHub id of a repository admin?

**Comment by smart-alek** [comment]
Hey @ucbjrl, thanks for submitting an issue! I've reached out to our support team before I answer anything on here.

But! In the meantime, can you tell me what you mean by a CircleCI machine user account? Did you create a machine user account on GitHub and use _that_ account to create a CircleCI account?

**Comment by ucbjrl** [comment]
Yes, I created a machine user account on GitHub and created a CircleCI account from that GitHub machine user account. I have some "test" repositories owned by that account on GitHub which I've been using for my CircleCI tests (successfully by the way). Those repositories were forked from the "production" GitHub repositories and the GitHub machine user has admin access to those "test" repositories.

The GitHub machine user has read/write access to the production repositories. I'd like to be able to run the same tests that I have been running on the "test" repositories, on the "production" repositories, but I'd rather not have to give the GitHub machine user admin access to the "production" repositories.

**Comment by smart-alek** [comment]
@ucbjrl apologies for the turnaround on this. Here's some quick answers to get you sorted, and then I'll have a docs update coming in hot.

Briefly:

Yes, you'll log in as the GitHub machine user you created. All CircleCI projects need a machine user with write access until **after** the project has been added. This is required to create a deploy key on CircleCI. After that, you can flip the machine user privileges back to read-only.

That last part is definitely not clear, but hopefully it will be after I mess with the docs! Thanks for your patience. :)
