### ISSUE TITLE
JUnit output example for fastlane (_cci1/test-metadata.md)

### ISSUE THREAD

**Issue by jmcopeland** [circleci/circleci-docs#257]
Would love to see an example using the JUnit output from `fastlane test` for iOS apps.

**Comment by smart-alek** [comment]
@jmcopeland thanks for requesting this!

We're closing out 1.0 issues involving edits/drafts in favor of our [2.0 docs](https://circleci.com/docs/2.0/). Just wanted to keep you in the loop! :)
