### ISSUE TITLE
Docker docs incorrect; impossible to get correct status exit code from tests

### ISSUE THREAD

**Issue by OJFord** [circleci/circleci-docs#258]
The [docker docs](https://github.com/circleci/circleci-docs/blob/master/jekyll/_docs/docker.md) talks about using `lxc-attach` to get around lack of Docker's `exec`.

This is incorrect, and results in:

> lxc-attach failed to get the init pid

since Docker now uses libcontainer instead of LXC.

This also means that it appears to be impossible to get a correct exit code out of docker-compose tests - since we cannot `exec`, `run` always exits `0`, and `run --rm` exits with test result before attempting to remove containers at which point it fails and exits `1`.

**Comment by keybits** [comment]
Sorry we never got back to you about this. We've been working hard on CircleCI 2.0, now in private Beta (https://circleci.com/beta-access/), which has much more complete Docker integration. The CircleCI 1.0 Docker support and docs won't be updated as we're encouraging all customers using Docker to try out 2.0.
