### ISSUE TITLE
Improve page "use custom Docker images with CircleCI"

### ISSUE THREAD

**Issue by dmitry-kabanov** [circleci/circleci-docs#2580]
# Missing Information
Give a brief overview of the information you were looking for.
When I read page "use custom Docker images with CircleCI", I don't see anything mentioning that CircleCI changes Docker user and entrypoint.
So, I was surprised to see that the Docker image I created and tested locally, does not work as I expected on CircleCI.
Particularly, locally I had entry point "/bin/bash --login" (and it was the root process), however, on CircleCI the root process is "/bin/sh" with "/bin/bash" being current subprocess.

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

# Potential Locations
Page ""use custom Docker images with CircleCI" could be much more improved if you mention that CircleCI creates a new user and how to modify an environment of this new user.

**Comment by smart-alek** [comment]
Hey @dmitry-kabanov, thanks for filing this!

So, we've got a section a bit further down that page that talks about [adding an entrypoint](https://circleci.com/docs/2.0/custom-images/#adding-an-entrypoint). Were you able to find that section? If not, do you have strong feelings on where that information should go?
