### ISSUE TITLE
Determine whether a job is running with the local CLI or not

### ISSUE THREAD

**Issue by stefanwalther** [circleci/circleci-docs#2584]
# Missing Information
I am missing some information how to find out whether a job is being executed locally (using the CLI) or online.
Use case: In case I am running the job locally, I don't want to e.g. push a docker-image to Docker Hub.

**Comment by smart-alek** [comment]
Hey @stefanwalther, thanks for submitting an issue! Was there somewhere you were already looking for this information in the existing docs?

**Comment by stefanwalther** [comment]
Yes, basically I did not find anything in the current documentation answering my question, in particular here: https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by smart-alek** [comment]
Hey @stefanwalther: sorry for the late response here!

While there is no explicit `CIRCLE_BUILD_LOCATION` env var, there are several (indirect) ways you could determine whether a job is running locally or not:

- use the `CI` variable. This should only be `true` if you're in a CI environment.
- check for an env var that **only** exists in the cloud, like `CIRCLE_BUILD_URL`
- check for an env var that **you** set in the project UI. These don't get exported into local builds

And in your particular use case, deploying should fail automatically for a local job! I'll close this issue for now, but let us know if you're still blocked. :)
