### ISSUE TITLE
Which roles are required for the service account to fetch and pull from GCR?

### ISSUE THREAD

**Issue by stabenfeldt** [circleci/circleci-docs#2589]
# Missing Information
I want to push my docker image to GCR after running tests on CircleCi.

Which roles does my service account require to be able to pull and push images to GCR?
Even as an account with the role "Project Owner", I get this error:

     gcloud --quiet container clusters get-credentials $PROJECT_ID
       Fetching cluster endpoint and auth data.
       ERROR: (gcloud.container.clusters.get-credentials) 
       ResponseError: code=403, 
       message=Required "container.clusters.get" permission(s) 
       for "projects/$PROJECT_ID/locations/europe-west1/clusters/$CLUSTER".

**This is how I authenticate**

*.circleci/config.yml*

          name: Authenticate
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

But it failed on the last step.

# Already Looked
I read your docs describing [Creating and Storing a Service Account](https://circleci.com/docs/2.0/google-auth/#creating-and-storing-a-service-account), but they don't tell which roles the service account requires.

# Potential Locations
It would be nice if you updated the existing [Creating and Storing a Service Account](https://circleci.com/docs/2.0/google-auth/#creating-and-storing-a-service-account) document.

**Comment by smart-alek** [comment]
@stabenfeldt great catch! I'll get these roles added to the document you linked. Thanks for submitting an issue :)

**Comment by smart-alek** [comment]
@stabenfeldt sorry for the delay — just hopping back into this one.

You **should** be able to just create a service account with whatever default role is present. When I tested that document, no special roles were necessary. It could be that permissions have changed on that particular cluster you're trying to access.

I did some digging for you, and maybe you can check out [this thread](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/10) and [this troubleshooting section](https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted).

Let me know if that's helpful or not!

**Comment by smart-alek** [comment]
Hey @stabenfeldt!

So I've cleaned up this document in a recent PR, but your issue called out two things:

- checking the clusters is not a necessary command for pushing to GCR
- the default role of the service account (Project > User) is sufficient to push to GCR
- setting the `GOOGLE_APPLICATION_CREDENTIALS` env var is required for server-to-server comms.

Hope that helps!

**Comment by stabenfeldt** [comment]
Thanks for the update! I'm now successfully pushing the images to GCR and deploying new images to the Kubernetes cluster.
My service account has these roles:
```
Kubernetes Engine Admin
Kubernetes Engine Cluster Admin
Storage Admin
Storage Object Viewer
```

**Comment by smart-alek** [comment]
Excellent! And in this case, you've done exactly what Google wants you to do, which is define more granular permissions instead of using the enormous hammer that is the "Owner" role.

Happy building to you, sir!

**Comment by stabenfeldt** [comment]
Hi, just wanted to let you know that the docs isn't updated yet.
https://circleci.com/docs/2.0/google-auth/#creating-and-storing-a-service-account

**Comment by teesloane** [comment]
Hi @stabenfeldt! Do you mind sharing any docs you found along the way describing permissions you needed to use/update on GCR? It sounds as though the level of specificity for permissions may vary from project to project depending on a user's tooling. While the current documentation found no issues using a default service account, perhaps we can at least link to some external docs to accompany the guide.

Thanks for lending a hand!

**Comment by stabenfeldt** [comment]
Hi @teesloane, 

I didn't find any documents describing exactly which permissions my **Build and deploy** role required. This is how I managed to figure out which it required.

- First I created an service account and downloaded it's keys.
- Then I authenticated as that account. 
   `gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json`

- Then I tried to push an image to GCR. It failed and I saw which permission it was complaining about missing. E.g. `Caller does not have permission 'storage.buckets.get'`. 
- Then I navigated my browser to *IAM & admin, Roles* and gave that permission to my **Build and deploy** role connected to my service account.

Hope this helps! :-)

**Comment by teesloane** [comment]
Hi @stabenfeldt,

Thank you for your very prompt and detailed response (I especially appreciate that you went through and recreated the steps). I'll put up a PR today and tag this issue so you can keep an eye on it's progress (and in case any other dev's make suggestions on the topic).

Cheers!!
