### ISSUE TITLE
CIRCLE_WORKFLOW_ID missing from builds

### ISSUE THREAD

**Issue by MandarinConLaBarba** [circleci/circleci-docs#2599]
# Locations
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

# Details
The above documentation states that CIRCLE_WORKFLOW_ID is available, but does not appear to available (at least in my builds). In the "Spin up Environment" step of my build, the env variables are printed and this environment variable is not present. I'm using Circle 2.0 configuration.

**Comment by smart-alek** [comment]
Hey @MandarinConLaBarba, thanks for filing an issue! I'll look into whether this was changed on our end, and update the docs as necessary.

**Comment by smart-alek** [comment]
Hey @MandarinConLaBarba, I synced up with one of our engineers, and he confirmed that the variable is indeed being set. He's guessing that you either didn't have a workflow or launched another shell with a different environment!

Thanks for the concern, though, and let us know if you have any other issues! :)
