### ISSUE TITLE
Artifactory usage missing from 2.0 docs

### ISSUE THREAD

**Issue by 00willo** [circleci/circleci-docs#2603]
We're using Artifactory and in looking up information about any integrations, I noticed that there is only documentation describing how to utilise their service in the 1.0 docs. 
https://circleci.com/docs/1.0/Artifactory/

I'm happy to submit a PR with a porting of the information to 2.0. Just wanted to check if there was anything that I should be aware of in relation to the doc porting process. As we use python, I'll add a python implementation example too.

**Comment by michelle-luna** [comment]
Hi @00willo 

We do have this documented for 2.0 now, see https://circleci.com/docs/2.0/artifactory/, let me know if this meets your needs or if anything is missing, etc.

We have a couple examples for python as well, https://circleci.com/docs/2.0/language-python/ and https://circleci.com/docs/2.0/project-walkthrough/ let me know if those are what you were looking for.

Thanks!
Michelle

**Comment by 00willo** [comment]
Hi @michelle-luna, somehow I totally missed that. I was sure I searched and couldn't find it.

As for python examples, I was referring to Artifactory specific example as was mentioned at the bottom of the 1.0 Artifactory docs, "more language examples to follow".
