### ISSUE TITLE
Missing details of machine image

### ISSUE THREAD

**Issue by 00willo** [circleci/circleci-docs#2604]
# Location
- https://circleci.com/docs/2.0/executor-types/#using-machine

# Explanation
- Does the "OS to use for builds" radio box under Build Settings - Build Environment also affect the machine executor or just docker images?
- What type of virtual machine is the machine executor?
- Custom images - not clear that you can't use these in the hosted environment.

Again, I'm happy to start a PR on this for feedback and review.

**Comment by michelle-luna** [comment]
Hi @00willo ,

Thanks for these comments, I would welcome a PR that add some more information! 

1. The OS radio button is only for 1.0, so it should not be used (1.0 will be end of lifed next week)
2. I'm not sure what this question means.
3. In the table on this page for Custom Image under the machine column 'No', but we can certainly call this out in the section as well.

Regards,
Michelle

**Comment by 00willo** [comment]
By type of machine executor, I mean is it Xen, KVM  etc?  As not all "virtual machines" are created equal, knowing more about the VM itself and the platform it's running on would allow devs to not waste time experimenting to see if "that's going to work".
