### ISSUE TITLE
Missing initial sections on the primary landing page for machine images

### ISSUE THREAD

**Issue by 00willo** [circleci/circleci-docs#2605]
# Location
- https://circleci.com/docs/2.0/build/

# Explanation
The fact that this page has "machine" in the title, but no further sections on it like it does for docker and IOS was extremely confusing at first. Being one of the first pages to hit while viewing the docs, lead me down the wrong path, as most of my usage of CircleCI involves utilising docker and other virtualisation.

**Comment by michelle-luna** [comment]
Right, we don't have separate docs for machine, so I think you would just like to see the 'Using Machine' section in the Choosing Executor Types document highlighted on this landing page? Would that have helped you?

Thanks for your time to feedback!
Michelle

**Comment by michelle-luna** [comment]
fixed this title in https://github.com/circleci/circleci-docs/pull/2668
