### ISSUE TITLE
RE: jekyll/_docs/language-python.md

### ISSUE THREAD

**Issue by philgyford** [circleci/circleci-docs#261]
When running unittests for a Django site they were failing due to a CSS file not being found. I'm using Whitenoise and so found [this issue](https://github.com/evansd/whitenoise/issues/86) and the solution, which is to `collectstatic` before running the tests:

    test:
      pre:
        - ./manage.py collectstatic --no-input

Maybe this should be mentioned in the part of the page that refers to Django tests?

**Comment by bear** [comment]
@philgyford done - thanks for the report and info to keep our docs awesome!
