### ISSUE TITLE
Move deployment section to anatomy article or link to it (_cci1/manually.md)

### ISSUE THREAD

**Issue by awlawl** [circleci/circleci-docs#264]
The "The anatomy of a CircleCI build" section outlines the document and the last item in the outline is "(Optionally) deploy your code". This section isn't in the document, and leaves me hanging about how to write the deployment section.

**Comment by felicianotech** [comment]
You can learn about the deployment section here: https://circleci.com/docs/configuration/#deployment

We'll make this doc more complete. I agree that currently it does a poor job of giving you all the information you need.
