### ISSUE TITLE
Unclear how to install on Windows

### ISSUE THREAD

**Issue by awentzel** [circleci/circleci-docs#2654]
# Missing Information
The documentation does not include how to install CircleCI CLI (new version) on Windows 10+.  It does so for Mac/Linux.  But, not windows.  Is Windows even supported or is it just missing documentation?

# Already Looked
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-cli.md
https://github.com/CircleCI-Public/circleci-cli
https://www.bing.com/search?q=how+to+install+%22circleci%22+cla+on+windows&qs=n&form=QBRE&sp=-1&pq=how+to+install+%22circleci%22+cla+on+windows&sc=1-40&sk=&cvid=A46170C3B58B4987BBB5814A0E6884B4

# Potential Locations
I would expect this to be right next to the installing on Linux/MacOS section.

**Comment by michelle-luna** [comment]
instructions were just added https://github.com/circleci/circleci-docs/pull/2658
