### ISSUE TITLE
Enabling xdebug does not work as written (_cci1/language-php.md)

### ISSUE THREAD

**Issue by torkiljohnsen** [circleci/circleci-docs#267]
Enabling xdebug with php7.0.4 does not work like the docs suggests:

``` bash
$ sed -i 's/^;//' /opt/circleci/php/$(phpenv global)/etc/conf.d/xdebug.ini
sed: can't read /opt/circleci/php/7.0.4/etc/conf.d/xdebug.ini: No such file or directory

sed -i 's/^;//' /opt/circleci/php/$(phpenv global)/etc/conf.d/xdebug.ini returned exit code 2

Action failed: sed -i 's/^;//' /opt/circleci/php/$(phpenv global)/etc/conf.d/xdebug.ini
```

**Comment by smart-alek** [comment]
@torkiljohnsen thanks for catching this! We're closing most of our 1.0 issues in favor of getting our [2.0 docs](https://circleci.com/docs/2.0/) to a good place. Just wanted to loop you in so you don't feel like you're being ignored! :)
