### ISSUE TITLE
Problem using "X11 forwarding over SSH"

### ISSUE THREAD

**Issue by eric-simonton-sama** [circleci/circleci-docs#2712]
# Description
I'm trying to find a more convenient way to debug browser tests. Yesterday I tried "Sharing CircleCI’s X Server", but has problems as you can see on #2711. Today I'm trying to follow the instructions for "X11 forwarding over SSH", and am running into error messages again.

Here I am running the 3 commands in the documentation, plus one more that I know should try to open a window, since it seems `xclock` (which the documentation tells me to run) is not on the machine.
```
Erics-MacBook-Pro:~ eric$ ssh -X -p 64535 ubuntu@xx.201.214.110
circleci@53a3d59e0193:~$ export DISPLAY=localhost:10.0
circleci@53a3d59e0193:~$ xclock
bash: xclock: command not found
circleci@53a3d59e0193:~$ google-chrome

(google-chrome:3388): Gtk-WARNING **: cannot open display: localhost:10.0
```

I tried this with xQuartz running (I'm on a mac), and I tried it using a bash shell from within an xQuartz window.

# Location
https://circleci.com/docs/2.0/browser-testing/#x11-forwarding-over-ssh

# Steps to Reproduce
See the console commands I ran above.

**Comment by michelle-luna** [comment]
thanks for reporting this, I will take a look

**Comment by michelle-luna** [comment]
Maybe this article helps you? https://superuser.com/questions/310197/how-do-i-fix-a-cannot-open-display-error-when-opening-an-x-program-after-sshi

**Comment by eric-simonton-sama** [comment]
I suppose I can look into it next time I want to try this. I take it the instructions in the docs worked as-is for you, so there must be something different with our setup? Maybe something to do with the docker images we use?
```
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/postgres:10.2
      - image: redis:3.2.9
```
