### ISSUE TITLE
How Build Artifacts are protected?

### ISSUE THREAD

**Issue by yuricus** [circleci/circleci-docs#2728]
# Missing Information
How Build Artifacts for private projects are protected? Same credentials as CircleCI user? Not protected at all? Just random link? How to configure this?

# Already Looked
https://circleci.com/docs/2.0/artifacts/

# Potential Locations
Maybe a section at https://circleci.com/docs/2.0/artifacts/?

**Comment by yuricus** [comment]
Ok, I found on my own that artifacts are protected with CircleCI account, nice to have it in the documentation too.

**Comment by michelle-luna** [comment]
thank you!
