### ISSUE TITLE
Does the side-menu actually work?

### ISSUE THREAD

**Issue by aspin** [circleci/circleci-docs#2746]
# Description
I can't use any of the navigation/table-of-contents controls on the left hand side of the CircleCI docs.

# Location
I think this happens on every page in the documentation: for e.g. https://circleci.com/docs/2.0/configuration-reference/

# Steps to Reproduce
I went to the above page (or any docs page) in Firefox, Chrome, in an incognito window, and asked a friend, and nothing happens when we select any of the options on the left. I expect the accordion to open up, and to be able to click the links to navigate to documentation.

**Comment by michelle-luna** [comment]
Hi, thanks for this report, yes it is broken by a recent push, @trevor-circleci is working on it now.

**Comment by michelle-luna** [comment]
ok, this was fixed earlier, but that fix caused another problem, so I reverted it and will close this issue. Thanks again for reporting it! https://github.com/circleci/circleci-docs/pull/2752
