### ISSUE TITLE
clarify how to run the same tests on multiple python images

### ISSUE THREAD

**Issue by piem** [circleci/circleci-docs#2757]
# Location

In [`language-python.md`](/circleci/circleci-docs/blob/master/jekyll/_cci2/language-python.md), it is unclear why `image: circleci/postgres:9.6.2` is being defined at all.

# Explanation

More generally, it would be nice to have an example of `.circleci/config.yml` running the same steps on 2 different images.

I am looking into migrating from the following `.circle.yml` to a v 2.0 configuration, running on both 2.7 and 3.6, as was the case with the previous configuration. Here are the two examples :
 - [previous `circle.yml`](https://github.com/aubio/aubio/blob/master/circle.yml)
 - [tentative `.circleci/config.yml`](https://github.com/aubio/aubio/blob/feature/circleci2/.circleci/config.yml)

thanks, piem

**Comment by michelle-luna** [comment]
thanks, I will add some comments to this guide to make it more clear (you can just define another job with the same tests and a different docker image.
