### ISSUE TITLE
Update Django-nose configuration requirements (_cc1/test-metadata.md)

### ISSUE THREAD

**Issue by Polidoro** [circleci/circleci-docs#276]
https://circleci.com/docs/test-metadata/#automatic-test-metadata-collection

Minor detail but this line wasn't accurate for my implementation:
_Configure your tests to run using the django-nose test runner. We’ll do the rest automatically._

I had to configure the CircleCI project to create a the `$CIRCLE_TEST_REPORTS/django` directory and move the nosetests.xml file there once the tests were done.

**Comment by smart-alek** [comment]
@Polidoro it's certainly possible that this doc isn't completely true!

However! we're closing most of our 1.0 docs issues so we can focus on [2.0 docs](https://circleci.com/docs/2.0). Check those out if you haven't yet, and thanks again for contributing! :)
