### ISSUE TITLE
Configuration reference levels are unclear

### ISSUE THREAD

**Issue by aspin** [circleci/circleci-docs#2760]
# Location
https://circleci.com/docs/2.0/configuration-reference

# Explanation
This probably isn't fixable purely via Markdown, but it's pretty hard to tell when you're going from a field (e.g. `job`) to another field on the same level (e.g. `workflows`) vs. to a parameter of `job` (e.g. `environment`). A slightly smaller text header (compared to another header which you probably don't see anymore since you scrolled down) isn't clear.

IMO the "best" solution to this would be to have the reference configuration TOC fixed on the side (probably right, since the documentation reference is already on the left) so you can easily see where you are in the page.

**Comment by michelle-luna** [comment]
Hi @aspin , 

Thanks for this feedback, much appreciated! We have a plan to try to improve this in exactly the way you describe (putting the TOC in the side menu).

We were thinking we would try to use slate and format the doc like the new format for our API doc, see https://circleci.com/docs/api/ and let me know what you think.

-Michelle
