### ISSUE TITLE
2.0 ECS ECR documentation missing explanation/source for deploy.sh script

### ISSUE THREAD

**Issue by mcgwiz** [circleci/circleci-docs#2781]
# Missing Information
In the [ECS ECR documentation](https://circleci.com/docs/2.0/ecs-ecr/), a reference to deploy.sh is made in the config file. This script is not detailed anywhere.

# Already Looked
Looks like this is a remnant of the [CircleCI 1.0 version of this documentation](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-aws-ec2-container-service.md). In that documentation, a reference is made to a [sample project](https://github.com/circleci/go-ecs-ecr), where the [deploy.sh](https://github.com/circleci/go-ecs-ecr/blob/master/deploy.sh) script exists.

# Potential Locations
These links and explanations should exist in the 2.0 ECS ECR documentation.

**Comment by michelle-luna** [comment]
thanks for this detailed comment, much appreciated!
