### ISSUE TITLE
Exact specifics of which types of git tag are supported is missing.

### ISSUE THREAD

**Issue by michaelkaye** [circleci/circleci-docs#2788]
# Missing Information

Does circleci's 2.0 support for builds based on tags use both lightweight and annotated tags or just one or just the other?

I want to be sure that my configuration issue is because of a configuration issue not that we're using the wrong sort of tags - confirming this one way or the other would be useful.

# Already Looked
https://circleci.com/docs/2.0/configuration-reference/#tags
https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/23
https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag

# Potential Locations
https://circleci.com/docs/2.0/configuration-reference/#tags
https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag

**Comment by michelle-luna** [comment]
Hi @michaelkaye we do support both lightweight and annotated.
