### ISSUE TITLE
missing example of how to use the commands section

### ISSUE THREAD

**Issue by grudelsud** [circleci/circleci-docs#2798]
# Missing Information
commands section has been added with config 2.1 but there is no example on how to use it in the jobs section

# Already Looked
everywhere in the reference https://circleci.com/docs/2.0/configuration-reference/

# Potential Locations
I would expect to see:
- an indication on how to find out if the server is running 2.1, particularly for on-prem installations
- an example on how to use any command from the commands section both in its dedicated paragraph and the full working example at the bottom of the config reference page

thanks!

**Comment by michelle-luna** [comment]
Thanks for this question and suggestion. I will check about 2.1 for on-prem.
