### ISSUE TITLE
Document how long `hold` jobs stick around for (forever)

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#2831]
It's not documented how long a `hold` job will wait around for someone to approve it. According to @KyleTryon, there's no time limit. We should document this.

ref: https://discuss.circleci.com/t/when-does-job-with-manual-approval-expires/25703/2?u=felicianotech

**Comment by KunalJain** [comment]
We are working on change where this will not be true. cc @appplemac

**Comment by appplemac** [comment]
Thanks for looping me in — we are likely to limit that at 30 days. I’ll add a note to update the docs once that is done.

**Comment by felicianotech** [comment]
@appplemac Friendly bump.

**Comment by appplemac** [comment]
Hi! We haven’t gotten to it yet. Will document this when we have a plan in place. Thanks for your patience.

**Comment by schuyler** [comment]
Bump
