### ISSUE TITLE
Correct python project cache configuration example

### ISSUE THREAD

**Issue by Agilulfo** [circleci/circleci-docs#2847]
# Locations
https://circleci.com/docs/2.0/language-python/#cache-dependencies

# Details
pipenv does not create a .venv folder
A folder instead is created under ~/.local/share/virtualenvs

probably this is a refuse from a previous version of the documentation using virtualenv

**Comment by teesloane** [comment]
Hi!

Thanks for taking the time to file an issue!

In the [python example](https://circleci.com/docs/2.0/language-python/#add-other-services-and-set-environment-variables) doc we set an environment variable (`PIPENV_VENV_IN_PROJECT`) that ensures a `.venv` folder is created and attached local to the project. You can also take a look at our example [config](https://github.com/CircleCI-Public/circleci-demo-python-django/blob/master/.circleci/config.yml#L8) in the linked repo to see the entire config.

I'll close this issue, but if you were finding that even with the above env variable set you were still running into caching issues, please comment and re-open the issue. Thanks!

**Comment by Agilulfo** [comment]
Gotcha! Now it makes sense! I incautiously removed that variable thinking that it was unnecessary for me.. Thanks for the explanation

**Comment by teesloane** [comment]
No problem! Happy to help!
