### ISSUE TITLE
RE: jekyll/_docs/cabal-test-timeout.md Timeouts inaccurate?

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#286]
This page says:

> By default, Circle times out tests if they have not produced output for 180 seconds. cabal test, even with --show-details=always, only produces output as each test suite completes, so it may be necessary to set a higher timeout for commands that run it:

I was under the impression that all commands have a default timeout of 600 seconds.  Am I mistaken or is this page inaccurate?

**Comment by eric-hu** [comment]
Looks like commands have a default timeout of 600 seconds: https://circleci.com/gh/eric-hu/support-sandbox/1115

**Comment by felicianotech** [comment]
@eric-hu Where did you get your info from? I'm a little confused now as well.

It's my understanding that a command, by default, has a timeout of 600 seconds aka 10 minutes. This is whether there's output or not, that's just the hard limit.

I thought this paragraph was mentioning that commands also get timed out when there is no output for 180 seconds, aka 3 minutes. This second timeout being strictly for a lack of output. If there is output the 180 second timeout doesn't apply.

**Comment by eric-hu** [comment]
@felicianotech If you take a look at that build I linked above, I ran "sleep 550" successfully in two phases of the build.  A command like that would be killed if there was a 180 second timeout rule, since `sleep` doesn't output anything while it's running.

**Comment by felicianotech** [comment]
Ah okay that's a great test. I completely missed that.

Interesting regarding `sleep 599`.
