### ISSUE TITLE
inconsistent examples in triggering jobs page (and possible bug)

### ISSUE THREAD

**Issue by rdnewman** [circleci/circleci-docs#2865]
# Locations
https://circleci.com/docs/2.0/api-job-trigger/

# Conflict Description
In `#overview`, it states

```
curl -u ${CIRCLE_API_USER_TOKEN}: \
     -d build_parameters[CIRCLE_JOB]=deploy_docker \
     https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>
```

Note "...`_API_USER_TOKEN`" and a trailing colon.

Later in `#conditionally-running-jobs-with-the-api` it states

```
if [[ true ]]; then
              curl --user ${CIRCLE_API_PROJECT_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=deploy_docker \
              .  .  .
```

Note it now refers to "...`_API_PROJECT_TOKEN`", not `USER_TOKEN`.  

I think the trailing colon is likely incorrect to, but I have less conviction (it seemed to work better when I removed it)"

**Comment by michelle-luna** [comment]
fixed in https://github.com/circleci/circleci-docs/pull/2895
