### ISSUE TITLE
AWS CodeDeploy is 404

### ISSUE THREAD

**Issue by infowolfe** [circleci/circleci-docs#2891]
# Missing Information
https://circleci.com/docs/continuous-deployment-with-aws-codedeploy/ 404

# Already Looked
https://circleci.com/gh/$project/$repo/edit#aws-codedeploy

# Potential Locations
At the above link, since it's referenced from the circleci ui.

**Comment by michelle-luna** [comment]
Thanks for this report, if you can take a screenshot of the ui where this link appears, that would help as well. I will let the UI team know, much appreciated!

**Comment by michelle-luna** [comment]
I reported this to the ui team, so closing because it isn't an issue with the docs repo. thanks!
