### ISSUE TITLE
Using a Local Browser to Access HTTP server on CircleCI

### ISSUE THREAD

**Issue by gfoidl** [circleci/circleci-docs#2902]
# Locations

https://circleci.com/docs/2.0/browser-testing/#using-a-local-browser-to-access-http-server-on-circleci

# Details

I think the ports are mixed, as this would be correct:

| Who | port |  
| -- | -- |  
| Ruby on Rails app | 3000 |  
| localhost | 8080 |

We have https://github.com/circleci/circleci-docs/pull/2876, https://github.com/circleci/circleci-docs/pull/2872, and https://github.com/circleci/circleci-docs/pull/2899 for this, but in current _master_ it is the other way around.

Maybe it's just me thats wrong, but I'm opening this issue in order to clarify before submitting another PR.

/cc: @michelle-luna

**Comment by michelle-luna** [comment]
Uh oh, did I make a mistake when I combined these? This appears in three places, can you specify which part is still incorrect? Thanks and sorry for the confusion!

**Comment by gfoidl** [comment]
Ah, we're here to fix it 😄 
I believe https://github.com/circleci/circleci-docs/pull/2872 is the root for this.

Correct would be the following:

----

2. To add port-forwarding to the command, use the `-L` flag. The following example forwards requests to `http://localhost:8080` to port `3000` on the CircleCI container. This would be useful, for example, if your job runs a debug Ruby on Rails app, which listens on port 3000.
```
ssh -p 64625 ubuntu@54.221.135.43 -L 3000:localhost:8080
```
3. Then, open your browser on your local machine and navigate to `http://localhost:8080` to send requests directly to the server running on port `3000` on the CircleCI container. You can also manually start the test server on the CircleCI container (if it is not already running), and you should be able to access the running test server from the browser on your development machine.

This is a very easy way to debug things when setting up Selenium tests, for
example.

----

So it's just the ports-mismatch. Please double-check if this is right.

Shall I submit a PR for this, or will you make the change?
