### ISSUE TITLE
Include required permissions to access Contexts

### ISSUE THREAD

**Issue by KyleTryon** [circleci/circleci-docs#2913]
# Location
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/contexts.md

# Explanation
Contexts (I believe) are only viewable by "Owners" of an organization. The permissions required are not listed in the docs to reflect this.

**Comment by michelle-luna** [comment]
I don't think this is the case, anyone who is a member can view and add contexts currently.

**Comment by KyleTryon** [comment]
@michelle-luna I just did some testing, it looks like you require "Admin" scope on any repo to access contexts. A regular user with only push access will not be able to access.

**Comment by KunalJain** [comment]
Right now you need to be an admin to view/add/edit contexts under an org.
