### ISSUE TITLE
Unable to install CircleCI Checks for org

### ISSUE THREAD

**Issue by jhoch** [circleci/circleci-docs#2918]
# Description
I am setting up CircleCI for my org/repo to see if my company wants to start using it.  When following the instructions to enable Github Checks, I encountered the following:

![image](https://user-images.githubusercontent.com/9355655/48462191-1ba47300-e78c-11e8-8d6a-b91b838309d3.png)

This only happened for the org - I was able to install the CircleCI Checks application for my personal repos in the expected straightforward fashion.

# Location
[Enabling GitHub Checks](https://circleci.com/docs/2.0/enable-checks/#section=projects)

# Steps to Reproduce
1. Switched to my company's org within CircleCI.
2. Clicked "Settings"
3. Clicked "VCS"

**Comment by KunalJain** [comment]
Can you please open a support ticket and include your GitHub organization name? If you renamed the organization on GitHub, can you please include the old and new name? Thanks!

**Comment by jhoch** [comment]
The issue seems to have gone away (perhaps because I started a paid membership?).  In any case, thank you for the quick response.
