### ISSUE TITLE
Contexts doc links to itself for instructions

### ISSUE THREAD

**Issue by ryanwohara** [circleci/circleci-docs#2933]
# Location
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/contexts.md#environment-variable-usage

# Explanation
Step 5 links to itself "for instructions" which leads a confusing user experience.

**Comment by teesloane** [comment]
@ryanwohara Thanks for catching this. I agree that it might be a bit confusing for a user. I'll get a PR up for this today.

**Comment by teesloane** [comment]
closed in #2942
