### ISSUE TITLE
RE: jekyll/_docs/docker-btrfs-error.md

### ISSUE THREAD

**Issue by benjamin-thomas** [circleci/circleci-docs#294]
Hello, this error returns an error code 1, and prevented my build from continuing.

I had to override it that way for the build to continue: 

``` circle.yml```
dependencies:
    override:
        - docker-compose whatever; echo IGNORE_BTRFS_ERROR
```

This could be useful to someone else?

**Comment by keybits** [comment]
Sorry we never got back to you about this. We've been working hard on CircleCI 2.0, now in private Beta (https://circleci.com/beta-access/), which has much more complete Docker integration. The CircleCI 1.0 Docker support and docs won't be updated as we're encouraging all customers using Docker to try out 2.0.
