### ISSUE TITLE
How to setup external host?

### ISSUE THREAD

**Issue by cannium** [circleci/circleci-docs#2946]
I'd like to run part of the workflow in a controlled environment, currently I can only find https://circleci.com/docs/2.0/vm-service/
There's a snapshot in the document, but I seem cannot find a link to the dashboard. Someone could help?

**Comment by teesloane** [comment]
Hi @cannium,

Thanks for submitting an issue!

The document you linked is for a server installation of CircleCI. If you are interested in running CircleCI on your own server you can sign up for that platform on the [hosting options page](https://circleci.com/product/#hosting-options).

If you are looking for the ability to be able to execute a single job in your config on your own local machine, the [CircleCI CLI tool can do that](https://circleci.com/docs/2.0/local-cli/).

Please let me know if either of these options are of help!
