### ISSUE TITLE
unclear what the page 'Testing Config Files Locally' is doing

### ISSUE THREAD

**Issue by tomdwp** [circleci/circleci-docs#2948]
# Location
https://circleci.com/docs/2.0/examples/#section=configuration

# Explanation
It's really unclear on this page what is going on.  what am I testing?  what will happen when I run the shell script?  Some more background and context plus maybe an example would be helpful.

**Comment by teesloane** [comment]
Hi @tomdwp ! Thank you for filing an issue. I can see how this page is a bit confusing. I've put up a PR (#2957) to make note of the fact that CircleCI has some newer tooling for validating configurations. 

The doc you linked is still relevant to users's on older versions of the CLI or are wanting to manually test things via the API.
