### ISSUE TITLE
RE: jekyll/_docs/docker.md

### ISSUE THREAD

**Issue by mattrayner** [circleci/circleci-docs#295]
Having played around with docker, it seems that mapping the ports 80 or 8080 on the circleci end doesnt work.

I.e. -p 80:80 or 8080:8080 wont respond if you later run a CURL on that port.

Instead, a mapping such as 3000:80 or 3000:8080 is required. This should be documented.

I'll look at adding this as a PR

**Comment by keybits** [comment]
Sorry we never got back to you about this. We've been working hard on CircleCI 2.0, now in private Beta (https://circleci.com/beta-access/), which has much more complete Docker integration. The CircleCI 1.0 Docker support and docs won't be updated as we're encouraging all customers using Docker to try out 2.0.
