### ISSUE TITLE
Creating CircleCI Orb Namespace missing two bits of info

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#2953]
# Missing Information

1. When creating a namespace via the CLI, the org name from the VCS provider is needed. What's undocumented is that that org you specify needs to be already added to CircleCI.

2. The org setting "Uncertified Orbs" needs to be enabled.

Without doing these two things, following the steps in the "creating-orbs" doc won't work.

**Comment by teesloane** [comment]
Thanks @felicianotech ! Are you referring to the [tutorial](https://circleci.com/docs/2.0/creating-orbs/#tutorial) section in the creating orbs docs? If so:

I've addressed 1) on #2940 . For 2), I believe the pre-requisite for uncertified orbs are mentioned in the [pre-requisites](https://circleci.com/docs/2.0/creating-orbs/#circleci-settings) section.

**Comment by felicianotech** [comment]
I'm referring to the very top of the "Creating Orbs" doc. I eventually found the prerequisites down in the doc but they weren't mentioned when they are relevant in the steps at the top.

**Comment by thomasr8** [comment]
Added content to Orbs documentation in PR #2999
