### ISSUE TITLE
Building Docker Images: Contradicting Information About Machine Executor

### ISSUE THREAD

**Issue by ecbrodie** [circleci/circleci-docs#2955]
# Locations
https://circleci.com/docs/2.0/building-docker-images/

# Conflict Description
The documentation mentions:

> setup_remote_docker is not currently compatible with the machine or the macos executors.

But then immediately after, shows a configuration example using the `machine` executor. This seems like contradictory information to me.

I hope this helps.

**Comment by iynere** [comment]
i think you're misunderstanding that docs page @ecbrodie which is probably on us

**Comment by iynere** [comment]
`setup_remote_docker` and the `machine` executor are 2 different ways of building docker images on circle

**Comment by iynere** [comment]
you can use either of them, but there would be no reason to use them both in one job
