### ISSUE TITLE
orbs documentation needs limitation for private installation of circleci

### ISSUE THREAD

**Issue by michelle-luna** [circleci/circleci-docs#2961]
# Missing Information
we need to add info to the using orbs and orbs faq to make clear that this is not yet available for server, "

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.

**Comment by thomasr8** [comment]
Added content to Orbs-FAQ and Creating-Orbs files and added Nathan and Hannah (along with you of course) to review.
