### ISSUE TITLE
StyleSheet not loading on 404 page

### ISSUE THREAD

**Issue by shoma** [circleci/circleci-docs#2995]
# Description
StyleSheet not loading on 404 page, then the page layout was broken.
`<link type="text/css" rel="stylesheet" href="https://d3r49iyjzglexf.cloudfront.net/site-300a0f43e8f43464bbfc37d42adec29bff910a7b271cee35a07623c702d4be8c.css">`

# Location
https://circleci.com/docs/2.0/foo-bar/

**Comment by teesloane** [comment]
Hi @shoma . Thanks for opening this issue.

As far as I can tell, the 404 page is appearing correctly on my browser. Could you post a screenshot of what you're seeing?

**Comment by michelle-luna** [comment]
I confirm this is fixed now, thanks for filing the issue, I saw it too for a time.
