### ISSUE TITLE
Create API Testbed

### ISSUE THREAD

**Issue by ndintenfass** [circleci/circleci-docs#3]
Would be great to have a web-based testbed for using the API

**Comment by bellkev** [comment]
Thanks for bringing this feature request to our attention. I'll run it by the product team as soon as possible.

**Comment by felicianotech** [comment]
@ndintenfass As in live testing? Using real data? Demo API token?

**Comment by drazisil** [comment]
I'm thinking live testing would be best. The result structure for example data should already be covered  in docs, but being able to quickly check a token for data would be faster then curl, especially on Windows where it doesn't usually come installed (that I recall)

**Comment by smart-alek** [comment]
For clarity, is this a browsable API a la https://stripe.com/docs/api? Or more something like this? http://restframework.herokuapp.com/

**Comment by smart-alek** [comment]
@ndintenfass gave me permission to close this one down. Too big to be merely an "issue".
