### ISSUE TITLE
Please remove `sudo` from the instruction of "Authorizing the Google Cloud SDK"

### ISSUE THREAD

**Issue by suzuito** [circleci/circleci-docs#3009]
# Locations

https://circleci.com/docs/2.0/google-auth/

<img width="871" alt="ss" src="https://user-images.githubusercontent.com/2217408/50381890-9dfe4c00-06d5-11e9-9a4e-bd4073c7426f.png">

# Details

I execute a build following this instruction but failed.

<img width="871" alt="ss" src="https://user-images.githubusercontent.com/2217408/50381890-9dfe4c00-06d5-11e9-9a4e-bd4073c7426f.png">

Remove `sudo` from the instruction, the build is succeeded.

<img width="961" alt="ss 1" src="https://user-images.githubusercontent.com/2217408/50381934-778ce080-06d6-11e9-9048-ce5e2eedb6de.png">

**Comment by michelle-luna** [comment]
thank you! fixed in https://github.com/circleci/circleci-docs/pull/3008
