### ISSUE TITLE
Unclear how to add badge to project

### ISSUE THREAD

**Issue by Crashnorun** [circleci/circleci-docs#3032]
# Location
Document in question: [Status Badges](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/status-badges.md)

# Explanation
Under [**Steps"**](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/status-badges.md), The first bullet point is unclear. Should I be looking for the notification section under github or circle ci?

**Comment by michelle-luna** [comment]
Thanks for this feedback! It is in the CircleCI app. On the Settings -> Status Badges page for your project you will find it.

**Comment by Crashnorun** [comment]
Thanks for the info. Adding step by step screenshots would have been helpful.
