### ISSUE TITLE
Configuration page on Environment Variables does not explain how to read them within config.yml

### ISSUE THREAD

**Issue by pete-heirendt-vacasa** [circleci/circleci-docs#3052]
# Missing Information

Although there are multiple doc pages describing how to set environment variables, I cannot find any documentation on how to **read** environment variables from within the `config.yml` file.

Here is example I ran across elsewhere, that does use the environment variables. I cannot find any doc page that describes this `${FOO}` syntax for reading (is it also called "interpolation"?).

```
  steps:
    - setup
    - run:
        name: Create AWS ElasticBeanstalk "Application Version"
        command: |
          export VERSION=${CIRCLE_BRANCH}${CIRCLE_TAG}+${CIRCLE_SHA1: -6}
          export TAG=${VERSION//[\/|+-]/_}
          zip -r "SourceBundle.${TAG}.zip" Dockerrun.aws.json
```
# Already Looked

I found this page dedicated to "Using Environment Variables". But it only describes **setting** them, or the built-in ones.  No mention on how to **read** them, or the `${FOO}` syntax, or any reference to another page that describes that syntax.

- https://circleci.com/docs/2.0/env-vars/#section=projects

# Potential Locations

On the above linked page on "Using Environment Variables".

**Comment by pete-heirendt-vacasa** [comment]
I think I see why I could not find anything in the CircleCI docs about reading environment variables. There are indeed examples in the CircleCI doc on "Using Environment Variables".  The example I had found (above) used `${FOO}` syntax, but the Circle doc uses the `$FOO` syntax.

- https://circleci.com/docs/2.0/env-vars/#section=projects

Both forms looks to be this bash syntax:

- https://www.gnu.org/software/bash/manual/bashref.html#Shell-Parameter-Expansion

Maybe it would be good to reference the bash documentation?

**Comment by michelle-luna** [comment]
Thanks for this feedback, I agree we should refer to the bash docs. Related to this, see h[ttps://ideas.circleci.com/ideas/CCI-I-67](url), Nathan makes a comment about parameterized jobs (documented in h[ttps://circleci.com/docs/2.0/reusing-config/](url)), which we should also highlight as an option now that we support them.
