### ISSUE TITLE
Clarify what happens to contexts if a repo moves orgs

### ISSUE THREAD

**Issue by Aghassi** [circleci/circleci-docs#3080]
# Location
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/contexts.md

# Explanation
The doc doesn't seem to consider what happens if I rely on a context and move my GitHub repo to another org. I'd like clarity, especially for GHE, on what happens.

**Comment by michelle-luna** [comment]
Thanks for this question, I think the doc implies that you can move the repo to another org and still use the unique name for the context and it should work cc'ong @KunalJain  in case this is incorrect.

**Comment by Aghassi** [comment]
I’m under the impression of the new org doesn’t have that context the job will break. So the context needs to exist with the same name in the new org right?

**Comment by michelle-luna** [comment]
Sorry for the delay on this, I'm still trying to get the right answer! Also, when we update this page, we need to remove the discuss link at the end of the page (it has been closed)

**Comment by jesskie** [comment]
Its ok sir

**Comment by michelle-luna** [comment]
Hi! Sorry for the delay, you are correct that if you move your repo to a new org, you must also have the context with that unique name set in that new org. I will update the doc to clarify this.

**Comment by Aghassi** [comment]
🙏 Thanks!
