### ISSUE TITLE
Missing some status information 

### ISSUE THREAD

**Issue by ganezasan** [circleci/circleci-docs#3088]
# Missing Information
Three of statuses are missing in this document. 
> https://circleci.com/docs/2.0/status/

- NOT RUNNING
- FAILING
- NEEDS SETUP

# Already Looked
This document mentioned these statuses. If those statuses also exist in Job, I think that it is better to list them.
> https://circleci.com/docs/2.0/workflows-overview/

**Comment by teesloane** [comment]
Hi @ganezasan. Thanks for filing an issue. As far as I can discern, these missing statuses you've listed are unique to workflows.

**Comment by michelle-luna** [comment]
Let's link from 2.0/status/ page to the workflows-overview section for details about those statuses. Thank you both!
