### ISSUE TITLE
Update node version in example docs

### ISSUE THREAD

**Issue by danawoodman** [circleci/circleci-docs#3089]
Current docs have Node version `4.8.2` which was released `2017-04-04`. Would be good to direct people to a relatively recent version of node instead, say `10.15.1`.

Found in: https://circleci.com/docs/2.0/language-javascript/

**Comment by teesloane** [comment]
Hi @danactive — I took a crack at bumping the version of Node in our demo project and ran into some snags. I think that the demo example might need a pretty thorough clean to get it running with updated dependencies. As it is, I think that the `mern` boilerplate example hasn't been updated in a while and we might need to move toward something simpler.

For now, we'll leave our dependencies pinned as they are in their working state, and I'll start thinking about how I can simplify the guide.

**Comment by danawoodman** [comment]
@teesloane, makes sense. Maybe make it a bit clearer you can specify any node release for the version param as I think people may not realize that

Btw, my username is @danawoodman 😉

**Comment by teesloane** [comment]
Woops! I totally flopped on the autocorrect 🤦‍♂️.

In the meantime, I'll update the docs to clarify that any node version is useable. 

Thanks again!
