### ISSUE TITLE
'Trigger a new Build by Project' does not work on organization specific projects

### ISSUE THREAD

**Issue by infrastructureSepior** [circleci/circleci-docs#3116]
Problem:

When trying to trigger a project under an organization which you are a member of it does not work

Tried:

When having a user specific project I was able to trigger a workflow. However when another project is made under an organisation there was no success. 
The documentation states: "https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/build?circle-token=:token"
As a username I used my github user, and as a token I tried using both a personal circleci which provided me with the following result:

> {
  "message" : "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/#get\"}"
}

when using project specific circleci token, it provides me with the following result:

> {
  "message" : "Project not found"
}

Just for fun I tried replacing username with organization name, which obviously gave me a:

> {
  "message" : "Permission denied"
}

It seems as if you forget to check for projects owned by organisations for which the user is a member of.

**Comment by mihaierosx2** [comment]
I have the same issue, keeps telling me that the project is not found. Can anyone help us with this one?
