### ISSUE TITLE
Notify/Webhook not documented

### ISSUE THREAD

**Issue by aemaem** [circleci/circleci-docs#3145]
# Missing Information
Missing configuration reference for notify/webhook configuration.

# Already Looked
Configuration Reference: https://circleci.com/docs/2.0/configuration-reference/#section=configuration

# Potential Locations
https://circleci.com/docs/2.0/configuration-reference/#section=configuration

**Comment by teesloane** [comment]
Hi there! Thanks for filing an issue. Can you tell me a little bit more about what question(s) you might have that our documentation could help you with? Are you referring to setting up email/slack/etc [notifications](https://circleci.com/docs/2.0/notifications/)? Or is there something specific you need to configure regarding notifications / webhooks in your `.circleci/config.yml`.

**Comment by michelle-luna** [comment]
If this is about the notify key, it is undocumented because it is unstable.

**Comment by aemaem** [comment]
I am referring to webhook notification configured in the 2.0 yaml configuration: https://discuss.circleci.com/t/circleci-2-0-notifications-webhooks/19075/9. I like to check the reference first before committing `config.yml` changes for trial and error.
Use case: Send notification after workflow started and ended to a certain URL.

**Comment by teesloane** [comment]
@aemaem Please correct me if I'm wrong, but it sounds like:

1. You want to validate your config reference file before committing your changes to your git repo
2. You want to send a notification when a workflow and has started and ended to a specific url.

Regarding 2) — to echo Michelle, `notify` as a feature is currently unsupported in 2.0. 
regarding 1) you can download the [circleci-cli](https://github.com/CircleCI-Public/circleci-cli) and run `circleci validate` on your config if you want to ensure your config is valid before making commits. You can read more about the CLI tool [here](https://circleci.com/docs/2.0/local-cli/).
