### ISSUE TITLE
How to uninstall CircleCI cli

### ISSUE THREAD

**Issue by y-nk** [circleci/circleci-docs#3161]
# Missing Information
I can't find how to uninstall the cli. It's unclear what files are installed and where, as the installer works in a silent magic way, so i don't want to `rm` files blindly.
 
# Already Looked
Googled "uninstall circle ci cli"

# Potential Locations
In the "Using circle ci cli" section

I only used it for a local check of my config. It would be very nice to provide an online tester instead, as this is overkill and a bit invasive for that particular use.

**Comment by teesloane** [comment]
Hi there! Thanks for filing an issue. We should add how to uninstall the CLI to our documentation. I will get on that shortly!

If you installed the CLI via our [curl command](https://github.com/CircleCI-Public/circleci-cli#install-script), you can head to the `DESTDIR` which is `/usr/local/bin` by defualt, and delete the `circleci` binary. If you used homebrew, you should be able to run `brew uninstall circleci`.

Let me know if that works!
