### ISSUE TITLE
Getting Started doesn't Get Started.

### ISSUE THREAD

**Issue by alexfornuto** [circleci/circleci-docs#3169]
# Location
https://circleci.com/docs/2.0/hello-world/

# Details
I have a CircleCI account, use it frequently for work projects. Followed [this guide](https://circleci.com/docs/2.0/hello-world/) to get a [new project](https://github.com/alexfornuto/terminus-installer/) going using CircleCi

I added the new `.circleci/config.yml` file exactly as described in step 2  of "Use the Hello-Build Orb" to a branch and pushed. No builds. I merged to master and staged more changes in a new branch, this time following step 1 of "Echo Hello World with a `build` Job` and still no jobs. 

As the docs suggest I went to my Projects page to try to **Add Projects**. At this point the docs mention a button called **Build Project**, but the button is **Set Up Project**.

# Location
https://circleci.com/docs/2.0/circleci-images/#php

# Details
Latest Tags aren't listed as they are with other images.

**Comment by teesloane** [comment]
Hi there!

Thanks for filing an issue. You've mentioned a few different things and I have a question or two. 

> I have a CircleCI account, use it frequently for work projects. Followed this guide to get a new project going using CircleCi.

Your link to "[this guide](https://github.com/alexfornuto/terminus-installer/)" brought me to your repo `terminus-installer`. Did you mean to refer to one of our documents? 

Further, you mentioned an improperly named button. Thank you — I will put up a PR to change the docs to change.

You also listed that we don't have any tags visible for PHP; I'm not sure why that is. I'll look into that and get back to you.

**Comment by alexfornuto** [comment]
How embarrassing! My apologies, I was multi-tasking when I wrote this. I've updated the issue to point to [this guide](https://circleci.com/docs/2.0/hello-world/).

**Comment by teesloane** [comment]
Not a problem! Thank you for patience in having us get back to you. I've since put up a PR to amend the incorrect copy reference in our docs and am researching missing docker tags.

Cheers!

**Comment by felicianotech** [comment]
I have a PR for the tags in the reference above ^.
