### ISSUE TITLE
Add Language Around Feedback and Comments to the footer

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#3170]
In the footer of most doc pages, we mention how a reader could submit a change or report a problem via a GitHub Issue.

For that last point, I think we should add that they should also do this to submit feedback/comments on docs. Not just reporting an issue.

**Comment by teesloane** [comment]
Makes sense to me. Maybe changing the line:

- `To report a problem with this documentation, open an issue on GitHub.`

to:

- `To report a problem in the documentation, or to submit feedback/comments, please open an issue on GitHub`

would work! I can get a PR up for this today.

**Comment by felicianotech** [comment]
That sounds good to me.
