### ISSUE TITLE
Broken Link on Orbs Page 

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#3179]
This link is broken under the See More section of this page: https://circleci.com/docs/2.0/creating-orbs/#section=configuration 

> Refer to [Local CLI] (/docs/2.0/local-cli) for more information about how you can use the CircleCI CLI in your orbs deployments.

**Comment by thomasr8** [comment]
Fixed in Orbs documentation.

**Comment by felicianotech** [comment]
This looks to be fixed already.
