### ISSUE TITLE
Remove recommendation around using machine user keys (_cc1/github-security-ssh-keys.md)

### ISSUE THREAD

**Issue by jasonm23** [circleci/circleci-docs#318]
Hello, 

I'm not sure recommending providing a "github machine user" is wise / good / necessary.

If specific access (e.g. to a git submodule authenticated differently) is required it can be provided by additional deploy keys.

Also if ci/automated write to a repo is required, deploy keys can also be write enabled.

**Comment by felicianotech** [comment]
Hi,

This is referring to a system user on a machine, such as a user on an Ubuntu box. If you don't use a dedicated GitHub/CircleCI user, what happens is you're then giving access to everything on the machine that the user would have access to. For example, if I use an SSH deploy key with CircleCI to a server that I log into using my own username, the host might be `felicianotech@mysever.com`. If I had passwordless `sudo` access on that server and somehow my SSH key on CircleCI gets compromised, lost, leaked, etc, someone can use it to do whatever they want on my server.

This isn't referring to access to repos on GitHub.com itself.

**Comment by smart-alek** [comment]
@jasonm23 Just following up: did @felicianotech clarify things or do you still feel like that doc is making a bad recommendation?

**Comment by jasonm23** [comment]
@smart-alek @felicianotech thank you for clarifying,  I feel my inference may be shared by others reading the docs.  

I hope rewording would be considered.

**Comment by smart-alek** [comment]
@jasonm23 We can definitely do that! I'll flip this issue over to confirmed so we can get the edit prioritized.

**Comment by smart-alek** [comment]
@jasonm23 just looping you in one last time. We're closing most 1.0 issues in favor of [2.0 docs](https://circleci.com/docs/2.0/).
