### ISSUE TITLE
Add reference to previousnext/phpunit-finder for globbing phpunit tests based on phpunit.xml

### ISSUE THREAD

**Issue by larowlan** [circleci/circleci-docs#3196]
# Missing Information
We wrote a library for globbing phpunit tests for circleci based on file paths defined in your phpunit.xml - https://packagist.org/packages/previousnext/phpunit-finder

# Already Looked

# Potential Locations
Perhaps it would be good to link to this library from the running tests in parallel documentation.

**Comment by teesloane** [comment]
Hiya! Thanks for letting us know about your library. I've just put up a Pr (#3197) to include a link to it in our parallel-tests document. 

Let me know if I missed anything! Thanks again!

**Comment by larowlan** [comment]
awesome!

**Comment by michaeldzjap** [comment]
Would it be possible to update the requirements for this package? Currently, it only allows PHP up to v8.0 and PHPUnit 9.

**Comment by larowlan** [comment]
@michaeldzjap try the 2.x series

**Comment by michaeldzjap** [comment]
@larowlan I am... If you look at the [composer.json](https://github.com/previousnext/phpunit-finder/blob/main/composer.json) file of the main branch you see that the requirements of _PHP_ are ^7.4||^8.0 and _PHPUnit_  ^9.5. This won't work with the requirements of those same dependencies with the latest version of _Laravel_ for instance.

**Comment by larowlan** [comment]
Can you open an issue, happy to relax as needed

**Comment by michaeldzjap** [comment]
That would be great, thanks! I don't see an issue tracker for the [repository](https://github.com/previousnext/phpunit-finder) though. Hence, the reason I commented here.

**Comment by larowlan** [comment]
The repo now supports issues @michaeldzjap
