### ISSUE TITLE
Unclear what AWS permission policies are necessary for terraform

### ISSUE THREAD

**Issue by carpiediem** [circleci/circleci-docs#3200]
# Missing Information
The *Deploying to AWS ECR/ECS* page is unclear on the permissions required by terraform

# Already Looked
I've tried [setting overly-permissive policies](https://console.aws.amazon.com/iam/home?region=my-region-1#/users/iam-user-matching-access-key-in-config?section=permissions) in AWS and I've read [Hashicorp's suggestions](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html), but I'm still confused about what precisely is required for this use case.

# Potential Locations
The [Prerequisites section](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/ecs-ecr.md#use-terraform-to-create-aws-resources) of the *Deploying to AWS ECR/ECS* page.

FYI, here the inline policies I used (repeated for `ecr`, `ecs`, & `iam`):

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "cloudformation:*",
            "Resource": "*"
        }
    ]
}
```

Also, I think I messed somthing up while trying to get the permissions right, since terraform will not finish successfully. I always get this error:

```
* aws_cloudformation_stack.vpc: 1 error(s) occurred:

* aws_cloudformation_stack.vpc: Creating CloudFormation stack failed: AlreadyExistsException: Stack [circleci-demo-vpc-stack] already exists
        status code: 400, request id: 2b757c33-418b-11e9-86a2-3b68ed5b3871
```

I tried both `terrafrom destroy` and looking for the stack [on the AWS console](https://console.aws.amazon.com/opsworks/home), but I can't find it.

**Comment by carpiediem** [comment]
After changing the prefix and trying again, I got a clearer error from terraform showing that the user also needed permissions for the `ec2`, `elasticloadbalancing`, and `iam` services. With all those permissions in place, the `apply` command completed successfully.

It would still be great to trim back the permissions I'm giving to the programmatic user.

**Comment by lokst** [comment]
Hi @carpiediem , thank you for reporting this! It would indeed be better to have a more minimal list of permissions required. We will look into this.
