### ISSUE TITLE
Wrong cache directory in Haskell sample configuration

### ISSUE THREAD

**Issue by runeksvendsen** [circleci/circleci-docs#3255]
# Description
The sample CircleCI configuration for Haskell projects (https://circleci.com/docs/2.0/language-haskell/) caches the wrong directory (`/root/project/.stack` instead of `/root/.stack`)

# Location
https://circleci.com/docs/2.0/language-haskell/

# Steps to Reproduce
Build any Haskell project with CircleCI and observe long building times as `/root/.stack` is repopulated with built dependencies.

Optionally add a build step that executes the command `ls /root/project/.stack` to observe that no such directory exists.

# Fix
Don't cache `~/.stack` but rather `/root/.stack`

**Comment by teesloane** [comment]
Thanks for reporting this @runeksvendsen — I'll fix this up shortly.
