### ISSUE TITLE
Explain what `circleci` command is and how to install it

### ISSUE THREAD

**Issue by drazisil** [circleci/circleci-docs#3261]
# Location
https://circleci.com/docs/2.0/creating-orbs/

# Explanation
I clicked to this page from the Orbs page on outer. As part of a getting started, I can't run `circleci namespace create sandbox github CircleCI-Public` as I do not know how to get this command onto my local machine.

**Comment by michelle-luna** [comment]
It is covered in step one on this page https://circleci.com/docs/2.0/creating-orbs/#step-1---set-up-the-circleci-cli

**Comment by Alialkhathami** [comment]
Good
