### ISSUE TITLE
Can't start a build from a Bitbucket fork repository

### ISSUE THREAD

**Issue by benf-portable** [circleci/circleci-docs#3266]
# Description

A correct CircleCI configuration is allowing one repository to build, but not a fork from that same repository to build (with the same configuration).

# Location

Following the directions to set up a new project, I learn that because the code base already has a correct CircleCI configuration, that “Start building” should start the build immediately.

These directions don't work (the page responds “Failed”).

# Steps to Reproduce

* Start with an existing Bitbucket repository ‘foo’, that has CircleCI builds successfully configured.
* Create a fork from that repository, ‘bar’.
* Go to CircleCI “Add projects” page.
  * Observe that CircleCI is already “following” repository ‘foo’.
* Find repository ‘bar’.
  * CircleCI correctly indicates this repository is a fork from another.
* Select “Set Up Project” for the ‘bar’ repository.
  * The “Projects > Add Projects > bar” page appears.
  * Observe the instruction “Want to skip ahead? Jump right into our documentation, set up a .yml file, and kick off your build with the button below.”
* Select “Start building”.
  * The button changes to “Building”.
  * The button then changes to “Failed”.
  * No better information is given as to why the build fails.

## Expected behaviour

With an existing, working ‘.circleci/config.yml’ file, “Start building” should:

* Start the build and follow the new project.
* Follow the project and allow viewing detailed information if the build fails.

**Comment by teesloane** [comment]
Hi there @benf-portable.

Thank you for filing an issue. I recreated the steps you listed and the build of my fork worked. 

Two questions: Have you tried building since (and if so, does it work?). If not, can you try pushing some code to your new fork to see if it re-triggers your build?

**Comment by benf-portable** [comment]
On Fri, 5 Apr 2019 at 04:42, Tyler <notifications@github.com> wrote:

> Thank you for filing an issue. I recreated the steps you listed and the build of my fork worked.

Okay, I'm not understanding what would cause the different behaviour.

> Two questions: Have you tried building since (and if so, does it work?).

Do you mean, have I tried the “Set Up Project” procedure through to
“Start building”? Yes, I tried just now and got the same result (the
“Start building” button changes to “Building”, then to “Failed”, then
back to “Start building”. No other apparent effect.)

> If not, can you try pushing some code to your new fork to see if it re-triggers your build?

Where would I see that? As best I can tell, this repository is still
showing up as not set up (it has a “Set Up Project” button in the
listing, and the repository name is not a link).

-- 
Ben Finney :: Senior Developer
<ben@portable.com.au>
Portable.com.au :: phone: 1300 323 179 :: 5 Easey Street, Collingwood, Vic 3066

**Comment by teesloane** [comment]
Hi @benf-portable . Sorry to hear this isn't working yet. It is rather strange that the project is not even registered as being "set up". I'm going to pass this on to support and see if there might be a bug that we're not aware of. 

In the meantime, does your project _have to be a fork_? As in, if you don't need the original forked history of the project, you could clone the original (`foo`), and re-push it to a fresh repository on BitBucket with a different `remote` address. If there is a bug with forked repos in CircleCi, this solution might help in the meantime. 

If you need the repo (`bar`) to stay as a fork, I'll at least see if we can get some support on that.

**Comment by benf-portable** [comment]
On Tue, 9 Apr 2019 at 01:24, Tyler <notifications@github.com> wrote:
> In the meantime, does your project have to be a fork? As in, if you don't need the original forked history of the project, you could clone the original (foo), and re-push it to a fresh repository on BitBucket with a different remote address.

That won't work; Bitbucket needs to know this is forked from a
specific other repository (and it's how CircleCI is determining that
fact too, I expect) when making merge requests. Without that, our
workflow fails so we need to keep that property of the repository.

> If you need the repo (bar) to stay as a fork, I'll at least see if we can get some support on that.

Looking forward to a resolution on this that allows any of our
repositories to have CircleCI builds.

-- 
Ben Finney :: Senior Developer
<ben@portable.com.au>
Portable.com.au :: phone: 1300 323 179 :: 5 Easey Street, Collingwood, Vic 3066

**Comment by teesloane** [comment]
@drazisil Do you have any thoughts on what might be happening here?

**Comment by drazisil** [comment]
Strongly suspecting a permissions issue. @benf-portable can you share what the results of the `/follow` API call are from th dev console when you click the button?

**Comment by benf-portable** [comment]
On Tue, 16 Apr 2019 at 07:49, Joe Becher <notifications@github.com> wrote:

> Strongly suspecting a permissions issue. @benf-portable can you share what the results of the /follow API call are from th dev console when you click the button?

You've lost me. In the web developer console, you want me to do what exactly?

-- 
Ben Finney :: Senior Developer
<ben@portable.com.au>
Portable.com.au :: phone: 1300 323 179 :: 5 Easey Street, Collingwood, Vic 3066

**Comment by drazisil** [comment]
Watch the network calls when you click the follow button and report the results of that call, please.

**Comment by teesloane** [comment]
@benf-portable -- something like this, I think:

<img width="1680" alt="bitbucket_issue" src="https://user-images.githubusercontent.com/12987958/56309003-a6601400-6116-11e9-97e0-1ab23a4c3171.png">

**Comment by benf-portable** [comment]
On Tue, 16 Apr 2019 at 21:44, Joe Becher <notifications@github.com> wrote:

> Watch the network calls when you click the follow button and report the results of that call, please.

I don't see a “follow” button.

Steps I used:

* Open the Network tab in Web Developer Tools.
* At <URL:https://circleci.com/add-projects/bb/portable> on the “Add
Projects” page, see the ‘benf-headspace’ entry.
* Select the “Set Up Project” control for that entry.
  * No network activity occurs.
  * The URL changes to
<URL:https://circleci.com/setup-project/bb/portable/benf-headspace>.
  * The page changes to “Add Projects > portable/benf-headspace”.
  * No “follow” control is shown.
* Select the “Start building” control.
  * The control's text changes to “Building”.
  * The network activity is logged:

=====
200 GET dmmj3mmt94rvw.cloudfront.net RobotoMonoRegular.woff font
x-font-woff 65.67 KB 65.09 KB 2034 ms
200 GET dmmj3mmt94rvw.cloudfront.net Roboto-Bold.woff font x-font-woff
81.83 KB 81.25 KB 2197 ms
400 POST circleci.com follow xhr json 1.07 KB 123 B 16292 ms
=====

  * The control's text changes to “Failed”.
  * After a brief pause, the text changes again to “Start building”.

-- 
Ben Finney :: Senior Developer
<ben@portable.com.au>
Portable.com.au :: phone: 1300 323 179 :: 5 Easey Street, Collingwood, Vic 3066

**Comment by benf-portable** [comment]
On Thu, 18 Apr 2019 at 09:39, Ben Finney <ben@portable.com.au> wrote:
>   * The network activity is logged:
>
> =====
> 200 GET dmmj3mmt94rvw.cloudfront.net RobotoMonoRegular.woff font
> x-font-woff 65.67 KB 65.09 KB 2034 ms
> 200 GET dmmj3mmt94rvw.cloudfront.net Roboto-Bold.woff font x-font-woff
> 81.83 KB 81.25 KB 2197 ms
> 400 POST circleci.com follow xhr json 1.07 KB 123 B 16292 ms
> =====

Examining the logged “POST” request, I see that it has an empty body.

Method: POST
URL: https://circleci.com/api/v1.1/project/bitbucket/portable/benf-headspace/follow
Header:
    Host: circleci.com
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0)
Gecko/20100101 Firefox/66.0
    Accept: application/json
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Referer: https://circleci.com/setup-project/bb/portable/benf-headspace
    X-CSRFToken:
4wjvmbxKPczlD6-FpaAnnq6ZeeDOHumYT7KdIqjG--DIgdJBSe2PLbRvJoKrCFMbjuidKishi0mgWatM
    Content-Type: application/json; charset=utf-8
    Content-Length: 4
    DNT: 1
    Connection: keep-alive
    Cookie: ajs_user_id=%22d5d316d9-40cc-4a23-832f-9b806148609f%22;
ajs_group_id=null;
ajs_anonymous_id=%22fd6fb66e-c207-492f-8e5d-4b02a5016247%22;
analytics-client-id=1549940078259;
optimizelyEndUserId=oeu1549940083119r0.826292339383558;
ring-session=%2Fbw1ImfCoWtCDE1NuJDl2WclQHPpkbxyoXYRTlTvHZ%2Bh1P29UGnY9LuulDbkmc2WNS4OYAyTBGVRr9VZODfEjT9CWyGLcecifP4Iv5OJUe%2Fj3dfT25nN6PGGbpypHLo8XKkM3l8zjz0gGEYAPoC3GCy6%2FB%2FaEfqGigtVm27XkFcTl0Fg1ALAXmLX4VpZLGYxrOHzt0xsvarPfi22%2BPomntYT2G%2BS86LQ%2B5m%2Bj8x58IL%2ByHPe09StS71nwLxbD%2BIsmeyqNXTDYrWq9GnK3XXxJHryK%2Fz4TNsARICg2jTNu7AuXYxJKWpJRLGr81MDzrAxoV38utGl5Ql%2FF5QtohRIkhdndS5UfhA2FXy5DQGHYd%2BHOVexrbFxJCFoOHZHIuX3v7qmN2Q1k4o33puc2cvlKL%2BykI9HQaQljUlLu9i3O3rhG0J%2BzzZtjxpVqWqaDDZ%2F--mvKnP5jmOVfKJwo1sG%2F7HiM2FBL8btkvqkWiiNclEXk%3D;
__tld__=1; amplitude-session-id=1555543861408; ajs%3Acookies=true;
ajs%3Atest=true; optimizelyDomainTestCookie=0.9559695809466306
Body:

-- 
Ben Finney :: Senior Developer
<ben@portable.com.au>
Portable.com.au :: phone: 1300 323 179 :: 5 Easey Street, Collingwood, Vic 3066

**Comment by teesloane** [comment]
Hi @benf-portable, sorry to put you through this trouble, but it appears that we don't currently support  forked repositories on Bitbucket at this time. I'm going to close this issue for now, but if any pertinent features/updates come out I will reopen and let you know.
