### ISSUE TITLE
Intermittent long times to clone our repo

### ISSUE THREAD

**Issue by spaul5** [circleci/circleci-docs#3277]
# Description
It seems like almost every other circle build, it takes a long time for circle to checkout our github repo

# Location
Inside a circle build during our checkout code step, circle takes a long time to clone our repo almost every other time. When this happens, "Receiving objects: %" gets stuck on the same percentage for a long time

# Steps to Reproduce
Start a build that checks out our code

**Comment by teesloane** [comment]
Hi @spaul5 !

Can you link me specific builds that are taking a long time?
I've looked at our last 10 or so builds and they are all wrapping up at no more than 5~ minutes. All of the checkout steps are taking less than 10 seconds.

And, in a sense, every other build does take longer; there are two different workflows (`build` and `js_build`) that have their own separate steps; the former makes up the bulk of the build time.

![image](https://user-images.githubusercontent.com/12987958/55903220-2b897d00-5b9b-11e9-8f56-3e5e81d8444c.png)

**Comment by teesloane** [comment]
Oh no! I totally misunderstood; I thought you were referring to the Github Docs repo's build time itself! Sorry about that.

In regard to slow checkout times, we're monitoring the issue over on our [discuss board](https://discuss.circleci.com/t/checkout-code-slow/28750). 

closing this in favor of referring to the discuss issue.

**Comment by teesloane** [comment]
Hi! Just wanted to follow up on this and cross link an issue: (https://github.com/circleci/circleci-docs/issues/2040) for anyone interested.
