### ISSUE TITLE
cli circleci query docs are masters of disguise

### ISSUE THREAD

**Issue by excenter** [circleci/circleci-docs#3278]
# Missing Information
any examples of `circleci query` calls using the cli to make API calls

# Already Looked
* https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-cli.md

# Potential Locations
* https://circleci.com/docs/api/v1-reference/ 
or as a result of `circleci query --help` 
because, while helpful 
```
Query the CircleCI GraphQL API.


Usage:
  circleci query <path> [flags]

Args:
  <path>      The path to your query (use "-" for STDIN)


Flags:
  -h, --help   help for query

Global Flags:
      --host string    URL to your CircleCI host, also CIRCLECI_CLI_HOST (default "https://circleci.com")
      --token string   your token for using CircleCI, also CIRCLECI_CLI_TOKEN
```
doesn't tell me what paths or parameters I could/should use. Explorer logs to follow.

**Comment by thomasr8** [comment]
Closing for now until we determine how we might want to address this issue in the future.
