### ISSUE TITLE
Xcode 10.2 documentation outdated

### ISSUE THREAD

**Issue by VincentCATILLON** [circleci/circleci-docs#3303]
# Missing Information

The documentation about Xcode 10.2 is outdated and mentions the beta.3 version previously released.

# Already Looked

https://discuss.circleci.com/t/xcode-10-2-image-released/29761
https://circleci.com/docs/2.0/testing-ios/

# Potential Locations

https://circleci.com/docs/2.0/testing-ios/

**Comment by teesloane** [comment]
Hi @VincentCATILLON , thanks for bringing this to our attention. I will update the docs shortly to reference the correction version of Xcode!
