### ISSUE TITLE
RE: jekyll/_docs/api.md

### ISSUE THREAD

**Issue by SuperTango** [circleci/circleci-docs#332]
I'm trying to get information from the REST API.  I can get make any call that doesn't require a vcstype/username/project to work properly, however I can't get any that require vcstype/username/project to return anything except a 404 error.

Couple of questions.:
* What is my username? Is it my github username (SuperTango)? I login to circleci with github, and the circleci "account settings" webpage doesn't actually show me any username.  the "/me" API response has a field called "login" (which in my case is also "SuperTango").  Not sure if this is the problem, but there's no information for me to use to debug.
* What is the actual project name I should use here? Is it the name of the github project?  
* If my username is "SuperTango", i'm a github user, and the project in github is called "funkware/funkware_app", is this the URL I should use?
`https://circleci.com/api/v1.1/project/github/SuperTango/funkware/funkware_app?circle-token=<my_token>`  (obviously `<my_token>` is replaced with my token that I have verified works by calling the "/me" URL.)  This URL is not working for me.  I get back a 404 reponse with the webpage.

**Comment by felicianotech** [comment]
Hi,

"What is my username?" - This is the username for your project on GitHub or Bitbucket. This could be a personal user account, or it can be an organization username.

"What is the actual project name?" - This is the repository name on GitHub or Bitbucket.

For the example you provided, the API call would be, `https://circleci.com/api/v1.1/project/github/funkware/funkware_app?circle-token=<my_token>`.

**Comment by SuperTango** [comment]
Ohhhhhh...I see.  I misunderstood the difference between "username" and "project".  I thought username was my username, and "project" was the full github project name.  My actual username doesn't matter, it's only the project username.  

Got it.

I think the docs could be updated. I'll submit an update request.  Thanks.

**Comment by felicianotech** [comment]
No problem. Much appreciated.
