### ISSUE TITLE
Is there a legalizing on environment variables?

### ISSUE THREAD

**Issue by Magicloud** [circleci/circleci-docs#3329]
# Missing Information
When creating an env var in context, there seems no restrictions. For example, I can name it as "api token". But in language like Bash, there cannot be a space in the var name. So is there a process to change the form of the name, or this is something I need to look out?

# Already Looked
Context document and usage of Environment Variables.

# Potential Locations
Usage of Env Vars.

**Comment by teesloane** [comment]
Hi there! Thanks for filing an issue! Here's what our [docs](https://circleci.com/docs/2.0/env-vars/#environment-variable-usage-options) say:

> CircleCI uses Bash, which follows the POSIX naming convention for environment variables. Valid characters include letters (uppercase and lowercase), digits, and the underscore. The first character of each environment variable must be a letter.

does that help at all regarding using environment variables?

**Comment by Magicloud** [comment]
Sorry for late reply. Seems like the doc you mentioned is not the one I read. But yours does help. Thanks.

**Comment by teesloane** [comment]
Glad it could help!
