### ISSUE TITLE
Where can I find the `VM Provider` configuration 

### ISSUE THREAD

**Issue by sonots** [circleci/circleci-docs#3335]
# Location

https://circleci.com/docs/2.0/vm-service/

# Explanation

Where can I find the `VM Provider` configuration on circleci 2.0?

**Comment by michelle-luna** [comment]
Hi,

Thanks for this question, what type of installation are you trying to complete? Is it AWS?

Regards,
Michelle

**Comment by pearsonhenri** [comment]
Hey there--just ran into this same issue. I am trying to configure this for AWS as well, but I can't find the panel that's screenshotted in the docs anywhere.

**Comment by rosieyohannan** [comment]
Hi @pearsonhenri, this option is for CircleCI Server administrators and can be found in the Management Console Settings page e.g. your-circleci-hostname.com:8800 and select Settings.

Let me know if you need further assistance.

Thanks!
Rosie

**Comment by pearsonhenri** [comment]
Ok so it sounds like this option is _only_ available for hosted CircleCI installations? This was not clear to me from the documentation. Would appreciate some clarification because I spent a very long time trying to find this page haha.

**Comment by rosieyohannan** [comment]
@pearsonhenri yes the Administration section of out docs is for administrators of hosted installs of CircleCI Server. Sorry for the inconvenience, I will make it clearer in future :-)
