### ISSUE TITLE
` character in env var value

### ISSUE THREAD

**Issue by GoshaEgorian** [circleci/circleci-docs#3369]
# Description
When I'm trying to add env var to build settings in UI interface that contains `` ` `` character it's failed without any message. If I escape this (`` \` ``) it saves successful but in build process this var contains `` \ `` and `` ` `` both so var is wrong.

# Location
I'm not sure but it can be linked: https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md

# Steps to Reproduce
We are trying to add `` test `` env var which value is `` ` ``.
1. Go to https://circleci.com/bb/ACC_NAME/PROJ_NAME/edit#env-vars
2. Try to set var named `` test `` and value `` ` ``
3. Try to save. It fails
4. Escape it: `` \` ``
5. Save (success)
6. Look for `` test `` env var. It will be whole `` \` `` but we need it setted to `` ` `` only.

**Comment by michelle-luna** [comment]
Adding @drazisil in case he knows how this could work.

**Comment by drazisil** [comment]
I would recommend filing this as a bug, @michelle-luna , I can't think of a workaround.

What about the `Add Environment Variables` API endpoint, @GoshaEgorian ? Same issue? https://circleci.com/docs/api/#download-an-artifact-file

(Unrelated, @michelle-luna can you file a request to make the endpoints anchors and add a TOC to that page?)

**Comment by GoshaEgorian** [comment]
@drazisil I just tried to add env var by API. I run
```bash
curl -X POST --header "Content-Type: application/json" -d '{"name":"test","value":"`"}' https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/envvar\?circle-token\=:token
```
I get an error:
```bash
{
  "message" : "This is an invalid bash environment variable value."
}%
```
If I set second `` ` `` then it's passed:
```bash
curl -X POST --header "Content-Type: application/json" -d '{"name":"test","value":"`Hello darkness my only friend`"}' https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/envvar\?circle-token\=:token
```
Result:
```bash
{
  "name" : "test",
  "value" : "xxxxend`"
}%
```
But there is backtick in var at start and at end of string. I need only one (because my password have only one).
I have try escape it:
```bash
curl -X POST --header "Content-Type: application/json" -d '{"name":"test","value":"\`Hello darkness my only friend\`"}' https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/envvar\?circle-token\=:token
```
Then I get an error:
```bash
{
  "message" : "Invalid JSON body."
}%
```

**Comment by GoshaEgorian** [comment]
Now the only workaround for me is to change pwd (and var value) to string without backtick `` ` ``. Fortunately, I can do it.
But if somebody can't I don't know solution for them.

**Comment by drazisil** [comment]
https://unix.stackexchange.com/questions/27428/what-does-backquote-backtick-mean-in-commands

I'm not sure that backticks should be allowed unescaped in envs, it feels like they could have adverse effects when parsed by bash.

https://www.starkandwayne.com/blog/bashing-your-yaml/

This article says that backticks should be escaped in YAML. I think this behavior is intentional and not a bug, but I recommend that @michelle-luna check with the correct team regarding this and if the documentation should be changed.

**Comment by GoshaEgorian** [comment]
I think it's right.
But the problem is that it's impossible to escape it because escaping `\` become part of a var value. It's expected that `` \` `` become only `` ` `` when somebody gets var.
