### ISSUE TITLE
Missing resource_class config example

### ISSUE THREAD

**Issue by JonathanC503** [circleci/circleci-docs#3376]
# Missing Information
Give a brief overview of the information you were looking for.
* Once an end-user has upgraded to a performance plan, an example config.yml that shows how to enable & configure resource_class would be helpful. 

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

* https://circleci.com/docs/2.0/configuration-reference/#resource_class

* Also searched support articles and found nothing available.

# Potential Locations
Tell us where you would expect to find this information.
* https://circleci.com/docs/2.0/configuration-reference/#resource_class

**Comment by teesloane** [comment]
Good point @JonathanC503 . I've put up a [PR](https://github.com/circleci/circleci-docs/pull/3381) to add an example to the `resource_class` example.
