### ISSUE TITLE
SSH debugging documentation is incorrect

### ISSUE THREAD

**Issue by drazisil** [circleci/circleci-docs#3379]
# Locations
https://circleci.com/docs/2.0/ssh-access-jobs/

# Conflict Description
```
This is what I read in https://circleci.com/docs/2.0/ssh-access-jobs/: " The build VM will remain available for 10 minutes after the build finishes running and then automatically shut down. (Or you can cancel it.)"

When I “Rerun job with SSH”, the output towards the end says “This box will stay up for 2h0m0s, or until 10m0s passes without an active SSH session.
Build timed out”

Can we update these docs?
```

Source: https://discuss.circleci.com/t/ssh-debugging-documentation-is-incorrect/30312

**Comment by glenjamin** [comment]
> The build VM will remain available for 10 minutes after the build finishes running and then automatically shut down. (Or you can cancel it.)

I think the intention is that this describes what happens until you connect

> This box will stay up for 2h0m0s, or until 10m0s passes without an active SSH session.

And this describes what happens after you've connected
