### ISSUE TITLE
Executors section of config reference has broken formatting

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#3384]
# Location
https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21

# Error Details
The table formatting is broken here, leading to the table beginning with `Executors define the environment` rendering as a paragraph.

```
Key | Required | Type | Description —-|———–|——|———— docker | Y (1) | List | Options for docker executor resource_class | N | String | Amount of CPU and RAM allocated to each container in a job. (Only available with the docker executor)
```

**Comment by jonprindiville** [comment]
👍Thanks

I spotted at least one more occurence of that sort of thing further down the same document. See [this `<job_name>` section](https://circleci.com/docs/2.0/configuration-reference/#job_name).

**Comment by teesloane** [comment]
Thanks @li3n3 and @jonprindiville ! Currently we have a PR #3380 pending to fix this.
