### ISSUE TITLE
Sometimes the implicit workflow goes away

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#3388]
I received the following feedback:

> Looks like this new workflow has overridden the implicit, default one that triggers on push. I added another WF and problem solved.

In CircleCI v2.1, when no workflow is provided in config, an implicit one is used. However, if you declare a workflow in order to do a scheduled build, the implicit workflow is no longer. The "normal" workflow needs to now be manually created in order for CircleCI to do its usual behavior of builds on every commit.

This is likely a candidate to be documented.... somewhere. I'm not sure where in Docs is best.

**Comment by michelle-luna** [comment]
thanks, I added this as a note in the scheduling a workflow section and tagged you as a reviewer.
