### ISSUE TITLE
MySQL example does not use CircleCI image

### ISSUE THREAD

**Issue by drazisil** [circleci/circleci-docs#3402]
# Locations
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/postgres-config.md

# Conflict Description
https://discuss.circleci.com/t/docs-should-have-a-canonical-mysql-image-reference/30507

Customer points out that we mix the MySQL example into the Postgres docs, making for bad SEO.

In addition, we are using a third-party MySQL service image, instead of our own
https://circleci.com/docs/2.0/circleci-images/#mysql

Suggest we separate the two examples for clarity, and change the example to use our image.

**Comment by hlorofos** [comment]
just got to this issue through google. its definitely worth to write an official manual, there are so many wrong articles on the net!
