### ISSUE TITLE
RE: jekyll/_docs/status-badges.md

### ISSUE THREAD

**Issue by knagode** [circleci/circleci-docs#341]
I copied the code for GIF badge in project setting. URL Is like:

```
https://circleci.com/gh/%%%/%%%/tree/develop.png?style=shield
```

And badge opens properly if I open URL via browser. 

However when I want to use this badge on github md page:

```
![CircleCI](https://circleci.com/gh/%%%/%%%/tree/develop.png?style=shield)
```

WHen I preview the MD file, I see that the image is broken. If I visit the image URL I see that it is github's url: 

```
https://camo.githubusercontent.com/e8c9d34844b1d212e4eeb116b3549c6995a3...
```
With response: 
```
Not Found
```

They must have some kind of caching but I would like to know how can I fix this?

**Comment by felicianotech** [comment]
Since you removed the repository user and name from the URL I'm assuming this is a private project? If so, did you generate a badge token and are using that on the GitHub md page?

**Comment by knagode** [comment]
I see. I didn't see immediately that I should generate badge token - I just copied the 'badge code' and tried it out. After that I was searching for solution via 'google search' which were quite misleading. Maybe you could autogenerate tokens for private repositories so badge code would always work ... I have a feeling that you could do something with UX here as well. I also saw that a lot of users are having similar issues on similar services as CircleCI - I am probably not the only one with this problem :D

**Comment by felicianotech** [comment]
That might be interesting, could save users a bit of time. Feel free to make a [feature request](https://discuss.circleci.com/c/feature-request) in CircleCI Discuss. Our PMs use the number of likes, activity, etc on those feature request to prioritise.
