### ISSUE TITLE
Still have problem with "Container ID xxxxxxxxxxx cannot be mapped to a host ID"

### ISSUE THREAD

**Issue by colinuipath** [circleci/circleci-docs#3437]
# Location
A link to the document that is unclear.
https://circleci.com/docs/2.0/high-uid-error/

# Explanation
I followed the instructions from the above link and fixed the uid problem. However, when I deploy it to Azure, it still complains about the Container ID as below:
`2019-06-11 17:57:29.827 ERROR - failed to register layer: Error processing tar file(exit status 1): Container ID 1185200044 cannot be mapped to a host IDErr: 0, Message: failed to register layer: Error processing tar file(exit status 1): Container ID 1185200044 cannot be mapped to a host ID`

If I run the find command locally, it can not find any more files with UID 1185200044
```
# find / \( -uid 1185200044 \)  -ls 2>/dev/null
#
```
Any insights that I missed anything?

**Comment by michelle-luna** [comment]
Hi, thanks for this report, adding @kimh as well. Did you recreate the image as well referring to this example? https://hub.docker.com/r/circleci/doc-highid

**Comment by kimh** [comment]
My assumption is that Azure is using a wrong image for some reason. Can you try this guide? https://social.msdn.microsoft.com/Forums/vstudio/en-US/f034bd0a-00e1-4a11-a716-8cf1112a5db4/container-id-xxxxxxx-cannot-be-mapped-to-a-host-id?forum=windowsazurewebsitespreview
