### ISSUE TITLE
Explain how to build Android library projects and projects that depend on them (_cc1/android.md)

### ISSUE THREAD

**Issue by clivejefferies** [circleci/circleci-docs#344]
There are no details about how to build Android library projects and projects that depend on them.

**Comment by smart-alek** [comment]
@clivejefferies thanks for the ask around Android sample projects. We're shifting our focus from 1.0 docs editing/drafting to 2.0 docs, so watch the [new site](https://circleci.com/docs/2.0/) for more frequent updates. And thanks again for submitting this! :)
