### ISSUE TITLE
Can't install Private npm packages using npm install

### ISSUE THREAD

**Issue by dwintermute** [circleci/circleci-docs#3461]
I tried installing form a private repo using npm install but all I get is a 404 error.  I have set up the npm token to get the repo in environmental variables for the project.  I'm also setting the registry in the config.yml.

I've already looks everywhere I can think of for a solution.  I have tried, `npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN`, and `echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc`

I followed the steps in the documentation and that didn't work.  any help would be appriciated.

**Comment by Jpropel** [comment]
Hey, did you find a solution to this in the end?
