### ISSUE TITLE
Incorrect information on resource_class

### ISSUE THREAD

**Issue by scwheele** [circleci/circleci-docs#3462]
# Locations
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md#resource_class

# Details
`Note: A paid performance plan is required to use the resource_class feature. If you are on a paid performance plan you will need to open a support ticket to have a CircleCI Sales representative contact you about enabling this feature on your account.`

Users on the performance plan have access to `resource_class`. Other parts of the document have a more accurate statement:
`Note: A paid account is required to access this feature. Customers on paid container-based plans can request access by opening a support ticket.`

**Comment by michelle-luna** [comment]
What is the change you are asking for? (We just updated this last week, so I want to be sure and I can't tell from this issue what you want me to change). Thanks!
