### ISSUE TITLE
iOS code signing without Fastlane Match

### ISSUE THREAD

**Issue by SandraNPR** [circleci/circleci-docs#3466]
# Missing Information
I'd like to know how to set up an iOS project without using Fastlane Match. This is not documented anywhere.
# Already Looked
Provide a list of places you've already looked for this information.
https://circleci.com/docs/2.0/ios-codesigning/

# Potential Locations
https://circleci.com/docs/2.0/ios-codesigning/

**Comment by michelle-luna** [comment]
Hi,

Thanks for this feedback, here is the doc for it, will add a link from the ios-codesigning doc if you agree. https://circleci.com/docs/2.0/hello-world-macos/#section=getting-started

**Comment by SandraNPR** [comment]
I was looking up how to set up our code signing specifically without Fastlane Match. We use Fastlane but we do not store our certs or provisioning profiles on Github. I had to google and found a blog where someone mentions this screen.
<img width="1349" alt="Screen Shot 2019-06-24 at 2 29 40 PM" src="https://user-images.githubusercontent.com/42179419/60042831-9a4f8000-968c-11e9-9449-fc5dd18795cf.png">
 It would be helpful to mention this option in https://circleci.com/docs/2.0/ios-codesigning/ and refer to https://circleci.com/docs/2.0/hello-world-macos/#section=getting-started for a sample configuration that does not use Fastlane at all.

**Comment by michelle-luna** [comment]
Hi,

Thanks for this additional detail, much appreciated. The settings on that UI screen are EOL'd, they can't be used with 2.0 (sorry if that was confusing, there should be a banner at the top of the page that says as much). We will definitely add a link to the hello-world-macos from the code signing doc though.

**Comment by SandraNPR** [comment]
There is a blog with an alternative https://medium.com/@m4rr/circleci-2-0-and-the-ios-code-signing-df434d0086e2 for teams not using Fastlane match. This is steps are very helpful and worth mentioning. Thanks!
