### ISSUE TITLE
Instructions for downloading artifacts are slightly off

### ISSUE THREAD

**Issue by dankamongmen** [circleci/circleci-docs#3471]
# Description
The instructions for downloading all artifacts aren't as good as they could be. For one, as written they require a temporary file; the provided usage, specifying a well-known filename in `/tmp`, is a bad security hole (could lead to wiping out symlinked files, etc). The `grep` furthermore overmatches. I've got a replacement which fixes both issues (but requires `jq`):

```
curl https://circleci.com/api/v1.1/project/$TYPE/$USER/$PROJECT/$BUILD/artifacts?circle-token=$TOKEN \
   | jq ".[] | .url" \
   | tr -d \" \
   | sed -e "s/$/?circle-token=$TOKEN/" \
   | wget -v -i -
```

# Location
https://circleci.com/docs/2.0/artifacts/#downloading-all-artifacts-for-a-build-on-circleci

**Comment by teesloane** [comment]
@dankamongmen - Thank you for opening an issue and PR! I have a question or two that I'll post over in the PR.

**Comment by dankamongmen** [comment]
Thanks for the merge! This seems closed.
