### ISSUE TITLE
Adding macOS mojave-specific information about SSH key generation

### ISSUE THREAD

**Issue by lokst** [circleci/circleci-docs#3473]
# Missing Information
With the release of macOS Mojave, the default SSH key generated by ssh-keygen is no longer the correct format for CircleCI (See: https://support.circleci.com/hc/en-us/articles/360021127693-How-to-generate-and-store-read-write-SSH-keys and https://discuss.circleci.com/t/error-when-adding-ssh-permissions-keys-on-macos-mojave/28034)

Would it be good to highlight this information?

# Already Looked
https://circleci.com/docs/2.0/add-ssh-key/#steps

# Potential Locations
https://circleci.com/docs/2.0/add-ssh-key/#steps

**Comment by michelle-luna** [comment]
Hi,

Thanks for mentioning this, we do document it here: https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-user-key

Caution: Recent updates in ssh-keygen don’t generate the key in PEM format by default. If your private key does not start with -----BEGIN RSA PRIVATE KEY-----, enforce PEM format by generating the key with ssh-keygen -m PEM -t rsa -C "your_email@example.com"

But, adding this to the SSH article is probably good, or at least adding a link.
