### ISSUE TITLE
Android images have a list of packages already installed

### ISSUE THREAD

**Issue by kevin-lot** [circleci/circleci-docs#3497]
# Locations
https://circleci.com/docs/2.0/circleci-images/#android

# Details
After [verification](https://hub.docker.com/r/circleci/android/dockerfile), Android images have all this packages already installed.

```
With the exception of Android images, all images include the following packages, installed via apt-get:

bzip2
ca-certificates
curl
git
gnupg
gzip
locales
mercurial
net-tools
netcat
openssh-client
parallel
sudo
tar
unzip
wget
xvfb
zip
```

**Comment by teesloane** [comment]
Thanks for raising this issue @kevin-lot — we are looking into confirming we can update our docs as you've suggested! Thanks for bringing this to our attention.
