### ISSUE TITLE
FAILING VS FAILED workflow status

### ISSUE THREAD

**Issue by mernst** [circleci/circleci-docs#3502]
At https://circleci.com/docs/2.0/workflows/#overview
this text about workflow states is confusing:

> FAILING: A Job in the workflow has failed
> FAILED: One or more jobs in the workflow failed

It seems that after one job has failed, the state could be either FAILING or FAILED.  How does CircleCI decide, and what is the distinction between the two states?

**Comment by michelle-luna** [comment]
@kunal can you describe this in a sentence or two please? I will add it to the doc

**Comment by KunalJain** [comment]
Workflow gets in `Failing` state when one of the jobs within the graph have failed while others jobs are still running. `Failing` state indicates that the workflow is eventually going to fail.

`Failed` status is when one or more jobs in the workflow graph have failed. It is a terminal state.
