### ISSUE TITLE
GitHub Labels - are they accessible?

### ISSUE THREAD

**Issue by rafaelmarques7** [circleci/circleci-docs#3505]
# Missing Information

This is a question: is it possible to access GitHub labels on CircleCI? 
Theoretically, this could be don,e for example, environmental variables, similar to what is done with the Github tags and commit hash.

The documentation does not mention this, so I imagine it is not available, but I would like to confirm this.

# Already Looked
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

# Potential Locations
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by teesloane** [comment]
Hi there @rafaelmarques7, thanks for filing an issue. As far as I know this isn't possible. We have a [discuss thread](https://discuss.circleci.com/t/tag-label-filter/11158/3)  requesting the same features, so we'll definitely keep an eye on it. Someone has also requested the feature over on our [ideas page](https://ideas.circleci.com/ideas/CCI-I-271). 

So, unfortunately it seems like tags / workflow filters is the only way to go for now, but we've definitely noted that our users are looking for more powerful filtering options.

Cheers!
