### ISSUE TITLE
Docker login example should use --password-stdin instead of --password

### ISSUE THREAD

**Issue by csmcallister** [circleci/circleci-docs#3518]
# Locations
This issue references [this page](https://circleci.com/docs/2.0/building-docker-images/).

# Details
There are two examples where the following command is used:
```bash
docker login -u $DOCKER_USER -p $DOCKER_PASS
```

Doing so causes Docker to raise the following warning:
```bash
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
```

I'm not sure if this is really an issue in an ephemeral CI box, but the warning is raised nonetheless and this might alarm people who've read the CircleCI docs. If the warning can be safely ignored, it might be nice to call this out. If the warning shouldn't be ignored, please consider using `--password-stdin`.  Since most CircleCI users will probably have their password stored as an environment variable, the following could be a good replacement for the CircleCI docs:

```bash
echo "$DOCKER_PASS" | docker login --username DOCKER_USER --password-stdin
```

**Comment by teesloane** [comment]
Hi @csmcallister, thank you for raising this issue. We will definitely use the alternative command you listed. Thank you for contributing this! I will cross-reference this issue in a PR when it goes up.
