### ISSUE TITLE
Replace `cabal` build tool with `stack` (_cc1/language-haskell.md)

### ISSUE THREAD

**Issue by TRManderson** [circleci/circleci-docs#352]
A large portion of the Haskell community now uses `stack` as a build tool instead of `cabal`. It would be worthwhile to include info about using `stack` on CircleCI.

**Comment by felicianotech** [comment]
Any particular resources you can point us to on `stack`?

**Comment by alexanderkjeldaas** [comment]
https://docs.haskellstack.org/en/stable/README/

Stack is now de-facto what the community uses.   It's vastly superior.

```

**Comment by smart-alek** [comment]
Hey @TRManderson @alexanderkjeldaas, thanks for the tip! We'll be sure to make this switch while updating docs for 2.0.
