### ISSUE TITLE
Confused about how to store test results for gradle project.

### ISSUE THREAD

**Issue by aguang-xyz** [circleci/circleci-docs#3567]
# Description
Hi, I'm a beginner about circle ci and trying to configure a gradle project to show failed test result in dashboard. But I feel confused and do know why it does not works well.

# Steps to Reproduce
[This](https://github.com/aguang-xyz/spring-boot-rest-registry/blob/master/.circleci/config.yml) is my circle ci config file. You can folk this project and try to reproduce.

This is currently what I see in dashboard, you can see that test summary not shows well.

![Screenshot-20190724005329-1832x871](https://user-images.githubusercontent.com/46846389/61731746-b8ed8780-adae-11e9-99dd-4121efe101bc.png)

**Comment by teesloane** [comment]
Hi there!

It seems that `gradle check` is failing; which has more to do with your project test (or "checks") not passing — until your tests pass you won't be able to store any test results !

Are you able to run `gradle check` locally with any success?

**Comment by aguang-xyz** [comment]
```
It seems that gradle check is failing
```

Yes, `gradle check` command in my project is used to run test cases. And I intentionally set up an incorrect test case in my project. The result what I expect is after I trigger a build job, it shows failed and reports which test cases not passed in Circle CI's dashboard.

```
until your tests pass you won't be able to store any test results
```

So how can I collect **detailed failed information** while running test cases.

Or you mean it is not possible to collect failed information?

**Comment by aguang-xyz** [comment]
Oh~ I'm just suddenly dawned. Previously I configured cicleci configs according to your this [doc](https://circleci.com/docs/2.0/collect-test-data/#gradle-junit-results). And now I know collecting test metadata is used to collect sth just such as coverage rate.

**Comment by aguang-xyz** [comment]
But in your design, how to collect sth like code passing rate and failed test cases. It may be useful if some project is quite big.

**Comment by teesloane** [comment]
Hi! Glad to hear this worked out; sorry my first post wasn't super clear; I don't think I quite understood what was happening. The wording between storing test results and what it represents (coverage) can be unclear too.

**Comment by aguang-xyz** [comment]
Oh, I think the root cause is that I forget to add `when: always` in store_test_results step. Now it works well.

```
       - store_test_results:
           path: /tmp/test-results
+          when: always
```

Thanks any way.
