### ISSUE TITLE
RE: jekyll/_docs/nightly-builds.md

### ISSUE THREAD

**Issue by chadbr** [circleci/circleci-docs#358]
How do you get a token into /home/ubuntu/.circle_token ?

**Comment by felicianotech** [comment]
You would obtain a token from the CircleCI.com website (either an account token or project specific token). Then, save it to that file. If you're following along with the doc, you can save it wherever you want. `/home/ubuntu/.circle_token` happens to be the location used in the example.

If you are trying to figure out how to do that via a terminal, you can use a terminal text editor such as nano to open (or create) that file and then save the token in it. The command to open the file would be:

`nano /home/ubuntu/.circle_token`
