### ISSUE TITLE
Instructions for downloading artifacts are inconsistent

### ISSUE THREAD

**Issue by ja5087** [circleci/circleci-docs#3590]
# Locations
https://circleci.com/docs/2.0/artifacts/#downloading-all-artifacts-for-a-build-on-circleci

# Conflict Description
1. `tr \"` is redundant in this case since `grep -o` won't match the quotes anyway.
1. `wget` is actually used to download the artifacts, not `curl`.
1. Description of commands is out of date e.g. this code doesn't use `xargs` or a temporary file anymore

(Also as a side note, `grep -o` is not POSIX compliant but the majority of people will be using GNU or BSD `grep` which has this flag)

**Comment by teesloane** [comment]
Hi @ja5087, Thanks for opening an issue. I'll fix this up shortly!
