### ISSUE TITLE
Documentation about env variables outdated - CIRCLE_ARTIFACTS env does not exist any more

### ISSUE THREAD

**Issue by Tset-Noitamotua** [circleci/circleci-docs#3599]
# Locations
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/environment-variables.md

# Conflict Description
CIRCLE_ARTIFACTS seems not to exist any more. At I am getting an error when I trying to access it.

**Comment by teesloane** [comment]
Hi there, 

You are correct, this variable is no longer available on CircleCI 2.0. The document you have linked to is from Circle 1.0. You can find a list of currently available environment variables in [this document](https://circleci.com/docs/2.0/env-vars/)
