### ISSUE TITLE
default docker image in set up other languages projects

### ISSUE THREAD

**Issue by keroloswilliam** [circleci/circleci-docs#3602]
# Locations
N/A

# Conflict Description
This is a minor but when you try to setup new project from the web interface 
and then choose other as a Language 

the given example shows `debian:stretch` as used docker image but the problem appears when you try the config file as a hello world that the used docker image don't have `git` or `ssh` 

so the following error appears when you try to build the project for the first time for "hello world" trial

`Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.`

**Comment by rosieyohannan** [comment]
Thanks for this feedback @keroloswilliam! I will report back to engineering about the choice of default image throwing up this warning. Closing this docs issue for now, as it's wider than just a docs issue, but feel free to reopen if you would like further clarification :-)
