### ISSUE TITLE
Filter values unclear. Strings or Expressions?

### ISSUE THREAD

**Issue by ahoffer** [circleci/circleci-docs#3648]
# Location
https://circleci.com/docs/2.0/configuration-reference/#filters-1

# Explanation
The documentation for the value of `only:` is a string or list:

`only | N | String, or List of Strings | Either a single tag specifier, or a list of tag specifiers`

The example does not look like a string (literal) or a list of strings:

`only: /v.*/`

The string `/v.*/` looks like a regular expression bound by forward slashes.

I scanned update and saw a mention of regex: 
`Branches can have the keys only and ignore which either map to a single string naming a branch. You may also use regular expressions to match against branches by enclosing them with /’s, or map to a list of such strings. Regular expressions must match the entire string.`

I suggest:
1. Do not call it a string. Call it a regular expression (if that's what it is).
2. Link to another page that explains in more detail the legal values for this type of data. 
3. In the explanation, include how to make lists of the strings/expressions and a reference to which flavor of regex is used.

**Comment by rosieyohannan** [comment]
Thanks for the feedback @ahoffer!! You're right, string, list of strings, or regular expression are valid for the `only` key. I will update the configurations reference document to be more complete in this regard. 😀

**Comment by rosieyohannan** [comment]
I have discussed this issue with our engineers and we have come to the conclusion that sting / list of strings is in fact an accurate representation, and there are notes on these sections to explain that regular expressions can be used to define a list of strings. I'm going to close this for now but please reopen if you disagree and feel these descriptions still need to be improved.
