### ISSUE TITLE
Configuration introduction mentions latest version is 2.0, but it's probably 2.1

### ISSUE THREAD

**Issue by kolen** [circleci/circleci-docs#3649]
# Locations
https://circleci.com/docs/2.0/config-intro/#section=configuration
https://circleci.com/docs/2.0/creating-orbs/#step-3---bump-version-property-to-orbs-compatible-21

# Conflict Description
[Configuration introduction](https://circleci.com/docs/2.0/config-intro/#section=configuration) mentions latest version as 2.0

> Line 1: This indicates the version of the CircleCI platform you are using. 2.0 is the most recent version.

Example config also has `version: 2.0`

["Creating orbs"](https://circleci.com/docs/2.0/creating-orbs/#step-3---bump-version-property-to-orbs-compatible-21) mentions that 2.1 version exists:

> Step 3 - Bump Version Property to Orbs-Compatible 2.1

**Comment by teesloane** [comment]
Ack! You are right! Thank you for catching and reporting this inaccuracy. I have opened a PR to fix this (#3655).

Thank you!
