### ISSUE TITLE
SSH into windows vm doesn't work -- it freezes

### ISSUE THREAD

**Issue by hokira** [circleci/circleci-docs#3653]
# Description
I followed a doc below to try windows and worked well! The problem is I cannot SSH into that VM. When I try to SSH, it freezes after accepting on the RSA key.

https://circleci.com/docs/2.0/hello-world-windows/

# Location
N/A

# Steps to Reproduce
Just launch windows executor and ssh into it. I'm using Ubuntu and I tried SSH using both powershell and bash.

**Comment by teesloane** [comment]
Hi there @hokira ; sorry to hear you're running into some issues with SSH'ing into your build. Can you confirm that you cannot type anything into the command at all? I think we've had experiences of the prompt not showing up but commands can still be typed in; can you retry SSH again and typing in `ls` to see if you get any results?

Either way, this sounds like a bug and I will report back when I know more.

**Comment by hokira** [comment]
Hi Tyler,

Thanks for looking into this!

Here's what happens when I try ssh into windows vm. Note that I removed few
strings for privacy:

$ ssh -p <port> <ip>
The authenticity of host 'xxxxx' can't be established.
RSA key fingerprint is SHA256:xxxxx.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[IP]:PORT' (RSA) to the list of known hosts.
<freezes, nothing happens, can't type>

**Comment by teesloane** [comment]
Hi @hokira — thanks for following up with more details; that is very helpful. I am looking into this with our windows team and I will get back to you as soon as possible!

**Comment by teesloane** [comment]
Hi there @hokira. To follow up, this is now listed as a known issue in our windows documentation and we are working to fix this. I will leave this issue open as the team works on it and update again when we see it fixed.

Cheers!

**Comment by hokira** [comment]
Hi @teesloane , to be clear, even Powershell on my windows box freezes when trying to ssh into any shell in CircleCI (bash, cmd, powershell). 

Basically I cannot ssh into a windows vm in CircleCI in ANY way.

**Comment by hokira** [comment]
Hi @teesloane , would you be able to confirm that all SSH connections are not working, or it's just me? I wonder because it didn't work for two laptops for me. Thanks!

**Comment by teesloane** [comment]
Hi @hokira , it sounds like you are running into a more unique issue than we have run into before; do you mind [submitting a support ticket?](https://support.circleci.com/hc/en-us/requests/new) to speed up fixing the issue?

Thank you and sorry about this!

**Comment by teesloane** [comment]
Reopening because I have something you can try @hokira !

When you ssh into the build can you specific a shell to use like so:

`ssh -p 54782 34.73.xxx.xxx -- powershell.exe`

hopefully this will work by either adding `-- powershell.exe` or `-- cmd.exe`

**Comment by hokira** [comment]
Oops, sorry that was a dumb mistake. Thanks for helping me to figure this out Tyler!

**Comment by teesloane** [comment]
No problem @hokira; thank you for raising this issue as it helped us improve our docs regardless (PR #3664).

Take care!
