### ISSUE TITLE
RE: jekyll/_docs/cant-follow.md

### ISSUE THREAD

**Issue by melinath** [circleci/circleci-docs#367]
I'm an admin and I can't follow a project. I have a Build project button, but it doesn't do anything - doesn't even give me an error message. I just get an endless spinner.

**Comment by melinath** [comment]
I.e. these docs are not helpful to me.

**Comment by smart-alek** [comment]
@melinath thanks for the feedback! We're updating our docs for 2.0 right now, but we'll have more information there about general debugging (for admins and non-admins alike).

**Comment by smart-alek** [comment]
(Also, this is quite late, but were you ultimately able to get your question answered?)

**Comment by melinath** [comment]
I have no idea. Too long ago.

**Comment by smart-alek** [comment]
@melinath oh well! if you remember, let us know. :)
