### ISSUE TITLE
Failed to follow project error

### ISSUE THREAD

**Issue by rob4629** [circleci/circleci-docs#3674]
# Description
It looks like we had issues with our Github repo over the weekend (which were quickly resolved). CircleCi removed access to some of our projects based on this. When trying to re-follow the project as per the instructions sent out in the email we received, we get "Failed to follow".

# Location
Describe where you caught the bug.
The `Follow Project` button description changes to `Failed to follow`

# Steps to Reproduce
Once access was removed by Github for a project, and re-instated, attempt to follow the project again on CircleCi.

**Comment by gmemstr** [comment]
Hi Rob, we'll handle this issue through ZenDesk :)
