### ISSUE TITLE
Output of circleci artifacts are yaml only. Why no JSON?

### ISSUE THREAD

**Issue by burninmedia** [circleci/circleci-docs#3681]
# Description
The CircleCI API for artifact retrieval only outputs YAML format right now. Powershell doesn't support YAML but does support JSON. Can you add an option so we can get the file list in JSON and not YAML? Since powershell doesn't support YAML this would make sense with your new windows containers. 

# Location
trying to parse the output in PowerShell for a new windows step of a build.

# Steps to Reproduce
try parsing the artifact retrieval response in powershell.

**Comment by teesloane** [comment]
Hi there @burninmedia , can you give me an example of what API call you are making? I've never seen it outputs YAML! 

When I make an API call to get my latest api arguments (at least, just dropping this into my browser) returns JSON:

```
https://circleci.com/api/v1.1/project/github/teesloane/<MY_PROJECT>/latest/artifacts?circle-token=<MY_TOKEN>
```

```json
[ {
  "path" : "artifact-file",
  "pretty_path" : "artifact-file",
  "node_index" : 0,
  "url" : "https://132-158751558-gh.circle-artifacts.com/0/artifact-file"
}, {
  "path" : "tmp/artifacts/artifact-2",
  "pretty_path" : "tmp/artifacts/artifact-2",
  "node_index" : 0,
  "url" : "https://132-158751558-gh.circle-artifacts.com/0/tmp/artifacts/artifact-2"
} ]
```
I am using [this endpoint](https://circleci.com/docs/api/#artifacts-of-the-latest-build)

Cheers!

**Comment by burninmedia** [comment]
After looking I don't think this is YAML but here is my command and response data clipped
https://circleci.com/api/v1.1/project/$vcs_type/$username/$project/$build_number/artifacts?circle-token=$CIRCLE_TOKEN -Method GET
**output:**
({:path "src.orig/ASPlayerTest.mxml", :pretty-path "src/bla.bla", :node-index 0, :url "https://15-198716507-gh.circle-artifacts.com/0/src/bla.bla"} {:path "src/Benchmark.mxml", :pretty-path "src/BenchmarkTab.mxml", :node-index 0, :url "https://15-198716507-gh.circle-artifacts.com/0/src/Benchmark.mxml"}.....continued

**Comment by teesloane** [comment]
@burninmedia So what's being sent back is actually a data format called `EDN`. If you want to return JSON you'll need to pass a header specifying so (`Accept: application/json`). Thanks!
