### ISSUE TITLE
Running GPU enabled tests

### ISSUE THREAD

**Issue by hhsecond** [circleci/circleci-docs#3687]
# Missing Information
GPU doc doesn't give much information about how can I setup circle CI to run tests on GPU. 

# Already Looked
- https://circleci.com/docs/2.0/gpu/
- https://discuss.circleci.com/t/easiest-way-to-run-gpu-enabled-tests/24105
- https://github.com/circleci/circleci-docs/issues/2302

# Potential Locations
I had expected to see a descriptive set of information at  https://circleci.com/docs/2.0/gpu/. Being a newbie to circle CI, it's extremely difficult for a user to search around and figure how things would work with GPU. A step by step guide with how to set up a GPU instance in circle CI (if it's available now) or how an AWS GPU machine can be made available for circle CI to run remote tests etc would be super great

**Comment by michelle-luna** [comment]
Thanks, the following document has been updated with the info we have so far (you need to contact support to enable this resource type). See https://circleci.com/docs/2.0/configuration-reference/#resource_class
