### ISSUE TITLE
Add note around exit code not showing in UI and doesn't cause test to fail (_cci1/background-process.md)

### ISSUE THREAD

**Issue by r3m0t** [circleci/circleci-docs#369]
There should be a note that the exit code of the background process is not shown in the user interface and doesn't cause the test to fail.

**Comment by smart-alek** [comment]
@r3m0t thanks for the suggestion! We're closing most of our 1.0 issues involving edits in favor of polishing up our [2.0 docs](https://circleci.com/docs/2.0/). Just wanted to loop you in so you don't think we're ignoring you! :)
