### ISSUE TITLE
Docker Folder Mounts Should Be Volume Mounts

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#3696]
# Location
https://circleci.com/docs/2.0/building-docker-images/#mounting-folders

# Explanation
The wording on mounts isn't incorrect, but not the typical Docker terminology. When it comes to mounts, especially with the -v flag, Docker refers to them as "volume mounts" not folder mounts. Hence the flag name `-v` which stands for volume. https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only

Also, this section list a workaround for volume mounts since they don't work in the `docker` executor. Another alternative is to use the `machine` executor where volume mounts do work.

**Comment by thomasr8** [comment]
Fixed in documentation.
