### ISSUE TITLE
Fastlane version needs to be upgraded

### ISSUE THREAD

**Issue by haikusw** [circleci/circleci-docs#3700]
Fastlane seems to be behind a version according to the Build and run tests log:

> #######################################################################
> # fastlane 2.130.0 is available. You are on 2.129.0.
> # You should use the latest version.
> # Please update using `sudo gem install fastlane`.
> #######################################################################
> 
> 2.130.0 Fastlane.swift for plugins and other improvements
> * [Fastlane.swift] generate Swift API for third party plugins and local actions (#15203) via Josh Holtz
> * [action] register_devices: Update file format (#15176) via Matěj Kašpar Jirásek
> * [spaceship] adding support for DEP_ID (#14852) via heartofagoof
> * [action] `is_ci` - added support for Github Actions CI (#15227) via Rishabh Tayal
> * [gym] remove is_string option on skip_codesigning (#15225) via Josh Holtz
> * [sigh] allow download_all to support the platform option (#15175) via nanci
> * [gym] add skip codesign option to build_ios_app (#15189) via Cameron Lowell Palmer
> * [action] plugin_scores: Add support for rendering multiline description of plugin actions on docs (#15212) via Daniel Jankowski
> * [download_dsyms] ix wait for dSYM file to appear on App Store Connect (#15049) via Jean Mainguy
> * [action] slather: Add :binary_file support for handling multiple input files (#15220) via Rob Nadin
> * [action] danger: Support for remove-previous-comments option (#15206) via Eric Jensen
> * [spaceship] changed body['resultString'] to body['userString'] as only userString contains the phrase 'Program License Agreement' whose inclusivity we are checking (#15193) via Ali Fawad
> * [snapshot] added --force option to fastlane snapshot update (#15187) via Josh Landry
> * [action] only add derived data parameter if it's set, and command is update, build… (#15166) via Jesper Westervig Nielsen
> * [core] chomp, not strip output in CommandExecutor (#15132) via Artem Sheremet
> * [CI] Run tests with Xcode 11 (and ruby 2.5) on Circle CI (#15142) via Jan Piotrowski
> 
> Please update using `sudo gem install fastlane`

**Comment by michelle-luna** [comment]
Thank you, which document needs to be updated please?

**Comment by haikusw** [comment]
Sorry, this should have been filed in the circleci cloud server repo directly.  I'll have to find which one it is.
