### ISSUE TITLE
Priority order of context / environment variables

### ISSUE THREAD

**Issue by jaygorrell** [circleci/circleci-docs#3702]
# Location
https://circleci.com/docs/2.0/contexts/#environment-variable-usage

# Explanation
This indicates that a global context takes priority over a local project's environment variables. I'm just assuming that's an error, but is that actually true?

**Comment by teesloane** [comment]
Hi there @jaygorrell — I think the wording in this section might need a bit of work—can you specifically point to the clause that reads as though a global context takes priority over a local project's env vars?

Is it the order of the list that is problematic (ie, does it read that step 7 would override step 1?)

In this case, the paragraph following the numbered list states that:

>Environment variables declared inside a shell command run step, for example `FOO=bar make install`, will override environment variables declared with the environment and contexts keys.

It is the case that the list in question represents order of precedence; where `1` has the highest precedence; in this case it is not correct that a global context takes priority of a local project's environment variable.

**Comment by jaygorrell** [comment]
Sorry for not being very clear. The specific ordering I'm referring to is:
>5. Context environment variables (assuming the user has access to the Context).
and
>6. Project-level environment variables set on the Project Settings page.

This seems to indicate that the context variables override the project-level environment variables. It's possible this is accurate and by-design but I'm assuming it's a documentation error. Please correct me if that is wrong -- though I'd be very interested in the reasoning for this. You'd expect a global context to be overridden by project-specific settings in any form... as seen by items 1-4.

**Comment by teesloane** [comment]
No, problem! I understand now. I'm going to have to check with some of the folks who built contexts on why they take precedence over project-level env vars, but I believe that is the case, here. So, for now, I cannot answer for the reasoning behind this.

In the meantime, is the precedence positioning blocking you from using environment variables beyond this (ie, are contexts overriding projects env vars for your use case?)  If this is the case, I might direct you to opening a [support ticket](https://support.circleci.com/hc/en-us/requests/new) to try and resolve your issue. Please let me know either way!

**Comment by jaygorrell** [comment]
It is not blocking me either way. We're about to start using contexts and it just dictates whether or not we need to remove environment variables from each project or not. It sounds like we don't if the context takes priority but it _seems_ unexpected if the documentation is accurate.

Feel free to close this if it's confirmed to be accurate -- I'd just be interested in the reasoning though.

**Comment by michelle-luna** [comment]
Hi,

You shouldn't need to remove them and (contexts will take precendence as the docs describe). Contexts will be processed/used first as the order implies. "Environment variables added on the Contexts page will take precedence over variables added on the Project Settings page." This is by-design, probably because the goal of contexts is to use variables across projects (share them).

Of course let us know if you have a different experience! (This documentation/list has been working for most, but we had to change it a while back to reverse how we describe it and it was reviewed and approved then by engineering, so I feel pretty confident...)? @KunalJain may have something to add to this about the design choice.

Thank you,
Michelle

**Comment by jaygorrell** [comment]
Got it, so there's no docs issue here so apologies for that. It actually happens to work out in my favor for this transition but doesn't that seem wrong? I'll go ahead and close this but would appreciate a little continued discussion.

All other priorities in the list favor the most local setting but for some reason a context (global by definition) takes precedence over project-specific variables. It's just something that everyone on our team assumed was a documentation error.

**Comment by michelle-luna** [comment]
Cool, thank you!
