### ISSUE TITLE
Enabling GO111MODULE reference is incorrect 

### ISSUE THREAD

**Issue by charlesgreen** [circleci/circleci-docs#3710]
# Description
The support page provides the incorrect command resulting in an error during the build step. 

# Location
"Method 2 - Use GO111MODULE" section
https://circleci.com/blog/go-v1.11-modules-and-circleci/

# Steps to Reproduce

1. Set GO111MODULE="ON"  - note "ON" is in capital letters. 
2. Build the project in CircleCI and you will receive the following error in the web console. 
3. Rerun the job with SSH and try building directly on the host for more info.
4. The correct setting should be `GO111MODULE="on"` with lowercase "on"

```
# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
```
```
# web console output 

#!/bin/bash -eo pipefail
go build ./...
go: unknown environment setting GO111MODULE=ON
Exited with code 1
```

```
# rerun with SSH enabled

$ go build
go: unknown environment setting GO111MODULE=ON
$ export GO111MODULE="on"
$ go build
go: finding golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: finding golang.org/x/text v0.3.2
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e
go: downloading golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: downloading golang.org/x/text v0.3.2
$ echo $GO111MODULE
on
$ export GO111MODULE="ON"
$ go build
go: unknown environment setting GO111MODULE=ON
$ export GO111MODULE="on"
$ go build
```

**Comment by teesloane** [comment]
@felicianotech — as the author of this blog post, are you able to update the environment variable referred to above? 

Cheers!

**Comment by felicianotech** [comment]
This has been fixed, thanks.

**Comment by teesloane** [comment]
Thanks!
