### ISSUE TITLE
Orbs don't inherit the default params

### ISSUE THREAD

**Issue by ArielGueta** [circleci/circleci-docs#3713]
Following an [issue](https://github.com/cypress-io/circleci-orb/issues/172) that I opened on Cypress repository. I'm using the orb they provided, but when I try to set built-in job parameters like `resource_class` or` branches`, I get the following error:

```
# Error calling workflow: 'build'
# Error calling job: 'cypress/run'
# Unexpected argument(s): resource_class, only
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

Orb jobs don't inherit the default job params?

**Comment by felicianotech** [comment]
Hi @ArielGueta. A question like this is best suited for [CircleCI Discuss](https://discuss.circleci.com).

You are correct though, orbs don't do this. The job itself from the orb would need to have those parameters declared, and then use it for its executor.

What you're trying to do in the linked issue won't work.

**Comment by felicianotech** [comment]
I should add, if you think this is something orbs should do natively, you can say so on our Ideas Website: https://ideas.circleci.com
