### ISSUE TITLE
What is CircleCI?

### ISSUE THREAD

**Issue by jfelixbanguera** [circleci/circleci-docs#3749]
# Missing Information
What is CircleCI? what is it for? what is it not for? Explanation and examples of what it does and how does it run.

# Already Looked
https://circleci.com/docs/
https://circleci.com/docs/2.0/first-steps/
https://circleci.com/docs/2.0/hello-world/
https://circleci.com/integrations/
https://circleci.com/orbs/
https://circleci.com/docs/api/#api-overview
https://circleci.com/open-source/

# Potential Locations
https://circleci.com/docs/

**Comment by michelle-luna** [comment]
Hi,

Thanks for filing this issue, sorry you didn't find this quickly. We have it here in the CI/CD Overview https://circleci.com/docs/2.0/about-circleci/ 
We will add some links from these other documents to make it easier to find as well as the What is CircleCI? heading.

**Comment by sameshl** [comment]
@michelle-luna I would like to take up this task. Could you just elaborate on where I exactly that section needs to be added?

Thanks!

**Comment by mvxt** [comment]
@michelle-luna Do you think this page should be in the "Getting Started" section?

Getting Started > Introduction > What Is CircleCI?

**Comment by michelle-luna** [comment]
works for me! thank you!

**Comment by rosieyohannan** [comment]
I'm going to take this as it's been hanging around a while...

**Comment by rosieyohannan** [comment]
Fixed!
