### ISSUE TITLE
Shellcheck page should reference the circleci/shellcheck orb.

### ISSUE THREAD

**Issue by apghero** [circleci/circleci-docs#3762]
# Missing Information
I wanted to use shellcheck, but knowing about orbs, I figured I'd build an orb so all of our organization's builds could just use it. I went to build one. I'll open another issue for a problem there.

I searched for prior art here, but assumed (wrongly) as it turns out that the shellcheck orb would be listed in the documentation somewhere, if it existed. I found the Using Shell Scripts page, which mentions how to run shellcheck, but it does not mention the orb. I continued on my own and built one. It wasn't until I was attempting to debug a failure to publish the orb that I noticed in `circleci orb list` the circleci/shellcheck orb. 🤦‍♂ 

# Already Looked
- [Using Shell Scripts](https://circleci.com/docs/2.0/using-shell-scripts/#shell-script-best-practices)
- Docs Search.

# Potential Locations
- [Using Shell Scripts](https://circleci.com/docs/2.0/using-shell-scripts/#shell-script-best-practices)
- Docs search. Either by indexing the registry, or having a page that lists the orbs that is indexed.

**Comment by rosieyohannan** [comment]
Thanks for this! Just pushing a change to add a link to the orb into the shell scripts doc.

**Comment by rosieyohannan** [comment]
fixed in PR #3876 Thanks for the feedback @apghero!
