### ISSUE TITLE
Available postgresql docker tags conflict reality

### ISSUE THREAD

**Issue by imajes** [circleci/circleci-docs#3768]
# Description
this page (https://circleci.com/docs/2.0/docker-image-tags.json) linked from your pre-built images help doc suggests there's a docker image with the tag `11.5-alpine-ram`. However:

<img width="1243" alt="Screen Shot 2019-09-26 at 6 17 49 PM" src="https://user-images.githubusercontent.com/2073/65731109-fcec5980-e089-11e9-8e8e-32199983980b.png">

# Location

Given I visit https://circleci.com/docs/2.0/circleci-images/#postgresql
When I click the available tags link and visit https://circleci.com/docs/2.0/docker-image-tags.json
Then I see a list of tags which doesn't appear to exist

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by teesloane** [comment]
Thanks for filing this @imajes . I'm a little confused — do you mean that when you go to [this link](https://circleci.com/docs/2.0/docker-image-tags.json)... you see a lot more tags than seem to exist on the [CircleCI images page](https://circleci.com/docs/2.0/circleci-images/#postgresql)? 

Or, is the large list of tags in `docker-image-tags.json` not loading for you?

**Comment by imajes** [comment]
@teesloane specifically, a tag that is in `docker-image-tags.json` does not load for me (as per the graphic)

**Comment by teesloane** [comment]
Ah sorry @imajes, I missed that. Before I research this internally, are you able to re-run your build with another docker-tag for Postgres? If not, I'll jump right into some investigating 🔍

**Comment by imajes** [comment]
Yes, the non-ram version.

**Comment by teesloane** [comment]
Sounds like a dep might have been temporary yanked, or has become temporarily unavailable. It also sounds like your config is properly setup as well if other versions are working. For now, I would recommend using `11.4-alpine-ram` (if it works!) and hope that 11.5 starts to work magically 🌟 soon. If that doesn't work, I will send along a link to internally file a ticket for this. 

Thanks!
