### ISSUE TITLE
RE: jekyll/_docs/requires-admin.md

### ISSUE THREAD

**Issue by jmandel** [circleci/circleci-docs#377]
This is more of a feature request than a documentation improvement, but: the docs here are a bit misleading, in suggesting that CircleCI _needs_ administrative privileges for these purposes. In addition to this automated, high-privilege solution, CircleCI should provide a workflow that for a manual, low-privilege approach that _informs an administrator_ how to set up a deploy key + webhook manually.

**Comment by felicianotech** [comment]
Hi,

Can you clarify? Is this something you expect a doc for or from within the CircleCI app?

**Comment by jmandel** [comment]
Well, both: the docs are a bit misleading in suggesting that this process can't be accomplished without admin access. But as I said: it's mostly a feature request :-)

**Comment by smart-alek** [comment]
@jmandel #814 probably takes care of your first concern, and your second concern is a valid feature request! :)
