### ISSUE TITLE
Use package-lock.json for CircleCI cache checksum

### ISSUE THREAD

**Issue by DanielRuf** [circleci/circleci-docs#3772]
# Locations
https://circleci.com/docs/2.0/language-javascript/

# Conflict Description
The checksum should be created from the lockfile, not the package.json as it changes less often.

**Comment by JoppeDC** [comment]
I'll take a look at this if thats okay

**Comment by teesloane** [comment]
Thank you @JoppeDC  and @DanielRuf ! 

Just as a heads up - we have some progress on this in [this pr](https://github.com/circleci/circleci-docs/pull/3685).

It looks like we just need to update the docs that still reference using the `package.json` as the checksum. Thank you for filing / helping!

**Comment by teesloane** [comment]
Added a comment to the PR, if you can check it out @JoppeDC  — almost ready to merge!
