### ISSUE TITLE
Fix artifacting in CircleCI build

### ISSUE THREAD

**Issue by mvxt** [circleci/circleci-docs#3785]
# Description
Right now in CircleCI builds of this docs repo, we artifact the generated static files for the docs site, but they're not browsable / previewable because the URLs linking to assets and styling are incorrect.

Fixing this would allow people to actually see what their actual changes look like rather than being forced to use a markdown previewer or other, which will always look slightly different.

# Location
Inside CircleCI builds of circleci-docs. Example link here: https://49446-48750547-gh.circle-artifacts.com/0/circleci-docs/index.html

Open the inspector console and notice the 404 messages and where they're pointing to.

# Steps to Reproduce
1. Push a commit on a separate branch and create a new build. OR, click on any existing build of "build" job
2. Notice how we artifact all of the HTML files, CSS / JS, and resources like images.
3. Click on "Artifacts" tab and then on `index.html`. Notice how the page comes with no style. Also open the browser console and observe the logs. Notice the various 404 warnings.

Links are actually pointing to:
```
https://49446-48750547-gh.circle-artifacts.com/docs/assets/*
```

But where they're actually located at:
```
https://49446-48750547-gh.circle-artifacts.com/0/circleci-docs/assets/*
```

Will update issue w/ root cause analysis when time permits. Creating this issue as placeholder.

**Comment by teesloane** [comment]
Thanks for filing this! I'd love to see a staging setup for docs too; however I'm not sure if we can do that with artifacts; everything gets thrown under `circleci-docs` but our built artifacts need to have the proper prod links (ie, your first paste of `docs/assets`). @felicianotech Might have some ideas here though...

**Comment by rosieyohannan** [comment]
@teesloane Maybe we could have a second staging deploy job, like this: https://github.com/circleci/circleci-docs/blob/c7236c31a1e421a73d517d0d3170676af935652a/.circleci/config.yml#L171 but that runs for all branches that aren't master and inserts the PR number into the URL before `docs/assets` ... I'm sure that's how we did it at the last place I worked. So to view the generated site for a PR you use the staging URL with the correct PR number?

**Comment by teesloane** [comment]
That sounds like the solution we need @rosieyohannan ; I don't think using artifacts is a sustainable or perhaps even possible solution at all currently.  We should post this into #docs though perhaps; I'm not sure who can contribute to the devops side of this. It might take me more time than I'd like to figure it out on my own 😅

**Comment by felicianotech** [comment]
Netlify does all of this out of the box if we're finally willing to switch over to a proper hosting solution.

The main site is hosted on S3 right now. If a staging PRs were to happen, it could be hosted there or on artifacts (S3 also), they I've personally never tried to host static files from artifacts. Could be interesting.

**Comment by rosieyohannan** [comment]
I have just noticed we have this file: https://github.com/circleci/circleci-docs/blob/master/jekyll/_config_staging.yml What is it's purpose? Sounds related to this issue!

**Comment by rosieyohannan** [comment]
I am going to close this issue for now - It's more of a long-term hosting convo that can move to Slack I think. Feel free to reopen though!
