### ISSUE TITLE
Root access now supported (RE: jekyll/_docs/manually.md)

### ISSUE THREAD

**Issue by adehnert** [circleci/circleci-docs#380]
According to https://circleci.com/docs/manually/,
> If you need anything else installed, please contact us and CircleCI support should be able to accommodate you. Be aware that for security reasons, we don’t provide root access.

However, `sudo` is now supported, as per [a blog post](https://circleci.com/blog/sudo-circleci-make-me-a-sandwich/), [other parts of the docs](https://circleci.com/docs/installing-custom-software/#installing-via-circleyml), and testing. This part of the docs should be updated.

**Comment by ndintenfass** [comment]
Thanks for the catch @adehnert
