### ISSUE TITLE
IRC Chatroom integration not working

### ISSUE THREAD

**Issue by jkoan** [circleci/circleci-docs#3814]
# Description
On navit-gps/navit i set up IRC Chatroom integration and klicked on "& Test Hook" after that it took a long time then a error popped up. I use a Server in the format like "example.com:12345" where 12345 is the port of the server because its not one standard Port

# Location
https://circleci.com/gh/navit-gps/navit/edit#hooks

# Steps to Reproduce
 
1. Go to https://circleci.com/gh/navit-gps/navit/edit#hooks
2. Enter Correct Details
3. Save
4. Click "& Test Hook"
5. Wait (60sec)
6. Got Error on the Top Left. Also nothing in the IRC-Chat posted

**Comment by rosieyohannan** [comment]
Hi @jkoan! Thanks for letting us know about this. Can I direct you to our support centre? As far as I can tell this is not a docs issue so opening a support request is the best course of action: https://support.circleci.com/hc/en-us/requests/new.
