### ISSUE TITLE
Is there any way to use single file?

### ISSUE THREAD

**Issue by 132yse** [circleci/circleci-docs#3824]
Is there any way to use single file,such as `circle I.yml`, but not `.circleci` folder

**Comment by teesloane** [comment]
Hi @132yse , as far as I know, you need to have a configuration file located at `.circleci/config.yml` to use CircleCI. Please let me know if this is what you are referring to!

**Comment by 132yse** [comment]
I want use `circleci.yml` instead of `.circleci/config.yml`, because it will have one more folder

**Comment by teesloane** [comment]
Unfortunately, the `config.yml` has to go into the `.circleci` folder!
