### ISSUE TITLE
Lexicographic vs. Alphanumeric Sorting on Tags

### ISSUE THREAD

**Issue by mvxt** [circleci/circleci-docs#3840]
# Description
On the page containing CircleCI's pre-built images, in each section when we list out the tags, we're trying to sort the tags and show only the latest. However, if you look carefully at certain image types, like Node.js, you'll see that the versions displayed are not the latest.

The issue is that our docs use the shopify/liquid templating library, and subsequently the `sort()` function uses lexicographic sorting (by character) as opposed to alphanumeric filtering.

What this means is that `9.0` technically is "larger" or "later" than `10.0` because 9 is larger than 1.

There's a Pull Request open on the [shopify/liquid repository](https://github.com/Shopify/liquid/pull/1028#issuecomment-538242103)  to add a `sort_numeric` function, but there's no ETA on when it will be merged. This will fix our issue.

If there are alternative methods to fixing this, that could also be explored.

# Location
This is seen visually on [CircleCI's pre-built images doc page](https://circleci.com/docs/2.0/circleci-images/). In the actual code, we can see in `/jekyll/_cci2/circleci-images.md` on line 286 where we display and sort the values:
```
285 <ul class="list-3cols">
286 {% assign tags = image[1].tags | sort | reverse %}
287 {% assign tagCounter = 1 %}
288 {% for tag in tags %}
289   {% if tagCounter > 99 %}
290     {% break %}
291   {% endif %}
```

Again, the issue is that Liquid's `sort` function is lexicographic, hence the PR in the liquid repository to introduce `sort_numeric`.

# Steps to Reproduce
Go to the pre-built images page. Notice that tags listed for Node.js go up to 9, because lexicographically 9 is "later" than 12. But Node.js current stable version is 12.x.

**Comment by felicianotech** [comment]
The tagging scheme for the current convenience images isn't consistent. Some tags won't have the version number first or at all, but they also would be newer tags.

I'm not sure if the Shopify PR would work well with our tags but if it gets merged soon, it's worth a try to take a look and see what it generates.

In the medium term, the tag list will be completely reworked as our newer convenience images start to come out of beta next quarter.

**Comment by rosieyohannan** [comment]
Closing as it looks like this will be fixed soon from @felicianotech's comment. Feel free to open again if this is wrong!
