### ISSUE TITLE
Starting and configuring rsyslog

### ISSUE THREAD

**Issue by tnedev** [circleci/circleci-docs#3849]
# Missing Information
I'm trying to figure out how to start the rsyslog on the CircleCI instance, but the documentation is limited and I couldn't find a way to start and configure it. 

I was reading https://circleci.com/docs/enterprise/logging/#integrating-with-syslog but couldn't figure it out.

**Comment by rosieyohannan** [comment]
Hi @tnedev, thanks for getting in touch. This document is for an older version of our enterprise product and is not relevant to current versions. Just a couple of questions so I can try to point you in the right direction: are you using an installation of our Server product? Or the managed Cloud version? If you are using Server are you using 1.0 builders? Best Wishes, Rosie :-)

**Comment by tnedev** [comment]
Hi @rosieyohannan  thanks for the quick reply. 
I'm using the cloud version of your product and the 2.0 configuration.

**Comment by rosieyohannan** [comment]
Could you give me some more information about why you want syslog with CircleCI 2.0 so I can try to help? 

You could try using a secondary container and configuring it how you need – I know this isn't a relevant example really but does show using a secondary services container: https://circleci.com/docs/2.0/language-python/#add-other-services-and-set-environment-variables.

**Comment by tnedev** [comment]
I'm trying to forward all system and apps logs to Papertrail because that's my central logging system and would be great if CircleCI's also go to there.

**Comment by rosieyohannan** [comment]
I'm going to close this for now, hopefully using a secondary, services container will give you the functionality you need. If you need assistance still please feel free to reopen if it's a docs issue, or you can open a support ticket :-).
