### ISSUE TITLE
Outdated Documentation - Connecting JIRA with CircleCI

### ISSUE THREAD

**Issue by cedricdg** [circleci/circleci-docs#3867]
# Locations
https://circleci.com/docs/2.0/jira-plugin/

Paragraph "Viewing Build and Deploy Statuses in Jira"

# Details
The structure of Jira changed, so point 3.-5. are not findable in the settings structure of Jira. Simply go into Jira 7 and check the paths: 
Build Settings does not exist anymore:
- Project Settings -> Build Settings -> Advanced Settings
- Project Settings -> Build Settings -> Environment Variables
API Permissions does not exist anymore:
- Project Settings -> Permissions -> API Permissions

**Comment by teesloane** [comment]
Heya! Thanks for filing this issue. I'm a little confused, so let me ask a question or two here.

The steps you have linked in our documentation (steps 3-5) are referring to changing some settings in *CircleCI*, however, you mentioned that "point 3.-5. are not findable in the settings structure of Jira". Correct me if I'm wrong:  it sounds like you are looking for the steps inside of Jira, when you should be in the settings in CircleCI.

<img width="1012" alt="Screen Shot 2019-11-04 at 10 03 31 AM" src="https://user-images.githubusercontent.com/12987958/68112950-7e85a180-feea-11e9-874d-21b78842b185.png">
