### ISSUE TITLE
There is an example of a `resource_class` being used with `machine` job` which is not a supported feature.

### ISSUE THREAD

**Issue by zekeatmoda** [circleci/circleci-docs#3870]
# Locations
Add a link to the document (or documents)
with the conflicting documentation.
https://circleci.com/docs/2.0/configuration-reference/#example-usage-1
# Conflict Description
Describe the conflicting documentation.
You provide an example of a `machine` job with configurable resource class.
According to your other documentation, and my experience experimenting with this, the `resoucce_class` feature is not supported for `machine` jobs.

**Comment by rosieyohannan** [comment]
Thanks for noticing and reporting this 🥳. The examples in the configuration reference are correct, we recently opened up the `resource_class` key across all executors. I will update the out-of-date docs to reflect this :-).
