### ISSUE TITLE
Badge doc page refer to Status page but the badge itself doesn't report all the available statuses

### ISSUE THREAD

**Issue by andreasph** [circleci/circleci-docs#3881]
# Locations
https://circleci.com/docs/2.0/status-badges/
https://circleci.com/docs/2.0/status/

# Conflict Description
According to Status Badges documentation page `the badge displays the status of your project’s default branch`
According to Status documentation page these are the available statuses:
```
SUCCESS: All jobs completed
FAILED: One or more jobs failed
RUNNING: Job run is in progress
ON HOLD: Job is waiting for approval
QUEUED: Job is waiting for available container
```

So I'd expect that the badge reports one of the previous five statuses, while it seems to report only `PASSED`/`FAILED` related to the last completed jobs run and not the ongoing one.
I was not able to find a way to embed in the page the status of the current jobs run.

**Comment by thomasr8** [comment]
@glenjamin or @felicianotech . I would like to work on this issue, but wanted to ask if you might know who I can work with on this issue so I can fix this customer-reported issue. Thanks so much for the help.

**Comment by glenjamin** [comment]
If we’re looking at updating the status badges, perhaps we can switch to the V2 API and use the workflow status rather than job status?

**Comment by thomasr8** [comment]
Going to loop in @ndintenfass and @jama22 to this issue to see if they would like to make these changes in API v2.

**Comment by andreasph** [comment]
hello, so there will be no implementation of seeing to current ongoing status of the default branch?
I think that documentation amended in #3939 is still misleading since it doesn't mention the fact that the status refer to the last completed run

**Comment by andreasph** [comment]
actually the amended page refers to the circleci dashboard, and now the listed statuses don't reflect the ones showed in the dashboard :)

**Comment by rosieyohannan** [comment]
Ah you are correct! - I'm updating that incorrect badge label now :-)
