### ISSUE TITLE
Windows helloworld: incorrect prerequisites (plan)

### ISSUE THREAD

**Issue by Reflexe** [circleci/circleci-docs#3896]
# Locations
https://circleci.com/docs/2.0/hello-world-windows/

# Details
The windows environment is not available for free accounts and open source projects.  However the `prerequisites` section says that a free account is enough. (wasted a lot of time on that one :\ )

**Comment by rosieyohannan** [comment]
Hi @Reflexe! Thanks for getting in touch. The Windows compute type is available to our customers on the free plan. There's a warning message in the UI about Windows requiring a 'usage-based' plan - and I wonder if that has caused this confusion? I'd be grateful if you could let me know and I can report back to our engineering team :-) ... our free plan is now a "usage-based" plan with an allocation of 2500 credits per week.
 
<img width="1480" alt="Screenshot 2019-11-04 at 11 41 41" src="https://user-images.githubusercontent.com/24589403/68159346-8294dc00-ff49-11e9-918e-f3f8f18fcdae.png">

**Comment by Reflexe** [comment]
Oh. Magically works now 😄  I got this error before: 
![](https://user-images.githubusercontent.com/22856488/68160160-cee91780-ff5b-11e9-95ef-18ef331f1e65.jpg)
(I have not used any credits)

Thank you, keep being great!
