### ISSUE TITLE
Project Setup - Branch for pushing .circleci/config.yml

### ISSUE THREAD

**Issue by nsreekala** [circleci/circleci-docs#3899]
# Missing Information
I am trying to find an official and definitive answer to this question:  
"When setting up a project in CircleCI for the first time, which branch should we be using to push the .circleci/config.yml file so that CircleCI detects the pipeline config?" 
Or, to put it in another way, "Can CircleCI identify pipeline config pushed to a branch other than 'master', when setting up the project?"

# Already Looked
Following links have been checked: 
https://circleci.com/docs/2.0/project-build/#section=getting-started
https://circleci.com/docs/2.0/hello-world/

# Potential Locations
Following links might well be the ideal places to hold this info, as they give info on initial steps to be taken when setting up a project: 
https://circleci.com/docs/2.0/project-build/#section=getting-started
https://circleci.com/docs/2.0/hello-world/

**Comment by teesloane** [comment]
Hi! If you go to "Advanced Settings" for in project's settings you will see the following:

<img width="931" alt="Screen Shot 2019-11-05 at 2 19 41 PM" src="https://user-images.githubusercontent.com/12987958/68215609-72c3d900-ffd7-11e9-8428-4a34b7d96d57.png">

But to note, as far as I know, by default CircleCI will run on another branch that isn't master ( I just tested it on a test repository and it worked).
