### ISSUE TITLE
CircleCI Go Demo App

### ISSUE THREAD

**Issue by sandipsau** [circleci/circleci-docs#3932]
# Location
https://github.com/CircleCI-Public/circleci-demo-go/blob/master/.circleci/config.yml#L35
https://circleci.com/docs/2.0/language-go/

# Explanation
Referring to the codebase and the supporting documentation I am little confused about the env variable **CONTACTS_DB_MIGRATIONS**. The documentation says the path should be the absolute path of my code base but if I use that then run test and start service fails in Circle CI. It seems to work only if I put the value as it is mentioned in demo app code base. I am not sure how the path **/home/circleci/project/db/migrations** is configured but it works even if I am building from my own repo cloned from the demo app.
My code repository url is of following format:
https://bitbucket.org/xyz/abc-searchportal-circleci-demo-go/src.
Any help would be greatly appreciated.
Thanks,
Sandip

**Comment by teesloane** [comment]
Hi there, thanks for filing an issue!

I believe our docs are out of date with the project; I will update them.

The path listed [here](https://github.com/CircleCI-Public/circleci-demo-go/blob/master/.circleci/config.yml#L35) that you linked is the path directly to the db/migrations when running from the circleci/container. I believe (at least if it's working for you!) that's the way to go. Please let me know if you have any other issues and we can re-open this issue!
