### ISSUE TITLE
PowerShell Core on Windows images?

### ISSUE THREAD

**Issue by casz** [circleci/circleci-docs#3954]
# Missing Information
Recommended way of using PowerShell Core for Windows orb?
Consider adding PowerShell Core to Windows orb?

# Already Looked
https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image
This is my current approach would be nice if I could select it as my default shell.
https://github.com/3shape/docker-ci/blob/85cdce1aaf8e201212f5cf0a88af93590e2d237c/.circleci/config.yml

# Potential Locations
https://circleci.com/docs/2.0/hello-world-windows

**Comment by casz** [comment]
Sadly not easy to install powershell core.
chocolatey does not have the ability to modify PATH variable for circleci nor does dotnet tool seem to be in PATH

**Comment by casz** [comment]
Some super odd quoting is going on!

**Comment by rosieyohannan** [comment]
Hey @casz sorry for the delay in getting back to you. I myself don't have the answer but I'm reaching out to our engineers for an answer and will get back to you ASAP :-)

**Comment by teesloane** [comment]
Hi @casz ! It sounds like you've managed to implement a means to use powershell core in your config (although it is less convenient that having the software natively installed). Until powershell core becomes available in our images, we'll make note of your solution in the docs. I'll circle back around and close this when we've put up a PR to make note of it.

**Comment by casz** [comment]
@teesloane much appreciated :)

**Comment by teesloane** [comment]
@casz no problem! I've put up a PR (#3992) referencing this issue. If you have the time to take a look and provide feedback, would you mind doing that? We definitely appreciate hearing more feedback from our users on how we can improve our Windows documentation. Cheers and thanks for filing this issue!
