### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by Thunder2425** [circleci/circleci-docs#3960]
# Description
Describe the bug you found.

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by Thunder2425** [comment]
> # Description
> Describe the bug you found.
> 
> # Location
> Describe where you caught the bug.
> If the bug occurs in a specific document,
> add the link here.
> 
> # Steps to Reproduce
> Describe the steps you took to produce the bug.

**Comment by Thunder2425** [comment]
My cell Phone his a brand new one but it just bug and take many time before changing as pages. I just had To print on the button 10 times fastly and the game is done

**Comment by Thunder2425** [comment]
Good site for who want To learn that incredible headbreacker.

**Comment by rosieyohannan** [comment]
@Thunder2425 this does not appear to be connected to CircleCI docs so closing.
