### ISSUE TITLE
CicleCI still ask for password, even when you add a ssh key fingerprint, while try to deploy on server

### ISSUE THREAD

**Issue by CutePotato** [circleci/circleci-docs#3973]
# Description
Can't deploy because cicleci ask for password on deploy even with ssh permission added.

# Location
While deploying build job

# Steps to Reproduce
Add ssh key fingerprint from your server on config.yml
add private key to circleci and public on github
deploying with this image: circleci/php:7.3-node-browsers

**Comment by CutePotato** [comment]
Update: after make some changes on ssh keys, get to new problem: @^@The authenticity of host 'bitbucket.org (...)' can't be established.
RSA key fingerprint is ...
Are you sure you want to continue connecting (yes/no)? 
How can I work around this?

**Comment by thomasr8** [comment]
Hello @CutePotato . Thank you for the question. If I may ask, have you tried reaching out to your CSM for more help? Your CSM should be able to help you resolve this issue.
