### ISSUE TITLE
Forked Pull Requests, Secrets, and Contexts

### ISSUE THREAD

**Issue by iamEAP** [circleci/circleci-docs#3974]
# Missing Information
The interaction of the `Pass Secrets to Builds From Forked Pull Requests` setting vis-a-vis environment variables that are set on a `Context` is unclear / not documented.

As written, I'm unsure...
- If only environment variables set on the specific project are restricted, or if it also applies to environment variables set via Contexts
- When a pull request is made from a forked repo, but by an individual who is a member of a security group with access to the Context, whether or not the environment variables are shared regardless of the value of the `Pass Secrets to Builds From Forked Pull Requests` setting

# Already Looked
- [OSS](https://circleci.com/docs/2.0/oss/) page
- [Contexts](https://circleci.com/docs/2.0/contexts/) page

# Potential Locations
Depending on the actual behavior above (it is not easy for me to test this at the moment), a sentence or two in both of the above documents seems like it would suffice.

**Comment by BELTRANSYS1** [comment]
Pass Secrets to Builds From Forked Pull Requests

**Comment by hdost** [comment]
Do we have any updates on this?

**Comment by teesloane** [comment]
Hi there. Sorry for the long reply on this, it slipped by me.

I've checked internally and here's what I've learned: 

> As written, I'm unsure...
> 
> * If only environment variables set on the specific project are restricted, or if it also applies to environment variables set via Contexts

The restriction applies to both env vars and contexts.

> * When a pull request is made from a forked repo, but by an individual who is a member of a security group with access to the Context, whether or not the environment variables are shared regardless of the value of the `Pass Secrets to Builds From Forked Pull Requests` setting

You need the setting to be enabled _and_ to have valid access to the context to be able to use it in a forked build.

I hope that helps! Will close for now, but feel free to open / comment if there are any further confusion / issues. In the meantime, I will patch a change into the docs to try and clear this up.
