### ISSUE TITLE
Windows docs seem inconsistent on reference to free plan vs. pricing

### ISSUE THREAD

**Issue by wrosecrans** [circleci/circleci-docs#3975]
# Locations
https://github.com/circleci/circleci-docs/blame/master/jekyll/_cci2/hello-world-windows.md#L21
vs
https://github.com/circleci/circleci-docs/blame/master/jekyll/_cci2/hello-world-windows.md#L38

# Conflict Description

"Either the Free plan (default) or a performance plan." vs. "The Windows executor is only available on the CircleCI Performance Plan." does't seem mutually consistent.
If there's a subtlety that I can "follow" the document without running the examples or something, perhaps the phrasing could be clarified about whether or not Windows is actually available in the free plan, or requires the paid level.

**Comment by rosieyohannan** [comment]
Good spot! Apologies for this inconsistency. I can confirm that the windows executor *is* available on the free plan using version 2.1 configuration :-). I will update the docs to reflect this. The most up to date truth for plans and pricing can always be found here: https://circleci.com/pricing/.
