### ISSUE TITLE
How to clean up external resources after a job

### ISSUE THREAD

**Issue by LBWright** [circleci/circleci-docs#3986]
# Missing Information
I've been trying to figure out a way to work with Bitbucket's `pullrequest:fullfilled` (or rejected) hook to clean up my auto deployed S3 buckets when my PRs are merged or declined. We auto deploy 

# Already Looked
I've looked at literally every page of the documentation three or four times. 
This is the closest resource I found: https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/jobs-steps.md#sample-configuration-with-imported-orb

# Potential Locations
I would expect to find it somewhere on running jobs or scheduled jobs.

If there's another resource out there, I'd really appreciate it. In the meantime, does anyone have an answer? All I need to do is run `aws s3 rb {{BUCKET_NAME}}` after one of these hooks - assuming the bucket is empty.

**Comment by rosieyohannan** [comment]
Hey @LBWright, I've checked with our engineering team, and unfortunately triggering pipelines using the hooks your describe isn't something we offer right now, but they did suggest some work around options:
 
* Have something external which receives hooks and calls our API to schedule cleanup tasks
* Have a scheduled workflow to do the cleanup
* Have the master workflow include a job which does cleanup based on which PRs are still open

Let me know if this is helpful or if you need more information :-)

**Comment by rosieyohannan** [comment]
I'm going to close this issue for now but please reopen if you would like to discuss further or request more information :-)
