### ISSUE TITLE
Android Docker Image shouldn't have "-alpha"

### ISSUE THREAD

**Issue by jlamson** [circleci/circleci-docs#4002]
# Locations
https://circleci.com/docs/2.0/language-android/#config-walkthrough

# Details
When setting up a new config for an android project based on the sample config, I updated the android image to api 29 (`- image: circleci/android:api-29`) and for the following error. 

```
Build-agent version 1.0.22073-f42bda98 (2019-12-10T12:59:15+0000)
Docker Engine Version: 18.09.6
Kernel Version: Linux d6d0a3541827 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64 Linux
Starting container circleci/android:api-29-alpha
  image cache not found on this host, downloading circleci/android:api-29-alpha

Error response from daemon: manifest for circleci/android:api-29-alpha not found
```

After removing `-alpha` from the docker image, my next build was able to correctly download an Android image.

**Comment by rosieyohannan** [comment]
Hi! Thanks for getting in touch about this. The image we specify in docs `circleci/android:api-25` with `-alpha` does exist, but there is no `circleci/android:api-29-alpha` image. For up to date image lists you can check out: https://circleci.com/docs/2.0/circleci-images/#android or https://hub.docker.com/r/circleci/android. I hope this is helpful :-)

**Comment by rosieyohannan** [comment]
I'm going to close this issue now, but please reopen if you would like further information etc :-)
