### ISSUE TITLE
Building against multiple python versions

### ISSUE THREAD

**Issue by clbarnes** [circleci/circleci-docs#4005]
# Missing Information

Official guidance on running the same tests against multiple python versions in parallel.

# Already Looked

#2838 , which allegedly addressed #2757, only states that you can change the image; presumably then having to copy and paste many other lines of config for each version (there are currently 5 supported python versions; that's a lot of copied text).
What we want is a way to change *only* the image and keep everything else the same for many jobs.

It is possible to set up a single python container, do `pyenv global <version1> <version2> ... <versionN>`, then run tox, but that means everything happens in serial, in one container, with a potentially huge log.

# Potential Locations

https://circleci.com/docs/2.0/language-python/

**Comment by clbarnes** [comment]
Found this forum post: https://discuss.circleci.com/t/pyenv-pyvenv-command-not-found/4087/6 which states

> On CircleCI 2.0 we recommend using different container images for different language versions.

I contend that unless you actually write that recommendation down somewhere people can find it, you're not actually recommending it :wink: This needs to go in the python docs.

**Comment by rosieyohannan** [comment]
Hey @clbarnes thanks for your message. If I'm understanding right, I think you want to run your test suite in parallel but specify a different docker image for each parallel run? If so, unfortunately that's not actually possible using job parallelism. However, you can define a reusable test job and use a parameter for the image tag, then run multiple instances of that job concurrently by calling them in a workflow, and setting the image tags for each one in the workflow too. Let me know if this makes sense, or if you would like more information. It's a good use case though and I'll work on representing it in our docs 🥳

**Comment by clbarnes** [comment]
[Here](https://github.com/clbarnes/meshio/blob/bdec8ae95c1ead1409cb39ff24e5a437a764fdad/.circleci/config.yml) is the solution I came up with.
Given the use case is absolutely essential for CI with many languages, and much simpler in most other major CI providers, it seems like a lot of boilerplate and isn't very extensible. It would be great to get the "proper" way represented in the docs!

**Comment by rosieyohannan** [comment]
Thanks @clbarnes, I'm going to work on getting this subject covered in docs, but in the mean time I wonder if you know about the reusable config options available if you use config `version 2.1`? Take a look here: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors - there's a section on using parameters on this page too, which should help.

**Comment by rosieyohannan** [comment]
An example of this kind of thing suggested to me for use case would be:
```
jobs:
  test:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<<parameters.version>>
    steps:
      - run: python -V
```

**Comment by rosieyohannan** [comment]
Hey again, I'm working on making this clearer in docs, so closing this issue for now. Feel free to reopen if you would like more information!
