### ISSUE TITLE
Internet Explorer on Windows?

### ISSUE THREAD

**Issue by anthony-chu** [circleci/circleci-docs#4007]
# Missing Information
Does Internet Explorer come default on Windows images?

# Already Looked
I've already taken a look at the list of pre-installed software at https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image. Does this mean that Internet Explorer was not installed? Or that Internet Explorer is already packaged by default for Windows and it was not additionally installed?

# Potential Locations
Would be helpful to include any Windows default applications on https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image as well.

**Comment by rosieyohannan** [comment]
Hey @anthony-chu, thanks for getting in touch. The list provided on the "hello world" page is a definitive list of what's included in the image. There may be some other elements that are installed as dependencies of the items we explicitly install, but we don't guarantee the presence of anything that is not in the list.

**Comment by rosieyohannan** [comment]
I'm going to close this issue but please get back in touch if you need further information :-)
