### ISSUE TITLE
Menu Screen Glitches

### ISSUE THREAD

**Issue by macoycorpuz** [circleci/circleci-docs#4011]
# Description
The menu screen glitches when you go to Pricing Page on Mobile.

# Location
https://circleci.com/pricing/

# Steps to Reproduce
Go to the link and click the menu icon

**Comment by teesloane** [comment]
Hi there!  Thanks for filing an issue. Unfortunately, this repo does not handle our home page (and subsequent pricing pages) so I'm going to label this as a non-issue on our repo and move it into our bug tracker. But in the meantime, can you provide any screenshots or recordings of the bug? We'd really appreciate the help none-the-less!

**Comment by macoycorpuz** [comment]
This is the screenshot of the bug. I also tried restarting the browser and re-opening the page, but this happened. 

![73D272A8-65E7-47DE-B8A3-FACBEFC3A7A6](https://user-images.githubusercontent.com/24865368/70923759-bfd1ab00-206b-11ea-8cc7-43f827212ddc.png)

**Comment by macoycorpuz** [comment]
I tried opening the page again but the menu is still the same. 

Environments:
- iPhone 7 plus
- Chrome App

**Comment by teesloane** [comment]
Thank you @macoycorpuz  - we really appreciate it!
