### ISSUE TITLE
VCS-CircleCI Permissions Map

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#4035]
# Missing Information
It would be very helpful to have a table that indicates what a user can or cannot do in CircleCI based on their permissions in their VCS provider. 

# Already Looked
https://circleci.com/docs/2.0/gh-bb-integration/#how-to-re-enable-circleci-for-a-github-organization

# Potential Locations
https://circleci.com/docs/2.0/gh-bb-integration/#how-to-re-enable-circleci-for-a-github-organization

**Comment by thomasr8** [comment]
Engineering resources are not currently available to address this issue, so I will be closing this issue for now and revisiting later when more Engineering bandwidth is available.
