### ISSUE TITLE
Unable to search for table elements

### ISSUE THREAD

**Issue by levlaz** [circleci/circleci-docs#4036]
# Description
When performing a search it appears that elements that are in tables are not able to be searched for. 

A specific example can be found on this page: https://circleci.com/docs/2.0/configuration-reference/#run

`no_output_timeout` appears in the table that defines run options. 

Performing a search[1] for `no_output_timeout` shows no results. 

[1] https://circleci.com/docs/?query=no_output_timeout

**Comment by teesloane** [comment]
So I took a look into this.

Unfortunately, adding "table" to the indexable html elements on Algolia ends up creating records that well exceed the record limit size (10kb on the open source plan... and even larger than what the paid plan allows - 20kb.)

Closing, but feel free to comment / investigate and re-open if an alternative solution arises.
