### ISSUE TITLE
Misleading Gradle environment information

### ISSUE THREAD

**Issue by hmijail** [circleci/circleci-docs#4039]
# Locations
https://circleci.com/blog/how-to-handle-java-oom-errors/

# Details
The information regarding Gradle is misleading/incorrect; the actual way in which Gradle uses the environment variables is more complicated. Notably, GRADLE_OPTS is rarely what one needs. It'd be better to just send the reader to the official Gradle docs.
https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables

**Comment by iynere** [comment]
@hmijail thanks for the feedback! what specifically is misleading/incorrect? we can/should definitely direct folks to the docs, as well

**Comment by hmijail** [comment]
CircleCI article says 
> GRADLE_OPTS
> Predictably, this variable is used to **set memory limits for Gradle projects**. It takes precedence over any general env vars used to set JVM memory limits—except _JAVA_OPTIONS._

Gradle docs say
> GRADLE_OPTS
>     Specifies JVM arguments to use when starting the Gradle client VM. **The client VM only handles command line input/output, so it is rare that one would need to change its VM options. The actual build is run by the Gradle daemon, which is not affected by this environment variable.**

**Comment by hmijail** [comment]
In fact, the whole Gradle memory discussion boils down to "if Gradle dies unexpectedly set this ineffectual environment variable because black art". It's what I'd expect from WikiHow or some such, not from the official CircleCI site.

**Comment by rosieyohannan** [comment]
@iynere shall I move these details to the blog repo?

**Comment by rosieyohannan** [comment]
Thanks for clarifying, @hmijail!

**Comment by rosieyohannan** [comment]
Closing as feedback on the blog post has been passed on ☺️
