### ISSUE TITLE
Miniconda not listed in Windows image pre-installed software

### ISSUE THREAD

**Issue by bdice** [circleci/circleci-docs#4040]
# Missing Information
It appears from brief testing that Miniconda comes pre-installed in the Windows executor images. However, Miniconda isn't listed in the section labeled "Software pre-installed in the Windows image": https://circleci.com/docs/2.0/hello-world-windows/

# Already Looked
https://circleci.com/docs/2.0/hello-world-windows/

# Potential Locations
I would expect to see this info in the pre-installed software list.
Also it might be useful to mention on the Python language page: https://circleci.com/docs/2.0/language-python/

Thanks for the great documentation! 👍

**Comment by teesloane** [comment]
Hi @bdice - how are you using miniconda on windows—can you post your config? 

I am not super familiar with Miniconda/Anaconda, but I presume the command `conda` should be available in the windows shell (I tried running it in a [windows build](https://app.circleci.com/jobs/github/CircleCI-Public/circleci-demo-windows/39) but it doesn't seem to be the case).

**Comment by bdice** [comment]
@teesloane Hey, thanks for taking a look. I should clarify what I was doing -- I wanted to install a specific version of Python (3.8), since Python wasn't listed in the pre-installed software and I thought I would need to install it myself. However, when I ran the installation with chocolatey, I got the message below, which says that a version of Python was already installed to `C:\tools\miniconda3`. For that reason, I thought miniconda was installed. I haven't actually tried to use the `conda` command. I would suspect that conda is installed but `conda` isn't on the PATH.

_From https://app.circleci.com/jobs/github/glotzerlab/signac/4491:_
Command:
```
#!powershell.exe -ExecutionPolicy Bypass
choco install python --version 3.8.1 --limit-output --no-progress
python --version
```
Output:
```
python
By installing you accept licenses for the packages.

python3 v3.8.1 [Approved]
python3 package files install completed. Performing other installation steps.
Installing 64-bit python3...
python3 has been installed.
WARNING: Provided python InstallDir was ignored by the python installer
WARNING: Its probable that you had pre-existing python installation
WARNING: Installed to: C:\tools\miniconda3
  python3 can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of python3 was successful.
  Software installed as 'exe', install location is likely default.

python v3.8.1 [Approved]
python package files install completed. Performing other installation steps.
 The install of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 2/2 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Python 3.7.3
CircleCI received exit code 0
```

Notice that at the end, the Python version found is Python 3.7.3 -- not Python 3.8, which is what I installed with chocolatey. This suggests to me that the `python` executable on the PATH is actually from somewhere in `C:\tools\miniconda3`. In a later commit, I moved the `python --version` check to a new command, and there it finds Python 3.8 correctly (because the PATH has been refreshed).

Here are some potential next steps:
- Document the Python version that is installed (Miniconda3 Python 3.7.3)
- See if you can add conda to the PATH (Appveyor's images include Miniconda and it would be a great feature for Python users testing packages with complex dependencies!)
- Document the conda version that is installed

Please let me know if I can assist further!
