### ISSUE TITLE
Can't acces to my project anymore

### ISSUE THREAD

**Issue by vincentproxistore** [circleci/circleci-docs#4046]
# Description
When I click on my project i have an error message: 
"Something doesn't look right ...
Something completely unexpected happened"

# Steps to Reproduce
Click on add project in the menu and select a project then the message appears.

**Comment by teesloane** [comment]
Hi there! This is outside of the documentation repo. Please consider contacting [support](https://support.circleci.com/hc/en-us) If you are unable to add projects!
