### ISSUE TITLE
Move and rename Troubleshooting Guide (_cci1/troubleshooting-guide.md)

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#405]
Noticed that this is under Troubleshooting in the left sidebar, and its title of "Troubleshooting Guide" suggests that it's a more general overview.

The only real section in it is called "The build passes locally but fails on CircleCI," which suggests that it might be better named, or maybe better placed elsewhere.

**Comment by smart-alek** [comment]
Agree with you @li3n3 but we'll have to transfer these lessons to 2.0 docs! :)
