### ISSUE TITLE
RE: jekyll/_docs/requires-admin.md refers to page that no longer exists

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#406]
"Manage Projects" doesn't seem to exist (anymore), though I got to take that opportunity to dive into the codebase with @drazisil (which was great!).

What page should this refer to now? `Add Projects`? `Projects` (which I don't have)? Something else?

I'm itching to rewrite this little doc in general. 😀

**Comment by felicianotech** [comment]
Not 100% but I would think it would be the Add Projects page: https://circleci.com/add-projects
