### ISSUE TITLE
Description of CIRCLE_NODE_INDEX references CIRCLECI_NODE_TOTAL instead of CIRCLE_NODE_TOTAL

### ISSUE THREAD

**Issue by bamItsCam** [circleci/circleci-docs#4060]
# Locations
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md#built-in-environment-variables

# Conflict Description
CIRCLE_NODE_INDEX currently shows:
`The index of the specific build instance. A value between 0 and (CIRCLECI_NODE_TOTAL - 1)`

it should be:
`The index of the specific build instance. A value between 0 and (CIRCLE_NODE_TOTAL - 1)`

**Comment by teesloane** [comment]
Hi @bamItsCam,

Thanks for catching this inaccuracy! I have put up a PR to address this (https://github.com/circleci/circleci-docs/pull/4073). We will merge it as soon as it's reviewed. 

Thanks again!
