### ISSUE TITLE
New View Unauthorized Doesn't Stop Duration Count

### ISSUE THREAD

**Issue by rachael-smith** [circleci/circleci-docs#4072]
# Description
When a build throws an unauthorized error in the new view the duration keeps running - in the old view it would stop

# Location
on the pipelines page

# Steps to Reproduce
on new view:
run a build that will throw an unauthorized error
after throw notice duration keeps going - currently have one that threw 13 days ago and have 315h 10m 34s in my duration column

**Comment by teesloane** [comment]
Hi there @rachael-smith !

Can you provide a link to the pipeline that is displaying an unauthorized error, or perhaps a screenshot?

Generally, this kind of issue should be filed in our [support portal](https://support.circleci.com/) as the issue is related to the performance of the web application. This repo is specifically used our documentation. In the meantime, I've already spoken with some folks to try and resolve what might be the issue, so feel free to post any other information here. Cheers!

**Comment by rachael-smith** [comment]
So sorry! This is where I was pointed to from i think circle for support? my bad! here is a screen shot
![Screen Shot 2020-01-20 at 1 10 10 PM](https://user-images.githubusercontent.com/30902149/72748847-596a0c00-3b86-11ea-8e16-1cb938bbd518.png)

**Comment by rachael-smith** [comment]
Same shot just closer in just wanted to show on the other that failed it working but unauthorized isn't

![Screen Shot 2020-01-20 at 1 09 55 PM](https://user-images.githubusercontent.com/30902149/72748862-625add80-3b86-11ea-87fb-030261533442.png)

**Comment by teesloane** [comment]
Oh my! 408 hours! Can you provide a url link to any of these pipelines?

**Comment by rachael-smith** [comment]
https://app.circleci.com/github/RedVentures/atomizer2/pipelines

**Comment by teesloane** [comment]
Hi @rachael-smith -- sorry for the late follow up. Are you still running into unauthorized builds with an incrementing count? 

On the application side, we'll fix the bug where build timing is incrementing on authorized builds, but I also wanted to make sure you weren't running into other issues related to this. One user has [referenced](https://discuss.circleci.com/t/unauthorized-authentication-required-when-using-docker-push/15538) running into unauthorized build issues based on missed payments to third parties) -- but other than that, I'm not sure what other bugs might be happening 🐛 .

Thanks again for any insight!

**Comment by teesloane** [comment]
@rachael-smith thanks for the quick response. It sounds like we've run into a front end bug based on the unauthorized build. We'll work on fixing that up and I'll ping you here when this is resolved. Thank you for your patience.
