### ISSUE TITLE
RE: jekyll/_docs/language-go.md

### ISSUE THREAD

**Issue by aj0strow** [circleci/circleci-docs#411]
Hey, it's unclear how to specify the required go version.  Anything under `1.7` breaks my code.

**Comment by felicianotech** [comment]
Setting the Go version in the machine section is not supported. We don't currently have Go 1.7 pre-installed. The referenced PR reflects that in the doc.

If you need a newer Go version in the meantime, you can install the binary yourself locally in `~/bin`.
