### ISSUE TITLE
Docker in OSX support

### ISSUE THREAD

**Issue by elgalu** [circleci/circleci-docs#412]
Is not mentioned in the docs:
https://circleci.com/docs/docker/

If the docker service is supported in OSX.

Can you clarify?

**Comment by huytran0605** [comment]
I can't install Docker in OSX

**Comment by felicianotech** [comment]
Docker isn't available in OS X builds. The referenced PR makes note of this. Thank you for pointing this out.

This Issue will close automatically once the referenced PR is merged.
