### ISSUE TITLE
Provide more info about Android Support (_cci1/build-image-trusty.md)

### ISSUE THREAD

**Issue by mpp-doric** [circleci/circleci-docs#413]
It would good to provide more info around your `android extra` section. Currently there is `m2repository` and `support` listed. 

The `m2repository` is actually the support repo, and listed in the SDK tools as `Android Support Repository` with version `39.0.0`. Trusty has v `31.0.0` which should be listed here also really, as its out of date and generally needs updating. 

Not sure what `support` is referring to, but guess its the old static support files, in which case it can be removed.

**Comment by doridori** [comment]
Corrected Google extras names also - unsure what versions your rocking tho!

**Comment by ryanwohara** [comment]
This problem is fundamentally addressed in CircleCI 2.0.
