### ISSUE TITLE
Should separate cluster parameter and deployment patrameter

### ISSUE THREAD

**Issue by sanoyo** [circleci/circleci-docs#4130]
# Locations
I'm checking below document.
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-cookbook.md#managing-gke-actions

I'm tying to deploy to gke by Circleci Orbs.

# Details
`gcloud container clusters get-credentials` should be cluster name in gke.
So I think you should separate cluster parameter and deployment patrameter.

![image](https://user-images.githubusercontent.com/24674237/74077534-c412b700-4a63-11ea-881a-7c4953d3e6a5.png)

https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-cookbook.md#managing-gke-actions

**Comment by thomasr8** [comment]
@sanoyo Hello. Thank you so much for catching this error. I went ahead and fixed it in the documentation to make it more clear.
