### ISSUE TITLE
Can't cancel search

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4139]
# Description
See thread here: https://circleci.slack.com/archives/C0KBNJGRH/p1581457313039100

# Steps to Reproduce
Use search bar in docs - try to cancel using the x .... the search term is removed from the URL but the search itself isn't cancelled - the only way out is to choose a search result or click back in browser.

**Comment by teesloane** [comment]
fixed by https://github.com/circleci/circleci-docs/pull/4178
