### ISSUE TITLE
Deploying To AWS ECR/ECS (ecs-ecr.md) uses very old version of orbs

### ISSUE THREAD

**Issue by ExternalReality** [circleci/circleci-docs#4144]
# Locations
https://circleci.com/docs/2.0/ecs-ecr/

# Conflict Description
The documentation uses very old versions of the ECR and ECS orbs. The documentation provides links to the latest version of these orbs but the examples use very early versions. This can be confusing for new users since they may not notice the version difference and/or the changes to the orbs interface. For example, the latest versions of the ECR orb uses the type `env_var_name` when the old version uses the `string` type for credentials.

The solution may be to simply update the examples to use the latest version of these orbs.

Related: https://github.com/CircleCI-Public/aws-ecs-orb/issues/94

**Comment by rosieyohannan** [comment]
Thanks for pointing this out @ExternalReality! I'll get this doc updated soon.
