### ISSUE TITLE
Incomplete mongo image name in Node.js - JavaScript Tutorial

### ISSUE THREAD

**Issue by effie-0** [circleci/circleci-docs#4180]
# Location
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-javascript.md
or
https://circleci.com/docs/2.0/language-javascript/

# Error Details
- The image name of mongodb is incomplete.
- In the document:
```
- image: mongo:4.2.0
```
- Possible fix:
```
- image: circleci/mongo:4.2.0
```

**Comment by teesloane** [comment]
Hi there @effie-0 !

The mongo image listed in the tutorial referenced is valid -- docker images don't have to be prefaced with a "circleci" tag -- those are just images that we happen to maintain :). The respective build project for the JS tutorial is building ok with the mongo tag it was configured with (here's a [link](https://app.circleci.com/github/CircleCI-Public/circleci-demo-javascript-express/pipelines/77cb66ac-de6e-4789-a825-49b1b5bacc75/config) if you want to see how the build works).

Let me know if that makes sense or if you have any questions. Cheers!

**Comment by effie-0** [comment]
Hi @teesloane ,

Thanks for your kind reply! It turns out that there was something wrong with the tests yesterday, instead of the configurations of CircleCI. Really grateful for CircleCI to help our team to find out the hidden problems (which didn't happen locally)!

**Comment by teesloane** [comment]
Ah good to know! Cheers!
