### ISSUE TITLE
Replace instances of "OS X" with modern "macOS" across docs

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#419]
via #335

**Comment by smart-alek** [comment]
Closing in favor of 2.0 docs.

**Comment by felicianotech** [comment]
This isn't a matter of 2.0 docs. OS X support is 1.0 only and will still need to be changed.
There's no point in changing the screenshots though until the actual app does the change first.

**Comment by smart-alek** [comment]
OK, I'm a bit unclear on what the action items are:

1. What does "change in the app" mean?
2. This original ticket had to do with changing the screenshots?

**Comment by felicianotech** [comment]
@smart-alek For the linked PR, the action item was the screenshots, at minimum.

I left this Issue closed though because there's no time frame that I'm aware of for when this change will first occur in-app.

**Comment by smart-alek** [comment]
@marcomorain just so this is on your radar; we won't be updating screenshots for this guide until copy is updated in-app. No rush! :)

**Comment by KunalJain** [comment]
@smart-alek Plan is to update the logged in application before we make changes to marketing and documentation. I will keep you posted when we do that.
