### ISSUE TITLE
failed to generate Deploy Key

### ISSUE THREAD

**Issue by alexluppi7** [circleci/circleci-docs#4199]
# Description
In one of my projects, when accessing PROJECT SETTINGS> Checkout SSH keys> Add Deploy Key, the following error is displayed

Error: {"message": "Not Found", "documentation_url": "https://developer.github.com/v3/repos/keys/#add-a-new-deploy-key"}

# Location
https://circleci.com/gh/nextqs/next.api.token/edit#checkout

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by rosieyohannan** [comment]
Hey @alexluppi7, thanks for getting in touch! The quickest way to get help with this is probably to go to https://support.circleci.com/hc/en-us  and open a support ticket. Thanks! Fell free to reopen this issue if I've misunderstood and there is a docs-specific problem 😃
