### ISSUE TITLE
Getting started should include new onboarding flow

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4204]
The following section should include the option to go through the new onboarding flow that commits "welcome" config direct to a new branch in your repo:

<img width="874" alt="Screenshot 2020-03-05 at 10 52 10" src="https://user-images.githubusercontent.com/24589403/75974874-71e07c80-5ecf-11ea-9555-136b5bb99a7d.png">

Also, we should perhaps change the manual steps to use the same 2.1 welcome orb config that's used in onboarding.

**Comment by teesloane** [comment]
I can jump on this.

**Comment by rosieyohannan** [comment]
This is done ✅
