### ISSUE TITLE
Third party tooling is missing on docs

### ISSUE THREAD

**Issue by redaxmedia** [circleci/circleci-docs#4209]
Hello,

I would love to contribute my project [Chroma Feedback](https://github.com/redaxmedia/chroma-feedback) to your docs but there is no section for third party tooling!?

Travis CI has something like this: https://docs.travis-ci.com/user/apps/

**Comment by teesloane** [comment]
Woah, neat project @redaxmedia ! Maybe we could add a section to our [open source](https://circleci.com/docs/2.0/oss/) page?  Would you care to make a PR to do that and I can follow up with you there?

**Comment by redaxmedia** [comment]
Thank you @teesloane for the quick response. I think it would be better to have an extra section as this page describes how to use Circle CI with open source and NOT what open source projects are using Circle CI ... it is a difference

Looking forward to a new section or sub-section to be named, then I can send the PR.

**Comment by teesloane** [comment]
Hi @redaxmedia — I think it might be more useful to put a link to external libraries under the [notifications page](https://circleci.com/docs/2.0/notifications/). Can you submit a PR on that file? Also, we have a [guest writer program](https://circleci.com/blog/guest-writer-program/) that might be more suitable as a way to share this cool project.

**Comment by redaxmedia** [comment]
Glad to hear that you like my project that much :-)

I think the notification page is still not the 100% right place as other projects are out there too, but I can send that PR if you say so. We can move it to another (third party tooling) page later.

According to the guest writer program, I reach out to gillian@circleci.com as suggested on the website. You properly inform him too, so I am not a complete strange to him.

Thanks so far

**Comment by teesloane** [comment]
No problem @redaxmedia ! 

Let's go with the notifications page for now, and as other third party tooling continues to grow in the ecosystem we will continue to evaluate where this information will live. Cheers!

**Comment by redaxmedia** [comment]
@teesloane Just added Chroma Feedback to the notification page...

This shows my software in action:
![chroma-feedback](https://user-images.githubusercontent.com/1835397/76713222-6ab33d00-671f-11ea-9162-914d3e5a4341.gif)

**Comment by teesloane** [comment]
closed in #4233
