### ISSUE TITLE
Better document workflows' `when` & `unless` clause

### ISSUE THREAD

**Issue by DominikGM** [circleci/circleci-docs#4212]
# Location
1. https://circleci.com/docs/2.0/configuration-reference/#using-when-in-workflows
2. https://circleci.com/docs/2.0/pipeline-variables/#conditional-workflows

# Unclear

- [ ] 1. Document all "truthy or falsy value" (in 1.)).
- [ ] 2. Which pipeline parameters types can be used in `when` resp. `unless`? In 2.) it says only a `boolean` could be used. But e.g. in [`docker-orb` a `steps` type](https://github.com/CircleCI-Public/docker-orb/blob/e92b35176b796fae8dc157a3dcb0cfb8610ff16c/src/jobs/publish.yml#L161) is also possible.
- [ ] 3. Can't you generate the whole config reference from code, please? It's annoying that still some bits are missing here & there.

**Comment by rosieyohannan** [comment]
Thanks for pointing this out @DominikGM! I've added clarification in the linked merged PR :-)

**Comment by DominikGM** [comment]
@rosieyohannan Thanks. You left out `steps` as a possible value (see 2.)). 

What about 3.)? I would be happy to get an answer from your developers. Any answer (also none) will help us forming evaluation on using CircleCI in the future.

Feel free to move this discussion to https://discuss.circleci.com. Please add a link to it here. Thanks.

**Comment by rosieyohannan** [comment]
Hey @DominikGM, the `when` usage you linked to is actually the use of when for a job, which does accept the `steps` type: https://circleci.com/docs/2.0/configuration-reference/#the-when-step-requires-version-21.

Our config reference is updated regularly both for improvements suggested by our contributors, and to reflect new features.

Let me know if you have any other questions :-)

**Comment by DominikGM** [comment]
@rosieyohannan 

>  the `when` usage you linked to is actually the use of when for a job

Yeah, now I got it. Thanks for clarification.


> Our config reference is updated regularly both for improvements suggested by our contributors, and to reflect new features.

Sure. But can't you automatically create the configuration *reference*, i.e. the API, directly from the code?

E.g. there's the new `machine: true` option which @pete-woods [already added to JSON-Schema](https://github.com/SchemaStore/schemastore/pull/1093) 👍 (see also [CircleCI idea](https://ideas.circleci.com/ideas/CCI-I-940)), but it's [not reflected in the configuration-reference](https://github.com/circleci/circleci-docs/blob/209ddbcb8ddedaff64719902342ef5794065798c/jekyll/_cci2/configuration-reference.md#machine), unfortunately.

**Comment by pete-woods** [comment]
> @rosieyohannan 
> 
> 
> 
> >  the `when` usage you linked to is actually the use of when for a job
> 
> 
> 
> Yeah, now I got it. Thanks for clarification.
> 
> 
> 
> 
> 
> > Our config reference is updated regularly both for improvements suggested by our contributors, and to reflect new features.
> 
> 
> 
> Sure. But can't you automatically create the configuration *reference*, i.e. the API, directly from the code? Best with automation, IMO.
> 
> 
> 
> E.g. there's the new `machine: true` option for `job`s which @pete-woods [already added to JSON-Schema](https://github.com/SchemaStore/schemastore/pull/1093) 👍 (see also [CircleCI idea](https://ideas.circleci.com/ideas/CCI-I-940)). But it's [not reflected in the configuration-reference](https://github.com/circleci/circleci-docs/blob/209ddbcb8ddedaff64719902342ef5794065798c/jekyll/_cci2/configuration-reference.md#machine), yet, unfortunately.

It’s not in there because we don’t really want anyone using it - it’s only supported because of backwards compatibility.

Though I do share your sentiment about it being nice if this schema could be sourced directly from us.

Some challenge there is that it’s done in a “code first” manner, so would need to be generated from an API call, and would likely not have consistent order, or all the docs inline.

**Comment by DominikGM** [comment]
@pete-woods 

> [...] “code first” manner, so would need to be generated [...] all the docs inline.

"all the docs inline" Yes, that's exactly what I mean. 

I have no experience how challenging it would be with Clojure ([CircleCI's main language](https://circleci.com/blog/update-how-circleci-processes-over-30-million-builds-per-month/#Languages), for other readers). But there are already many helper libraries around there. A quick search for Clojure:

1. [Schema](https://github.com/plumatic/schema) which has a [converter to JSON-Schema](https://github.com/vodori/schema-forms). Not much recent work, though.
2. Newer [`json-schema`](https://github.com/luposlip/json-schema) which can directly create JSON-Schema from EDN.
2. Official [`clojure.spec`](https://clojure.org/about/spec) (which will succeed Schema and Herbert) is [still in alpha-stage](https://github.com/clojure?q=spec&type=&language=), AFAIK.
