### ISSUE TITLE
Missing trigger info in Migrating from Github Actions

### ISSUE THREAD

**Issue by lijok** [circleci/circleci-docs#4213]
# Missing Information
In the Concepts/Jobs and Workflows section the Github and CircleCI workflow files being compared do not include information on other triggers such as pull-request, fork etc

# Already Looked
https://circleci.com/docs/2.0/migrating-from-github/

# Potential Locations
https://circleci.com/docs/2.0/migrating-from-github/

**Comment by rosieyohannan** [comment]
Hi @lijok sorry for the delay in replying! Thanks for getting in touch. These documents are designed to just give an overview for comparison, rather than have exhaustive lists of features. We will however look to keep these documents up to date as feature sets change.
