### ISSUE TITLE
Nomad 0.9.7 should be suggested instead of 0.9.3

### ISSUE THREAD

**Issue by chuckyz** [circleci/circleci-docs#4215]
# Description
When upgrading to 2.19, Nomad 0.9.7 should be used instead of 0.9.3.  Nomad 0.9.3 has some very nasty bugs lurking in it (mainly around Vault paths).  These were resolved in 0.9.5, however 0.9.7 has all those fixes, and some high importance security patches.

# Location
https://circleci.com/docs/2.0/update-nomad-clients/index.html

# Steps to Reproduce
Follow 2.19 upgrade guide.

**Comment by chuckyz** [comment]
For reference, I just upgraded to 2.19 using 0.9.7 clients and its working swimmingly. :)

Thanks for making a great product!

**Comment by robloxrob** [comment]
Thanks @chuckyz for getting to the bottom of this!

**Comment by rosieyohannan** [comment]
Hey @chuckyz, thanks for getting in touch about this! We can only officially support the version we used for release testing - for v2.19 that was 0.9.3. But you are of course free to upgrade beyond that, and you can submit support tickets with us if you experience issues, and we will try to help ☺️
