### ISSUE TITLE
Found an error in the circleci/gcp-cloud-run@1.0.2 orb

### ISSUE THREAD

**Issue by tthebst** [circleci/circleci-docs#4231]
# Locations
https://circleci.com/orbs/registry/orb/circleci/gcp-cloud-run?version=1.0.2#quick-start

In the example, the steps should use gcp-cloud-run instead of cloudrun.

# Details
There is a mistake in the example. Can I submit a PR to the orb page?

**Comment by felicianotech** [comment]
Hi @tthebst!

Yes you can. All of the CircleCI created orbs like this one have their own GitHub repositories. The repository for this orb specifically is here: https://github.com/CircleCI-Public/gcp-cloud-run-orb

You'll be able to create an Issue or PR for the orb there. Thank you ahead of time for the PR. :+1:
