### ISSUE TITLE
How to base64 encode gcloud service account credentials correctly

### ISSUE THREAD

**Issue by MeLight** [circleci/circleci-docs#4234]
# Missing Information
Looking for a way to correctly encode gcloud credentials

# Already Looked
https://circleci.com/docs/2.0/google-auth/

# Potential Locations
I would expect to find links from documents that deal Google auth and gcloud. 

# More specifics
I'm trying to encode the key (GCLOUD_SERVICE_KEY) correctly for an hour now. In the doc it says it _should not_ be base64 encoded. But when running to workflow it breaks if not encoded (bad input for base64).
When encoding it doesn't identify the key 🤦‍♂ 

In any case, a one-liner on how the system expects to get the creds would save a lot of time.

**Comment by gmemstr** [comment]
Hi @MeLight :) This is noted here: 

> Remember to download the JSON-formatted key file

Would you mind detailing a little bit about how this key is being used?

**Comment by thomasr8** [comment]
Hi @MeLight : If I may ask, were you able to resolve your issue? If not, I will escalate the issue to the Engineering and Support teams so we can find a resolution to your issue.

**Comment by MeLight** [comment]
@gmemstr The problem is not with the key, but with the way it's supposed to be encoded. After speaking with CircleCI support (awesome, btw) I was provided with the encoding command with the correct flags: `cat <file> | base64 -w 0`

It would save me (and maybe others) a lot of time if this command were somewhere in the doc and easy to find.

@thomasr8 the issue was resolved, thanks
