### ISSUE TITLE
Revise docs to account for old SauceLabs image (_cci1/browser-testing-with-sauce-labs.md)

### ISSUE THREAD

**Issue by cgreene** [circleci/circleci-docs#427]
Just FYI, SauceLabs is no longer updating sc-linux-latest. In my e-mails with them, they now point me to this:
https://saucelabs.com/versions.json

We are apparently supposed to grab the latest linux version from there and go about things that way. If you follow these instructions, you reach this error:
https://support.saucelabs.com/customer/portal/questions/15881491-error-failed-to-bring-up-tunnel-vm-intermittently

It's worth noting that the saucelabs blog post on the topic is also out of date:
https://saucelabs.com/blog/announcing-circleci-integration-on-sauce-labs

I've had some correspondence with their support staff about the inconvenience that this causes, as things appear to get set up correctly before the connection fails. They don't seem to think that serving an old version through sc-linux-latest is an issue though. Consequently, I guess it falls to CircleCI to write new docs to actually fix this.

**Comment by ryanwohara** [comment]
SauceLabs integration works as expected in 2.0.
