### ISSUE TITLE
How do I troubleshoot the time based splitting on my own?

### ISSUE THREAD

**Issue by agamm** [circleci/circleci-docs#4271]
# Missing Information
I couldn't find why I'm getting:
>No timing found for ...

> Error reading historical timing data: file does not exist

>Error autodetecting timing type, falling back to weighting by name. Autodetect no matching filename or classname.  If file names are used, double check paths for absolute vs relative.

 -- Which in the docs says it doesn't matter if it is relative or absolute.

How do I figure out why these happen? I got my JUnit file and I can't figure out what is bad with it. Also, there is no source code that I could find for the `circleci test ` cli agent available so I could try to figure out from the code. 

# Already Looked
https://discuss.circleci.com/t/test-timings-cant-be-found/33702/6
https://circleci.com/blog/how-to-output-junit-tests-through-circleci-2-0-for-expanded-insights/
https://github.com/CircleCI-Public/circleci-demo-go/blob/master/.circleci/config.yml
https://circleci.com/docs/2.0/configuration-reference/#store_test_results
https://circleci.com/docs/2.0/parallelism-faster-jobs/

# Potential Locations
All the links above.

**Comment by teesloane** [comment]
Hi there - sorry you're running into issues. Are you able to post your config.yml file? 

> Also, there is no source code that I could find for the circleci test cli agent available so I could try to figure out from the code.

The CircleCI CLI is available as an [open source repo](https://github.com/CircleCI-Public/circleci-cli) - are you referring specifically to being unable to find the source code for the `test` command?

**Comment by agamm** [comment]
> Hi there - sorry you're running into issues. Are you able to post your config.yml file?
> 
> > Also, there is no source code that I could find for the circleci test cli agent available so I could try to figure out from the code.
> 
> The CircleCI CLI is available as an [open source repo](https://github.com/CircleCI-Public/circleci-cli) - are you referring specifically to being unable to find the source code for the `test` command?

@teesloane  Well, I can't share all of the source, here is a part, example:

> No timing found for "github.com/myproj/server/util/js"

Here is the JUnit time data:
```
<testsuite tests="3" failures="0" time="3.210000" name="github.com/myproj/server/util/js">
<properties>
<property name="go.version" value="go1.13 linux/amd64"/>
</properties>
<testcase classname="github.com/myproj/server/util/js" name="Test1" time="1.100000"/>
<testcase classname="github.com/myproj/server/util/js" name="Test2" time="1.000000"/>
<testcase classname="github.com/myproj/server/util/js" name="Test3" time="1.110000"/>
</testsuite>
```

Here is "$CIRCLE_INTERNAL_TASK_DATA/circle-test-results":
```
{"classname":"github.com/myproj/server/util/js","file":null,"name":"Test1","result":"success","run_time":0.94,"message":null,"source":"unknown","source_type":"unknown"},
{"classname":"github.com/myproj/server/util/js","file":null,"name":"Test2","result":"success","run_time":0.86,"message":null,"source":"unknown","source_type":"unknown"},
{"classname":"github.com/myproj/server/util/js","file":null,"name":"Test3","result":"success","run_time":0.99,"message":null,"source":"unknown","source_type":"unknown"},
```

Here is the code to run the tests in my config.yml:
```
PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=testname)
gotestsum --junitfile ${TEST_RESULTS}/test-output.xml -- -timeout 120m -tags mytag $PACKAGE_NAMES 2>&1 | tee unit_test_output.log
```

---
Regarding the cli - I meant the source code for the test command.

**Comment by teesloane** [comment]
Hi @agamm - sorry about this. Do you mind trying to curl your build [with our API](https://circleci.com/docs/api/#get-build-test-metadata) to see if you get any results? If you're not getting any reports we'll move ahead and file an issue on the support portal; but maybe we can at least get some results in the command line for you.

**Comment by agamm** [comment]
> with our API — post here if you need a hand on that!

@teesloane 
I didn't manage to get a response (some times it returned html and sometime an empty array, I'm not sure the parameters I entered were correct too). 
Overall, I see the test JUnit file and the `$CIRCLE_INTERNAL_TASK_DATA` in my artifacts - so it does generate them...

**Comment by teesloane** [comment]
Hmm. I'm really sorry this isn't working. I think I might get you to [file a support issue](https://support.circleci.com/hc/en-us/requests/new) and in the meantime, I will do some testing when I have some extra cycles. Please feel free to reference this issue as well in your report and hopefully we can figure out what's going on. Thanks for bringing this up!

**Comment by agamm** [comment]
I did, I didn't get a response 10 days already :/
(Request number: 69777)

**Comment by teesloane** [comment]
I see. I'm sure support has a lot going on, so let's continue trying to debug. Can you please post the following: the curl call you used against the api, as well as both responses? In the meantime, I'll walkthrough our and try out a sample repo.

**Comment by agamm** [comment]
@teesloane it returns this:
```
{
  "tests" : [ ]
}
```

**Comment by teesloane** [comment]
@agamm I can't link you my email through GitHub, so we'll have to keep debugging on this public issue (which is better for other folks to find issues too. I know that some of your config can't be shared publicly, but can you post any of the following?

- a screenshot of the failing step?
- a paste of the text from the failing step?

And just to be clear - are you seeing your jobs run in parallel? For example, the [CircleCI demo ruby project](https://app.circleci.com/pipelines/github/CircleCI-Public/circleci-demo-ruby-rails/11/workflows/7baa8e84-31d5-49f7-a46e-84ef0632be9e/jobs/104/parallel-runs/0?filterBy=ALL) runs a few jobs in parallel, and it should look like this:

![image](https://user-images.githubusercontent.com/12987958/79783583-ddab6700-830e-11ea-9e4d-dae7b6c19018.png)

**Comment by agamm** [comment]
@teesloane 
My step isn't failing. It just outputs this:
`No timing found for ...` (it is green)

I changed the command slightly:
`PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)` (It seems that `testname` doesn't work with go atm).

And yes, they run in parallel. But they are not splitted evenly as you'd think (because it probably said that it couldn't find the timing).

**Comment by agamm** [comment]
Still no answer but it seems irrelevant
