### ISSUE TITLE
Getting Started: Link to "Sign Up" page does not open in a new tab, resulting in the reader losing their place in the documentation

### ISSUE THREAD

**Issue by jennbriden** [circleci/circleci-docs#4293]
# Description
As I was reviewing the getting started documentation with the hat on of someone who had never used CircleCI before, I ran into an issue that prevented me from being able to continue along with the getting started steps. Rather than opening in a new tab, the page to sign up for CircleCI opened up in the same tab as the documentation I was reading. As a result, I had to open a new tab and return to the documentation.

# Location
https://circleci.com/docs/2.0/first-steps/

The link in question is in step 1, with the URL of https://circleci.com/signup/.

# Steps to Reproduce
1. Navigate to https://circleci.com/docs/
2. Under **Getting Started**, click **Sign Up & Try**.
3. Now on the https://circleci.com/docs/2.0/first-steps/ page, click **Sign Up** in step 1.

**Actual**: Sign Up page loads in the same tab as the documentation and subsumes it.

**Expected**: Sign Up page opens in a new tab (so that the user can continue to follow the documentation while starting to learn CircleCI in practice).

**Comment by teesloane** [comment]
Thanks for filing this issue. I will implement this feature this week.
