### ISSUE TITLE
Revise confusing/incorrect instructions (_cci1/language-go.md)

### ISSUE THREAD

**Issue by adborden** [circleci/circleci-docs#430]
I'm not seeing the `GOPATH` behavior described here in the docs. When I SSH into the container, both in trusty and precise, I see `GOPATH=/home/ubuntu/.go_workspace:/usr/local/go_workspace`. Also, I don't see a symlink in `~/.go_project`, it doesn't even exist.

**Comment by adborden** [comment]
And to clarify, I'm looking at the [Environment](https://circleci.com/docs/language-go/#environment) section which describe:
> `GOPATH: "${HOME}/.go_workspace:/usr/local/go_workspace:${HOME}/.go_project"`
> ...
> CircleCI places all projects in the ubuntu user’s home directory as `/home/ubuntu/<REPO_NAME>`. To work with Go’s expected directory structure, a symlink is placed to your project’s directory at `/home/ubuntu/.go_project/src/github.com/<USER>/<REPO_NAME>`.

**Comment by dotdoom** [comment]
The symlink is created during "dependencies" stage, unless you override it (that's what I do).

However, I find this setup weird. What problem are CircleCI trying to solve by putting project into `.go_project` and dependencies into `.go_workspace` and how it is supposed to work with subpackages? 

E.g. `import "github.com/user/repo"` will either fail (default), or pull the `master` branch of that subpackage (`go get`).

**Comment by ryanwohara** [comment]
This problem is fundamentally addressed in CircleCI 2.0.
