### ISSUE TITLE
Integration with Jira doesn't work

### ISSUE THREAD

**Issue by pbb-admin** [circleci/circleci-docs#4303]
# Description
I have issues with setting up CircleCI integration with Jira Cloud via Jira Connect, it gets stuck on attempt of generating token:
https://take.ms/NYEC3
Please advise.

# Location
Jira Cloud
https://id.atlassian.com/manage-profile/apps

# Steps to Reproduce
Find the app in Jira App Store, add it, then click Get Started. 
The app gets stuck on the second step (check the link above).

**Comment by teesloane** [comment]
Hi there @pbb-admin  - From your screenshot it looks as though this issue is happening on the Jira Marketplace side. Can you open a ticket on our [support page](https://support.circleci.com/hc/en-us) to get this addressed - it seems like it is out of the scope of the docs.
