### ISSUE TITLE
Hello build error - your tests failed on CircleCI. How can I fix it? Who will help?

### ISSUE THREAD

**Issue by kent7301** [circleci/circleci-docs#4309]
# Description
Describe the bug you found.

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by thomasr8** [comment]
Hi @kent7301 : Thank you for bringing this issue to our attention. If I may ask, can you provide more information about which tests failed, and any error messages that you received? CircleCI Support should be able to help you with resolving your issues. Please feel free to reach out to Support via https://support.circleci.com/hc/en-us/requests/new.

Thank You,

Thomas

**Comment by kent7301** [comment]
Thank you!

**Comment by thomasr8** [comment]
@kent7301 Closing this issue for now, but please let us know if we should change our docs with the fixes you get from Support.
