### ISSUE TITLE
API triggering should include v2

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4312]
# Missing Information
https://circleci.com/docs/2.0/api-job-trigger/#section=pipelines should be "API triggering"  and include both 1.1 job triggering and v2 Pipeline triggering

**Comment by gmemstr** [comment]
Should it completely drop v1.1, or at least add a note that the endpoint is deprecated? I agree that we should add a v2 section at least.

**Comment by rosieyohannan** [comment]
connected to #4347 - check

**Comment by teesloane** [comment]
I think this is sufficiently addressed by https://github.com/circleci/circleci-docs/pull/4402, no @rosieyohannan ?

**Comment by rosieyohannan** [comment]
@teesloane yes let's close this issue. I think my original thought was that as the doc is listed in the sidebar, it should be about pipeline triggering as that's what we want people to be doing. But that can be another issue for another day!

<img width="385" alt="Screenshot 2020-06-05 at 22 01 56" src="https://user-images.githubusercontent.com/24589403/83922480-42fccf80-a778-11ea-92de-305f12d254cf.png">
