### ISSUE TITLE
badge status in multi-workflow setup

### ISSUE THREAD

**Issue by prune998** [circleci/circleci-docs#4326]
# Missing Information
Our use casse is we build/test/... then deploy on our staging env. We also have a manual job to deploy to UAT (using the approval job to keep it on hold until we're confident todeploy).
In this setup, the "build status" as seen on github (and in the badge) is yellow. It won't get green until we trigger the end of the workflow.

We tested putting the UAT deployment (using an approval) into another workflow. In this case, the whole build is `failed` until we trigger the second workflow.

Questions are: 
- is it the right thing to mode the UAT deployment in a new workflow on it's own ?
- how can we create a badge that only report one of the workflow status ? 

If not possible, I strongly suggest you add this feature :)

# Already Looked
workflow docs, badge docs...

# Potential Locations
workflow docs, badge docs

**Comment by thomasr8** [comment]
Hi @prune998: I have added this to the list of features to be added with the next iteration of the product.
