### ISSUE TITLE
Update link to deprecated doc in Android guide

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#434]
https://circleci.com/docs/android/, in this part

> alternatively, you can create your own if these don’t suit your purposes.

links to https://developer.android.com/studio/tools/help/android.html#AVDCmdLine

which now starts with

> This tool is no longer supported. You should instead use Android Studio to create AVDs and create projects.

Not sure where it SHOULD go (or if other updates are warranted), but wanted to note this while I'm looking at it.

**Comment by smart-alek** [comment]
@li3n3 I'd either (a) remove that line entirely or (b) change the link to [this](https://developer.android.com/studio/run/managing-avds.html).
