### ISSUE TITLE
Circleci

### ISSUE THREAD

**Issue by weldingham** [circleci/circleci-docs#4361]
# Location
A link to the document that is unclear.

# Explanation
Describe what confused you about the document.
This could be syntax, word choice, sentence length, or something entirely different.

**Comment by weldingham** [comment]
New to Circleci will in to learn

**Comment by weldingham** [comment]
New to circleci willing to learn

**Comment by rosieyohannan** [comment]
Hey @weldingham, take a look at our [getting started guide](https://circleci.com/docs/2.0/getting-started/#section=getting-started)  to find our more about using CircleCI in your repos. If you have feedback on our docs feel free to let us know here ☺️
