### ISSUE TITLE
site.data.trusty.versions.summary Incorrectly reporting Java versions

### ISSUE THREAD

**Issue by drazisil** [circleci/circleci-docs#437]
Followup to PR #435

**Comment by smart-alek** [comment]
@kimh: @felicianotech mentioned that you might have more insight into why this is happening (see the conversation in #435).

**Comment by kimh** [comment]
@drazisil I vaguely remembered this issue, so let me start from the beginning.

In #435, you changed the default version to `oraclejdk7` but I believe it's `oraclejdk8`. You can see it [here](https://circleci.com/gh/kimh/trusty-test/732) (it could be changed, though).

Another question is where you saw `oraclejdk6` and `openjdk6` in 14.04 image. As far as I can see,  *jdk6 is not installed in the image. You can see it [here](https://circleci.com/gh/kimh/trusty-test/733)

**Comment by drazisil** [comment]
@kimh This was 4 months ago and I believe you have updated the image at least 1-2 times since.

I believe I used `update-alternatives` and saw that Java 6 was still on the image, but it is not there any more.

The primary concern was that the versions.json file did not seem to be being updated in Docs when a new version was being pushed, bus that may have been corrected in that time frame.

**Comment by smart-alek** [comment]
I double checked `versions.json`, and I'm not seeing Java 6, so unless either of you object, I'm going to lay this issue to rest! 😴
