### ISSUE TITLE
RE: jekyll/_docs/environment-variables.md

### ISSUE THREAD

**Issue by ilyakatz** [circleci/circleci-docs#438]
Is it possible to set environmental variables using linux commands, something like this

```
  environment:
    JS_TESTS:
      - COMPARE_SHAS=$(echo $CIRCLE_COMPARE_URL | awk '{sub(/https:\/\/github.com\/execonline-inc\/exec_online\/compare\//,""); print}')
      - git diff --name-only $COMPARE_SHAS |grep -oEc '.js|.jsx|.json'
```

**Comment by felicianotech** [comment]
Please direct questions like these to [CircleCI Discuss](https://discuss.circleci.com).

To answer your question, no. In the environment section, only straight string assignments will work here. No commands would be executed.
