### ISSUE TITLE
Slack notifications are not working

### ISSUE THREAD

**Issue by CesarRegiosDigitales** [circleci/circleci-docs#4428]
# After 22 of May the slack notifications for CircleCi deploys stop working and is causing headaches for our company, this is weird because the webhook key and app is integrated correctly and we have a github/CircleCi dedicated channel for this.

# Location
Slack channels

# Steps to Reproduce
Have a slack channel
Integrate CircleCi app
Configure webhook, channel, etc.
Make a deploy process in CircleCi.

![CircleCi slack bug](https://user-images.githubusercontent.com/48389516/83343503-f66d4c00-a2c0-11ea-8a57-b2065fddb209.png)

**Comment by thomasr8** [comment]
Hi @CesarRegiosDigitales : I am sorry you having issues with Slack notifications. I have reached out to our support team so they can help you further on this issue. Please let me know if there is anything else I can do for you to resolve this issue.

**Comment by thomasr8** [comment]
Hi @CesarRegiosDigitales I reached out to Support and they wanted me to ask if you would please go to the following GitHub page so the correct team can assist you with your Slack notification issue:

https://github.com/CircleCI-Public/slack-orb/issues

Thank You,

Thomas
