### ISSUE TITLE
Note that Chromedriver 2.23 has poor support for Chrome v43 (_cci1/build-image-precise.md)

### ISSUE THREAD

**Issue by anvox** [circleci/circleci-docs#443]
Default chrome version in Ubuntu 12.04 is v43 
Image contains 2 chromedriver as default 2.16 and 2.23 

As chromedriver release note: 
https://chromedriver.storage.googleapis.com/2.16/notes.txt
https://chromedriver.storage.googleapis.com/2.23/notes.txt

Chromedriver 2.23 doesn't support Chrome v43 well. I think it's better to note this in document to avoid confusion when upgrade.

**Comment by ryanwohara** [comment]
https://circleci.com/docs/1.0/build-image-trusty/

Google Chrome
Version: 54.0.2840.100

ChromeDriver
Version: 2.27.440175


Precise is deprecated. Don't use it.
