### ISSUE TITLE
"circleci tests split" does not find timing data from test classes for Junit5 report

### ISSUE THREAD

**Issue by sachinmeesho** [circleci/circleci-docs#4430]
# Description
`circleci tests split` does not find time data from Junit5 test cases.
XML report of Junit5 tests:
```xml
<testsuite name="com.xyz.abc.ClassToTest$NestedTestClass" tests="4" skipped="0" failures="0" errors="0" timestamp="2020-05-31T17:21:36" hostname="SGBDJE7YH8" time="0.015">
...
</testsuite>
```
`$` this seems to be the issue here. 
Just wondering if this issue is already resolved as I don't think i am the first person to try this on Junit5.

Note: Junit tests work fine.

# Location
NA

# Steps to Reproduce
`circleci tests split --total=4 --split-by=timings --timings-type=classname`

this outputs:

No timing found for "com.abc.xyz"
No timing found for "com...."
No timing found for "com...."

**Comment by thomasr8** [comment]
Hi @sachinmeesho : I wanted to follow up with you to see if this is still an issue for you. Were you able to find a resolution to your issue? If not, I will reach out to Engineering to find you a solution. Thanks!

**Comment by gremsam** [comment]
@sachinmeesho @thomasr8 was there a resolution for this problem? I've encountered a similar issue

**Comment by sachinmeesho** [comment]
No resolution. Moved to junit4.

**Comment by wind57** [comment]
we get the same exact problem. `@Nested` tests are not resolved.

What I mean by that, suppose I do : 

```
 circleci tests glob "**/src/test/**/**.java" .... > /tmp/all_tests.txt
```

then, to see what's in that file:

```
cat /tmp/all_tests.txt
```

output is:

```
xxx.classA
xxx.classA$InnerA
yyy.classB
```
If I next do : 

```
cat /tmp/all_tests.txt | circleci tests split --split-by=timings > /tmp/this_node_tests.txt
```
this is what I will see in logs:

```
Autodetected classname timings.
No timing found for 'xxx.classA'
No timing found for 'xxx.classA$InnerA'
```

What is far more interesting is that if I look at the `.xml` testsuite:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="xxx.classA" time="2.641" tests="1" errors="0" skipped="0" failures="0">
  </properties>
  <testcase name="healthEndpointShouldContainKubernetes" classname="xxx.classA$InnerA" time="0.253"/>
</testsuite>
```

which to me is a clear indication that this is a bug in circleci. At least, imho.

**Comment by samdenty** [comment]
This happened for me, because a test name included the words `file path`. They must be using regexes
