### ISSUE TITLE
CircleCI Favicon Fails to Load

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#4435]
The favicon is no longer working. Thus the production Docs site doesn't have a favicon at the moment.

**Comment by rosieyohannan** [comment]
@felicianotech it's working for me?

**Comment by felicianotech** [comment]
It's still not for me. With cache deleted, in both Google Chrome and Firefox it's missing. The first image is Chrome, the second is Firefox.

![Screenshot from 2020-06-02 17-29-25](https://user-images.githubusercontent.com/6017470/83572097-f2c30a80-a4f6-11ea-8eff-6f36d1eed575.png)
![Screenshot from 2020-06-02 17-29-34](https://user-images.githubusercontent.com/6017470/83572103-f6569180-a4f6-11ea-96e3-68858dbca490.png)

**Comment by michelle-luna** [comment]
When I open a new incognito window, I see the favicon is missing, thanks for filing Ricardo!

**Comment by teesloane** [comment]
Strange - mine is working in Firefox and Chrome on mac. Will test on my linux machine shortly.

**Comment by rosieyohannan** [comment]
Hey all - it's failing for me now too. Very strange!

**Comment by teesloane** [comment]
Are you on dark mode @rosieyohannan ? If so, the favicon is there, but will not be easily visible.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/12987958/84927848-6f2f1f00-b09b-11ea-9966-38c3b1b9a51b.png">

**Comment by rosieyohannan** [comment]
Nope not dark mode, controversially I don't much care for it! haha. 

Now I'm looking again the favicon *has* loaded though, so must be an intermittent thing. I checked several times over the day and it wasn't working 🤔

**Comment by rosieyohannan** [comment]
I've had not favicon loaded for like a week now :-(
