### ISSUE TITLE
Two different levels of indentation for branch filters

### ISSUE THREAD

**Issue by zachdavid** [circleci/circleci-docs#4460]
# Locations
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/

filters:
            branches:
              only: master

# Conflict Description
In workflows section you have different indentations for branch filtering. very confusing

**Comment by thomasr8** [comment]
@zachdavid If I may ask, which document did you see this in? Maybe the Configuration Cookbook?

**Comment by thomasr8** [comment]
Hi @zachdavid I went ahead and reviewed our content and was not able to see any issue in the indentations we are using in our code samples. Our YAML validation works correctly, so I am going to close this issue for now. If you find any other instances of indentation issues, please let us know and we will fix right away.

Thank You :)
