### ISSUE TITLE
RE: jekyll/_docs/how-cache-works.md

### ISSUE THREAD

**Issue by zond** [circleci/circleci-docs#447]
I need to download and install a tool that doesn't change all that often.

To speed up the build, I'd like to cache that tool.

Is it possible to configure using circle.yml so that the tool only gets downloaded and installed if not already cached? How?

I'd love for the referred document to tell me this.

**Comment by felicianotech** [comment]
Linodians.com is a statically generated website built with a tool called [Hugo](gohugo.io). Which isn't pre-installed on CircleCI. If you take a look at it's `circle.yml`, you can see how it uses a Bash script and `cache_directories` to cache the Hugo binary. It only downloads Hugo when it's missing or a newer version is needed.

I hope that helps.

**Comment by zond** [comment]
I actually ended up doing something like that (https://github.com/zond/diplicity/blob/master/circle.yml) :D
