### ISSUE TITLE
Example config for Context usage in Overview Image incorrect

### ISSUE THREAD

**Issue by sriedel** [circleci/circleci-docs#4470]
# Locations
https://circleci.com/docs/2.0/contexts/#overview

# Details
1. a colon is missing for the build element of the workflows.build.jobs array
2. the additional indentation of context is very easy to overlook, and since you have an image of text, cut'n'paste won't help with the schema error resulting from naive copying of the configuration here.
Maybe just put copyable text here instead of an image.

**Comment by rosieyohannan** [comment]
Thanks for pointing this out @sriedel 🎉 . The indentation error is due to a text alignment issue with Illustrator. I will fix this ASAP :-)
