### ISSUE TITLE
Adding SSH keys: navigation title changed

### ISSUE THREAD

**Issue by gjj** [circleci/circleci-docs#4473]
# Locations
Add a link to the document (or documents)
with the conflicting documentation.

This is the page in question: https://circleci.com/docs/2.0/add-ssh-key/

# Conflict Description
Describe the conflicting documentation.

Under step 3,

> 3. In the **Permissions** section, click on **SSH Permissions**.

The Permissions section no longer seems to be there? It's just SSH Keys now, or am I missing something?

This is the page that I can find: `https://app.circleci.com/settings/project/github/<Org Name>/<Project Name>/ssh`

**Comment by yaningo** [comment]
1. In a terminal, generate the key with `ssh-keygen -m PEM -t rsa -C "your_email@example.com"`. See the (SSH) Secure Shell documentation web site for additional details.

2. In the CircleCI application, go to your project’s settings by clicking the **Project Settings** button (top-right on the **Pipelines** page of the project).

3. On the **Project Settings** page, click on **SSH Keys** (vertical menu on the left).

4. Scroll down to the **Additional SSH Keys** section.

5. Click the **Add SSH Key** button.

6. In the **Hostname** field, enter the key’s associated host (for example, “git.heroku.com”). If you don’t specify a hostname, the key will be used for all hosts.

7. In the **Private Key** field, paste the SSH key you are adding.

8. Click the **Add SSH Key** button.

**Comment by yaningo** [comment]
The documentation has been updated accordingly.
