### ISSUE TITLE
Confusing and inconsistent instructions for ruby bundle clean in rails bundle caching

### ISSUE THREAD

**Issue by sosaucily** [circleci/circleci-docs#4477]
# Locations
https://circleci.com/docs/2.0/caching/#bundler-ruby

# Conflict Description
The docs say to `add a step that cleans Bundler BEFORE restoring dependencies from cache.`

But in the example the code does a bundle clean AFTER restoring the cache.

**Comment by sosaucily** [comment]
And it kinda makes sense to me that the bundle clean should come before the bundle install, but i'm quite unsure... Just a thought.

**Comment by sosaucily** [comment]
Also, `bundle clean` seems to need the `--force` option now, as it just returns a message and error code without that.

**Comment by teesloane** [comment]
I will fix this. Thanks for the heads up @sosaucily.
