### ISSUE TITLE
Unclear how to use logic in configuration - missing an example or links to further docs

### ISSUE THREAD

**Issue by wlad** [circleci/circleci-docs#4495]
# Location
https://circleci.com/docs/2.0/configuration-cookbook/#using-logic-in-configuration

# Explanation
> The action parameter will default to build on pushes, but you can supply a different value to select a different workflow to run, like report.

The first part (**The action parameter will default to build on pushes**) is clear. 

But what do you mean by "**but you can supply a different value to select a different workflow to run, like report**"? When does this apply? How/when can I supply a different value? Can you give an example? May be I am missing some explanation about pipeline parameters usage?

---

I suggest the marked text in screenshot below to become links to further docs or to provide an example in the same section.
![image](https://user-images.githubusercontent.com/64201310/85982819-c069d780-b9e6-11ea-8bc8-c4679fb0c5d8.png)

**Comment by rosieyohannan** [comment]
Thanks so much for pointing this out @wlad. Just working on making this clearer now :-)
