### ISSUE TITLE
Remove references to enable pipelines

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4499]
100% of Cloud customers now have pipelines enabled automatically so we need to go through all docs and remove references to enable pipelines steps.

We have a reusable snippets for some of these instances.

**Comment by yaningo** [comment]
@rosieyohannan, should we add comments here with links to pages, if we come across any mentioning "enable pipelines"?

**Comment by rosieyohannan** [comment]
Thanks @yaningo! It should be OK though, I'll probably just do a docs-wide search for relevant terms and hopefully catch them all :-D
