### ISSUE TITLE
Language Guide for Go mention unexisting Makefile rule from demo project

### ISSUE THREAD

**Issue by Horgix** [circleci/circleci-docs#4557]
# Location
https://circleci.com/docs/2.0/language-go/

# Explanation
The Language Guide for Go references the following repository all along: https://github.com/CircleCI-Public/circleci-demo-go

However, some things mentioned in the doc seem to be absent from the repository.
For example, there is a `make test` mentioned in the pipeline, but no `test` rule in the linked `Makefile` (maybe I missed it?)
I think it would be better to either not use `make` for the demo, or have an up-to-date corresponding `Makefile`.

**Comment by teesloane** [comment]
Thanks for pointing this out @Horgix  - I'll fix this up.
