### ISSUE TITLE
Docs returns japanese language instead of english

### ISSUE THREAD

**Issue by Simperfy** [circleci/circleci-docs#4591]
# Description
Wrong language in documentation, the dropdown that changes languange in the middle left of the docs is also broken.

# Location
https://circleci.com/docs/2.0/

# Steps to Reproduce
After Visiting [https://circleci.com/](https://circleci.com/) I see the landing page in english.
After Clicking Explore the docs in Gray button it gives me a docs which is in Japanese.
After Clicking the logo at the top left corner to go to landing page, now I see everything in Japanese.

**Comment by rosieyohannan** [comment]
Thanks @Simperfy! This should be fixed now. Please reopen if you are still seeing the language issues :-)
