### ISSUE TITLE
Timing based test splitting docs improvements

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4594]
Expand examples to show all possibilities. 

Currently we have `cat my_java_test_classnames | circleci tests split --split-by=timings --timings-type=classname` in the timings split section but "split by classname" is actually a _rare_ example. 

If people use this (i.e. copy paste from docs) when there are no classname fields in their testcases, the timings data will be empty but they may think it's working fine.

In docs we should give an example test suite/test cases and show how the split command should be formed to match what's contained.

**Comment by rosieyohannan** [comment]
From @mkly :

common issues for troubleshooting:

1. No file= in XML for test formatter. Sometimes this can be fixed with a different or 3rd party test formatter or extra option passed in to formatter.
2. Did not add them to store_test_results
3. Used --timings-type=classname or `--timings-type=testname`
4. File path `./test/my_test.rb` as opposed to `test/my_test.rb` Usually this can be solved with change in the directory `circleci tests glob` is run in or adding something like pwd to the front of the files passed (edited) 
5. No historical test timings data. Because they set parallelism to 1
6. No jUnit format. We do also support cucumber JSON but its mostly all jUnit XML (edited)

**Comment by rosieyohannan** [comment]
Guru card for debugging: https://app.getguru.com/card/c9a4bp9i/Debugging-Test-Splitting

**Comment by nbialostosky** [comment]
We have some helpful support articles with some content that can be pulled:

https://support.circleci.com/hc/en-us/articles/360048786831-Use-test-splitting-with-Python-Django-tests
https://support.circleci.com/hc/en-us/articles/360056636191-Common-test-splitting-issues-with-pytest

For a section on troubleshooting test splits, beyond the above article information, it can be noted that storing the tests results as an artifact can also help troubleshoot as you can see the content of the file being uploaded.

If they see the following error but they are uploading test results:

```
Error reading historical timing data: file does not exist
```

They should ensure they are setting `parallelism: 2` or greater for the job.

Example test splitting with Ruby:

https://github.com/CircleCI-Public/ruby-orb/blob/master/src/commands/rspec-test.yml

Example test splitting with Go:

https://github.com/CircleCI-Public/circleci-demo-go/blob/master/.circleci/config.yml#L37-L40
