### ISSUE TITLE
Error calling workflow: 'build_and_deploy'

### ISSUE THREAD

**Issue by Grayhat00** [circleci/circleci-docs#4607]
**I got this error in circle ci:**

 Error calling workflow: 'build_and_deploy'
 Error calling job: 'build'
 Cannot find a definition for command named restore_chache

# This is config file. Whats am I doing wrong?
![Screenshot from 2020-08-02 13-24-31](https://user-images.githubusercontent.com/43954334/89117962-d24a0900-d4c3-11ea-91b1-90ee8c96cc13.png)
![Screenshot from 2020-08-02 13-25-02](https://user-images.githubusercontent.com/43954334/89117965-d70ebd00-d4c3-11ea-8bad-1fd21b06517e.png)
![Screenshot from 2020-08-02 13-26-03](https://user-images.githubusercontent.com/43954334/89117966-d9711700-d4c3-11ea-9724-f127d296a1e3.png)

**Comment by rosieyohannan** [comment]
Hey! You have an extra `h` in cache... Take a look at `restore_cache` listed in our configuration reference: https://circleci.com/docs/2.0/configuration-reference/#restore_cache and our guide to caching dependencies: https://circleci.com/docs/2.0/caching/#section=projects. Let me know if you don't find what you need ☺️

**Comment by Grayhat00** [comment]
Oh thanks, I've find the mistake. But I get schema errors like:

 [#/jobs/build] only 1 subschema matches out of 2
1. [#/jobs/build/steps/4] 0 subschemas matched instead of one
|   1. [#/jobs/build/steps/4] Input not a valid enum value
|   |   Steps without arguments can be called as strings
|   |     enum:
|   |     - checkout
|   |     - setup_remote_docker
|   |     - add_ssh_keys
|   2. [#/jobs/build/steps/4/save_cache] required key [paths] not found

I'm new at CI, please help me.

**Comment by teesloane** [comment]
Hi there @Grayhat00. It looks like you have a typo:

![image](https://user-images.githubusercontent.com/12987958/89540161-ad5adc00-d7ca-11ea-9cac-97c4e09d27e2.png)

`path:` should be `paths:`.

Try changing that and let us know if it works. If it does not can you post a plain-text version of your config (if you are comfortable sharing it) and we can try and help you debug it. 

Cheers!

**Comment by Grayhat00** [comment]
It works, thank a lot!

**Comment by Grayhat00** [comment]
> Hi there @Grayhat00. It looks like you have a typo:
> 
> ![image](https://user-images.githubusercontent.com/12987958/89540161-ad5adc00-d7ca-11ea-9cac-97c4e09d27e2.png)
> 
> `path:` should be `paths:`.
> 
> Try changing that and let us know if it works. If it does not can you post a plain-text version of your config (if you are comfortable sharing it) and we can try and help you debug it.
> 
> Cheers!
