### ISSUE TITLE
Parameter expansion <<# - what is it?

### ISSUE THREAD

**Issue by bmilner-rally** [circleci/circleci-docs#4609]
# Missing Information
I cannot see examples of parameter expansion using the <<# syntax that I see in orbs and also where is this syntax documented.

# Already Looked
Many google searches, https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration and looking at configuration full reference.

# Potential Locations
https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration - this is where I would have expected examples and syntax

**Comment by rosieyohannan** [comment]
Hey thanks for getting in touch about this! The reason this isn't documented currently is that although it works, it's not officially supported. However, I will look into whether is should be supported with our engineers and if so I will add to the docs ☺️

**Comment by roopakv** [comment]
@rosieyohannan it has been mentioned in the official documentation under the boolean param. 

![image](https://user-images.githubusercontent.com/678239/89701325-898eb780-d8ea-11ea-9800-5dd16299211f.png)

If it isn't officially supported could we remove it from there? I use this all over the place in my orb and my companies config too.

kinda makes me a bit worried

**Comment by rosieyohannan** [comment]
@roopakv thank for pointing this out! Let me check what's going on and I'll get back to you ☺️

**Comment by rosieyohannan** [comment]
Hi again,
I've had confirmation from engineering that it's not a problem if you're using this in your orbs, but we don't want to encourage it's use so I will switch out the example in the docs for an alternative. Thanks for pointing out this issue! :-)

**Comment by roopakv** [comment]
@rosieyohannan If it is ok to use this in orbs, why is it not encouraged? Also if there is a plan to remove support how would you let people who use it know?

**Comment by rosieyohannan** [comment]
Hi @roopakv... This has kicked off a lengthy discussion on this so I will work on docs updates to make it clearer what is and isn't supported here in the coming weeks. To hopefully reassure you, with regards to what is currently working, if we ever phase this out, which is unlikely, there will be a very lengthy deprecation period with lots of public communication.

**Comment by rosieyohannan** [comment]
@teesloane or @thomasr8 this example just needs changing to not use https://mustache.github.io/mustache.5.html as we don't officially support it: https://circleci.com/docs/2.0/reusing-config/#boolean

**Comment by roopakv** [comment]
@rosieyohannan what templating do you officially support?

**Comment by thomasr8** [comment]
Updated the example to make more clear. Closing this issue.
