### ISSUE TITLE
RE: jekyll/_docs/install-and-use-yarn.md

### ISSUE THREAD

**Issue by gilm31** [circleci/circleci-docs#462]
https://circleci.com/docs/install-and-use-yarn/
using the same script as the full example giving us an error in the script step 

if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
  echo "Download and install Yarn."
  curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
else
  echo "The correct version of Yarn is already installed."
fi
Download and install Yarn.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  6491    0  6491    0     0  45666      0 --:--:-- --:--:-- --:--:-- 45711
Installing Yarn!
bash: line 175: yarn: command not found

if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
  echo "Download and install Yarn."
  curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
else
  echo "The correct version of Yarn is already installed."
fi
 returned exit code 127

Action failed: if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
  echo "Download and install Yarn."
  curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
else
  echo "The correct version of Yarn is already installed."
fi

1 step before that script, i echo "$PATH" to make sure yarn path is there and its look fine.
any ideas how do i solve it? 
i saw some posts saying i need to add "/yarn.js" in the yarn path, but that didn't works for me as well

**Comment by felicianotech** [comment]
I did find one issue: https://github.com/circleci/circleci-docs/pull/463

If that's not your problem, then if you can provide your `circle.yml` to me either here or on Discuss (same username) I can try to determine the problem. Alternatively a link to a build.

**Comment by gilm31** [comment]
i see, we solved it with a workaround, 
this issue can be closed
