### ISSUE TITLE
Not possible to add an ssh key by following the documentation

### ISSUE THREAD

**Issue by BurningDog** [circleci/circleci-docs#4625]
# Locations

The incorrect information is at https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/add-ssh-key.md

# Details

In step 2, it says: `In the CircleCI application, go to your project's settings by clicking the the Project Settings button (top-right on the Pipelines page of the project).`

In the new UI experience, not only does that project settings button not exist, but I couldn't not figure out *any* way of finding the `Project Settings` page, and I failed to add the SSH key. This is worrying, given that the new experience will be compulsory in a few days.

In the old UI experience, there is no Pipelines page. On the Jobs page, while there is Settings button on the top-right on the Pipelines page of the project, it links to https://circleci.com/bb/organizations/[my-organization]/settings?pipelines-ui-opt-out=null which does not contain any way to add the SSH key.

In fact, I had to find the *other* settings button the Jobs page, on the *left hand* side, next to the list of previously ran jobs. That then linked to the correct Project Settings page - https://circleci.com/bb/[my-organization]/my-repository]/edit

I discovered that link by accident, and had almost given up trying to add a ssh key.

**Comment by rosieyohannan** [comment]
Hey @BurningDog I can see how this is confusing so I will update the doc with some images. On the pipelines page if you filter for your project the Project Settings page is accessible from a button at the top right:

<img width="1341" alt="Screenshot 2020-08-11 at 16 08 13" src="https://user-images.githubusercontent.com/24589403/89915184-f4433a00-dbed-11ea-9e82-60d25ce0da65.png">

**Comment by rosieyohannan** [comment]
Alternatively, Project Settings can be accessed on the Workflows page:

<img width="1340" alt="Screenshot 2020-08-11 at 16 09 10" src="https://user-images.githubusercontent.com/24589403/89915371-2e144080-dbee-11ea-940e-9b14e04651f6.png">

and the jobs page:
<img width="1340" alt="Screenshot 2020-08-11 at 16 09 49" src="https://user-images.githubusercontent.com/24589403/89915419-3e2c2000-dbee-11ea-8b8d-c43f690b10f1.png">

**Comment by BurningDog** [comment]
Thanks @rosieyohannan - on your 2nd and 3rd screenshots I see the same thing as you do (I wouldn't have known to look there).

> On the pipelines page if you filter for your project the Project Settings page is accessible from a button at the top right

Ah! Ok, I completely missed that. Thanks!

**Comment by rosieyohannan** [comment]
@BurningDog I've also passed your feedback on to the new UI design team :-)
