### ISSUE TITLE
Double scrollers and the bottom footer get stuck

### ISSUE THREAD

**Issue by grndvl1** [circleci/circleci-docs#4654]
# Description
Double scrollers in a window are bad bad bad design.  One for the left menu and one for the page.  If you scroll the page down all the way then the menu becomes blocked and mostly unscrollable.  Double scroller in a window is always been a bad design.  The footer should be minimized in the least case fix or just go away.

# Location
Describe where you caught the bug.
All documentation pages

# Steps to Reproduce
Go to document pages, expand a larger menu, start scrolling the content page to the bottom and then try and use the menu once the footer shows.  Its very annoying

**Comment by teesloane** [comment]
Hi there! I'll pass this information onto the design team. I'd agree with you, double scrollers are not ideal. Because this ticket is not related to our content specifically, I will be closing this issue and make a note of it internally.

Cheers!
