### ISSUE TITLE
Environment variable for pipeline number

### ISSUE THREAD

**Issue by corydorning53** [circleci/circleci-docs#4663]
# Missing Information
Looking for the 'Pipeline' number as its represented in the new UI, on the pipeline page, next to the pipeline name.

# Already Looked
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

# Potential Locations
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by rosieyohannan** [comment]
Hey @corydorning53! I think what you need is Pipeline Values: https://circleci.com/docs/2.0/pipeline-variables/#pipeline-values. Does that solve your problem?

We should really be linking to this from the env vars section of our docs so thanks very much for pointing this out :-)

**Comment by thomasr8** [comment]
Hi @corydorning53 I went ahead and provided a link in the section you noted to the Pipeline Variables page. Thank you so much for noting this for us!
