### ISSUE TITLE
Project Slug in "List of Pipeline" API Endpoint

### ISSUE THREAD

**Issue by pawanbahuguna** [circleci/circleci-docs#4674]
# Missing Information
Code sample for API endpoint https://circleci.com/docs/api/v2/#get-a-list-of-pipelines seems incomplete. It doesn't show where to put `org-slug`.

It should be like https://circleci.com/api/v2/project/{org-slug}/pipeline

Also, the `org-slug` should be `project-slug`, because we also need a project name to get the pipeline of that project.
i.e `vcs/org/project`

# Already Looked
NA

# Potential Locations
API endpoint https://circleci.com/docs/api/v2/#get-a-list-of-pipelines

**Comment by thomasr8** [comment]
Hi @teesloane : Do you happen to know if this was resolved in an API update? If not, would you mind looking into this issue if it is still an issue? Thanks!

**Comment by teesloane** [comment]
Not sure if this has been addressed. Will test this week.

**Comment by teesloane** [comment]
This has been marked as resolved.
