### ISSUE TITLE
Check old workflows docs

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4679]
We have a few very short workflows troubleshooting docs which should probably just be part of the main workflows doc - or part of a troubleshooting guide. Also the content looks to be out of date:

* https://circleci.com/docs/2.0/workflows-waiting-status/
* https://circleci.com/docs/2.0/workflows-not-starting/

**Comment by teesloane** [comment]
Confirmed: these two documents, as well as `workflows-overview.md` all receive less than 0.3 % of monthly traffic. I will migrate their content to workflows.md.
