### ISSUE TITLE
Old settings doc

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4680]
This doc is out of date. I think we could just bin it though? https://circleci.com/docs/2.0/settings/

**Comment by teesloane** [comment]
Hmm - it has been 2 years since it was updated, and from a scan of analytics, just under a 1000 people have viewed it since the beginning of July. Perhaps it's only useful to a handful of server users at this point.

**Comment by rosieyohannan** [comment]
Yeah - or I guess maybe it's useful for people to see these pages listed in docs, I don't know. Can easily enough add tabs with screenshots of the new UI.
