### ISSUE TITLE
Visual Studio workloads installed

### ISSUE THREAD

**Issue by asklar** [circleci/circleci-docs#4683]
# Missing Information
The docs mention that VS 2019 Community edition is installed in the Windows image, but it doesn't mention what workloads are installed/available. For example, is UWP supported? desktop? .net ?

# Already Looked
https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image

# Potential Locations
https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image

**Comment by rosieyohannan** [comment]
Hey @asklar thanks for getting in touch. Visual Studio is installed with Chocolatey with all recommended and optional workloads included. More info here: https://chocolatey.org/packages/visualstudio2019community/16.3.6.0. Hope this helps!
