### ISSUE TITLE
update artifacts image

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4749]
old image in use here: https://circleci.com/docs/2.0/artifacts/#artifacts-overview needs updating to look like the image here: https://circleci.com/docs/2.0/caching/

**Comment by devil-cyber** [comment]
I would like to work on this issue, would you assign this to me

**Comment by rosieyohannan** [comment]
@devil-cyber Thanks for getting in touch! This work is already completed in #4751, it just isn't merged in yet.

**Comment by devil-cyber** [comment]
ok

**Comment by rosieyohannan** [comment]
Fixed: https://circleci.com/docs/2.0/persist-data/#section=getting-started
