### ISSUE TITLE
overview of persisting data

### ISSUE THREAD

**Issue by rosieyohannan** [circleci/circleci-docs#4750]
We don't have a doc that covers workspaces, caching and artifacts and when to use each, as per this blog post. Might be a nice overview to have somewhere as this info is quite spread out in docs right now:

https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/

**Comment by 17sushmita** [comment]
Hi, if the issue is still open, I'd like to take this. And I'd like to know a little more information about how you want this doc structure to be

**Comment by rosieyohannan** [comment]
Hey @17sushmita thanks for your message! If you look to the right of the issue there's a linked PR where I've started work on this new page - some of which required work by our internal design team. If you have anything to add to the page feel free to submit ideas though ☺️

**Comment by rosieyohannan** [comment]
fixed: https://circleci.com/docs/2.0/persist-data/#section=getting-started
