### ISSUE TITLE
Configs examples in ordered lists are indented one whitespace character

### ISSUE THREAD

**Issue by dsayling** [circleci/circleci-docs#4768]
# Description
Configs examples in ordered lists are indented one whitespace character. (Maybe unordered too?)

# Location
See the config under ordered list 1, https://circleci.com/docs/2.0/getting-started/#using-the-workflows-functionality
If you copy and paste this config, it doesn't work.

# Steps to Reproduce
When you highlight the text, the whitespace character is visible.

**Comment by rosieyohannan** [comment]
Fixed!
