### ISSUE TITLE
Link to coveralls doc points to an old page

### ISSUE THREAD

**Issue by sarthakgupta072** [circleci/circleci-docs#4782]
# Locations
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/code-coverage.md#coveralls

In this section the link points to https://coveralls.io/docs which is an old page and is not maintained anymore.

# Details

The link can be updated to https://docs.coveralls.io/

**Comment by devil-cyber** [comment]
I would like to work on this issue, would you assign this to me
