### ISSUE TITLE
Enhancing readability of docs

### ISSUE THREAD

**Issue by simarpreetsingh-019** [circleci/circleci-docs#4802]
I am exploring the docs, I am thinking to enhance the readme and other doc files where there are more than 2 pages, because for the instant reading of a particular thing and finding it directly from top of the page will be good and time-saving than opening the doc, scrolling up and down over the whole document to search for it.

I will add a Table of content to docs having lots of info, so that the one will know which content he/she will be seeing in the repo.

An example of what i will do is in screen shot.
![Screenshot (114)](https://user-images.githubusercontent.com/47384034/94999633-4eea8800-05d8-11eb-9cae-e091ab18eaa1.png)

please assign this issue to me.

**Comment by teesloane** [comment]
Hi! Thank you for stating your intention on improving our readability. While we appreciate contributions we are internally working on enhancing readability. There is an active PR on adding a table of contents sidebar (#4542) , which you can monitor or contribute to based on known issues. Thank you for letting us know that this is something we do need to work on.
