### ISSUE TITLE
docker hub auth for circle-provided executors

### ISSUE THREAD

**Issue by drobert** [circleci/circleci-docs#4812]
# Missing Information

A notification email just went out about dockerhub rate-limiting unless the request is from an authorized user. Circle sent this document around to demonstrate how to add dockerhub authentication: https://circleci.com/docs/2.0/private-images/

The documentation covers to executor types:
1. `docker`
2. `machine`

But some executors are pulled in from orbs, e.g. [python default executors](https://circleci.com/developer/orbs/orb/circleci/python#executors-default)

It's not clear for these (e.g. `executor: python/default`) how to specify dockerhub authentication

# Already Looked

- python orb documentation: https://circleci.com/developer/orbs/orb/circleci/python#executors-default
- provided dockerhub auth documentation: https://circleci.com/docs/2.0/private-images/

# Potential Locations

I believe https://circleci.com/docs/2.0/private-images/ is probably the best location

**Comment by rosieyohannan** [comment]
Hi @drobert! Thanks so much for bringing this up. I am going to talk to our engineers and see if I can find out. I will get back to you and update the doc to make it clear 👍

**Comment by rosieyohannan** [comment]
Hi again @drobert. Looks like this is currently not possible but there is work being done on a fix right now so that should be available soon.

**Comment by sportanova** [comment]
Any update on this?
