### ISSUE TITLE
RE: jekyll/_docs/how-cache-works.md

### ISSUE THREAD

**Issue by alexanderkjeldaas** [circleci/circleci-docs#482]
Can you add a section about what is *not cached* - i.e. is there a syntax for explicitly excluding something from the cache?

A use-case is where I have a locally forked version of a `node` module that I don't want to cache in `node_modules` to avoid inconsistencies in the build.

**Comment by felicianotech** [comment]
There isn't a syntax to do this. CircleCI is given specific directories to use for cache, and post the dependencies phase, the cache is stored.

You can always try posting in [CircleCI Discuss](https://discuss.circleci.com) to see if other's have found a way to get around this.
