### ISSUE TITLE
Badge needs explicit reference to master, despite claim that it defaults to a default branch

### ISSUE THREAD

**Issue by matkoniecz** [circleci/circleci-docs#4822]
# Description
> By default, a badge displays the status of a project’s default branch, though you can also display the status of specific branches.

appears to be untrue

# Location
https://circleci.com/docs/2.0/status-badges/

# Steps to Reproduce
Have failing tests in PR (?)

see https://github.com/valhalla/valhalla/pull/2638 https://github.com/valhalla/valhalla/issues/2636#issuecomment-706176582 https://github.com/valhalla/valhalla/pull/2638#issuecomment-706354945

**Comment by rosieyohannan** [comment]
Hey @matkoniecz! Thanks for getting in touch. I have tried to recreate this but for me the badges are working as expected.

Are you saying you had a failing build on a non default branch, and that was causing the status badge in the readme to display "failed"  using the standard example described here: https://circleci.com/docs/2.0/status-badges/#generating-a-status-badge ?

**Comment by matkoniecz** [comment]
> you had a failing build on a non default branch, and that was causing the status badge in the readme to display "failed" using the standard example described here

Yes. It is apparently not always happening, but it happened in linked case and was also happening with some other "your build is failing according to readme badge" issues that I reported.

**Comment by rosieyohannan** [comment]
Hi @matkoniecz as we're having trouble recreating this, I'm going to close this issue for now but if you find it happen again would you mind reopening? Thanks! :-D

**Comment by matkoniecz** [comment]
> would you mind reopening

Note that people without special rights cannot reopen issues closed by maintainers (I will probably open a new issue if I will spend time again on tracking down what went wrong)
