### ISSUE TITLE
branches key parent is unclear or misleading

### ISSUE THREAD

**Issue by aereal** [circleci/circleci-docs#4828]
# Locations

[Configuration reference (in Japanese translation)](https://circleci.com/docs/ja/2.0/configuration-reference/)

# Details

Configuration reference in Japanese translation puts `branches` key at samel level of `filters` key, but `branches` key must be in under `filters` key.
Also `branches` section mentions nothing about parent key.
These may mislead us that `branches` key should be appeared in as siblings of `filters` or other keys.

[Configuration reference in English](https://circleci.com/docs/2.0/configuration-reference/#branches-2) does correctly.

**Comment by rosieyohannan** [comment]
Hmmm this is odd. Looks like `branches` is hidden from the TOC in the English version using `{:.no_toc}`, but this isn't working in the translated version for some reason. I'll try to find out what's going on! Thanks so much for flagging this issue @aereal

**Comment by rosieyohannan** [comment]
@teesloane or @thomasr8 could you take this? I've added a note about what the issue is but not sure I'll get to it.
