### ISSUE TITLE
RE: jekyll/_docs/continuous-deployment-with-heroku.md

### ISSUE THREAD

**Issue by tobiasmcnulty** [circleci/circleci-docs#483]
At the moment, on BOTH the 12.04 and the 14.04 images, calling `heroku run` manually from your deployment script (as suggested in the docs: https://circleci.com/docs/continuous-deployment-with-heroku/) prompts you for your credentials (thereby hanging indefinitely).

I have my Heroku API key set in my Circle CI account and I even tried refreshing it with a newly generated key, to no avail.

**Comment by felicianotech** [comment]
Referenced PR will update documentation with proper instructions. I've also opened up an internal ticket to see if we can have Heroku creds available to the build for "standard" deploys in addition to "Heroku" deploys.
