### ISSUE TITLE
Instructions (steps and screenshots) to create a Bitbucket user key pertain to the old/legacy UI

### ISSUE THREAD

**Issue by yaningo** [circleci/circleci-docs#4830]
# Missing Information
How to create Bitbucket user keys in the new UI. (The current instructions apply to the legacy UI.)

# Already Looked
https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-bitbucket-user-key

# Potential Locations
Not located anywhere else. Documentation needs to be updated to be consistent with the new UI.

**Comment by michizhou** [comment]
@yaningo I have just submitted a new PR with updated instructions and screenshots for the creation of Bitbucket user keys. If there are any additional changes or modifications that need to be made, please let me know.

**Comment by michizhou** [comment]
@yaningo I have restored the legacy UI instructions for creating the Bitbucket user key, including them in addition to the instructions for users of the new UI for maximum accessibility. Please let me know if additional changes are needed.

**Comment by rosieyohannan** [comment]
> Thanks for the contribution, @michizhou!
> 
> I think we still need to have **instructions for both the legacy UI and the new one** because for now, CircleCI server still uses the former

I recommended removing the legacy UI info because server only supports GitHub and GitHub Enterprise right now :-)

**Comment by yaningo** [comment]
Good point, @rosieyohannan! I completely missed that.

Sorry about the extra work, @michizhou. You were right from the start!

**Comment by thomasr8** [comment]
@yaningo & @michizhou : Is there anything else that I should work on for this issue before closing it? Since @rosieyohannan is on leave right now, I am trying to close old issues for her. Thanks 👍

**Comment by thomasr8** [comment]
This seems to have been resolved with another GH issue (#4865), so I am going to close this issue.

**Comment by yaningo** [comment]
@thomasr8 Sorry I completely missed your update to this GitHub issue. I just left a comment in the (now closed) PR.
