### ISSUE TITLE
Will workflows fail when I run out of credits?

### ISSUE THREAD

**Issue by pickleshy** [circleci/circleci-docs#4834]
# Missing Information
I am looking for information about whether CircleCI workflow tests will continue to function after running out of credits. My organization is on the free plan, and some of our commits recently failed the tests. I looked at our CircleCI dashboard and found that we went over our credit allotment this week (which I wasn't aware could happen – nor did I receive a notification about this). I am trying to figure out whether running out of credits can cause the workflow tests to fail, and generally, what else will not function when we run out of credits. This will help me debug our errors and also determine if/when to upgrade our plan.

# Already Looked
I looked for information on these pages:
- https://circleci.com/docs/2.0/faq/#billing
- https://circleci.com/docs/2.0/credits/
- https://circleci.com/docs/2.0/workflows
- https://circleci.com/docs/2.0/faq/#credit-usage-plans

# Potential Locations
I would expect to find this information on the two pages listed above, specifically in the "What happens when I run out of credits?" section of the billing page: https://circleci.com/docs/2.0/faq/#what-happens-when-i-run-out-of-credits

**Comment by rosieyohannan** [comment]
Hey @pickleshy! Thanks for getting in touch. I have checked with engineering and yes, once you have run out of credits on the free plan, jobs will fail to run. I'm updating our plans and pricing FAQ to reflect this in: #4867 ... Let me know if I can help you further! ☺️

**Comment by pickleshy** [comment]
Looks clear now on https://circleci.com/docs/2.0/faq/#what-happens-when-i-run-out-of-credits, thank you!
