### ISSUE TITLE
Old Insights screenshot in Test Metadata Docs

### ISSUE THREAD

**Issue by mvxt** [circleci/circleci-docs#4856]
# Locations
https://circleci.com/docs/2.0/collect-test-data/

# Details
We're still using a screenshot of the old Insights in the Collecting Test Metadata doc.

**Comment by rosieyohannan** [comment]
Hey @mvxt, this has been left in as it's still used by Server customers. We could try separate out the Server/Cloud sections more if you feel it's a confusing read. It's not ideal I know :-/

**Comment by mvxt** [comment]
Ah, that explains it. If that's the case then maybe just adding a simple image caption might clarify
