### ISSUE TITLE
Search results not pinned to orb tab

### ISSUE THREAD

**Issue by dsayling** [circleci/circleci-docs#4857]
# Description
When you search for a term and select the orbs tab/results, you can immediately scroll up. I would imagine that selecting orbs would remove the other results. Scrolling between the two tabs seems odd (maybe that's me)

# Location
https://circleci.com/docs/?documentation%5Bquery%5D=node.js#search-results-orbs

# Steps to Reproduce
search for something (link above), select orbs, scroll up

**Comment by teesloane** [comment]
Definitely a valid point! Thanks for raising this. CC @tfe .

**Comment by teesloane** [comment]
This has since been fixed in https://github.com/circleci/circleci-docs/pull/5036
