### ISSUE TITLE
Disable checks and Enable checks are not the same thing.

### ISSUE THREAD

**Issue by pboling** [circleci/circleci-docs#4871]
# Missing Information
TL:;DR - In order to enable checks I had to follow some of the instructions to disable checks, and this is bass ackwards.

I needed to figure out how to _enable_ checks on my projects.  They were already partially enabled it seemed, but on runs that required approval before a deploy (which is nearly all runs!) the status checks for the pre-approval steps never get reported as passed in the main PR view.  They do show as "success" in the workflow view on github, but that's not very useful, because it is the main view "success" that constrains the availability of the "Green Merge" button.

The documentation for how to _enable_ checks appears to have documentation *only* for steps that have *already been done* and which were *not enough* to get it working.

https://circleci.com/docs/2.0/enable-checks/

The documentation on the same page for how to _disable_ checks actually has a set of instructions that are half telling how to _disable_, and half telling how to _enable_ (see screenshot attached).

Following [step 5 here](https://circleci.com/docs/2.0/enable-checks/#steps-1), ensuring "Github Status Updates" is set to "On" is what I needed to do.  Note: It doesn't make any sense to set status updates to "On" in the section describing how to turn them "Off".  The whole page needs to be reworked as it doesn't make any sense.

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

https://circleci.com/docs/2.0/enable-checks/
https://circleci.com/docs/2.0/enable-checks/#steps-1

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.

https://circleci.com/docs/2.0/enable-checks/

![Screen Shot 2020-10-23 at 5 35 57 PM](https://user-images.githubusercontent.com/19505/97056214-a9c32f80-1545-11eb-9961-3527001202ed.png)

**Comment by rosieyohannan** [comment]
Thanks so much for raising this @pboling. I'm working on improving this page and will update here once it's done 😄
