### ISSUE TITLE
GitHub Deploy vs User Keys

### ISSUE THREAD

**Issue by haikusw** [circleci/circleci-docs#4881]
# Location
https://circleci.com/docs/2.0/gh-bb-integration/#enable-your-project-to-check-out-additional-private-repositories

# Explanation
Wondering why CircleCi can't use multiple Deploy Keys to talk to multiple repos (this is the implication but not explicitly stated in this document - hence the "unclear documentation" tag).
It seems like security would be better and since talking to multiple repos is getting more and more common multiple deploy keys would be a good thing to support.

**Comment by thomasr8** [comment]
Hello @haikusw : Thank you for the feature suggestion. I will reach out to the Engineering team to see about adding this feature in a future release.
