### ISSUE TITLE
incorrect orb name template in orb-concepts and using-orbs pages.

### ISSUE THREAD

**Issue by irajtaghlidi** [circleci/circleci-docs#4883]
# Locations
https://circleci.com/docs/2.0/orb-concepts/#jobs
and
https://circleci.com/docs/2.0/using-orbs/#jobs

# Details
The orb name is incorrect template, it should be start with `<namespace>` and next with `<orb>` name, like:
```
orbs:
    <orb-name>: <namespace>/<orb-name>@1.2.3
```

But, it's in this wrong format now:
```
orbs:
  <orb>: <orb>/<namespace>@x.y #orb version

```

**Comment by rosieyohannan** [comment]
Fixed in #4884
