### ISSUE TITLE
Using images from AWS ECR requires certain IAM permissions

### ISSUE THREAD

**Issue by mvxt** [circleci/circleci-docs#4889]
# Missing Information
When pulling images from AWS ECR, the user will require at least ECR read permissions. It'd be helpful to just include this quick note in our docs/examples for using custom images from AWS ECR. We can additionally link to [AWS documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly).

# Already Looked
[Using Docker Authenticated Pulls](https://circleci.com/docs/2.0/private-images/#section=configuration). 

# Potential Locations
Would expect it in the same page as above: [Using Docker Authenticated Pulls](https://circleci.com/docs/2.0/private-images/#section=configuration).

Suggested content:

**Note:** In order for CircleCI to pull images from AWS ECR, the IAM user will require at least AmazonEC2ContainerRegistryReadOnly permissions. For more details, see the [AWS documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly).

**Comment by rosieyohannan** [comment]
FYI connected issue here: #4165

**Comment by mvxt** [comment]
@rosieyohannan You could close this issue as a duplicate of #4165. This issue was opened on behalf of a customer who voiced the same concern
