### ISSUE TITLE
Job Status Badges feature idea

### ISSUE THREAD

**Issue by suculent** [circleci/circleci-docs#4892]
It would be nice to allow tying status badges to specific job. 
E.g. in testing workflows this would allow running more test builds in parallel and display status of each job separately.

**Comment by rosieyohannan** [comment]
Hey @suculent! Would it be ok for you to add your idea here so it's visible to the relevant engineering teams? https://ideas.circleci.com/cloud-feature-requests 😄

**Comment by keyguru** [comment]
Sure, done. Thanks.
