### ISSUE TITLE
API V1.1 documetation no up-to-date ?

### ISSUE THREAD

**Issue by xakraz** [circleci/circleci-docs#4902]
# Locations

https://circleci.com/docs/api/v1/#circleci-v1-api-overview

# Details

In many endpoint (if not all, I didn’t check them all), the `:username` URI parameter is not valid anymore …

Documentation: https://circleci.com/docs/api/v1/#summary-of-api-endpoints

```
/project/:vcs-type/:username/:project
```

Tests
```
curl -v -X GET "https://circleci.com/api/v1.1/project/github/xakraz/ORG_NAME/REPO_NAME?circle-token=XXXXXXXXXXX


...
> Host: circleci.com
> User-Agent: curl/7.67.0
> Accept: */*
> 

* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/html;charset=utf-8
< Date: Wed, 04 Nov 2020 09:55:09 GMT
```

Rather:

```
curl -v -X GET "https://circleci.com/api/v1.1/project/github//ORG_NAME/REPO_NAME?circle-token=XXXXXXXXXXX


...
> Host: circleci.com
> User-Agent: curl/7.67.0
> Accept: */*
> 

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: text/plain;charset=utf-8
< Date: Wed, 04 Nov 2020 10:02:23 GMT
```

**Comment by teesloane** [comment]
Yep, username still works. Try formatting your curl requests as per the documentation examples in the[ sidebar of the api reference](https://circleci.com/docs/api/v1/#builds-and-jobs). For example, the following API requests succeeded for me:

```sh
# Fetching a specific build
curl https://circleci.com/api/v1.1/project/github/teesloane/hello-world/1 -H "Circle-Token: xxxxxxxxxxxxxxxxxxxxx"
```


```sh
curl https://circleci.com/api/v1.1/project/github/teesloane/hello-world -H "Circle-Token: xxxxxxxxxxxxxxxxxxxxx"
```

**Comment by xakraz** [comment]
Hi @teesloane ,

Thanks for your reply.

After reading my issue and remembering the way GitHub manages repos (Organizations are "users"), I have tested back my repos and your example and everything is working as expected ...

PEBCAK

` "https://circleci.com/api/v1.1/project/github/xakraz/ORG_NAME/REPO_NAME` -> ` "https://circleci.com/api/v1.1/project/github/ORG_NAME/REPO_NAME`

I thought I had to specify my username but the token act as an ID and Password, so no need to ...

Sorry for the noise and thanks again for your time.

**Comment by teesloane** [comment]
No problem - glad it's working!
