### ISSUE TITLE
Technical problems bug fixes

### ISSUE THREAD

**Issue by Rmkasun-8** [circleci/circleci-docs#4928]
# Description
Describe the bug you found.

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by thomasr8** [comment]
Hi @Rmkasun-8 : Would you be able to point us to the place where you found these errors so we can correct our documentation?

Thank You!
