### ISSUE TITLE
Runner Platform Support is Unclear

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#4934]
Doc: https://circleci.com/docs/2.0/runner-overview/#circleci-runner-limitations

For platform support, it means "Intel +" such as this: `Intel + Ubuntu`

Are we saying then that this wouldn't run on an AMD x86_64 processor? While I'm not 100% positive that it does, I'm fairly sure that it would. Intel doesn't technically own their own 64-bit platform right now so unless we're using Intel specific microcode APIs, amd64 is supported.

**Comment by glenjamin** [comment]
I think we should replace all mentions of `Intel` with `x86_64`, as that's the most commonly used term IME.
