### ISSUE TITLE
agent.circleci.com does not exist

### ISSUE THREAD

**Issue by symbiont-ji** [circleci/circleci-docs#4942]
# Description
agent.circleci.com does not exist. Just trying 

# Location
`https://circleci.com/docs/2.0/runner-api/` claims that the runner api is available at `agent.circleci.com`. However, no such DNS entry exists

# Steps to Reproduce
```
$ host agent.circleci.com
Host agent.circleci.com not found: 3(NXDOMAIN)
```

**Comment by appplemac** [comment]
Thank you - we’re fixing this in #4943 .
