### ISSUE TITLE
Document how runner users can customise the job timeouts and drain timeouts

### ISSUE THREAD

**Issue by appplemac** [circleci/circleci-docs#4945]
# Missing Information

We need to document the following configuration options for runners:

* Setting the max job run time
* Setting the drain timeout
* Relationship between those values

# Already Looked

* https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/runner-faqs.adoc
* https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/runner-installation.adoc
* https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/runner-overview.adoc

# Potential Locations

This needs to be a part of the runner docs.

**Comment by appplemac** [comment]
@glenjamin Does this look right? Anything else we need to include in this update?

**Comment by glenjamin** [comment]
@danmux can you confirm?

We could link up to the equivalent PRs from the preview docs?

**Comment by thomasr8** [comment]
@appplemac and @glenjamin : I will work on this content this week and add it to the Runner documentation.

**Comment by danmux** [comment]
> @danmux can you confirm?
> 
> We could link up to the equivalent PRs from the preview docs?

Drain timeout isn't directly configurable - it is 1 minute longer than `max_run_time` documented here... https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/runner-installation.adoc#runnermax_run_time

**Comment by danmux** [comment]
I did attempt to explain draining when we did have a separately configurable drain period.

https://github.com/CircleCI-Archived/runner-preview-docs/commit/e70f596f8b1638e3be8c924b6396fe5ba0a0c1da#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0R158

Most of that is still accurate.

**Comment by glenjamin** [comment]
ok, so in summary, we should add this section to the `max_run_time` notes

> Launch Agent attempts to gracefully shutdown. On receipt of a `TERM` signal the launch agent will enter 'draining' mode,
> during this time Launch Agent will not accept any new jobs, but will allow any current active job to complete.
> 
> At the end of draining the Launch Agent will signal the Task Agent to cancel any active job (by sending it a `TERM` 
> signal). If the Task Agent does not exit after a brief period Launch Agent will kill it (by sending it a `KILL` signal).
> 
> Draining can end in one of two ways:
> 
> 1. The task has been in the draining state for longer than the configured `max_run_time`.
> 1. A `TERM` signal is received by the Launch Agent during draining.

**Comment by thomasr8** [comment]
Added this content to Installation page, so I am closing this ticket.
