### ISSUE TITLE
Misleading images in approval workflows

### ISSUE THREAD

**Issue by dsayling** [circleci/circleci-docs#4962]
# Locations
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/workflows.md
https://circleci.com/docs/2.0/workflows/#holding-a-workflow-for-a-manual-approval

# Details
The images display approval jobs that appear to actually perform "builds" and "tests", however, these jobs would not actually be performing any steps. These images should be updated to show jobs 'build approval' -> 'build' and 'test approval' -> 'test' or maybe just replace it with the example of 'hold' -> 'deploy' in the config example above these images.

It may also be helpful to remind users that the job doesn't run any steps.

**Comment by teesloane** [comment]
I made a quick mockup-change to make sure I've understood your request. Can you confirm if I am understanding the requisite change?

![update_screenshot_ticket](https://user-images.githubusercontent.com/12987958/101672414-d5ca3f80-3a23-11eb-8c88-c3eb94451261.png)


> It may also be helpful to remind users that the job doesn't run any steps.

By this, do you mean we should state something along the lines of "please note that approval jobs do not have to run any steps and can exist solely for the purpose of pausing the execution of your pipeline" ?

Thanks for the catch + input @dsayling.

**Comment by dsayling** [comment]
This looks great - I think that statement captures my request. Thanks!
