### ISSUE TITLE
Clearer documentation of `circle orb create`

### ISSUE THREAD

**Issue by lucas42** [circleci/circleci-docs#4963]
## Problem

When trying to publish an orb for the first time, my job kept failing with the error message `the '%s' orb does not exist in the '%s' namespace. Did you misspell the namespace or the orb name?`
Searching for this error message didn't give any useful documentation.  It's also difficult to find information on how to create an orb, that's not buried deep in a long tutorial which does loads of other unnecessary stuff at the same time.

## What would have helped

Being able to find documentation which explains I need to run `circleci orb create`.  

(Now that I've worked out the answer, I can search your docs and see it's in step two of https://circleci.com/docs/2.0/orb-author-validate-publish/ - but that page is very difficult to discover and is aimed at publish pipelines happening outside circleci)

## What I ended up doing instead
* Google search for the error message
* Only found 1 result, which was the `circleci-cli` source code
* Worked backwards from the the api in the code, to work out which cli command I needed
* Ran the CLI command which told me about the 'Uncertified Orbs' feature, which I'd somehow missed
* Enabled 'Uncertified Orbs' and re-ran the CLI command

**Comment by teesloane** [comment]
Hi @lucas42 - thanks for sharing your experience using the documentation - sorry it wasn't easier to get to the information a bit faster. We are working on finding ways to make reading and navigating long documents. Do you happen to know if you were you using the [orb development kit](https://circleci.com/docs/2.0/orb-author/#orb-development-kit) originally when creating your command or did you use the "[manual orb authoring process](https://circleci.com/docs/2.0/orb-author-validate-publish/)" that you linked above?

**Comment by lucas42** [comment]
I had a play with the development kit initially, but found it difficult to understand (it created a load of boilerplate config which was a bit overwhelming for me).  Therefore I decided to do it manually.  However, I couldn't find the "manual orb authoring process" doc at that stage (it wasn't listed in the nav or anywhere immediately obvious).  So I ended up cobbling things together from whatever other places I could find (other docs, existing orbs and reading the CLI's source code).

**Comment by teesloane** [comment]
Thanks for the quick, detailed response. We recently re-organized our documentation around the orb-development-kit - and because we want to leverage it as the starting point for most development, it has pushed the manual documentation to the background. It's good to know that some user's will want to take that manual-route and so we will re-integrate these documents into our sidebar in a future PR! For now, I'm going to close this, but will reference it in a PR that re-introduces the change in our sidebar.
