### ISSUE TITLE
RE: jekyll/_docs/test-metadata.md

### ISSUE THREAD

**Issue by chaffeqa** [circleci/circleci-docs#499]
Could you expose the command you use to run django tests using django-nose?  This is because we want to be able to override it simply to change the pwd its run in, but dont know what the command should be

**Comment by felicianotech** [comment]
You should be able to expand that section in your build and see the command. Is this not the case?

**Comment by chaffeqa** [comment]
no, because well... we had to override it  :(

**Comment by felicianotech** [comment]
That's no problem. You can create a quick temp branch, and remove `test:override` from that branche's `circle.yml`.
