### ISSUE TITLE
V2 API Token verbiage does not match actual site

### ISSUE THREAD

**Issue by andysnowden** [circleci/circleci-docs#4995]
# Locations
https://circleci.com/docs/2.0/managing-api-tokens/

# Conflict Description
The documentation for project tokens mentions they can only be "read" and provides the levels as "Status", "Build", "All".  This however does not match the actual values when creating a key at all.  The actual values are "Status", "Read Only", "Admin".  The latter "Admin" implies full access including the ability to start a 2.0 workflow which is not the case.

[image](https://puu.sh/H0AUG/a11e12be99.png)

This is extremely frustrating when trying to automate with the 2.0 API.  This level of support provided by the doc is amazingly unacceptable given the price we have to pay.

**Comment by teesloane** [comment]
Hi there @andysnowden - thank you for reporting the inaccurate information and I apologize that this has made usage difficult. We will update the document to reflect the changes in the UI shortly.

**Comment by teesloane** [comment]
Update: wording has been updated in https://github.com/circleci/circleci-docs/pull/4986. 

As for triggering workflows, it is possible to [trigger a pipeline](https://circleci.com/docs/api/v2/#operation/triggerPipeline). If you do this, you can pass [pipeline parameter](https://circleci.com/docs/2.0/pipeline-variables/#passing-parameters-when-triggering-pipelines-via-the-api) with which it may be possible to conditionally render a workflow. I hope this helps!
