### ISSUE TITLE
Mismatch in line number and contents between the image and learnings 

### ISSUE THREAD

**Issue by nsnikhil** [circleci/circleci-docs#4996]
# Locations
https://circleci.com/docs/2.0/config-intro/#section=configuration

# Conflict Description
The example image for Part One, Part Two, and Part Three do not match the learnings bullet list below each of them. 

eg: 
In Part One, one of the learnings of bullet point is:
Line 6-7: The steps collection is an ordered list of run directives. Each run directive is executed in the order in which it was declared.

but in the image line, 6-7 has the following content:
        auth:
          username: mydockerhub-user

and the same issue occurs through out the part two and three.

**Comment by teesloane** [comment]
Hi @nsnikhil - thanks for the update on this. I will update these example to properly align with the code line-num blocks.
