### ISSUE TITLE
GitHub Events Not Clear

### ISSUE THREAD

**Issue by ghost** [circleci/circleci-docs#5012]
from Twitter

# Description
@circleci
 hey, I couldn't find documentation about all the github events you subscribe to by default, do you have pointers? For example I don't understand why you need to know about the events for comments, or wiki, or watches... ThanksDescribe the bug you found.

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by thomasr8** [comment]
This is already clearly documented in the Server Administration Guide, so no need to duplicate this content elsewhere in the Server documentation.

**Comment by thomasr8** [comment]
Checked with Engineering and there isn't a set of defaults for GitHub Events when a user subscribes.
