### ISSUE TITLE
Is Config enterprise or self hosted

### ISSUE THREAD

**Issue by abretmounet** [circleci/circleci-docs#5013]
# Description

@CircleCI
 is CircleCI config 2.1 supported in enterprise/self-hosted? The documentation doesn't seem to make this clear.

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by thomasr8** [comment]
This is already documented, so no need to duplicate this content elsewhere.
