### ISSUE TITLE
404 Testing Mac OS apps

### ISSUE THREAD

**Issue by abretmounet** [circleci/circleci-docs#5014]
# Description
It's unclear which of your MacOS images have SIP disabled, and when you try to play whackamole to figure it out, the error message links to 404 documentation

"Please choose an image with SIP disabled. Documentation: https://circleci.com/docs/2.0/testing-macos-apps"

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by thomasr8** [comment]
This has already been fixed and a 404 error no longer appears.
