### ISSUE TITLE
Possible inaccuracy when running Rails 5.0.1 (_cci1/test-metadata.md)

### ISSUE THREAD

**Issue by Geesu** [circleci/circleci-docs#502]
```test:
  override:
    - bundle exec rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS/reports":
        parallel: true
        files:
          - test/**/*_test.rb
```

This override fails on rails 5.0.1 (minitest 5.10.1) with:

```'plugin_rails_options': invalid option: --ci-dir=/tmp/circle-junit.G7A8BX3/minitest (OptionParser::InvalidOption)```

**Comment by ryanwohara** [comment]
This should be solved in 2.0.
