### ISSUE TITLE
explicitly passing AWS credential

### ISSUE THREAD

**Issue by neeleshhenkel** [circleci/circleci-docs#5033]
Trying to pass the AWS credential explicitly as I use the same yaml to deploy to dev and prod which are separate accounts.
 aws-ecs/deploy-service-update:
          name: deploy-2-prod
          requires:
            - deploy-2-staging
          aws-access-key-id: PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: PROD_AWS_SECRET_ACCESS_KEY
          force-new-deployment: true
          verify-revision-is-deployed: true
          family: "${SERVICE_NAME}" # task name
          service-name : "${SERVICE_NAME}" # service name
          cluster-name: "app2-cluster" 
          container-image-name-updates: "container=${SERVICE_NAME},tag=${CIRCLE_SHA1}"

Not working. It still takes the keys form the CircleCI env variables :
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY.

Please help.

**Comment by thomasr8** [comment]
@neeleshhenkel : Hi. I will work with Engineering to find a resolution for your issue. Thank you for bringing this issue to our attention.

**Comment by neeleshhenkel** [comment]
@thomasr8 thanks for the response. In the meantime, I have figured it out to pass different credentials using CircleCI context. 
 - aws-ecs/deploy-service-update:
          **context: prod**
          name: deploy-2-prod
          requires:
            - deploy-2-staging
          force-new-deployment: true
          verify-revision-is-deployed: true
          family: "${AWS_ECS_CLUSTER_NAME}-${SERVICE_NAME}" # task name
          service-name : "${SERVICE_NAME}" # service name
          cluster-name: "${AWS_ECS_CLUSTER_NAME}-cluster"
          container-image-name-updates: "container=${SERVICE_NAME},tag=${CIRCLE_SHA1}"

**Comment by thomasr8** [comment]
Hi @neeleshhenkel : Thank you for the update. I am happy you found a workaround, but I am going to work with the team to update our documentation accordingly.

**Comment by neeleshhenkel** [comment]
@thomasr8 that'd be great coz many would have the same problem if they try to deploy to a separate AWS account. Using context is the right way to solve.
