### ISSUE TITLE
RE: jekyll/_docs/rspec-exit-codes.md

### ISSUE THREAD

**Issue by EstelleQ** [circleci/circleci-docs#505]
Rspec runs pass ,but CircleCi fails ,how can I debug?

**Comment by felicianotech** [comment]
Hi,

This is something that should be posted in https://discuss.circleci.com not a CircleCI Docs GitHub Issue. You'll be able to find help there. I'd also suggest trying to provide any error messages, `circle.yml` snippets, or anything else that you could provide that provides context.
