### ISSUE TITLE
Add section describing troubleshooting steps for debugging upstream image issues

### ISSUE THREAD

**Issue by nbialostosky** [circleci/circleci-docs#5058]
# Missing Information
There are situations where a customers build will start to fail without any change on their end. Usually, when this happens it's from an upstream change or issue either within their docker image they are using or their dependencies.

We don't have any information currently about debugging these type of issues or identifying when its an issue with the image vs. an issue with CircleCI. It would be helpful if we had some best practices/next steps for these situations.

# Already Looked
https://circleci.com/docs/2.0/executor-types/#using-docker

# Potential Locations
Likely here:

https://circleci.com/docs/2.0/executor-types

Since you can technically use docker images in places other than docker executor (like remote docker on machine images) it may be a good section that covers all the executors.

**Comment by teesloane** [comment]
Hey @nbialostosky - do you think [these proposed changes](https://github.com/circleci/circleci-docs/pull/5137) sufficiently describe what you've put forward?
