### ISSUE TITLE
Clarify extra steps required to get started with Google Cloud (_cci1/google-cloud-platform.md)

### ISSUE THREAD

**Issue by choliver** [circleci/circleci-docs#506]
This documentation doesn't really get one started.  I've spent the last two hours going round in circles trying to figure out what magical combination of roles, service-account permissions, key configurations, etc. are required to enable that `gcloud compute copy-files` example to actually work, and am still not done.  I realise this is largely the fault of the sub-optimal GCloud docs, but it would be great if you guys could commoditise this.

~~(Once I've finally figured it out I'd be happy to contribute something more constructive than this rant!)~~

### Update

Ok, these seem to be the missing things required to get `gcloud compute copy-files` to work:

1. Ensure the service account has the [`roles/compute.instanceAdmin` role](https://cloud.google.com/compute/docs/access/iam).  (It may be possible to lock this down further, or tie to it the instance being targeted, but Google's docs are terrible :( )
2. Generate a dedicated key-pair, and cache it.  (Otherwise `copy-files` [will generate](https://cloud.google.com/compute/docs/instances/connecting-to-instance#generatesshkeypair) and register a new one for each build!)  Possible CircleCI feature-request is for the ability to register SSH keys to files other than the default `id_rsa`.

    ```
     dependencies:
      pre:
        - if [ ! -e ~/.ssh/google_compute_engine ]; then ssh-keygen -f ~/.ssh/google_compute_engine -N ""; fi
      cache_directories:
        - ~/.ssh

3. Explicitly specify the zone, e.g. `gcloud compute copy-files --zone ${GCLOUD_ZONE} ...`.  Otherwise one receives an interactive prompt.

4. Explicitly specify the user e.g. `gcloud compute copy-files ... ${SERVICE_ACCOUNT_NAME}@${TARGET_VM}:${DEST}`.  Otherwise it attempts to SSH as the current user (`root` here, given the use of `sudo`).

**Comment by smart-alek** [comment]
@choliver this is extremely helpful; thanks for putting in the hours to figure out how this works! We're working our way through these issues, and I'll be incorporating your changes by EOM.

Thanks again!

**Comment by sha1sum** [comment]
FYI: Documentation has been PR'd for 2.0 GKE deployment. It does not address everything in this issue, but for those looking for 2.0 documentation, it will likely assist. I did also include the necessary commands for `compute/zone` configuration.
