### ISSUE TITLE
RE: jekyll/_docs/docker.md

### ISSUE THREAD

**Issue by kommunicate** [circleci/circleci-docs#512]
The section titled "Connecting to services outside of the container" has a code snippet that uses Postgres v9.4, which is no longer present. Both v9.5 and v9.6 seem to be on there, so it's not clear which one should be used. It would be nice if there was something a little handier to use here. I ended up solving this problem by copying to both the 9.5 and 9.6 versions since I wasn't sure which one would get used.

**Comment by felicianotech** [comment]
In the referenced PR, the example was updated to Postgres v9.5, which is what the default image, Ubuntu 14.04 uses.

This Issue will close automatically when the referenced PR gets merged. Thank you.
