### ISSUE TITLE
Add new requirement re: Code Climate (_cci1/code-coverage.md)

### ISSUE THREAD

**Issue by leonelgalan** [circleci/circleci-docs#514]
Newer versions of the _codeclimate-test-reporter_ gem require us to manually call `bundle exec codeclimate-test-reporter` after the tests are run to send the results to Code Climate. Simply setting _CODECLIMATE_REPO_TOKEN_ is no longer enough.

See https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03 for details.

**Comment by ryanwohara** [comment]
Somewhat addressed in https://github.com/circleci/circleci-docs/pull/1614

**Comment by leonelgalan** [comment]
"Somewhat addressed" it's a stretch, why not fix the links and improve documentation rather than remove it? Am I in the minority using Code Climate with Circle CI?
