### ISSUE TITLE
Clarify usage of Accept header for API requests

### ISSUE THREAD

**Issue by fernfernfern** [circleci/circleci-docs#5159]
# Missing Information
We received a report about an issue when  interacting with our API in [this forum post](https://discuss.circleci.com/t/api-v2-malformed-json-bodies-returned-on-400s/39393). The heart of the issue is that when users make API calls the response content-type header is set to text, but all the APIs return JSON. This can cause some tools to break when the content type doesn't match the content.

After discussion with engineering it looks like that behavior is expected, and users should add the `Accept: application/json` header to their requests for the content-type header to be set correctly on the response.

It looks like [this information was included in an overview section](https://circleci.com/docs/api/v1/#accept-header) of the v1 docs. But there's no similar overview section [for our v2 docs](https://circleci.com/docs/api/v2/), which is where I originally looked when trying to learn more about this. I didn't notice it in the v1 docs until I did some searching on the repo here. I see that we do include the Accept header usage within the examples [in our current developer API guide](https://circleci.com/docs/2.0/api-developers-guide/), but there's no similar explanation to the significant of it as there is in the v1 docs.

I'm just raising this as an issue for now as i'm not sure the best way to approach this. But my initial thoughts are that it would be good if there was an "overview" section above the "authentication" section in the v2 docs, to be more inline with our v1 docs with providing this information. As well as including it in the current developer API guide. Since both of these are more current documentation points users are likely to encounter.

Happy to submit an initial PR with those changes if it would be helpful.

# Already Looked
https://circleci.com/docs/api/v2/

# Potential Locations
https://circleci.com/docs/api/v2/
https://circleci.com/docs/2.0/api-developers-guide/

**Comment by teesloane** [comment]
Hi @fernfernfern - thanks for bringing attention to this. I think we could probably find a way to integrate this information into the final api reference guide (at docs/api/v2). The content for this guide is all generated from a [spec](https://circleci.com/api/v2/openapi.json) -- if the API team can find a place for that information in the spec we should add it there; if not, we will want to update the api-developer's guide (actually, we may wish to make note of it in the api-developer's guide anyway so I will look into that in the meantime).
