### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by nibbl** [circleci/circleci-docs#5203]
https://circleci.com/docs/2.0/artifacts/?section=pipelines#description-of-commands

_First, the CIRCLE_TOKEN environment variable is created. Then, the curl command fetches all artifact details for a build and pipes them to grep to extract the URLs. Using sed your circle token is appended to the file to create a unique file name. Finally, wget is used to download the artifacts to the current directory in your terminal.

But I don't see any sed using in the examples, looks like deprecated info

**Comment by teesloane** [comment]
Thanks @nibbl  - yep, this looks like out of date info from a previous code sample. I'll patch this up and notify when merged in.

**Comment by teesloane** [comment]
I'm running into this issue too. I think there might be a bug here, as my curl request is returning an empty array as well. I have mentioned it internally to see if we can sort it out or if there might be an issue with our docs. Sorry for the inconvenience!

**Comment by nibbl** [comment]
Thank you, let me know when something change

**Comment by teesloane** [comment]
Ok, so I've got this curl request working:

```
export CIRCLE_TOKEN=<my token>

    curl -H "Circle-Token: $CIRCLE_TOKEN" --request GET \
    --url https://circleci.com/api/v1.1/project/gh/circleci/circleci-docs/latest/artifacts
```
    
  which returns:
  
  ```
  [ {
  "path" : "circleci-docs",
  "pretty_path" : "circleci-docs",
  "node_index" : 0,
  "url" : "https://77577-48750547-gh.circle-artifacts.com/0/circleci-docs"
} ]
```

I'm not sure what might be wrong, but could it be that your url, which has `myproject/frontend/latest/artifacts`, should replace <myproject> with <your_github_username>?

**Comment by nibbl** [comment]
Hello, I'm sorry, I did debug my script and realized that my script request artifacts from JOB that doesn't contain artifacts, API endpoint not broken.
Excuse me, please.

But for a better explaining, I can send PR that change the documentation part "Downloading all artifacts for a build on CircleCI" to define the build as a job, not a pipeline, because this confused me and can confuse others.

**Comment by teesloane** [comment]
No problem! Glad you were able to fix the issue. We love contributions - if you are comfortable making a pull request please do! If not, I think I know what needs to change (`build` -> `job` terminology change). Thanks!

**Comment by nibbl** [comment]
Okay, I will do PR within a few days, thanks
