### ISSUE TITLE
Not passing parameters correctly for newman testing in CircleCI

### ISSUE THREAD

**Issue by leirhyh72** [circleci/circleci-docs#5219]
# Description
When we were testing API collections in Postman by newman, both testing in Postman and Newman worked fine for passing.
parameters.  However, when we tried the same testing in CircleCI, we got issues for passing parameters.  It appeared to be unable to read parameters in body in CircleCI.
sample body parameters in Postman is as follows:
{
	"completeness": "Complete",
    "side": "Left",
    "designator": "123",
    "key1": "ABC 2021-115",
    "key2": "ABC 2021-114-I-220",
	"identification_date": "01-01-2021",
	"remains_status": "Released",
	"remains_release_date": "02-02-2021"
}

The errors in CircleCI is as follows:
 ┌
  │ { message: 'The given data was invalid.',
  │   errors:
  │    { key1:
  │       [ 'The accession number field is required.' ],
  │      designator: [ 'The designator field is required.'
  │  ],
  │      side: [ 'The side field is required.' ],
  │      completeness: [ 'The completeness field is requir
  │ ed.' ] } }

**Comment by teesloane** [comment]
Hi there! I'm not super familiar with Newman and haven't used Postman for a while so you may have to bear with me for a bit. Are you using the [newman orb](https://circleci.com/developer/orbs/orb/postman/newman) or running it manually in your configuration? Are you able to share your config.yml (or the portion using Newman) here?

**Comment by leirhyh72** [comment]
Hi there,
I did use newman orb and please see config.yml as follows:
parameters in body from collection now pass correctly.
Thanks and I appreciate your time.

All the best,

Runhua

version: 2.1
orbs:
  newman: ***@***.***
jobs:

  test-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./'test - API.postman_collection.json'
          environment: ./Testing.postman_environment.json




workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-collection-run
________________________________

**Comment by teesloane** [comment]
> parameters in body from collection now pass correctly.

It sounds like things are working correctly, then! Please feel free to re-open if that is not the case.
