### ISSUE TITLE
RE: jekyll/_docs/language-go.md - private dependancies

### ISSUE THREAD

**Issue by yoiang** [circleci/circleci-docs#522]
I have a number of projects that use shared private dependancies we own and fail when they cannot access them (even though they are also each being built by CircleCI). It would be great to have an explanation of how to set up access!

**Comment by felicianotech** [comment]
You'd need to use [User Keys](https://circleci.com/docs/github-security-ssh-keys/#security) in order for `git clone` on CircleCI to have permission to pull the private repos.

Please respond back here if you feel this information still doesn't help you enough.

**Comment by yoiang** [comment]
That was super helpful, thank you! Because git repo access is so well integrated with golang it may be helpful to add these links to golang support documentation!
