### ISSUE TITLE
Built-in variables do not appear to be working, e.g. CIRCLE_BUILD_NUM

### ISSUE THREAD

**Issue by gmike11** [circleci/circleci-docs#5225]
# Description
I've tried referencing the built-in variable CIRCLE_BUILD_NUM in a variety of ways in my config.yml file, but nothing has worked, so far. I tried $CIRCLE_BUILD_NUM, ${CIRCLE_BUILD_NUM}, %CIRCLE_BUILD_NUM%.

I'm using a win/default executor, if that helps.

What have I missed?

Thanks.

**Comment by thomasr8** [comment]
Hello @gmegidish : I am going to reach out to the Engineering team to see how we can unblock you. I will post in this thread when I have input from Engineering.

**Comment by gmike11** [comment]
Figured it out.

Needed to prefix the variable with 'env', e.g. $env:<variable-name>.
________________________________

**Comment by thomasr8** [comment]
@gmike11 : Thank you for the update. Please feel free to reach out to us if you have any more issues.
