### ISSUE TITLE
Automatic test balancing for Java + maven project

### ISSUE THREAD

**Issue by igor-dmitriev** [circleci/circleci-docs#523]
Hi. I found your article how to configure automatic test balancing for ruby, but how can I do it for Java project?
here is my circle.yml:
test:
  override:
    - mvn integration-test:
      parallel: true
  post:
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

But it runs ALL tests (does not split) in parallel on different instances. But I wanna have this smart automatic test balancing that based on test reports. What should I add to make it works?? Thank you in advance

**Comment by smart-alek** [comment]
Hey @igor-dmitriev! This is a great question to pose on our [Discuss](https://discuss.circleci.com/) forums. You can get answers from other users or our support staff.

Hope you got or will get your answer there! :)
