### ISSUE TITLE
Server 2.19 to 3.0 transition with pipelines unclear

### ISSUE THREAD

**Issue by lloydChris** [circleci/circleci-docs#5239]
When a server customer migrates from 2.19 to 3.0 they are directed to this page: https://circleci.com/docs/2.0/build-processing/#transitioning-to-pipelines when viewing projects that had jobs run before pipelines were enabled:
![image](https://user-images.githubusercontent.com/12780493/114422855-df9bb500-9b73-11eb-8905-f4d4709e3d1d.png)

It seems like an action is required for the user, but I am not sure what it is.  Also I don't know why I care about the environment variable `CIRCLE_COMPARE_URL` .

Also from a strictly server perspective, 3.0 is compatible with 2.0 configs so that should be noted.

**Comment by rosieyohannan** [comment]
@lloydChris do you know if pipelines are auto enabled - or maybe the enable pipelines switch isn't even available anymore - for 3.0 server installs?

**Comment by lloydChris** [comment]
Pipelines are always enabled in server 3

**Comment by rosieyohannan** [comment]
I'm uncertain what to do with this issue. @circleci/server Is this still the message presented to migrating customers? Is this to do with jobs in reality check not using config verison 2.1 or something maybe?

**Comment by ryanwohara** [comment]
@rosieyohannan (I could be wrong but) I think the issue here is that jobs that are migrated over are not pipelines. The 2.x systems didn't have a concept of the 2.1 config or pipelines - everything was a workflow. To view past jobs you need to go to the legacy jobs view.

It's possible we already documented this since the issue was filed in April

**Comment by SarawutAutchan** [comment]
😀😀

ในวันที่ พฤ. 9 ธ.ค. 2021 เวลา 20:53 ryanwohara ***@***.***>
เขียนว่า:
