### ISSUE TITLE
Language links are broken

### ISSUE THREAD

**Issue by jasonkarns** [circleci/circleci-docs#5254]
# Description

The language-specific deep-links are broken within the document here: https://circleci.com/docs/2.0/circleci-images/?section=executors-and-images#legacy-language-images

![image](https://user-images.githubusercontent.com/119972/115303466-aba32f80-a131-11eb-981c-54a441e30f26.png)

Each of those language names is linked like: `#ruby`

But the language-specific headers are anchored as `#image1name` (For instance, the full `Ruby` header anchor is: https://circleci.com/docs/2.0/circleci-images/?section=executors-and-images#image1name which is not only wrong, it's also duplicated for _all_ of the language headers.

# Location
https://circleci.com/docs/2.0/circleci-images/?section=executors-and-images#legacy-language-images

**Comment by teesloane** [comment]
Thanks for catching this @jasonkarns . This is due to a new markdown linting process used for translating our docs that auto-assigns header-ids. I'll fix this up.
