### ISSUE TITLE
Run multiple laravel dusk test in CircleCI

### ISSUE THREAD

**Issue by leirhyh72** [circleci/circleci-docs#5262]
Hi all,
I was able to setup and run single task. I have 100s of laravel dusk tests needed to run in Circleci.
I put the following three runs, however, it only runs the first one. Do you happen to know a way to run the following three in the same job, for example, test-ui-run ? If so, could you share how you did it?
Thanks and I appreciate it.

All the best,

Runhua

  - run:
      name: Laravel dusk test run
      command: php artisan dusk --group=groupBrowerA
      environment:
        APP_URL: https://cora-vuetify-dev.herokuapp.com
  - run:
      name: Laravel dusk test run
      command: php artisan dusk --group=groupBrowerB
      environment:
        APP_URL: https://cora-vuetify-dev.herokuapp.com
  - run:
      name: Laravel dusk test run
      command: php artisan dusk --group=groupBrowerC
      environment:
        APP_URL: https://cora-vuetify-dev.herokuapp.com
My yml file is as follows:
version: 2.1
orbs:
newman: postman/newman@0.0.2
jobs:
test-ui-run:
docker:
- image: circleci/php:7.4-node-browsers

steps:
  - checkout

  - run:
      name: "Prepare Environment"
      command: |
        sudo apt update
        sudo docker-php-ext-install zip

  - run:
      name: "Create Environment file"
      command: |
        mv .env.dusk.testing .env

  - run:
      name: "Install Dependencies"
      command: composer install --ignore-platform-reqs

  - save_cache:
      key: v1-dependencies-{{ checksum "composer.json" }}
      paths:
        - ./vendor

  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "composer.json" }}

  - run:
      name: Update Chrome Driver
      command: php artisan dusk:chrome-driver 72

  - run:
      name: "Install Dusk and Update Chrome Drivers"
      command: php artisan dusk:install

  - run:
      name: Start Chrome Driver
      command: ./vendor/laravel/dusk/bin/chromedriver-linux
      background: true
#how can I run multilple tests????
- run:
name: Laravel dusk test run
command: php artisan dusk --group=groupBrower
environment:
APP_URL: https://cora-vuetify-dev.herokuapp.com

  - store_artifacts:
      path: tests/Browser/screenshots
workflows:
version: 2
test:
jobs:
- test-ui-run

**Comment by teesloane** [comment]
Hi @leirhyh72, can you please edit your original post to group your code blocks using [code fences](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) for easier readability?

Based on the information you provided, I'm not sure if you need to split your tests in parallel (in which case you can consult our [section on splitting tests using the CircleCI CLI](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-test-files). It sounds like [workflows](https://circleci.com/docs/2.0/workflows) might also be useful for you.
