### ISSUE TITLE
Pre Built CCI Docker Images

### ISSUE THREAD

**Issue by Confiance** [circleci/circleci-docs#5272]
Identified in Apr 26, 2022 DevHub meeting as in need of updates for Q2. https://circleci.com/docs/2.0/circleci-images/

**Comment by christinanguyen332** [comment]
I'd like to add more background to this ticket.  Presently ~60% of our convenience images usage are legacy images. We'd like to decrease this number by encouraging legacy image users to upgrade to next-gen images. Also, for new users to start their configurations using next-gen images. Approx 4k users visit this (Pre-Built CCI Docker Images) page every month. Through usability tests, we've found that most people do a control-F to find the image they're interested in using. Unfortunately, this usually results in one of the legacy images. We should consider moving the legacy images off to a different page.

**Comment by teesloane** [comment]
@christinanguyen332 Thanks for voicing your thoughts here. I'm not sure if we would immediately want to move content, without looking at how the content could be re-arranged first. I think we could first try and improve the wording on promoting the next-gen images and discouraging use of legacy images. I've started on this by reducing the repetition in the document and removed some redundant headings.  I've also attempted hiding the tags under a "details' html tag:

-----

<img width="696" alt="Screen Shot 2021-05-05 at 3 32 43 PM" src="https://user-images.githubusercontent.com/12987958/117198672-4d27b380-adb7-11eb-9c3b-8639036f4680.png">

-----

You can see a preview of the proposed alterations to the page [here](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/fix-5272-preview/2.0/circleci-images/).

**Comment by christinanguyen332** [comment]
I agree with your feedback, let's not necessarily remove any of the content, at least immediately.  Is it possible in addition to reducing the repetition, removing redundant headings, and hiding tags, can we consider re-ordering - specifically moving the Legacy language images below the Next-gen language images? At least if users do a control-F on a language image, they'll first be brought to the next-gen image before the legacy ones.

**Comment by teesloane** [comment]
Certainly, I think it makes sense at this point to re-order next-generation above legacy images! right now the two are woven together in each section, so I will split that up and re-organize.

**Comment by christinanguyen332** [comment]
Thanks so much! I think with all of the proposed changes, I think we'll get a little bit closer to encouraging at least new users to use next-gen images. This may actually be a good data point to look into/ track - % of new users using legacy vs next-gen images. Thanks again!

**Comment by teesloane** [comment]
I've merged in https://github.com/circleci/circleci-docs/pull/5392 which makes some incremental improvements on the CCI images page. Happy to move forward with larger changes in the future too!
