### ISSUE TITLE
List of Available Machine Images Should Include windows-server-2019-vs2019 machine image

### ISSUE THREAD

**Issue by Kurt-von-Laven** [circleci/circleci-docs#5289]
# Missing Information
[The windows-server-2019-vs2019 machine image](https://circleci.com/developer/orbs/orb/circleci/windows#orb-source)

# Already Looked
[The list of available machine images](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images)

# Potential Locations
[The list of available machine images](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images)

**Comment by teesloane** [comment]
Hi @Kurt-von-Laven ! As you linked in the orbs source, it is indeed possible to custom specify the machine image for windows, however, using the windows orb is the recommended path to getting started with Windows. I will check internally if this is no longer the case, however.

**Comment by teesloane** [comment]
To follow up, we are going to continue to recommend users use orbs to get going with Windows - however, we will be revamping our machine image documentation in the future and will re-consider where this information should go. Thanks for bringing attention to it!
