### ISSUE TITLE
Conflicting config paths, parameter names in dynamic config cookbook example

### ISSUE THREAD

**Issue by jonprindiville** [circleci/circleci-docs#5292]
# Locations

https://circleci.com/docs/2.0/configuration-cookbook/?section=examples-and-guides#execute-specific-workflows-or-steps-based-on-which-files-are-modified

# Conflict Description

This section talks about a dynamic config and as and example gives the following example repo structure:

```
.
├── service1
│   ├── Service1.java
├── service2
│   ├── Service2.java
├── tests
│   ├── IntegrationTests.java
└── config.yaml
```

Subsequently the example goes on to describe the content of that config file and the `path-filtering/filter` job contains the following key:

        # this is the path of the configuration we should trigger once path filtering and pipeline parameter value updates are complete. In this case, we are using the parent dynamic configuration itself.
        config-path: ".circleci/config.yml"

From the context, it feels like this is maybe meant to be a reference to this same file, except that previously it was introduced as "config.yaml" at the top level of the repo and now it is "config.yml" and is no longer at the top of the repo it's inside ".circleci/".

**If it is meant to be a reference to the same file,** then I'm confused about the close-but-no-cigar names.

**If it is not meant to be a reference to the same file,** then I'm confused about the incomplete example -- could you show *both* `config.yaml` and `.circleci/config.yml`?

In either case I'm confused by the wording of the comment on that `config-path` line about "we are using the parent dynamic configuration itself" ... parent? itself? is this a self-reference or not?

---

Here's a bonus confusion:

The parameters in the `path-filtering/filter`'s `mapping` section match the parameters in the `parameters`:
- `run-service-1-job`
- `run-service-2-job`

Later on in the `workflows`, though, it seems like you use different parameter names:
- `run-build-service-1-job`
- `run-build-service-2-job`

**Comment by annabaker** [comment]
thank you for bringing this up, @jonprindiville! i've resolved all the issues, i believe (correct me if i'm wrong)!
https://circleci.com/docs/2.0/configuration-cookbook/?section=examples-and-guides#execute-specific-workflows-or-steps-based-on-which-files-are-modified

**Comment by jonprindiville** [comment]
Great, thanks, @annabaker! Looks less confusing to me now 👍

---

If you want some minor minor nitpicks, I still think the phrase "we are using the parent dynamic configuration itself" is an odd way to say that we are referring to this very same file. (But now that the `.circleci/config.yml` path is consistent, I think that the chance for confusion is much much less.)

Also, on a purely visual note, some of the line-drawing parts of the directory contents looks a little janky. If that info just comes out of a tool, then whatever, no problem. If it's put together by hand, then maybe the following looks less "cut-off" at the end:

```
.
├── .circleci
│   └── config.yml
├── service1
│   └── Service1.java
├── service2
│   └── Service2.java
└── tests
    └── IntegrationTests.java
```

---

Thanks again, I appreciate the fix!
