### ISSUE TITLE
Overview/Concepts/Orbs: The graphic above?

### ISSUE THREAD

**Issue by rsivan** [circleci/circleci-docs#5302]
# Locations
https://circleci.com/docs/2.0/concepts/?section=getting-started#orbs

# Conflict Description
The text says: "The graphic above illustrating an example Java configuration can be greatly simplified using orbs. The following illustration re-creates the same configuration with the Maven orb.", however the actual java configuration above does not perform a test task.

**Comment by teesloane** [comment]
Hi @rsivan - thanks for catching this. You are correct the illustrations are mis-aligned. We'll put that in the to-fix queue; cheers!

**Comment by teesloane** [comment]
Hi there @rsivan. I've put up a change to fix this issue. 

To follow up, the wording needed to be fixed and the images will be staying the same. The first image you encountered in the docs is meant to represent the various components of a `.config.yml` file that _can_ be customized/configured. Prior to the proposed change, the language indicated that the orb would wholesale replace all parts of the complicated example (Which in the example provided, it does not). However, orbs are indeed intended to reduce configuration. Sorry for the confusion!
