### ISSUE TITLE
experimental chat notify configs: jekyll/_docs/configuration.md

### ISSUE THREAD

**Issue by NewAlexandria** [circleci/circleci-docs#535]
Regarding the `circle.yml` configs, is there a way to specify this? :

* all builds on master (pass, fail, etc) will notify
* all non-master builds will notify only if they fail. 

It wasn't obvious from the docs if that can be specified, as in the `Chat Notifications` section.

Thanks!

**Comment by felicianotech** [comment]
You can only filter the notifications by branch, not build status.
