### ISSUE TITLE
Build number as a global variable available to jobs?

### ISSUE THREAD

**Issue by mixophrygian** [circleci/circleci-docs#5361]
# Missing Information
I would like to pass the currently-running build number as a parameter to another circle job, which will ultimately curl this build's artifacts.  I can't seem to find documentation on whether that information is available to jobs.

# Already Looked
https://github.com/sgesin/circleci-docs/blame/master/jekyll/_cci2/artifacts.md#L181 seems to be the only mention of build numbers referenced in code.

# Potential Locations
Linked _from_ the above location to its own paragraph or sub-section.  

Thanks! 🧀

**Comment by mixophrygian** [comment]
Updated, I was able to locate CIRCLE_BUILD_NUM in the env variables section but please consider this a request to revisit the search bar functionality on your docs site - I would expect `BUILD NUM` or even literally CIRCLE_BUILD_NUM to show the environment variable page as a result but it does not.

**Comment by teesloane** [comment]
Hi there. Thanks for letting us know that things are working. We also appreciate the feedback on the docs!
