### ISSUE TITLE
Outdated deploying-ios example

### ISSUE THREAD

**Issue by stebl** [circleci/circleci-docs#5380]
# Locations
[Deploying-ios/#setting-up](https://circleci.com/docs/2.0/deploying-ios/#setting-up)

# Details
The current instructions suggest setting up an apple account specific to CI and configuring that apple_id and `FASTLANE_PASSWORD` in the system.  

Recently Apple made 2FA required for accounts, which means the current example requires the account owner to manually respond to the 2FA request during a build.  While the example still technically works, this is less than desirable for an automated system.  

Fastlane has [recommendations on how CI systems can authenticate](https://docs.fastlane.tools/best-practices/continuous-integration/#authenticating-with-apple-services), as well as extensive documentation on the recommended practice of generating an [appstore connect API key](https://docs.fastlane.tools/app-store-connect-api/).

**Comment by teesloane** [comment]
Thanks for bringing this up @stebl . We've got plans to update our mac-os documentation and this will be included in a forthcoming update. Cheers!
