### ISSUE TITLE
Can't get insights before 2021.2.1

### ISSUE THREAD

**Issue by evalizhangli** [circleci/circleci-docs#5404]
# Description
I try to get my data 
https://circleci.com/api/v2/insights/{{org_slug}}/workflows/{{workflow_name}}/jobs/{{stage_name}}?start-date=2021-01-01&end-date=2021-02-01
but I can't retrieve correct data

# Location
https://circleci.com/docs/api/v2/?section=insights#operation/addEnvironmentVariableToContext
I follow this doc

right expect:
get full data since 2021-01-01 to 2021-02-01

**Comment by teesloane** [comment]
Hi @evalizhangli - can you please post how you are making your http request to the API ( for example - if it's a curl request, post it here (but don't post your api token!) as it will be easier to debug the issue.

**Comment by teesloane** [comment]
Closing due do inactivity.
