### ISSUE TITLE
RE: jekyll/_docs/docker.md

### ISSUE THREAD

**Issue by nkve** [circleci/circleci-docs#544]
I can't see any mention of what docker version is used here - is that information included somewhere else?

This page also doesn't mention getting the docker via:
`- curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0`

Again - what versions are available?

Am I just looking in the wrong place...?

**Comment by nkve** [comment]
Ok - I've found found where the version of docker is listed: https://circleci.com/docs/build-image-trusty/#docker

Personally - I'd link to this from here: https://circleci.com/docs/docker/
It's one of the first things I want to know 

(don't tell me you are already and I missed it!)

**Comment by felicianotech** [comment]
I've opened a PR to add the version into the doc. Thank you.
