### ISSUE TITLE
quickstart is not getting picked up in the TOC

### ISSUE THREAD

**Issue by katiecircle** [circleci/circleci-docs#5444]
# Description
Describe the bug you found.

# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by teesloane** [comment]
@katiecircle Can you post the link to the page where quickstart is not showing in the TOC?

**Comment by thomasr8** [comment]
Hi @katiecircle : Is this issue still appearing with the changes that have been made recently?

**Comment by thomasr8** [comment]
It appears that this has been fixed with some design changes, so I am closing this issue for now.
