### ISSUE TITLE
Unclear sentence about primary container image

### ISSUE THREAD

**Issue by GinXian** [circleci/circleci-docs#5461]
# Location
https://circleci.com/docs/2.0/configuration-reference/?section=configuration#docker-machine-macos-windows-executor
# Explanation
The original sentence is:

> The first image listed in the file defines the primary container image where all steps will run.

which is under _**<job_name>**_->_**docker/machine/macos/windows(executors)**_.

The sentence seems to imply that the first image of the file defines the primary container image for all jobs, but the concise expression should be "The first image listed under a job defines its own primary container image".

Actually, the [section](https://circleci.com/docs/2.0/executor-types/#using-multiple-docker-images) explains primary container image by saying:

>  In a multi-image configuration job, all steps are executed in the container created by the first image listed.

Therefore, my confusion seems to make sense. However, even though the documentation does use the concise expression, there is still unclear explanation somewhere. Beginners are prone to this ambiguity at first glance.

Hope my thought does help someone out there. It is also my pleasure to provide feedbacks for the community. :-)

**Comment by rosieyohannan** [comment]
Thank you for pointing this out to us @GinXian. I will update to help clear this up for all readers ☺️
