### ISSUE TITLE
Report problem in the documentation

### ISSUE THREAD

**Issue by ntnghia0320** [circleci/circleci-docs#5478]
# Description
https://circleci.com/docs/2.0/postgres-config/
The docs guide at part Example mysql project. At "Install MySQL CLI; Import dummy data; run an example query" it not work, i research and i know circleci/mysql:8.0.4 isn’t designed to be run directly and the primary image, but as service image. This image already includes mysql-client. There’s no need to install it.

# Location
https://circleci.com/docs/2.0/postgres-config/#example-mysql-project

# Steps to Reproduce
I have no idea.

**Comment by rosieyohannan** [comment]
@circleci/cpeng any guidance on this?

**Comment by felicianotech** [comment]
Hi @ntnghia0320, what is the error message you are getting? Do you have a CircleCI config you are able to link to?

**Comment by thomasr8** [comment]
Hi @ntnghia0320 : Are you still having a problem with this issue? If so, please let us know and we will look to find a resolution to your problem.

Thank You

**Comment by ntnghia0320** [comment]
I was fixed it

    steps: # a collection of executable commands
      - checkout # check out source code to working directory

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

**Comment by thomasr8** [comment]
Great...thank you for the update. Please reach out again if you run into any issues and we will make sure to help you out.
