### ISSUE TITLE
RE: jekyll/_docs/test-metadata.md

### ISSUE THREAD

**Issue by retorquere** [circleci/circleci-docs#55]
If I add `--format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber` as per the suggestion in this document, I get no output from the build myself. Is there a way to collect these artifacts while still seeing the build progress?

**Comment by bear** [comment]
@retorquere cucumber allows you to have multiple `--format` output selections, so this is possible:

```
--format pretty --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber
```

**Comment by retorquere** [comment]
So it does! Would be useful to add to the docs I think.

**Comment by bear** [comment]
we were discussing this very thing in our internal support/docs channel :)

I'm going to mark this as closed if that is ok?

**Comment by retorquere** [comment]
absolutely, thank you for your help.
