### ISSUE TITLE
RE: jekyll/_docs/yarn.md

### ISSUE THREAD

**Issue by itaysabato** [circleci/circleci-docs#551]
The new docs page about yarn integration does not specify how to pass CircleCI the desired yarn version - hopefully, there is a way to do that...

Thanks.

**Comment by felicianotech** [comment]
With Yarn pre-installed, there is no longer a way to do this. I'm assuming this is because you want to use the latest version?

I'm not sure the best way to update Yarn manually with this issue currently in discussion: https://github.com/yarnpkg/yarn/issues/1139

**Comment by itaysabato** [comment]
Since yarn is still new technology I would like to be able to have control over which version is running in all my builds (and make sure it is in sync with all my other environments). If CircleCI will always install the latest stable version it would probably be OK though for the most part.

If this is the case, I believe it should be documented along with the current pre-installed version.

**Comment by itaysabato** [comment]
@felicianotech I appreciate the quick response BTW! :)
Thanks

**Comment by felicianotech** [comment]
At the moment, Yarn is being managed the same way most software, including NPM is managed on CircleCI 1.0. The CCI Ubuntu 14.04 image is created every couple of months and it's within this window where we try to update the software it contains. Once an image is cut ([this is the latest](https://discuss.circleci.com/t/ubuntu-14-04-build-image-update-201701-01/9245)), the software is frozen at that version until the next update. The ['Announcements' category](https://discuss.circleci.com/c/announcements) on CircleCI Discuss can be used to follow these announcements.

This is the process we use currently to try and balance the need by many developers to have newer versions of tools vs the strain and stress constant updates can cause both developers and our infrastructure (the image is large).

Once the Yarn Team figures out a way to fix `yarn self-update` (re: the link I first posted), then we can update this doc to include instructions on how to update Yarn automatically during a build.

**Comment by itaysabato** [comment]
Thanks, I have certainly been informed :)

I'll be sure to keep up with the image updates from now on.

**Comment by felicianotech** [comment]
No problem.

**Comment by moretti** [comment]
@felicianotech Do you know if there's any temporary workaround?
I tried with:
```
dependencies:
  pre:
    # Upgrade Yarn
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update && sudo apt-get install yarn
```
But it doesn't seem to work:
```
Preparing to unpack .../archives/yarn_0.20.3-1_all.deb ...
Unpacking yarn (0.20.3-1) ...
Setting up yarn (0.20.3-1) ...
```
```yarn install v0.18.1``` <- 🤔
