### ISSUE TITLE
videos on page say that theyre unavailable

### ISSUE THREAD

**Issue by sebastian-lerner** [circleci/circleci-docs#5520]
# Description
https://circleci.com/docs/enterprise/quick-start/ the videos on this page say they're unavailable on youtube

# Location
Describe where you caught the bug.
https://circleci.com/docs/enterprise/quick-start/

# Steps to Reproduce
Describe the steps you took to produce the bug.

**Comment by sebastian-lerner** [comment]
do i assign this to anyone? or does someone automatically get a notif?

**Comment by teesloane** [comment]
Hi @sebastian-lerner - the enterprise/quick-start pages are archived - so you don't have to worry about this page :)
