### ISSUE TITLE
Boolean Parameter Conditionals

### ISSUE THREAD

**Issue by joechchung** [circleci/circleci-docs#5526]
# Locations
https://circleci.com/docs/2.0/reusing-config/#boolean

# Details
Tried to use the boolean parameter conditions in my `config.yml` and set it to default `false` but it took the `true` parameter instead

```
version: 2.1
parameters:
  all_projects:
    type: boolean
    default: false
  debug:
    type: boolean
    default: false
```

```
<<# parameters.all_projects >> --all <</ parameters.all_projects >><<^ parameters.debug >> --debug<</ parameters.debug >>
```

**Comment by rosieyohannan** [comment]
@joechchung Hey! I'm not managing to recreate this myself, do you happen to have a link to the repo where you're using it if it's public?

**Comment by thomasr8** [comment]
Hi @joechchung : Is this still an issue for you? If not, I will go ahead and close this issue.
