### ISSUE TITLE
Document how to do more complex version pinning of Orbs

### ISSUE THREAD

**Issue by jamesbraza** [circleci/circleci-docs#5542]
# Missing Information

In the Orbs FAQ, specifying versions are described to use semantic versioning like so ([link](https://circleci.com/docs/2.0/orbs-faq/#how-to-use-the-latest-version-of-an-orb)):

```yaml
orbs:
  # SEE: https://circleci.com/docs/2.0/orbs-faq/
  my-org/my-orb@1      # Pinning major version
  my-org/my-orb@1.2    # Pinning minor version
  my-org/my-orb@1.2.3  # Pinning bugfix version
```

Last Friday (7/16/2021), one orb I used published breaking changes as a bugfix version, which is frustrating, as it breaks semantic versioning.

I now want to pin the Orb to be anything newer than a particular bugfix version `4.5.6`.  How to do this isn't covered in the docs.

# Already Looked

https://circleci.com/docs/2.0/orbs-faq/#how-to-use-the-latest-version-of-an-orb

# Potential Locations

I would expect to find this in the Orbs documentation.

The particular page it's on doesn't matter to me, as long as it's centralized and shows up in a Google search result.

**Comment by rosieyohannan** [comment]
Hey @jamesbraza thanks for reaching out about this, and sorry this happened to you. Currently it is only possible to pin orb versions to a major or minor version, for example `1` would get you `1.x.y` or `1.2` would get you `1.2.x`.
