### ISSUE TITLE
Update instructions / possible inaccuracy (_cci1/troubleshooting-ios-and-OSX.md)

### ISSUE THREAD

**Issue by milos-league** [circleci/circleci-docs#556]
The instructions need to be updated. When running the ones you've listed, I get:

`xcrun instruments -w "iPhone 7 (10.1)" || true
Waiting for device to boot...
Instruments Usage Error: No template (-t) specified
instruments, version 8.2 (61756)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]`

**Comment by felicianotech** [comment]
@appplemac Thoughts?
