### ISSUE TITLE
Update the example for how to unlist an orb

### ISSUE THREAD

**Issue by labsquared** [circleci/circleci-docs#5570]
# Location
https://circleci.com/docs/2.0/orb-author-faq/#deleting-orbs

# Error Details
Example command has orb name and namespace reversed. 
Current: `circleci orb unlist myOrb/myNamespace`
Should be: `circleci orb unlist myNamespace/myOrb`

**Comment by thomasr8** [comment]
Hello @labsquared : Thank you very much for pointing out this error for us. I have gone ahead and asked for confirmation from one of our engineers, and will be pushing this change to our docs site.
