### ISSUE TITLE
Undocumented use of `/dev/null |` in scala language guide

### ISSUE THREAD

**Issue by slavaschmidt** [circleci/circleci-docs#5591]
# Missing Information
In [Scala language guide](https://circleci.com/docs/2.0/language-scala/) all sbt calls are prefixed with `cat /dev/null`, for example: `cat /dev/null | sbt clean update dist`. The need for this is not explained.

# Already Looked
Google search, CircleCI documentation search

# Potential Locations
I'd expect a short explanation of why this is done the way it is in the [Scala language guide](https://circleci.com/docs/2.0/language-scala/) itself.

Thank you.

**Comment by thomasr8** [comment]
Hello @slavaschmidt : Thank you for bringing this issue to our attention. I reached out to Engineering to get clarification on why this is required and was told the following:

"That technique is normally used to prevent a command from hanging if it prompts for interactive input and doesn't do any detection of whether it's running with an interactive TTY. It looks like sbt prompts on failures by default"

I am going to update the documentation to reflect this. Thank you again for the help in finding this issue.
