### ISSUE TITLE
Add context for new users re: Google Cloud (_cci1/continuous-deployment-with-google-container-engine.md)

### ISSUE THREAD

**Issue by ghost** [circleci/circleci-docs#560]
It would be helpful to note a few extra details for new users starting out (I have used AWS, but was new to Google cloud AND CircleCI, so I'm highlighting the mistakes I made)

-the project  name is really your project ID in Google Cloud (found right under the project name)
- for your service account, selecting a role that is only related to the Google Container Engine will do the trick (i.e. you don't need to have this service account act as owner/have access to all of your resources). Until I fixed this, I kept getting a "RROR: (gcloud.container.clusters.describe) ResponseError: code=403, message=Required "container.clusters.get" permission" error.
-if you run into python openssl errors, it could be installing open ssl, so in dependencies, you could add:
  override:
    - pip install pyopenssl

and in requirements, you can add:
CLOUDSDK_CORE_DISABLE_PROMPTS: 1

-but that openssl error I found was an artifact relating to broader authentication issues. One was that I had to remove the -i from --decode -i. Before I fixed this, the CircleCI build report also returned a p12 error from a later gcloud command, even when the key was a JSON key. Turns out that's because this base64 call wasn't working, so Google wasn't even being presented a key, JSON or not.
-A good suggestion for users new to Google Cloud, to avoid being bugged too much by questions up front, would be to suggest running all of the gcloud commands locally first (after setting environment variables locally), especially:
sudo gcloud config set project $PROJECT_NAME
sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file yourKeyFile.json
sudo gcloud --quiet config set container/cluster $CLUSTER_NAME
sudo gcloud --quiet container clusters get-credentials $CLUSTER_NAME

If those work locally, at least you know it's not an authentication issue with your service key.

Hope these comments will save folks a few hours!

**Comment by smart-alek** [comment]
Hey @mantrabio! Thanks for writing this up, it's very helpful. I'll be incorporating these changes into the docs by EOM.

**Comment by ryanwohara** [comment]
@smart-alek Did these changes ever get incorporated?

**Comment by smart-alek** [comment]
@ryanwohara They did not. :( But we are in the midst of a recent push, so I'll be getting to it next week. 🤞
