### ISSUE TITLE
Request for PR Review

### ISSUE THREAD

**Issue by sweeneyskirt-sl** [circleci/circleci-docs#5605]
I submitted a PR to update the documentation related to Sauce Labs and we got some initial feedback, some of which we have addressed and some of which we have asked for clarification on, but our reviewer seems to have gone dark on us. I have pinged a couple of resources who seem to be owners of this repo, but with no response. I am hoping someone might be able to re-engage, even if it's just to give me an estimate for when you might be able to devote some time to the PR.

Thanks!

PR: https://github.com/circleci/circleci-docs/pull/5529

**Comment by kbatuigas** [comment]
Hi @sweeneyskirt-sl , I'm one of the technical writers at CircleCI, just wanted to let you know that I'm also helping to follow up on our end regarding the PR. I don't have any updates for you just yet, but hopefully we'll have a resolution soon.

**Comment by sweeneyskirt-sl** [comment]
Thank you, @kbatuigas. I have been working with @rosieyohannan as well.
