### ISSUE TITLE
multi-os matrix example broken and orbs outdated

### ISSUE THREAD

**Issue by duncdrum** [circleci/circleci-docs#5611]
# Description
The example uses two orbs node and win. The win orb has a default `shell: powershell.exe` the node orb runs a bash script to use nvm during the install phase. Resulting in errors on windows, like so:

```
#!powershell.exe -ExecutionPolicy Bypass
# Only install nvm if it's not already installed
if command -v nvm &> /dev/null; then
    echo "nvm is already installed. Skipping nvm install.";
else
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash;
    echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV;
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use' >> $BASH_ENV;
    source $BASH_ENV;
fi

if [ "$NODE_PARAM_LTS" = "1" ]; then
    nvm install --lts
    nvm alias default lts/*
else
    nvm install "$NODE_PARAM_VERSION"
    nvm alias default "$NODE_PARAM_VERSION"
fi

echo 'nvm use default &>/dev/null' >> $BASH_ENV

At line:2 char:3
+ if command -v nvm &> /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At line:2 char:19
+ if command -v nvm &> /dev/null; then
+                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
At line:11 char:3
+ if [ "$NODE_PARAM_LTS" = "1" ]; then
+   ~
Missing '(' after 'if' in if statement.
At line:11 char:5
+ if [ "$NODE_PARAM_LTS" = "1" ]; then
+     ~
Missing type name after '['.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

Exited with code exit status 1

CircleCI received exit code 1

```

Both orb version numbers are out of date. 

To fix the first problem, we would either need a documented way for how to switch the default shell of the windows orb to `shell: bash.exe`  that is included in the code-listing (and on the windows orb page). Or change the node orbs shell script to be non bash specific. I think the former is the wtg. 

To fix the second, would it be possible to at least automatically scan the documentation's code listing and update orb references whenever circle releases new orbs? Even better run use the updated code listings for some documentation driven development/testing. 

# Location
https://circleci.com/docs/2.0/configuration-cookbook/#use-matrix-jobs-to-run-multiple-os-tests 

# Steps to Reproduce
https://app.circleci.com/pipelines/github/evolvedbinary/fusion-studio/33/workflows/275dbd1d-6b07-415b-9fd8-f106b316a8b2/jobs/92

**Comment by felicianotech** [comment]
I can take a look at this but might need help from @circleci/cpeng orb people.
