### ISSUE TITLE
Dynamic config: are parameters passed to config.yml passed on to continue_config.yml?

### ISSUE THREAD

**Issue by maxwell-carbon** [circleci/circleci-docs#5621]
# Missing Information

We currently have a rather large config.yml that accepts many parameters (~20), and we're interested in using dynamic config orbs like `path-filtering`, but it's unclear whether I need to duplicate those 20 parameters, and if/how they're even passed to continue_config.yml.

Normally I'd just experiment with this myself, but CircleCI doesn't really give me a safe and easy way to simulate workflows, AFAIK.

# Already Looked

* https://circleci.com/docs/2.0/configuration-cookbook/?section=examples-and-guides#execute-specific-workflows-or-steps-based-on-which-files-are-modified
* https://circleci.com/developer/orbs/orb/circleci/path-filtering

# Potential Locations

Either of the above two places I looked, but probably the orb documentation.

**Comment by netcazean** [comment]
#5673

**Comment by roopakv** [comment]
Check out `additional-param-map` here -> https://circleci.com/developer/orbs/orb/roopakv/swissknife#jobs-filter-and-continue

I built this to solve exactly this case and we use it to pass params from config to continue_config without config having to duplicate this.

**Comment by kbatuigas** [comment]
Hi, @maxwell-carbon - I'm one of the technical writers at CircleCI and I just wanted to check in and ask if the other comments are of help for what you're looking to do. Thanks.

**Comment by kbatuigas** [comment]
Hi, @maxwell-carbon - thank you for your patience. I have just confirmed with our engineering team that this document will answer your questions: https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/setup-workflows.md

In particular you'll want to note this bullet point:

> - pipeline parameters declared in the setup configuration must also be declared in the continuation configuration, and can be used at continuation time

Hope that helps! We'll work on updating our docs shortly to include this info - it will probably go up on our [Dynamic Configuration](https://circleci.com/docs/2.0/dynamic-config/) page.
