### ISSUE TITLE
single-box installation instructions should mention Storage

### ISSUE THREAD

**Issue by osowskit** [circleci/circleci-docs#563]
The instructions to configure a single box installation on AWS is very concise and straightforward. However, the [AWS](https://github.com/circleci/circleci-docs/blob/master/jekyll/_docs/enterprise/single-box.md#on-aws) section should include an optional step for configuring build-related artifacts storage on AWS S3 as using `Instance Profile` should be configured when [provisioning the server](http://docs.aws.amazon.com/codedeploy/latest/userguide/how-to-create-iam-instance-profile.html).

**Comment by felicianotech** [comment]
@GERey Thoughts?

**Comment by 1810755jiawei** [comment]
bbbbb
