### ISSUE TITLE
RE: jekyll/_docs/test-metadata.md

### ISSUE THREAD

**Issue by arielvalentin** [circleci/circleci-docs#564]
It is unclear to me how one can leverage this feature in rspec or cucumber if you have a multi-staged build that divide a test suite, e.g. unit, integration, requests.. 

Are you only allowed to have 1 rspec junit metadata file per build for this to work?

**Comment by drazisil** [comment]
Hi @arielvalentin,

Thanks for the issue, we added a note on a third-party tool you can try.

**Comment by arielvalentin** [comment]
@drazisil Will merging the results provide enough information for the auto-balancer to work properly?

**Comment by drazisil** [comment]
@arielvalentin That is a very good question. I'm not sure. I would try it and if you see issues please open either a help desk ticket or a forum bug report so we can investigate and escalate as needed.

**Comment by zzak** [comment]
@arielvalentin I think merging results may provide **too much information** to the auto-balancer.

We've had a number of users run into this problem where times are unbalanced because it's comparing short-lived unit tests to long-lived integration test times.
