### ISSUE TITLE
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

### ISSUE THREAD

**Issue by Ghsouza1** [circleci/circleci-docs#5680]
Hey @all

I´m facing this issue when I add a new job to generate an Allure report:

" ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. " 

I have three jobs on this config.yml:

- API Tests
- UI Tests
- Generate Allure Report

In the last one I have those commands:

command: |
    npm install -g allure-commandline --save-dev
    allure generate --clean

API Tests and UI Tests works fine, but the third job is not OK yet, I tried to find on circle-Documentation and I haven´t found nothing so far about this error!

Thanks!

![image](https://user-images.githubusercontent.com/24716622/132758516-fc9e46cf-0496-43a0-b49d-f45615ea1221.png)

**Comment by devinmarieb** [comment]
Hi @Ghsouza1 , if you weren't able to find what you're looking for in the [environment variable guide](https://circleci.com/docs/2.0/env-vars/) to help you sort out your Java PATH and you’re still having trouble setting up Java in your environment, you can [open a support ticket](https://support.circleci.com/hc/en-us) and someone will try to help you.
