### ISSUE TITLE
Revise copy, specifically for badge type use cases (_cci1/status-badges.md)

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#572]
The copy for this page can be improved. Specific things to note:

- suggestion on which badge type to use and when
- when to use a CircleCI token and which one specifically
- `style=shield` example

**Comment by Dorian** [comment]
There is a `style=shield` example actually but the formatting of the whole page is very messy and misleading

**Comment by smart-alek** [comment]
Also include changes suggested in #575

**Comment by smart-alek** [comment]
@felicianotech I redid this whole page for 2.0. Can you take a look at some point and see if your issues are resolved there? I doubt I'll be revising 1.0 copy but happy to include your suggestions in 2.0 if they're still needed.

https://circleci.com/docs/2.0/status-badges/

**Comment by felicianotech** [comment]
I agree that we don't need to update the 1.0 version.

For 2.0, the only small piece I see missing is noting that for a FOSS project, an API token isn't needed. Just for private projects.
