### ISSUE TITLE
Orb publishing process - merge commit message

### ISSUE THREAD

**Issue by andormarkus** [circleci/circleci-docs#5722]
# Locations
https://circleci.com/docs/2.0/creating-orbs/#issue-a-new-release

# Details
We are Bitbucket cloud customers are I have followed the Orb publishing process.

I have created the PR as described:
<img width="957" alt="Screen Shot 2021-09-23 at 20 57 26" src="https://user-images.githubusercontent.com/51825189/134567559-4ab188d7-86d3-4a2f-b22e-17a631c8a862.png">

Once the pull request is approved, I created the merge commit as described. The pull request title was preserved in the body of the commit message.
<img width="594" alt="Screen Shot 2021-09-23 at 21 11 14" src="https://user-images.githubusercontent.com/51825189/134569186-bf6377d0-2dd5-4081-8fba-9132ae121ef3.png">

My Orb release failed because the commit subject did not contain the SemVer increment
<img width="1191" alt="Screen Shot 2021-09-23 at 21 02 37" src="https://user-images.githubusercontent.com/51825189/134567984-6d0a8afc-a7e0-4bc1-a9ac-704f9787999f.png">

# Possible solution
1. The [circleci/orb-tools](https://circleci.com/developer/orbs/orb/circleci/orb-tools) checks the first line of the body of the commit message, thus Bitbucket customers release will not fail. Bitbucket preserves the PR title in the first line of the body not in the subject.
2. Changing the documentation and explicitly saying for Bitbucket customers needs to include the SemVer increment in the first line (subject) on the merge commit message.
<img width="592" alt="Screen Shot 2021-09-23 at 21 11 25" src="https://user-images.githubusercontent.com/51825189/134569631-ac81683f-6d1d-4bfd-965e-38a259382f07.png">

Thanks,
Andor

**Comment by devinmarieb** [comment]
@andormarkus Thanks for reaching out! We have added an additional clarification on the docs page for this. I am going to follow up with the Orbs team to see if we can do anything about changing the actual process for the future.
