### ISSUE TITLE
Extra Parenthesis Typo

### ISSUE THREAD

**Issue by Xavientois** [circleci/circleci-docs#5728]
# Location
https://circleci.com/docs/2.0/docker-layer-caching/#how-dlc-works

# Error Details
Under the **Limitations** subsection of the **Overview** section, there is a stray right-parenthesis in the last paragraph:
<img width="758" alt="Screen Shot 2021-09-27 at 12 42 43 PM" src="https://user-images.githubusercontent.com/34867186/134950695-e882da00-da41-42a1-9d8d-9a7ad334ba2a.png">

**Comment by kbatuigas** [comment]
Thanks, @Xavientois ! Merging a fix for this shortly.
