### ISSUE TITLE
Update for latest version of Google Cloud (_cci1/continuous-deployment-with-google-container-engine.md)

### ISSUE THREAD

**Issue by thecreator232** [circleci/circleci-docs#577]
This document needs to be updated for the latest version of gcloud, apparently for the latest version of gcloud the kubectl commands are not working they are returning the following error:

`error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

I have not been able to find a solution till now.

**Comment by sha1sum** [comment]
FYI: Documentation has been PR'd for 2.0 GKE deployment in case anyone comes here looking for it.

#1073
