### ISSUE TITLE
How to specify path containing wildcards in save_cache

### ISSUE THREAD

**Issue by tlaurion** [circleci/circleci-docs#5804]
# Missing Information
It is not currently possible to use wildcards in save_cache paths.

# Already Looked
- Issue was opened for API 1.0 and [closed](https://github.com/circleci/circleci-docs/issues/241) 
- Discussions happened [without mitigation proposal](https://discuss.circleci.com/t/support-globs-in-save-cache/39368)
- Feature request was [proposed](https://ideas.circleci.com/cloud-feature-requests/p/support-wildcards-in-savecachepaths) and upvoted by 77 persons as of now

# Potential Locations
I would expect to just work. Then no documentation would be needed? Otherwise documentation explaining how to go around that limitation.

**Comment by tlaurion** [comment]
@devinmarieb is there a way?
Was working before though.

Current issue https://github.com/osresearch/heads/issues/1039

**Comment by devinmarieb** [comment]
@tlaurion I'm still waiting for a response from the engineering team. I'll let you know as soon as I hear from them :)
