### ISSUE TITLE
how to upload documents

### ISSUE THREAD

**Issue by Pradeep18563** [circleci/circleci-docs#5872]
# Missing Information
Give a brief overview of the information you were looking for.

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.

**Comment by devinmarieb** [comment]
Hi @Pradeep18563 Could you please fill out the issue form and provide information about what part of the Docs you were looking for or having issues with? We need further information to help, otherwise we will be closing the issue.
