### ISSUE TITLE
Add parallel doc for BitBucket (_cci1/github-permissions.md)

### ISSUE THREAD

**Issue by minac** [circleci/circleci-docs#588]
What about Bitbucket? Is there a way to connect with bitbucket, but only allow access to the repos under the organization of the user (and not other orgs which have shared their code)?

**Comment by smart-alek** [comment]
Hi @minac from more than a year later (!). You should get the answers you need in this article about [GitHub/Bitbucket Integration](https://circleci.com/docs/2.0/gh-bb-integration/#permissions-for-team-accounts) for our 2.0 platform.

Happy building! :)
