### ISSUE TITLE
Searching for machine image info

### ISSUE THREAD

**Issue by nkve** [circleci/circleci-docs#5907]
# Locations
https://circleci.com/docs/2.0/executor-types/#using-machine

# Details
The text at the top:

Legacy images with the prefix "circleci/" will be deprecated on December 31, 2021. For faster builds, upgrade your projects with next-generation convenience images.

Links to here: 
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/

But these images aren't compatible with the machine executor...

Where is the list of available machine images?

I found this, which seemed useful, but, is an announcement (not in docs) and is only for a specific image.
https://discuss.circleci.com/t/linux-machine-executor-images-october-q4-update/37847

There's this, but, no discussion of what's on each image:
https://circleci.com/docs/2.0/configuration-reference/#machine

Googling a specific image I can find the announcement for it and thus get its requirements, so here's the latest one:
https://discuss.circleci.com/t/linux-machine-executor-images-2021-july-q3-update/40772

Am I missing something here? Is there a doc with all this info in one place?

**Comment by rosieyohannan** [comment]
Hey @nkve If you look on the executor-types doc https://circleci.com/docs/2.0/executor-types/#using-machine and scroll down a bit, there's a link:

<img width="838" alt="Screenshot 2021-11-08 at 10 42 31" src="https://user-images.githubusercontent.com/24589403/140728398-54ef22bc-df7a-4410-8312-e81410045ad7.png">

which takes you here: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

I hope this is what you are looking for? I will open up a PR to make this link clearer and move it to the top of the section if so - thanks so much for this valuable feedback :-D

**Comment by nkve** [comment]
Hi, thanks for getting back to me on this.
I did see that, but I was expecting to see the spec of each image documented here too...

I probably confused things by mentioning two issues...

## Context

I have a file containing the following:
```   
journeyTests:
     machine:
       image: circleci/classic:latest
```
I'm manually installing java 11 onto this.
I wondered if I still have to do this, or is there an updated image I can use.
I hit the docs...

### Issue 1. Confusing (incorrect?) warning message 

One of the first **machine** reference pages I see is this one: https://circleci.com/docs/2.0/executor-types/#using-machine

I notice a warning at the top 

> Legacy images with the prefix "circleci/" will be deprecated on December 31, 2021. For faster builds, upgrade your projects with next-generation convenience images.

I note that my current **machine** image is **circleci/classic:latest** so this is telling me current image is going to be deprecated and replaced with the ones mentioned in this post: https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/

**But** as far as I can tell, these images referenced in this post aren't machine images, they're docker images.
So, the warning at the top of the **machine** section is sending me somewhere which isn't actually relevant (for machine use)

### Issue 2. Where are the specs for the supported machine images?

I managed to find the section you referenced and found a list of images:

> Available machine images
Specifying an image in your config file is strongly recommended. CircleCI supports multiple machine images that can be specified in the image field:

> ubuntu-2004:202107-02 - Ubuntu 20.04, Docker v20.10.7, Docker Compose v1.29.2,
> ubuntu-2004:202104-01 - Ubuntu 20.04, Docker v20.10.6, Docker Compose v1.29.1,
> ubuntu-2004:202101-01 - Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2,
> ubuntu-2004:202010-01 - Ubuntu 20.04, Docker v19.03.13, Docker Compose v1.27.4, ubuntu-2004:202008-01 is an alias

This is almost what I'm looking for, except, I'm expecting a breakdown of everything installed on these images, not just docker and docker compose.

I hit the docs again, but keep ending up back here again...
I'm convinced that circleci has to specify more detail than this, but I can't find it anywhere.
I eventually find a forum post like this: https://discuss.circleci.com/t/linux-machine-executor-images-october-q4-update/37847
which is exactly what I wanted. 

I'm now confused as to whether I'm missing the docs page that lists all the available images **and** their specs or whether they're intentionally separated...

If this information isn't all in one page (it may well be!) I'd find it incredibly useful if it were...

**Comment by devinmarieb** [comment]
@nkve and @rosieyohannan Just jumping in to say that I don't believe **machine** images are being updated, just **convenience** images (like the Discuss article mentions). The convenience images are being updated over time, so more should be updated from now through December. The machine images should remain as is.

As far as a breakdown, I know we breakdown what's on the machine images in the docs, but I'm not aware that we do this for the convenience images. I'll tag @felicianotech if he wants to also jump in here.

**Comment by rosieyohannan** [comment]
Ah yes @nkve I see what you're saying now. We have images listed in the developer hub: https://circleci.com/developer/machine/image/ubuntu-2004 but I can see this also down not give as comprehensive a list as what you get in each image as in that discuss post you linked to. I'll see if this level of detail is something we can get added to the relevant pages in the dev hub and go from there. Does that make sense? You can get to the images section of the dev hub from the docs site - orbs and images are listen in the page header :-)

<img width="1680" alt="Screenshot 2021-11-08 at 21 53 28" src="https://user-images.githubusercontent.com/24589403/140824201-d20c5409-bdf3-483a-82bb-36a98edf38b8.png">

**Comment by rosieyohannan** [comment]
Hey again @nkve I have checked with our engineering teams and it seems the current source of truth for the machine image contents is actually that Discuss post at the moment but they are right now working on getting this information fully listed in the dev hub, linked to in my previous post. I hope this helps!

**Comment by nkve** [comment]
Thanks.
I actually hadn't seen that whole images section...

My last few suggestions would be
1. Link to the relevant images section (https://circleci.com/developer/machine/image/ubuntu-2004) from here https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
2. Update https://circleci.com/developer/machine/image/ubuntu-2004 to have an up to date list of tags (it's currently missing ubuntu-2004:202107-02)
3. Update https://circleci.com/developer/machine/image/ubuntu-2004 to specify, in detail, the specs of each image (which seems to be the plan) or at least reference where/how to find the forum posts which _do_ define the specs

**Comment by rosieyohannan** [comment]
Thank you @nkve 🎉

**Comment by rosieyohannan** [comment]
@circleci/cpeng There are a couple of suggestions here for the dev hub machine images page

**Comment by felicianotech** [comment]
Hi @nkve,

Some clarifications I wanted to make.

> Am I missing something here? Is there a doc with all this info in one place?

This is the big one. It's not great and the answer is no however I am working on this as we speak. This will make it much, much easier to find all this information in one place going into January and 2022.

```yaml
     machine:
       image: circleci/classic:latest
```

The banner you are seeing does not apply to this image you are using. The banner applies to legacy Convenience Images which use the Docker executor.

That being said, it just so happens that the image you are using will also be deprecated in the near future. It's running Ubuntu 14.04 which is very, very old and isn't support by Canonical (the company behind Ubuntu) anymore. I do suggest upgrading to a supported Ubuntu 20.04 image which are the ones listed here: https://circleci.com/developer/machine/image/ubuntu-2004#image-tags

As for your suggestions:

1. This will be taken care of by the new Image Docs update I'm working on.
2. Looks like someone beat me to this? I see the version listed now.
3. We're working on adding the detail in now. That will take a bit so perhaps in the meantime, we can do the forum link as you suggested. That sounds reasonable to me.
