### ISSUE TITLE
undocumented add is_key_content_base64 to app_store_connect_api_key to make easier for env and CI 

### ISSUE THREAD

**Issue by jkzilla** [circleci/circleci-docs#5930]
# Missing Information
Give a brief overview of the information you were looking for.
https://github.com/fastlane/fastlane/pull/17401
add is_key_content_base64 to app_store_connect_api_key to make easier for env and CI 

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document."

ios

**Comment by devinmarieb** [comment]
@jkzilla Thanks for the information. We can see if there's a good place to mention this in our section on best practices, however the expectation is that when setting up Fastlane parameters, people are using the [Fastlane Docs](https://docs.fastlane.tools/actions/app_store_connect_api_key/) to find information about setup and parameters. We can definitely add some links in our own Docs that directly reference the Faslane docs for easier set up!
