### ISSUE TITLE
Node.js env broken

### ISSUE THREAD

**Issue by gengjiawen** [circleci/circleci-docs#5933]
# Description
https://app.circleci.com/pipelines/github/gengjiawen/node-build/148/workflows/f76b736f-d9f7-4cdb-8099-773fda3af450/jobs/310

```
/bin/bash: line 1: nvm: command not found
```

but when I ssh into this machine, nvm is there.

```console
circleci@ip-172-28-37-44:~$ nvm

Node Version Manager

Note: <version> refers to any version-like string nvm understands. This includes:
  - full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)
  - default (built-in) aliases: node, stable, unstable, iojs, system
  - custom aliases you define with `nvm alias foo`
```

# Location

https://github.com/gengjiawen/node-build/blob/master/.circleci/config.yml#L13

# Steps to Reproduce

build the linked repo

Looks like a regression of https://discuss.circleci.com/t/nvm-does-not-change-node-version-on-machine/28973.

**Comment by rosieyohannan** [comment]
Thanks for flagging this, I have reported your issue to engineering and will get back to you when I know more :-)

**Comment by rosieyohannan** [comment]
Hi! We recommend specifying a machine image. A list is available here: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images. I think you've maybe got this working now though, is that the case?

**Comment by gengjiawen** [comment]
>  I think you've maybe got this working now though, is that the case?

Yeap. But I don't like you changing the default to a deprecated version.
