### ISSUE TITLE
Icons assets are not loading

### ISSUE THREAD

**Issue by muddlebee** [circleci/circleci-docs#5934]
# Description
Icons assets are not loading

# Location
during local deployment

# Steps to Reproduce

1. yarn install
2. yarn start

| [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/youtube_tutorials.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/docs/arrow-right.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/insights.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/getting_started.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/executors.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/configure.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/examples.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/deployment.svg' not found.
jekyll    | [2021-11-15 06:20:39] ERROR `/docs/assets/icons/sidebar/pipelines.svg' not found.
jekyll    | [2021-11-15 06:20:40] ERROR `/docs/assets/icons/sidebar/projects.svg' not found.
jekyll    | [2021-11-15 06:20:40] ERROR `/docs/assets/icons/sidebar/admin.svg' not found.
jekyll    | [2021-11-15 06:20:40] ERROR `/docs/assets/icons/sidebar/reference.svg' not found.
jekyll    | [2021-11-15 06:20:40] ERROR `/docs/assets/icons/sidebar/youtube_tutorials.svg' not found.

**Comment by rosieyohannan** [comment]
@circleci/docs-disco I think this is a known issue?

**Comment by rosieyohannan** [comment]
Thanks @muddlebee! :-)

**Comment by devinmarieb** [comment]
This issue should be resolved now 👍
