### ISSUE TITLE
Left nav does not work at all in docs on chrome.

### ISSUE THREAD

**Issue by bhazard** [circleci/circleci-docs#5963]
# Description
Navigate to https://circleci.com/docs/ with google chrome
Click on anything in the left nav.  No reaction.

**Comment by jpmatusik** [comment]
Same experience. Tried it with chrome, firefox, and safari.

**Comment by devinmarieb** [comment]
@bhazard and @jpmatusik Thanks! This is a known issue that popped up this morning. Someone is already working on it, so it should be updated shortly :)

**Comment by jpmatusik** [comment]
Awesome. Thanks for the heads up!

**Comment by devinmarieb** [comment]
This should be fixed!

**Comment by jpmatusik** [comment]
Confirmed. Thanks a bunch!

**Comment by bhazard** [comment]
Thanks for quick fix!
