### ISSUE TITLE
Document how often custom docker images are retrieved

### ISSUE THREAD

**Issue by oliver-subskribe** [circleci/circleci-docs#5987]
# Missing Information

How often are job custom docker images pulled from a registry? 

I would like to use a custom docker image to run several jobs in a workflow. However it is not clear how often this image will be pulled from docker registry: 

- Will my custom image get pulled from our private docker registry every once for every job in the workflow? or just once for the whole workflow? 
- Will the image be cached somewhere in circleci so that if the workflow runs 100 times a day, the image will be fetched only once from its docker registry (then stored for some period of time in circleci somewhere, so that every time the jobs are run, circleci just fetches the image locally as done presumably for cimg/* images)

# Already Looked

I searched the circleci docs

# Potential Locations

In https://circleci.com/docs/2.0/custom-images/

**Comment by rosieyohannan** [comment]
@circleci/cpeng Could you help us add something to cover this question?

**Comment by BytesGuy** [comment]
@rosieyohannan You can probably pull this in as-is (removing mentions of DLC)

https://support.circleci.com/hc/en-us/articles/360052269651-How-does-Caching-Work-in-the-Docker-Executor-Spin-Up-Environment-Step-

**Comment by oliver-subskribe** [comment]
Excellent yeah that answers all my questions.
