### ISSUE TITLE
Network Tab

### ISSUE THREAD

**Issue by pawanbahuguna** [circleci/circleci-docs#6081]
# Locations
https://circleci.com/docs/2.0/persist-data/#network
https://circleci.com/docs/2.0/persist-data/#overview-of-storage-and-network-transfer

# Details

"**Object** Tab" is now the **Network** tab. Can we modify this and also replace the screenshot?

**Comment by devinmarieb** [comment]
@pawanbahuguna Are the UI changes for this section now complete? This image has already been updated twice in the past few weeks because the UI keeps changing. I'd suggest removing the screen shots all together and just explaining with text. Would an explanation without images suffice?

**Comment by pawanbahuguna** [comment]
> @pawanbahuguna Are the UI changes for this section now complete? This image has already been updated twice in the past few weeks because the UI keeps changing. I'd suggest removing the screen shots all together and just explaining with text. Would an explanation without images suffice?

I can't comment on if it's complete or not, but it looks like it is completed. 
Screenshots look good and should be there. If you are thinking to update the screenshot later, then I think we can remove it for now and once everything is finalized we can add a new screenshot back.

Can we check with the product team if anything going to change in the future, else we can update the screenshot now?

**Comment by devinmarieb** [comment]
@pawanbahuguna I will remove the screen shots for today and we can update them when the UI is complete. I also don't have access to those particular screen shots. I can only view the UI in the context of our own information, which shows huge overages and lots of red, which I don't think is the best to use as an example 🙃  I will have to find someone to get some good examples of usage.

**Comment by pawanbahuguna** [comment]
@devinmarieb Sounds good, if you want I can provide a screenshot from my plan page which doesn't have anything.

**Comment by devinmarieb** [comment]
@pawanbahuguna I asked the runner team on what their preference is with showing an example with small overages or no overages. Hopefully we'll get it sorted by EOD tomorrow or early next week 👍
