### ISSUE TITLE
CCIE Docs Won't Appear In Search

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#609]
If/when PR #608 is merged, CCIE Docs will no longer appear in the on-page search. If this is REALLY important, then we need to patch the current search system. If this can wait a couple of weeks, the new search system will handle CCIE Docs no problem.

**Comment by felicianotech** [comment]
@keybits Thoughts?

**Comment by keybits** [comment]
I think it can wait until new search is implemented. CCIE folks may feel differently but my feeling is that CCIE docs are not heavily searched right now.

**Comment by smart-alek** [comment]
@keybits agree on how often CCIE docs are being used. From some analysis I did a few weeks back, they're hardly accessed compared to the other docs.

**Comment by smart-alek** [comment]
can we close this issue since we all agree on new search being able to handle?

**Comment by felicianotech** [comment]
Yes, but I want to still track this specific problem. You'll be amazed how often new features that should solve a minor problem forget to solve the minor problem. Tracked here: #618.
