### ISSUE TITLE
Document Possible Front Matter

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#611]
Document somewhere all possible Front Matter variables a doc can have. This can be in an `.md` file within the repo, using GitHub's Wiki, or an actual CircleCI Doc (my least favorite option).

**Comment by ndintenfass** [comment]
The CONTRIBUTING.md now has a word on Front Matter - @felicianotech do you think what's there is sufficient? If not, we can document all options in that section as the answer to this ticket.

**Comment by smart-alek** [comment]
@ndintenfass @felicianotech #912 might solve a lot of this; spruces up CONTRIBUTING.md and fleshes out front matter section.

**Comment by smart-alek** [comment]
Closing this since #912 was merged.
