### ISSUE TITLE
Possibly outdated examples for Code Coverage

### ISSUE THREAD

**Issue by kelvintaywl** [circleci/circleci-docs#6144]
# Missing Information
Give a brief overview of the information you were looking for.

As pointed out from [a customer](https://circleci.zendesk.com/agent/tickets/102368), it does appear that our Code Coverage guide needs an update.
Specifically for the customer, following the [PHP example here](https://circleci.com/docs/2.0/code-coverage/#php) did not help, as with the latest XDebug installed, one would need `XDEBUG_MODE=coverage` set in order for coverage reports to be generated.
> See https://xdebug.org/docs/upgrade_guide#New-Concepts

I noted that overall, we are still referencing the legacy `circleci/*` images, so this may also need an update.

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.

**Comment by kbatuigas** [comment]
Thanks, @kelvintaywl ! I saw that the customer has not responded to your last comment; if you could submit a PR for the PHP section that would be great.

As for the legacy images, we are working on getting that fixed soon!

**Comment by kbatuigas** [comment]
The convenience image has already been updated from legacy to next-gen.
