### ISSUE TITLE
Category indices should use short titles, not doc titles

### ISSUE THREAD

**Issue by smart-alek** [circleci/circleci-docs#615]
When I click on "Quickstart Guides", I should see a list of docs like:

**Quickstart Guides**
Go
JavaScript
Python

rather than:

**Quickstart Guides**
Quickstart Guide: Go
Quickstart Guide: JavaScript
Quickstart Guide: Python

**Comment by felicianotech** [comment]
I'm not a fan of this but I'm not sure why either so opened a PR. :)
