### ISSUE TITLE
There does not appear to be any API documentation, only reference

### ISSUE THREAD

**Issue by gitcos** [circleci/circleci-docs#6263]
# Missing Information
Introduction to the API and basic "getting started" orientation.

# Already Looked
https://circleci.com/docs/api/v2/ - this is bare-bones reference documentation that is nearly impossible to use unless you're already familiar with the API.

https://circleci.com/docs/ - there is no mention of "api" here anywhere, no link to any API documentation.

**Comment by thomasr8** [comment]
Hi @gitcos : Thank you for reaching out to us about the API documentation. For CircleCI API v2, we have an [API Developer's Guide](https://circleci.com/docs/2.0/api-developers-guide/) which might help you understand how to use the API and give you a much more detailed explanation of the API itself. I have added the link here, but please let us know if you need additional information and we will make sure to respond back to you quickly with any answers you need.

Thank You!

**Comment by gitcos** [comment]
Ahh, this may be the documentation I want.  Please link it from https://circleci.com/docs/

**Comment by thomasr8** [comment]
@gitcos We are happy we were able to help you out. We will look to add a link from our main docs page so it is easier to discover this content. Thank you for the suggestion, and as always, please reach out to us if you need any additional assistance.

Thank You!
