### ISSUE TITLE
command lunch not found

### ISSUE THREAD

**Issue by stupid-kid-af** [circleci/circleci-docs#6281]
I'm compiling aosp.
After invoking "source build/envsetup.sh" I entered command lunch arrow_devicename but it's showing these errors

#!/bin/bash -eo pipefail
lunch arrow_moon-userdebug

/bin/bash: lunch: command not found

Exited with code exit status 127

CircleCI received exit code 127

**Comment by stupid-kid-af** [comment]
My github repo => https://github.com/stupid-kid-af/Rom

**Comment by stupid-kid-af** [comment]
Screenshot of my error
![image](https://user-images.githubusercontent.com/54206927/151380144-c50cd00d-8384-4a35-b4c1-477a4451e32d.png)
This is working on Cirrus ci but not on CircleCI

Please fix it

**Comment by devinmarieb** [comment]
Hi @stupid-kid-af - this needs to be filed as a ticket with support. You can choose Build Failure/Configuration Help from the dropdown menu:
https://support.circleci.com/hc/en-us/requests/new
