### ISSUE TITLE
Footer no longer showing up on docs

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#631]
Noticed today, when looking at https://circleci.com/docs/ssh-build/, that there was no "hey, help us improve this doc! you can file an issue or edit the page" footer at the bottom.

And then I checked a few others, and it's missing from those, too.

I'm guessing this is a re-organization quirk. Just wanted to bring it up!

**Comment by felicianotech** [comment]
Great thank you, I'll have this fixed tonight.
