### ISSUE TITLE
`circleci config validate` doesn't work for PRIVATE orbs

### ISSUE THREAD

**Issue by mfcaro** [circleci/circleci-docs#6346]
# Description
circleci config validate doesn't work for PRIVATE orbs, as the documentation establishes.
I tried different ways but still not working. The doc says there is a workaround but it just doesn't work. Either the doc is incorrect or the circleci CLI is not working as expected.

# Location
In the doc: https://circleci.com/docs/2.0/orb-intro/#private-orbs
It says:
`You will be unable to use the circleci config validate command to validate your configuration. You may, however, either paste the content of the orb into the “orbs” stanza of your configuration inline or use the circleci config validate --org-slug <your-org-slug> <path/to/config.yml> command to validate your configuration.`
However it doesn't work.

# Steps to Reproduce
Prerequisites:
- You need to have your private orb
- add the orb in your pipeline configuration 
- Try `circleci config validate -o <orb-slug> <path/to/config.yml> 

Error:

`Error: Unable to validate config: Host (y) must be absolute URL, including scheme`
- It doesn't work at all if I follow the doc:
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/52413307/153060334-2022cdad-3c15-4adf-98e9-d45b67d177a4.png">
- It doesn't work being in the folder where the config.yml file is
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/52413307/153060540-03dbf0b1-d818-4bba-b77d-49245eddfc8e.png">

**Comment by rosieyohannan** [comment]
@mfcaro Thank you for letting us know! @circleci/cpeng Could someone take a look at this?

**Comment by KyleTryon** [comment]
@rosieyohannan this would fall within @circleci/extensibility

**Comment by rosieyohannan** [comment]
So sorry for the delay, we are missing a definition of org slug in the doc. It should be `<your-VCS>/<your-org-name>` so for you: `gh/thirdbridge` :-D ...

Can you try that and let me know? I'll update the doc 🎉

**Comment by rosieyohannan** [comment]
@mfcaro ^^

**Comment by rosieyohannan** [comment]
@mfcaro I'll close this issue but please reopen and let us know if you still have issues after updating your org slug. :-D

**Comment by mfcaro** [comment]
Hey @rosieyohannan . Thanks for your response so far. Apologies I didn't get back to you before.
Looking at your comment you said it should be something like:

```
circleci config validate --org-slug  thirdbridge/infrastructure-aws@1 config.yml
```
Is it right? I'm still having the same issue. 

Thanks for your help!
