### ISSUE TITLE
Windows Software Info Should be Removed

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#6356]
On this page: https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image

That list of software isn't updated. Right now it's out of date. Currently, the CPE/Images Team post Windows info in Discuss whenever we release an image. In the near future we will move to this information being in the DevHub, which is ultimately where all of this info will be for all images.

**Comment by rosieyohannan** [comment]
@felicianotech thank you! Can we get a link in there to the discuss thread to replace this outdated list? Then we can switch that out to the Devhub link when it's operational?

**Comment by devinmarieb** [comment]
@rosieyohannan I think we can probably just delete this section? I have a ticket next week looking at some Windows stuff, so I can do it then if no one gets to it before then.

**Comment by JalexChen** [comment]
Hello! Sorry for the late comment here, but here's the PR for this issue so I think it should be fine to delete the section: https://github.com/circleci/developer-hub-indexer/pull/142
