### ISSUE TITLE
Isn't `api_key_query` authentication method already removed?

### ISSUE THREAD

**Issue by leonardbinet** [circleci/circleci-docs#6367]
# Location
https://circleci.com/docs/api/v2/#section/Authentication/api_key_query
<img width="442" alt="Screenshot 2022-02-14 at 12 10 13" src="https://user-images.githubusercontent.com/1590371/153855013-9386a33a-336a-4b0d-be9d-cf398da0a589.png">

# Explanation
It seems to me that the authentication method is already removed (I receive 404 response code when using this method).

In that case, wording could be replaced by `This authentication method is no longer supported.`

cf https://github.com/roopakv/orbs/issues/98

**Comment by devinmarieb** [comment]
@leonardbinet oh good catch, we will follow up with the correct team and verify this shortly, thanks!

**Comment by devinmarieb** [comment]
The team who owns this section is aware of this and has marked it as something to change, thanks!
