### ISSUE TITLE
Document how to override inferred steps for Python

### ISSUE THREAD

**Issue by merwok** [circleci/circleci-docs#639]
Hello!  I am using a helper written in Python in an npm-based project.  My machine configuration defines a Node version and a Python version; dependencies are overriden to run pip install and npm install; test is also defined explicitly in the config file; there is no unittest.py file (documented to cause nosetests to be used as default test command for a Python project; I haven’t seen docs that explain how inference works for a project that mixes two runtimes such as Node and Python).

Right after a pyenv commend that I defined in machine.post runs, I see another item titled “pyvenv” (note: not pyenv) and labelled “inference” that runs (what I guess from the output is) pip install nose.  The docs do a good job of explaining the inferred commands for test, and how to override them, but this machine step is just a waste of time and bandwith for my project, and I have no idea how to prevent it.

Thanks!

**Comment by smart-alek** [comment]
@merwok Sorry for getting back to you late! 😬 

While we _should_ do a better job of documenting inference for 1.0, your situation sounds ideal for switching over to 2.0. We're not currently running inference on our newest version, so you'd have more freedom over each step of your build. Try it out [here](https://circleci.com/beta-access/)

**Comment by merwok** [comment]
Thanks for the reply!  Good that v2 removes this kind of mystery.

I’ll try v2 with my next project.

**Comment by smart-alek** [comment]
Closing in favor of reporter using 2.0. 😄
