### ISSUE TITLE
How to run a build with arm.medium that builds a Docker image?

### ISSUE THREAD

**Issue by gounthar** [circleci/circleci-docs#6401]
# Missing Information
I'm trying to build a Docker aarch64 image with CircleCi, but just changing the `resource_class` to `arm.medium` does not work.

# Already Looked
This [config file](https://github.com/sgerrand/docker-glibc-builder/blob/main/.circleci/config.yml) works for x86_64.

# Potential Locations
I would expect to find the documentation [here](https://circleci.com/docs/2.0/arm-resources/) or [there](https://circleci.com/docs/2.0/building-docker-images/).

Thanks.

**Comment by devinmarieb** [comment]
@gounthar I'm passing this message along from the team who works on this: Currently, the Docker executor doesn't support anything other than Linux/amd64 images, so only those types of Convenience images can be used. However, arm64 images are supported when building Docker images, or running Docker images with the `docker run` command, either with the amd64 Linux VMs and cross-compiling, or on the arm64 Linux VMs, natively.

If this doesn't answer your question, I would encourage you to open a support ticket under the category of _Build Failure/Configuration Help_ where you can get support with your set up.
https://support.circleci.com/hc/en-us/requests/new

**Comment by gounthar** [comment]
Got it, thanks.
