### ISSUE TITLE
RE: jekyll/_ccie/single-box.md

### ISSUE THREAD

**Issue by lelau** [circleci/circleci-docs#644]
Typo - Installing CircleCI Enterpise on a single [spelling "enterpise"]

Potential typo - SECURITY NOTE: All builds that run on this machine will have access to the IAM privileges [should it say "AIM privileges"?]

**Comment by smart-alek** [comment]
That first one is certainly a typo, but the second refers to [AWS IAM privileges](https://aws.amazon.com/iam/). Thanks for catching the first! :)
