### ISSUE TITLE
Video on Setting Up Parallelism doc is outdated

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#645]
Doc spelunking! I found https://circleci.com/docs/setting-up-parallelism/, which has a really great, clear video by Kevin. However, it's over two years old at this point, and the majority of the user interface has changed since then.

Obviously not critical, but would be great to get a fresh version up sometime (maybe with subtitles or other accessibility wins?).

**Comment by ndintenfass** [comment]
@smart-alek @bellkev should we just kill this video given how increasingly dated it is? I'm thinking "Yes"...

**Comment by bellkev** [comment]
Go for it.

**Comment by smart-alek** [comment]
Gm7 -> C7 -> F7 - > D7
