### ISSUE TITLE
RE: jekyll/_cci1/nightly-builds.md

### ISSUE THREAD

**Issue by wheresrhys** [circleci/circleci-docs#646]
It's not clear from the doc _where_ you would trigger the nightly builds from. Is this possible from somewhere within the circle settings, or do I need to develop my own system to trigger the nightly? Can I use your config APIs to add a nightly build script to all my repos without having to edit all the `circle.yml`'s in their repos?

**Comment by felicianotech** [comment]
With the API, you can do whatever you want really. You can have a script that pulls down the repo and adds a script into it if you wanted. That seems complex in my opinion.

Many people inject an environment variable to signal that this is a nightly build, in which case you can choose to run a different set or tests, or maybe ignore deployment, for example.

**Comment by wheresrhys** [comment]
Thanks for the edit :smile:
