### ISSUE TITLE
Get all Pipelines sometimes gives an invalid next-page-token

### ISSUE THREAD

**Issue by Snarik** [circleci/circleci-docs#6472]
# Description
Im writing a script to parse a pipeline and get all instances of it. I'm looking for specific tags. Occasionally, the script encounters a next-page-token that simply returns {u'message': u'Not Found'} and the linked list ends. Would be nice if we could get some guarantees on next-page-tokens being valid. 

# Location
Circle CI v2 API

# Steps to Reproduce
Im querying the GET /project/slug/pipeline endpoint. Note I am explicitly not including a branch, as I am interested in tags, which seems to be precluded if you specify a specific branch. 
Most requests give a valid page, but occasionally I get an invalid one. Not entirely sure why that would happen.

**Comment by kbatuigas** [comment]
Hi @Snarik I just wanted to give you an update that our engineers will be taking a look and have created an internal ticket for this as well. Thanks for your patience.

**Comment by Snarik** [comment]
Were they able to replicate?

**Comment by Snarik** [comment]
Were they able to replicate?

Sent via Superhuman ( ***@***.*** )

**Comment by Blineberger** [comment]
> # Description
> Im writing a script to parse a pipeline and get all instances of it. I'm looking for specific tags. Occasionally, the script encounters a next-page-token that simply returns {u'message': u'Not Found'} and the linked list ends. Would be nice if we could get some guarantees on next-page-tokens being valid.
> 
> # Location
> Circle CI v2 API
> 
> # Steps to Reproduce
> Im querying the GET /project/slug/pipeline endpoint. Note I am explicitly not including a branch, as I am interested in tags, which seems to be precluded if you specify a specific branch. Most requests give a valid page, but occasionally I get an invalid one. Not entirely sure why that would happen.

**Comment by kbatuigas** [comment]
Hi @Snarik , thank you very much for your patience. Our engineers were not able to replicate -- are you still experiencing this? I'd recommend [opening a ticket](https://support.circleci.com/hc/en-us/requests/new) with our Support team to look more closely at your pipeline/script.

**Comment by kbatuigas** [comment]
Hi @Snarik , we'll go ahead and close this issue for now, but definitely reach back out and also get in touch with our Support team if you need any more help.
