### ISSUE TITLE
Podman Support Clarity

### ISSUE THREAD

**Issue by Nitrodist** [circleci/circleci-docs#6484]
# Description

The tool, html documentation online, these github issues etc. do not mention Podman support. Please update the CLI and online HTML documentation to indicate that you only support the `docker` command for now (AFAICT?) 🙇

# Location

In HTML documentation, in CLI documentation `circleci --help`

# Steps to Reproduce

Two ways. The first is a general internet search using a search engine for 'podman circleci'. There will be no relevant results.

The second way is to run the `circleci --help` command and not see where I can configure the `docker` command. I had a look at the .circleci/cli.yml file itself too without luck.

**Comment by devinmarieb** [comment]
Thanks! I'll work with the team(s) who owns these and hopefully get it sorted out.

**Comment by michael-webster** [comment]
@Nitrodist can you give more detail on your use case?

If you are trying to use podman as an alternative container engine on your local machine when using the CLI, you can create an alias for docker pointed at podman.

If you're interested in using podman inside of a running pipeline, I'd like to understand the use case more.

**Comment by devinmarieb** [comment]
@Nitrodist we're happy to help with your specific issue if you need further support - we can reopen the ticket if needed.
