### ISSUE TITLE
CI status badge is not working when changing repo visibility.

### ISSUE THREAD

**Issue by Harmouch101** [circleci/circleci-docs#6576]
# Description

Basically, in the past few days, I was working on a  [`project`](https://github.com/Harmouch101/frozndict) in which I settled on using circle ci to automate my test-build-deploy workflow. Everything is working fine and dandy, except for the status badge on the readme file.

# Location

You refer to my repo to see [the issue](https://github.com/Harmouch101/frozndict) live.

# Steps to Reproduce

1. Create a private repo. 
2. Add circle ci config: the badge is not working which is normal behavior because it requires a token as mentioned in [the docs](https://circleci.com/docs/2.0/status-badges/#creating-badges-for-private-repositories).
3. Make the repo public: the badge is still not working, which should be and doesn't require a token(optional). For example, the [web3.py repo](https://github.com/ethereum/web3.py) uses a badge URL without appending a token as shown in [raw data](https://raw.githubusercontent.com/ethereum/web3.py/master/README.md), and it is working like a charm.

My hypothesis is that circleci is somehow thinking that the repo is still private, hence the badge didn't show up.

Note: I took the badge URL from the repo settings as shown in the following screenshot:
 
![Screenshot from 2022-03-23 15-00-10](https://user-images.githubusercontent.com/62179149/159712862-3e10ece2-f31c-4a30-8021-c689d7ce665c.png)

Let me know if something is not quite right about my configs. I really do appreciate your guidance in advance.

Regards.

**Comment by thomasr8** [comment]
Hi @Harmouch101 Thank you for bringing this to our attention. I am going to reach out to our Engineering and Support teams to see how we might be able to help you with this.

**Comment by Harmouch101** [comment]
> Hi @Harmouch101 : I received a link to an article that should help you with your issue:
> 
> https://support.circleci.com/hc/en-us/articles/360021666393-How-to-manually-stop-building-by-removing-your-deploy-key-and-webhook-from-GitHub?source=search&auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOjM4NjU5MDA1NDczNCwidGlja2V0X2lkIjo1NDgwNSwiY2hhbm5lbF9pZCI6NjMsInR5cGUiOiJTRUFSQ0giLCJleHAiOjE1NjY3NjM1NTV9.h-4HG-9gXeyu3WkMHYxavYWxnGOGeYVUGLUac5wC0SM
> 
> Please let me know if this helps you with your issue, or if I can find more information for you.
> 
> Thank You!

Thanks for your reply. 

Actually, I am not facing a deployment issue with circleci because it is working as intended, and I am not willing to stop using it. Reading the article that you have provided doesn't actually address my issue. My concern is that It is quite odd to see that the status badge is not working on the readme file, even though the [workflow was successful](https://app.circleci.com/pipelines/github/Harmouch101/frozndict/63/workflows/168f11ac-96e1-42e3-846e-630e918ea5f4). Moreover if you open up [this link](https://circleci.com/gh/Harmouch101/frozndict/tree/main.svg?style=svg), you will notice that the status badge is working, unlike the case on [the readme file](https://github.com/Harmouch101/frozndict/blob/main/README.rst).
I am wondering whether or not it is a GitHub markup issue, or a circle ci issue. However, I think the latter is more probable cause the issue exists on [pypi](https://pypi.org/project/frozndict/)(Notice the broken image of circleci badge!) as well.

I hope that the above information clarifies the issue that I am currently having. 

Regards.

**Comment by thomasr8** [comment]
Hi @Harmouch101 I just got a response from our Support team and they would like you to open a support ticket with them so they can help you directly with your issue.

https://support.circleci.com/hc/en-us/requests/new?ticket_form_id=855268

Please let me know how else I might be able to help.

Thank You!

**Comment by thomasr8** [comment]
Hi @Harmouch101 Thank you again for reaching out to us about your issue. I am going to close this issue for now, but please feel free to reach out to us again if you need additional help or support.

Thank You!
