### ISSUE TITLE
How to modify postgresql.conf using circle.yml

### ISSUE THREAD

**Issue by aniket03** [circleci/circleci-docs#658]
If I wish to change settings for postgres [test database] like setting fsync, full_page_writes to off. How can i do so using circle.yml

**Comment by keybits** [comment]
Thanks for your question. I see you asked on Discuss here: https://discuss.circleci.com/t/can-postgres-config-postgresql-conf-file-be-changed-using-circle-yml/10621 < I'll answer there.

We're working on updating our database documentation so I've made a note to get this kind of information added in the future.
