### ISSUE TITLE
Add version numbers for memcached, rabbitmq, neo4j, riak (_cci1/build-image-trusty.md)

### ISSUE THREAD

**Issue by vlj91** [circleci/circleci-docs#659]
Memcached and RabbitMQ sections appear to be missing their version numbers:

https://circleci.com/docs/build-image-trusty/#memcached
https://circleci.com/docs/build-image-trusty/#rabbitmq
https://circleci.com/docs/build-image-trusty/#neo4j
https://circleci.com/docs/build-image-trusty/#riak

**Comment by ryanwohara** [comment]
That is no longer the case.
