### ISSUE TITLE
"<N> more" links on /docs/ don't do anything

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#66]
I'm assuming they're supposed to expand?

Example: 
![screen shot 2016-04-12 at 4 52 34 pm](https://cloud.githubusercontent.com/assets/676307/14454879/187bc74c-00cf-11e6-8d14-d41e426ee5a1.png)

**Comment by felicianotech** [comment]
They are suppose to go to the index page for that particular category. Apparently, they broke. I assume when the icons were changed. Looking into this now.

**Comment by felicianotech** [comment]
Apparently this wasn't a recent issue. PR with fix opened.
