### ISSUE TITLE
TypeScript Cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by SoldierAb** [circleci/circleci-docs#6616]
I’m runnning ‘yarn docs:build’ command on my respository https://github.com/SoldierAb/k-view-next, It works on my machine (it builds without errors).
But when I try plugging it into CircleCI , it throws this error:
![image](https://user-images.githubusercontent.com/33128022/160740904-66b9c57c-9bf9-4d0c-86ba-6b60fb41be17.png)

**Comment by devinmarieb** [comment]
Hi @SoldierAb, this seems to be an issue better suited for support. Please open a ticket and chose Build Failure / Configuration help from the dropdown.
https://support.circleci.com/hc/en-us/requests/new
