### ISSUE TITLE
error authentication with ECR

### ISSUE THREAD

**Issue by lacostenycoder** [circleci/circleci-docs#6617]
# Description
Followed example [given here in your documentation](https://circleci.com/docs/2.0/sample-config/) using. We have verified these credentials work locally using the aws-cli and we're able to authenticate without errors. 
```
  aws_auth:
    aws_access_key_id: AWS_ECR_READER_ACCESS_KEY_ID
    aws_secret_access_key: AWS_ECR_READER_SECRET_ACCESS_KEY
```

# Location
https://app.circleci.com/pipelines/github/q-centrix/web/7643/workflows/e739f734-f53f-4459-8bde-b558509701d1/jobs/42510

# Steps to Reproduce
run the job

**Comment by Plataformaalgoritmica** [comment]
Hello World.

**Comment by thomasr8** [comment]
Hello @lacostenycoder: I have reached out to our Engineering and Support teams to help you with your issue. As soon as I have a resolution, I will let you know.

Thank you for letting us know about this issue so we can update the documentation accordingly.

**Comment by rosieyohannan** [comment]
@lacostenycoder which doc were you following here? the link you supplied is just referencing this issue.

**Comment by lacostenycoder** [comment]
@rosieyohannan my bad, updated the url above, but here it is again https://circleci.com/docs/2.0/sample-config/

**Comment by lacostenycoder** [comment]
@thomasr8 ⬆️

**Comment by ogii** [comment]
Hi @lacostenycoder,

When passing in values for authentication, I believe you need to pass in the actual secret value, and not the variable name.
This is reflected in the current version of the linked documentation page.

Could you try changing it to the following (add $ before the variable name)?

```
aws_auth:
    aws_access_key_id: $AWS_ECR_READER_ACCESS_KEY_ID
    aws_secret_access_key: $AWS_ECR_READER_SECRET_ACCESS_KEY
```

This syntax is valid for the image key to allow users to pass in credentials for private images.

There is an additional example here:

https://circleci.com/docs/2.0/private-images/#aws-ecr

Thank you!

**Comment by kbatuigas** [comment]
Hi @lacostenycoder , we'll close this issue within the next day, but if you need further help please reach back out, or you could [contact our support team](https://support.circleci.com/hc/en-us/requests/new) directly as well. Thank you!
