### ISSUE TITLE
All circleci/* images to replace with cimg/* except for some cases

### ISSUE THREAD

**Issue by tnir** [circleci/circleci-docs#6664]
`circleci/*` images were deprecated in 2021, we need to replace them with `cimg/*`.

https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034#deprecation-timeline-11

> Legacy images with the prefix "circleci/" were [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) on December 31, 2021.

**Comment by devinmarieb** [comment]
Closing this since the branch was merged.
