### ISSUE TITLE
Not clear how to use CIRCLECI_OIDC_TOKEN

### ISSUE THREAD

**Issue by q42jaap** [circleci/circleci-docs#6670]
# Missing Information
I need to interact (deploy code) with AWS, but it's unclear how we should use the CIRCLECI_OIDC_TOKEN to hold of a AWS access key/secret/session.
It might be just me, but the amount of docs that don't say what to do exactly makes it really hard to test this. Every aspect must be right in order for it to work. And it's not easy to test parts of the flow separately.

# Already Looked
The page that explains about CIRCLECI_OIDC_TOKEN: https://circleci.com/docs/2.0/openid-connect-tokens/
Also the page on AWS that explains the concept: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html

# Potential Locations
For example, the docs on github.com to achieve this with Github actions is a lot more understable:
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

**Comment by devinmarieb** [comment]
@q42jaap Thanks for the feedback! The page is new, so I will ask the team if there's more clarity we can provice.

**Comment by devinmarieb** [comment]
@q42jaap Quick update - the team is working on a tutorial specifically for AWS that is being released next week on our blog and we will work the tutorial into the docs. I'll send the link when I have it :)

**Comment by devinmarieb** [comment]
@q42jaap Here is the blog post. We will work the content into the docs soon. Hope this helps!
https://circleci.com/blog/openid-connect-identity-tokens/
