### ISSUE TITLE
Example on /adv-config does not work

### ISSUE THREAD

**Issue by tnir** [circleci/circleci-docs#6673]
# Description
Example for Cloud/Server v3/Server v2 does not work.

Initial problem would be like:
```
Starting container cimg/postgres:9.6.5
Digest: sha256:eaeccafddaeb7681620190188dda0619c7cc79c8dba9d6fda92967f2099b16c4200B/200B8MB
Status: Downloaded newer image for circleci/python:3.6.2-stretch-browsers
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading cimg/postgres:9.6.5

Error response from daemon: manifest for cimg/postgres:9.6.5 not found: manifest unknown: manifest unknown
```
from https://app.circleci.com/pipelines/github/tnir/circleci-docs-pr-6660/1/workflows/28c59b34-2c83-41cf-b4d7-3ad7f7260956/jobs/1

# Location
https://circleci.com/docs/2.0/adv-config/

# Steps to Reproduce
Copy and run the example on https://circleci.com/docs/2.0/adv-config/. Example is prepared at https://github.com/tnir/circleci-docs-pr-6660/pull/1

**Comment by devinmarieb** [comment]
Hi @tnir thanks for pointing out that our example uses a version that we no longer support. We will update the examples to `<version>` and link out to the available versions we support on the [Developer Hub](https://circleci.com/developer/images/image/cimg/postgres#image-tags).
