### ISSUE TITLE
bytesguy/danger doesn't work

### ISSUE THREAD

**Issue by romansorochak** [circleci/circleci-docs#6729]
# Description
I'm investigating `CircleCI` and was trying to adopt [Testing iOS Applications / Using Multiple Executor Types ](https://circleci.com/docs/2.0/testing-ios/#using-multiple-executor-types-macos-docker). 
Though it gives me an error below.
<img width="1452" alt="Screenshot 2022-04-25 at 20 52 30" src="https://user-images.githubusercontent.com/7702356/165145739-5c3cc4b8-ed91-4842-95f0-98f379b9cc7d.png">

# Location
https://circleci.com/docs/2.0/testing-ios/#using-multiple-executor-types-macos-docker

# Steps to Reproduce
1. Create a fresh Xcode iOS project
2. Add `Dangerfile` (attached below)
3. Modify `.circleci/.config.yml` (attached below)
4. Create `PAT` on `GitHub` and save it in `CircleCI / Project Settings / Environment Variables` under the key - `DANGER_GITHUB_API_TOKEN`
5. Open `PR` on `GitHub`

## Attachments

[bytesguy:danger issue attachments.zip](https://github.com/circleci/circleci-docs/files/8556824/bytesguy.danger.issue.attachments.zip)

**Comment by devinmarieb** [comment]
@romansorochak Thanks for bringing this to our attention! I will check in with @BytesGuy -- upon a first glance, I don't see this image listed as being supported anymore, which would mean this example is much out of date.

**Comment by BytesGuy** [comment]
The danger and swiftlint images were only quickly re-made a couple of years ago when this section was last updated. The previous image was made by an employee that had left and it was no longer available/not working. These images are not officially supported by CircleCI so we should probably just remove them from the docs entirely now and replace it with a better example. I don't intend to maintain these images as I don't have the bandwidth to do so (side note, this did seem to work locally for me, but ymmv I guess)

**Comment by devinmarieb** [comment]
We've opened a ticket to address this. I'm going to close this issue, but if anything further is needed to solve your problem we can revisit. Thanks for brining this to our attention!
