### ISSUE TITLE
Replace buildpack-deps and circleci/buildpack-deps with cimg/base

### ISSUE THREAD

**Issue by tnir** [circleci/circleci-docs#6746]
Replace `circleci/buildpack-deps` images with `cimg/base`.

See https://circleci.com/docs/2.0/next-gen-migration-guide/#deprecated-images

While Docker's official `buildpack-deps` are not deprecated, let us replace `buildpack-deps` images with `cimg/base` in the circleci-docs repo as well at the time.

See also #6732

## TODOs

- [ ] #6749
- [x] #6750
- [x] #6751

----

### Original comments from @devinmarieb

> @tnir Hey, this one is a little trickier! It definitely needs to get updated, but `circleci/buildpack-deps` will need to get updated with `cimg/base`. Feel free to adjust the PR otherwise we will make an internal ticket for it. You can read about it in the [Discuss](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) post. Also related in the docs is this [migration page](https://circleci.com/docs/2.0/next-gen-migration-guide/#deprecated-images).

_Originally posted by @devinmarieb in https://github.com/circleci/circleci-docs/issues/6732#issuecomment-1111421144_

**Comment by rosieyohannan** [comment]
🎉 👏
