### ISSUE TITLE
Default Elasticsearch version is incorrect (_cci1/installing-elasticsearch.md)

### ISSUE THREAD

**Issue by lchin-gpsw** [circleci/circleci-docs#676]
Hmm.. My default elasticsearch is still 0.9.x.  You need to correct this documentation.

**Comment by keybits** [comment]
Thanks for letting us know about this. 1.7.2 is the version on our 14.04 Build image which is the default. It sounds like your still on our 12.04 image?

You can change the build image via the menu in Project settings > Build environment. You'll need to trigger a new build by pushing a commit once you've made this change (just running a 'rebuild' will reuse the same build image). 

Closing this for now.
