### ISSUE TITLE
Android license procedure needs update

### ISSUE THREAD

**Issue by andreidiaconu** [circleci/circleci-docs#677]
On this [page](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/android.md) it is stated that in order to accept licenses, one needs to use `echo y | android update sdk --no-ui --all --filter "package-name"`. This is correct, but incomplete, as this no longer works for ConstraintLayout. 

As a solution, developers can to use `sdkmanager`, as described in this [SO response](http://stackoverflow.com/a/42505589/2710246). When I'll have the time, I will make a PR with an edit to the circleCI docs, but until then maybe someone can view the answer and confirm that this is a good solution. Maybe even update the docs to point the user to use `sdkmanager` in all situations with a link to the [official docs](https://developer.android.com/studio/command-line/sdkmanager.html) and also update the SDK Tools on the machines to the latest version.

This will have to get done eventually, as `sdkmanager` becomes the default package manager for android.

**Comment by marcomorain** [comment]
@andreidiaconu thanks for point this out 👍 - we appreciate it. I'm going to share that SO link about `sdkmanager` around our mobile team.

**Comment by smart-alek** [comment]
@andreidiaconu picking up from where @marcomorain left off. We _believe_ you were using CircleCI 1.0 when you filed this issue, which has both good and bad bits attached. The bad: we're not going to fix this issue. The good: moving to CircleCI 2.0 should make this a non-issue _and_ give you some extra speed — Android is 5-10 times faster on 2.0.

SO! Long-winded, but I hope you understand why we're keeping our focus on 2.0. Thanks!

**Comment by andreidiaconu** [comment]
Sounds good to me. Thanks for the update on this issue. We plan on
switching to 2.0 asap so this will indeed no longer affect us.
