### ISSUE TITLE
mistranslation in はじめてのビルドの成功（グリーンビルド）

### ISSUE THREAD

**Issue by a-takahashi223** [circleci/circleci-docs#6795]
# Location

https://github.com/circleci/circleci-docs/blob/4934e91b63cdb332fb2501e15bd270ffb33ca1b3/jekyll/_cci2_ja/getting-started.md?plain=1#L40

# Error Details

> CI スターターパイプラインを新しいブランチにコミットするを選択し、config.yml のスターターテンプレートの使用を選択し、

I don't understand.

In English page,

https://github.com/circleci/circleci-docs/blob/4934e91b63cdb332fb2501e15bd270ffb33ca1b3/jekyll/_cci2/getting-started.md?plain=1#L40

> Select the option to commit a starter CI pipeline to a new branch

It is clear what needs to be done.

**Comment by devinmarieb** [comment]
@Mayuko-Sa could you take a look at this, thank you!

**Comment by Mayuko-Sa** [comment]
@a-takahashi223 Thanks for the heads-up! I will fix this translation.

**Comment by devinmarieb** [comment]
@Mayuko-Sa Thank you! I will close this ticket then.
