### ISSUE TITLE
Circle CI "copy link" button on links does not "copy"

### ISSUE THREAD

**Issue by johncorderox** [circleci/circleci-docs#6796]
# Description
When reading the CircleCI docs, it seems as though hovering over a hyperlink Title opens the "Copy Link" helper text, yet when clicking on "copy link", It does not paste with either "Command + V" or "right-click + paste"

# Location
[Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.](https://circleci.com/docs/2.0/enable-checks/)

# Steps to Reproduce

1. Hover over the text "GitHub Check and GitHub status updates" and click on the chain icon next to the text
2. Click the icon which displays "Copy Link"
3. Command + V or paste somewhere
4. Notice the URL bar will display the correct hyperlink but it does not allow me to paste 
<img width="579" alt="Screen Shot 2022-05-11 at 11 45 50 AM" src="https://user-images.githubusercontent.com/12385343/167923560-8ffe73aa-5403-40f0-b907-60f209b3bf20.png">

I hope this makes sense!

**Comment by devinmarieb** [comment]
@johncorderox Thanks, we're looking into it!
