### ISSUE TITLE
Feedback and suggested edits to Google Container (_cci1/continuous-deployment-with-google-container-engine.md)

### ISSUE THREAD

**Issue by ahmetb** [circleci/circleci-docs#684]
I have spotted a few issues with https://circleci.com/docs/1.0/continuous-deployment-with-google-container-engine/. First of all it's a great piece of tutorial/samples, I really appreciate it. It took me a few builds to get it straight, but within 10 minutes I was ready to go!

### 1. kubectl needs Application Default Credentials 

For some reason, kubectl needs `GOOGLE_APPLICATION_CREDENTIALS` env var to be set: to work, otherwise it complains about app default credentials. I reported this to GKE team, as it looks like `gcloud auth activate-service-account --key-file` does not benefit `kubectl`.

So you can just add this to `env:`:

     GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/account-auth.json

### 2. circle.yml feedback

- This line seems redundant: https://github.com/circleci/docker-hello-google/blob/d1c082e6d55525d3cbb8be72cdfa2fabb2ca9471/circle.yml#L17

- This line setting `zone` is redundant too: https://github.com/circleci/docker-hello-google/blob/d1c082e6d55525d3cbb8be72cdfa2fabb2ca9471/circle.yml#L19 you can just pass `--zone` to `get-credentials` command.

- `$ACCT_AUTH` on this line should be `$GCLOUD_SERVICE_KEY` to be compatible with the [tutorial](https://circleci.com/docs/1.0/continuous-deployment-with-google-container-engine/).

**Comment by gkop** [comment]
This one will definitely stump people: https://github.com/circleci/circleci-docs/pull/962

**Comment by sha1sum** [comment]
FYI: Documentation has been PR'd for 2.0 GKE deployment. It does not address everything in this issue, but for those looking for 2.0 documentation, it will likely assist.

#1073
