### ISSUE TITLE
Concrete numbers for API Rate Limit

### ISSUE THREAD

**Issue by Eldrick19** [circleci/circleci-docs#6861]
# Missing Information
Looking for a concrete value for API rate limits (e.g. X requests / hour) 

# Already Looked
I've looked in the following pages:
- https://circleci.com/docs/2.0/api-developers-guide/#rate-limits
- https://circleci.com/docs/api/v2/
- https://circleci.com/docs/2.0/configuration-reference/

# Potential Locations
I would expect to find it in the following docs (in order of priority):
- https://circleci.com/docs/2.0/api-developers-guide/#rate-limits
- https://circleci.com/docs/2.0/configuration-reference/

**Comment by Eldrick19** [comment]
For example, GitHub highlights its GitHub Actions rate limits like: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions

**Comment by devinmarieb** [comment]
Hi @Eldrick19, we don't explicitly post rate limits for a few reasons, one of which is our rate limits are not necessarily set in stone, and rate limits change depending on what plan someone is using. Our rate limits are in place to stop malicious activity, and regular users/organizations using CircleCI are not expected to hit rate limits. If you do hit rate limits, I would suggest reaching out to support.

**Comment by Eldrick19** [comment]
Thanks for the response @devinmarieb that makes sense and was my suspicion. Would you find it valuable mentioning this in the docs?

> rate limits are not necessarily set in stone, and rate limits change depending on what plan someone is using

Not necessary for me at this point but just a suggestion. Feel free to close out this issue 👍🏾

**Comment by devinmarieb** [comment]
@Eldrick19 Yeah I can see what some of the engineering teams say about including that. It's worth mentioning also that different parts of the API will have different rate limits as well. Again, we don't expect people to hit them necessarily, but it's not a standard limit in that regard either.
