### ISSUE TITLE
Job Status "type" is presumably an enum, but documented as "any" and not clear as to its final type

### ISSUE THREAD

**Issue by adamtaylor13** [circleci/circleci-docs#6874]
# Missing Information
Give a brief overview of the information you were looking for.

I expected that similar to the "enum" defined by Workflow's "status" or Pipeline's "state", I'd find a Job's "status" type defined.
For example, a workflow defines the following for "status":
<img width="994" alt="CleanShot 2022-05-30 at 21 25 15@2x" src="https://user-images.githubusercontent.com/2922753/171080462-fa0aa93a-ec38-4cd9-8493-be92b98c4a7c.png">

It's quite possible I'm making false assumptions here, but while working with the API, I always seem to get an enum-ish string back which makes me think perhaps the job's status is indeed an enum?

Another piece of evidence that this might be the case is that I'm getting the jobs from `/workflow/<workflow_id>/job` which maybe just applies the parent workflow's status on this job? 🤔 If that is the case, perhaps a note on the Job object stating:
> Inherits the parent workflow's status

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

- https://circleci.com/docs/api/v2/#operation/getJobDetails
![CleanShot 2022-05-30 at 21 22 33@2x](https://user-images.githubusercontent.com/2922753/171080247-9036cfde-96be-4594-abad-f36065f5e942.png)

- I also dug around the Jekyll site a bit, to no avail: https://circleci.com/docs/2.0/api-developers-guide/#get-job-details

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.
I think just having this documented in https://circleci.com/docs/api/v2/#operation/getJobDetails would make sense.

**Comment by kbatuigas** [comment]
Thanks for opening this @adamtaylor13 - we'll double-check with our team and let you know when we have more info.
