### ISSUE TITLE
Broken link to Project Values and Variables guide.

### ISSUE THREAD

**Issue by dobesv** [circleci/circleci-docs#6878]
# Locations

https://circleci.com/docs2/2.0/pipeline-variables

# Details

If I click on the link to "[Project Values and Variables guide](https://circleci.com/docs2/docs/2.0/variables#pipeline-values)" I get a 404 page.

**Comment by devinmarieb** [comment]
Opening this again as the problem has resurfaced.

**Comment by devinmarieb** [comment]
This issue has been resolved as part of our update to some docs architecture :)
