### ISSUE TITLE
Its unclear how long caches last

### ISSUE THREAD

**Issue by piersy** [circleci/circleci-docs#6909]
# Location
https://circleci.com/docs/2.0/caching/#introduction

# Explanation
In the linked document it is stated that
>By default, cache storage duration is set to 15 days

It's not clear whether that means that all caches will last exactly 15 days or caches will persist for 15 days after their most recent restore?

**Comment by devinmarieb** [comment]
@piersy Caches are not saved unless there is a (re)build. So if day 15 rolls around and the cache has not been built again, it will expire. If the cache is rebuilt on day 14, the retention period will start over, with the default retention period being 15 days.

If you have a paid account, you can read about how billing cycles relate to retention periods in the Custom Storage Usage section of the Persisting Data page.
https://circleci.com/docs/2.0/persist-data/#custom-storage-usage

Let me know if you need more clarity!

**Comment by piersy** [comment]
Thank you @devinmarieb, would you be able to clarify what events could cause a cache rebuil?

**Comment by devinmarieb** [comment]
The only time when a cache is built is during `save_cache`. If CircleCI sees a cache with an existing key, we will not update it. If your cache's retention period has passed, CircleCI sees it as a new cache to store the next time that key is used, which would be a "rebuild" on the your end.

**Comment by devinmarieb** [comment]
@piersy Yep!

**Comment by piersy** [comment]
Great! Thank you @devinmarieb!

**Comment by piersy** [comment]
Hi @devinmarieb, sorry to re-open this but looking at some old builds I'm seeing caches reused that were much older than 15 days.

I've checked the Plan -> Usage Controls and we have the default setting of 15 days for the cache.

I noticed that when a cache is restored the logs tell you what job that cache is from.

```
Found a cache from build 79285 at system-contracts-cache-celo-core-contracts-v3.rc0-compiled-system-contracts-v1-celohq/node10-gcloud:v3
```

That log was from a job that ran on the 20th May 2022

The referenced job ran on 14th Feb 2022 which is 95 days prior, interestingly job 79285 did not actually build the cache it restored a cache from a prior job which did build the cache and ran on 6th Feb 2022, which means this cache existed for at least 104 days.

**Comment by devinmarieb** [comment]
@piersy I had to double check with the team working on the storage features, but the cache in this instance is from before we started enforcing retention periods. The likely scenario is CircleCI will purge older caches soon, but you would not be charged for the retention of older caches.

**Comment by piersy** [comment]
Hi @devinmarieb thank you for checking, do you know the date that the retention periods started being enforced?
