### ISSUE TITLE
Fixes Needed for Recent Build Image Changes

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#70]
Pages now 404ing that we need to redirect:
- https://circleci.com/docs/environment/
- https://circleci.com/docs/trusty-image/

Pages with links without trailing slashes:
- jekyll/_docs/configuration.md
- jekyll/_docs/manually.md
- jekyll/_docs/time-seconds.md

Pages with links containing double trailing slashes:
- jekyll/_docs/language-ruby-on-rails.md

**Comment by felicianotech** [comment]
@BellaSpence The first work item was addressed by Kim: https://github.com/circleci/circleci-docs/pull/74

I'm not sure where you're at but if you didn't get to that, it's done. If you did, you'll have a merge conflict now unless you drop your changes.

**Comment by BellaSpence** [comment]
@felicianotech Yeah. I had to stash my work.... It' ok. getting it back on track

**Comment by felicianotech** [comment]
@BellaSpence Another option would have been to switch to master, pull the latest changes, switch back to your branch, and rebase on master. Like this:

```
# Commit any changes in your current branch.
git checkout master
git pull
git checkout my-branch
git rebase master
```

**Comment by felicianotech** [comment]
Completed in #76
