### ISSUE TITLE
Grammatical error in Collecting test data document

### ISSUE THREAD

**Issue by hoanghiep20146283** [circleci/circleci-docs#7019]
# Location
https://circleci.com/docs/2.0/collect-test-data

# Error Details
In this section: https://circleci.com/docs/2.0/collect-test-data#viewing-storage-usage there may be a typo:
"For information on viewing your stoarage usage, ..."

<img width="950" alt="image" src="https://user-images.githubusercontent.com/44150058/176373613-dee54dc6-f61b-420d-ba9a-edb1a831042a.png">

**Comment by kbatuigas** [comment]
Hi @hoanghiep20146283 , thanks for bringing this to the CircleCI team's attention! We will be publishing a fix shortly.
