### ISSUE TITLE
Update text for "Open an issue about this page"

### ISSUE THREAD

**Issue by smart-alek** [circleci/circleci-docs#706]
Most issues that get created by our users have titles in the format of:

"RE: jekyll/_docs/<name_of_doc>"

While this does tell us _where_ the issue is, it doesn't do a good job of summarizing the issue for development and maintenance. Instead, let's have the issue pull just the name, then require the issue creator to specify what the problem is. Like so:

"<name_of_doc>: <action_item>"

**Comment by felicianotech** [comment]
@smart-alek This can already be done now. If we want to force users to write something in the subject, then we should probably just leave it blank. I think they won't add to the title if that's what we put there.

**Comment by smart-alek** [comment]
So you're saying that leaving it blank will force a description? Cool, yeah, I'd like to try this out.
