### ISSUE TITLE
Migrate from scheduled workflow to pipeline with multiple branches

### ISSUE THREAD

**Issue by randi274** [circleci/circleci-docs#7076]
# Missing Information
I'm looking to migrate a scheduled workflow to use a pipeline. The workflow currently triggers two branches, but it's unclear how to recreate this with triggers. I'm looking to recreate the following workflow, and I think the only way to do it currently is with two almost identical `triggers`. It would be great if the docs could confirm as much.

`daily-build:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - develop
                - main`

# Already Looked
[This](https://circleci.com/docs/scheduled-pipelines#migrate-scheduled-workflows) is where I would expect it to be. Additionally, it could be good to mention this on the API documentation.

**Comment by kelvintaywl** [comment]
hi @randi274 

thank you for your updates!
I see now, that this is a scheduled workflow to run only on your `develop` and `main` branch , and at 00:00 UTC every day then.

We can map this to a scheduled pipeline, as following the document indeed, with the following:

1) Remove the `triggers` section within this `scheduled-workflow` declaration.

```diff
  scheduled-workflow:
-   triggers:
-     - schedule:
-         cron: '0 0 * * *'
-         filters:
-           branches:
-             only:
-               - develop
-               - main
    jobs:
      - build-all
```

2) Add conditions on this workflow to ensure it can only be triggered on a schedule (via scheduled pipeline)

```diff
  scheduled-workflow:
+   when:
+     and:
+       - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
+       - or:
+           - equal: [ main, << pipeline.git.branch >> ]
+           - equal: [ develop, << pipeline.git.branch >> ]
    jobs:
      - build-all
```

3) Set up the scheduling [via API](https://circleci.com/docs/scheduled-pipelines#api), or [via the UI](https://circleci.com/docs/scheduled-pipelines#project-settings) which is arguably more convenient.

For setting this up via the UI, I think perhaps some screenshots in the doc could have been useful.
With scheduled pipelines, **you can only specify 1 branch per schedule.**
In other words, we would thus need to create 2 schedules then in your case.

Here is an example when you are setting up for the `main` branch.
<img width="690" alt="Screen Shot 2022-07-14 at 8 01 59" src="https://user-images.githubusercontent.com/2164346/178890646-10bcee41-6383-4254-9a5a-2dae219137d2.png">

One important difference to note, regarding scheduled pipelines, is that you cannot specify the exact minute the schedule runs.

In the example above, we are asking CircleCI to schedule this pipeline to run once per hour from 00:00.
In this case, it does not necessarily run at 00:00 UTC but will definitely be triggered between 00:00 to 00:59 UTC then.
You can read more about this under our FAQ: https://circleci.com/docs/scheduled-pipelines#faq:~:text=Q%3A%20Why%20did%20my%20scheduled%20pipeline%20run%20later%20than%20expected%3F

Hope this helps!

**Comment by randi274** [comment]
@kelvintaywl thanks for the screenshots, those are immensely helpful! The part that was confusing especially was the "you can only specify 1 branch per schedule.", which would be great to add explicitly in the docs. But if that's tracked separately I'm good to close this issue 👍

**Comment by kelvintaywl** [comment]
Hi @randi274

I'm glad to hear that this was helpful.
Indeed, I have made a PR here at #7101 to address this note about 1 branch per schedule.

I'm checking in with the Documentation team to have this PR reviewed then.

**Comment by kelvintaywl** [comment]
@randi274 I will go ahead and close this issue, since i believe your issue is addressed, in addition to us updating our docs! :)
