### ISSUE TITLE
When the language setting is set to Japanese, link to the API reference is 404.

### ISSUE THREAD

**Issue by ouchi2501** [circleci/circleci-docs#7125]
# Description

I'm expecting `https://circleci.com/docs/api/v2` , but it's `https://circleci.com/docs/ja/api/v2`
The API reference does not have a page with Japanese support, but the link path contains `ja`, so it seems to be a 404.
As far as I have observed, this phenomenon seems to occur for all links to references, including those in the sidebar and in the document.
![スクリーンショット 2022-07-21 17 55 43](https://user-images.githubusercontent.com/11391317/180173608-ae1a44d1-0b42-48b7-a401-7f3521856621.png)
https://circleci.com/docs/ja/api/v2
![スクリーンショット 2022-07-21 16 51 22](https://user-images.githubusercontent.com/11391317/180173622-b18754cc-d8bc-470d-bef0-82fb9cf32ef2.png)

# Location
sidebar
https://circleci.com/docs/ja/api-intro
https://circleci.com/docs/ja/webhooks
etc...

# Steps to Reproduce
Set the language setting to Japanese and click on the link to the API Reference

**Comment by devinmarieb** [comment]
@ouchi2501 Thanks! Someone is looking into this.

**Comment by devinmarieb** [comment]
Sorry for the late response, but this issue has now been resolved.
