### ISSUE TITLE
Undocumented Conditional `<<# >> <</ >>` syntax

### ISSUE THREAD

**Issue by Xavientois** [circleci/circleci-docs#7130]
# Missing Information
I was looking through a project that used the `<<# parameter >> <</ parameter >>` and  `<<^ parameter >> <</ parameter >>` syntax, but it took me a long time to figure out what it did since it is not documented anywhere.

# Already Looked
 - https://circleci.com/docs/configuration-reference
 - https://circleci.com/docs/pipeline-variables
 - google.com

# Potential Locations
- https://circleci.com/docs/configuration-reference

**Comment by devinmarieb** [comment]
Hi @Xavientois that syntax is actually [mustache syntax](http://mustache.github.io/mustache.5.html). The << and >> are proprietary and what we use to define the tags, and what's inside those tags is mustache syntax for some logic. We had removed most of the mustache syntax out of the docs, but it looks like we might have missed a page. Were you looking at the examples on the Reusable Config Reference Guide?
https://circleci.com/docs/reusing-config

**Comment by Xavientois** [comment]
@devinmarieb That was one of the only places that I was able to find it in the docs. I eventually found out that it is mustache syntax.

Is the reasoning behind removing it from the docs to discourage new users from using this syntax in unintended ways?

**Comment by devinmarieb** [comment]
@Xavientois My guess would be that we don't want to officially support it, and some older code snippets just haven't been updated by the engineering teams with a preferred way of doing it yet. Using mustache should be fine though if people want to use it (I'm not aware of any official effort to _not_ support it), it's just no longer the preferred method. In the past we did find that some users found the syntax confusing. I'll take another look at any examples we have left and see if those teams can get better examples in there.

**Comment by devinmarieb** [comment]
@Xavientois We've updated the code snippet on this page, though the current version of the orb it's referencing still uses Mustache behind the scenes, so we've made a note of that as well.
