### ISSUE TITLE
Clarify use of :username and/or provide real API sample (_cci1/api.md)

### ISSUE THREAD

**Issue by rosskevin** [circleci/circleci-docs#716]
`:username` is misleading in the api docs, rather it is `:organization_or_username`. Perhaps a section that explains each path param's usage would be nice.  

This may be less of an issue if the tokenized samples also provided a real sample and you could look up

**Comment by ryanwohara** [comment]
```Project Username (:username)
This is the GitHub or Bitbucket project account username for the target project (not your personal GitHub or Bitbucket username).```
