### ISSUE TITLE
Adding status badge for private repo 

### ISSUE THREAD

**Issue by mariesalet** [circleci/circleci-docs#7186]
# Missing Information
Give a brief overview of the information you were looking for.
Adding a status badge for a private repo fails when following the example in the document.
https://circleci.com/docs/status-badges.

This worked: 
[![Build Status](https://circleci.com/gh/<my-private-network>/<my-private-project>/tree/main.svg?style=svg&circle_token=<my-api-token>)](https://circleci.com/gh/<my-private-network>/<my-private-project/?branch=main&circle_token=<my-api-token>)

# Already Looked
Provide a list of places you've already looked for this information.
Found the answer here:
https://discuss.circleci.com/t/circleci-badge-not-displaying-on-private-repository/37955

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.
The existing document examples for a private repo would be most helpful.

**Comment by kbatuigas** [comment]
Hi @mariesalet , 

Thank you for reaching out. I was unable to reproduce the issue (i.e. I was able to get the status badge display for a private project). You may want to double check that you've added the API token with a scope of "Status" as mentioned in this section of the doc: https://circleci.com/docs/status-badges#creating-badges-for-private-repositories

If you are still unable to get the badge to display, please reach out to our Support team by [submitting a new request](https://support.circleci.com/hc/en-us/requests/new), and our colleagues will be able to investigate further. Best of luck!
