### ISSUE TITLE
Remove `CI_PULL_REQUESTS` from _cc1/environment-variables.md

### ISSUE THREAD

**Issue by smart-alek** [circleci/circleci-docs#720]
This environment variable is not actually supported. Might be worth it to do a once-over of this entire file to see if there are any other discrepancies between documentation and reality.

**Comment by felicianotech** [comment]
@smart-alek Check Jira. You're correct that it's not available but it's because there's an open bug for this. this is suppose to exists and once the bug fix lands, will be back.

**Comment by smart-alek** [comment]
@felicianotech Where on JIRA?

**Comment by felicianotech** [comment]
@smart-alek There's two related tickets. I'll PM you.

**Comment by smart-alek** [comment]
Related JIRA tickets:

https://circleci.atlassian.net/browse/CIRCLE-2630
https://circleci.atlassian.net/browse/CIRCLE-3037
