### ISSUE TITLE
RE: jekyll/_cci2/parallelism-faster-jobs.md

### ISSUE THREAD

**Issue by kevart** [circleci/circleci-docs#722]
* Does this only work for java?
* Can it be used to parallelize other tasks e.g. task 1: spin up a server, task 2: curl the server

**Comment by smart-alek** [comment]
Hey @kevart!

1. Nope, this tool is language agnostic.
2. My understanding is that this tool was only designed to run _tests_ in parallel. I believe there's a setting in the actual `config.yml` that allows you to run other tasks in parallel.

Friendly reminder: please ask questions on our [Discuss forum](https://discuss.circleci.com/); you'll generally get a faster, better response from support engineers, and then other people can search the info you got.
