### ISSUE TITLE
gain access to contract

### ISSUE THREAD

**Issue by rdotterer09** [circleci/circleci-docs#7244]
I asked for circle to upgrade my contract so I would have access to it, I got in return an upgraded EVM contract, exactly what I was trying to get out of, how can this be resolved?

**Comment by devinmarieb** [comment]
Hi @rdotterer09, it seems like you are looking for support on your account/contract. Our support page can be found here: https://support.circleci.com/hc/en-us/requests/new and you can choose **Accounts / Billing** from the drop down menu.

**Comment by rdotterer09** [comment]
Thank you
