### ISSUE TITLE
Add clarification around direct usage of hostname (_cci1/adding-read-write-deployment-key.md)

### ISSUE THREAD

**Issue by kutenai** [circleci/circleci-docs#725]
This does not work. At all. I feel you are missing some critical information here.

The new key I've added based on this does not get used for git, so I still can't push to git.. I don't know what other steps are needed to make this work, but they are not listed here.

Overall, I've found that CircleCI documentation is horrible. As soon as I have some time, I'll switch from this poorly documented system. Sorry, but that's how I feel right now ofter spending literally HOURS spinning my wheels to do simple shit.. I want to use npm version to update the version and create a tag. This just won't work, and I pretty much lay the blame at your poor documentation for causing me HOUR AND HOURS of wasted time.

**Comment by kutenai** [comment]
After messing with this a while, I finally realized that you use the hostname as an entry in .ssh/config, and the host name has to match github.com.

If course I re-read the instructions and you said use github.com in the hostname, but I had use a name that identified the 'purpose' of this key, not the hostname. I followed more of a pattern from github where you identify the key, not realizing that the hostname was used directly.

Please add that to the documentation.

**Comment by smart-alek** [comment]
Hey @kutenai, sorry to hear about your crappy experience with the 1.0 docs. We're aware that those are bloated and often out of date or missing information.

The good news is that we're thinking much more carefully about our [2.0 docs](https://circleci.com/docs/2.0/), so if you haven't already tried that out, please do!

**Comment by ryanwohara** [comment]
https://github.com/circleci/circleci-docs/pull/1843
