### ISSUE TITLE
Clarify support for custom OIDC verification scripts

### ISSUE THREAD

**Issue by Michael-Wheeler** [circleci/circleci-docs#7297]
# Missing Information
I would like to use OIDC for auth when deploying to a private, custom package repo. I won't be able to use the GCP or AWS integrations documented in [Using OpenID Connect Tokens in Jobs](https://circleci.com/docs/openid-connect-tokens), as the resources will access a private server. 

As far as I can tell, with OIDC being an open standard, I can use a custom authoriser that verifies CicleCI OIDC tokens using OpenID Connect Discovery to access the public key. I can use the information in the token to manage authorisation.

Before I do this, I would like to check that this is a valid use case and that the ability to use a custom authoriser won't somehow be removed in future. 

If it is possible, it could be useful to add in the documentation, as it opens up a lot of possibilities. An example of GitHub documenting/validating the approach can be found [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#using-custom-actions). It would also then be useful to add an example token so that we can easily see all the content that is sent.

Thank you for any help you can give.

# Already Looked
[Using OpenID Connect Tokens in Jobs](https://circleci.com/docs/openid-connect-tokens)

# Potential Locations
After the official cloud provider documentation here: "[Using OpenID Connect Tokens in Jobs](https://circleci.com/docs/openid-connect-tokens)"

**Comment by devinmarieb** [comment]
Hi @Michael-Wheeler, our OIDC token conforms to OpenID standard, so validation of ID Token (the OIDC token in jobs) can be done manually by following the steps in the [OpenID official doc](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitTokenValidation). CircleCI is/will continue to be compliant with OIDC standard. We've included the OpenID claims in our docs, which goes over the content that can be sent [here](https://circleci.com/docs/openid-connect-tokens#format-of-the-openid-connect-id-token).

**Comment by Michael-Wheeler** [comment]
Great, thank you
