### ISSUE TITLE
How to use latest python version instead of specific version

### ISSUE THREAD

**Issue by peter-wangxu** [circleci/circleci-docs#730]
Currently, I have to specify multiple specific python version to trigger tox:
```ini
-machine:		
 -  post:		
 -    - pyenv global 2.7.12 3.4.4 3.5.2 3.6.0		
 -
```

however, I want to test the latest 2.7.x 3.4.x3.5.x 3.6.x installed on the build image.
when i removed above description, error thrown:
https://circleci.com/gh/peter-wangxu/persist-queue/75?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
ERROR: InvocationError: Failed to get version_info for python3.4: pyenv: python3.4: command not found

The `python3.4' command exists in these Python versions:
  3.4.3
  3.4.4


py35 create: /home/ubuntu/persist-queue/.tox/py35
ERROR: InvocationError: Failed to get version_info for python3.5: pyenv: python3.5: command not found

The `python3.5' command exists in these Python versions:
  3.5.1
  3.5.2


py36 create: /home/ubuntu/persist-queue/.tox/py36
ERROR: InvocationError: Failed to get version_info for python3.6: pyenv: python3.6: command not found

The `python3.6' command exists in these Python versions:
  3.6.0
```

**Comment by smart-alek** [comment]
Hey @peter-wangxu! This is a great question for our [Discuss](https://discuss.circleci.com/) forum. Head on over there and get some help from other users and our support engineers. :)
