### ISSUE TITLE
Unclear: Use private images without explicit authentication - specifies auth

### ISSUE THREAD

**Issue by ecki** [circleci/circleci-docs#7366]
# Location

https://circleci.com/docs/docker-hub-pull-through-mirror

# Explanation

the document lists the script as a sample to verify the authenticationless access while it still lists auth_username and auth_password. Maybe the text needs to explain when this (other) user is needed and for what?

BTW the whole document probably should also address private registries and how to mix them with dockerhub pull-through mirrors.

**Comment by rosieyohannan** [comment]
Hello @ecki! Sorry for the huge delay in responding, can I just check if you use an installation of CircleCI server?
