### ISSUE TITLE
Document timing from Junit Test Results

### ISSUE THREAD

**Issue by thomasmatecki** [circleci/circleci-docs#7421]
# Missing Information
If I wish to parallelize by file, Where does CircleCI expect timing information to be in a junit XML?

I have an report like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0">
  <testsuite name="Root Suite" timestamp="2022-09-30T15:00:44" tests="0" file="cypress/e2e/SomeFeature.cy.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Describe Some Part of Something" timestamp="2022-09-30T15:00:44" tests="3" time="16.1050" failures="0">
...
    </testcase>
  </testsuite>
</testsuites>
This doesn't work, ostensibly because the testsuite with a file (is that the attribute circle expects?) has time=0.00 and no tests. So it must be something else. I can get this file in any format CircleCI needs using either an XML transformation or a custom reporter.
```
Here's a guess:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0">
  <testsuite name="Root Suite" timestamp="2022-09-30T15:00:44" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite 
        name="Describe Some Part of Something" 
        timestamp="2022-09-30T15:00:44" 
        tests="3" 
        time="16.1050"
        file="cypress/e2e/SomeFeature.cy.ts" 
        failures="0">
...
    </testcase>
  </testsuite>
</testsuites>
```
or maybe this?
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0" file="cypress/e2e/SomeFeature.cy.ts" >
...
</testsuites>
```
It'd be good if this was documented. Right now I have to spend time and Circleci credits trying to figure out the format the platform expects. It'd be much easier to justify using CircleCI over your competitors if this was more seamless.

# Already Looked
https://circleci.com/docs/parallelism-faster-jobs
https://circleci.com/docs/collect-test-data

# Potential Locations

**Comment by 0xcompton90** [comment]
Agreed 👍🏻

**Comment by kbatuigas** [comment]
Hi @thomasmatecki - thanks for reaching out. I'm on the Docs team at CircleCI and will help get some answers for you; I'll get back to you as soon as I have more info.

**Comment by 0xcompton90** [comment]
> Hi @0xcompton90 👋 - thanks for reaching out.

**Comment by kbatuigas** [comment]
Hey @thomasmatecki -- thanks for your patience as we investigate. Test splitting by filename doesn't take into account timing information. Did you have a specific reason or goal for determining where CircleCI expects timing data in the XML file?

**Comment by thomasmatecki** [comment]
> Test splitting by filename doesn't take into account timing information.

For clarity, I'm splitting by `timings`, but using filenames as inputs to my test command. The closest example in the docs is [here](https://circleci.com/docs/parallelism-faster-jobs/):
```
circleci tests glob "**/*.go" | circleci tests split --split-by=timings
```

I'm using [cypress](https://www.cypress.io/), which accepts a set of filenames with the `--spec` parameter. So, I'd assume something like this is a reasonable incantation to split test files by timing, turn them to a a comma separated list and pass to cypress:
```
$ cypress run ... --spec=$(circleci tests glob "e2e/**/*.ts" | circleci tests split --split-by=timings | paste -s -d, -)
```
This appears to work. If no timing is present for a particular file, `circleci` outputs a warning, so I assume when timing is available, `circleci` is using it. Cypress' [junit reporter](https://www.npmjs.com/package/cypress-junit-reporter) outputs a file like the first example above, which doesn't produce timings for circleci. This make sense because the `timing` value of the `testsuite` with a `file` is always `"0.000"`.

> Did you have a specific reason or goal for determining where CircleCI expects timing data in the XML file?

There are a few Junit schema definitions out on the internet ([here](https://github.com/behave/behave/blob/main/etc/junit.xml/junit-4.xsd) and [here](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd)) though none of them (AFAIK) include a `file` attribute anywhere. There is one example on the [Linux Light Group](https://llg.cubic.org/docs/junit/) which does include a `file` attribute on `testsuite`s. Producing an XML report like that example works with `circleci` but leaves a lot to the imagination --  🤷 I assume all `testsuites` with the same `file` are _summed_ to produce meaningful timing data for a particular file, though I have no way of know if this is actually the case. Perhaps the timing of the _first_ or _last_`testsuite` of a particular file is used.

Anyhoo, after a fair bit of toil I was able to get this working, but y'all should document how this timing stuff works. Beyond the three simple examples in the docs, it isn't obvious how the nuts and bolts work and it's very easy to waste a lot of credits on pipelines with sub-optimal parallelism.

**Comment by kbatuigas** [comment]
Hi @thomasmatecki , sorry about the delay in circling back to this. Just trying to make sure I'm on the same page -- do your reports have the <testcase> tag with a `file` attribute?

**Comment by thomasmatecki** [comment]
Yes.

> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0">
>   <testsuite name="Root Suite" timestamp="2022-09-30T15:00:44" tests="0" file="cypress/e2e/SomeFeature.cy.ts" 
> ...

**Comment by kbatuigas** [comment]
Sorry @thomasmatecki , I didn't realize that I hadn't formatted my response properly. That was supposed to have read:

> Hi @thomasmatecki , sorry about the delay in circling back to this. Just trying to make sure I'm on the same page -- do your reports have the `<testcase>` tag with a `file` attribute?

**Comment by thomasmatecki** [comment]
Amazing!
