### ISSUE TITLE
Improvement proposal for Japanese translation of the self-hosted runner overview page

### ISSUE THREAD

**Issue by bufferings** [circleci/circleci-docs#7467]
# Locations

https://circleci.com/docs/ja/runner-overview/

> Kubernetes クラスタにセルフホストランナーをインストールするには、コンテナランナーを使用する方法と、Machine Executor 環境内でマシンランナーを使用する方法があります。

# Details

The English version is

> You have the option of installing your self-hosted runner in a Kubernetes cluster using a container runner, or within a machine execution environment using a machine runner.

So the translation could be something like this:

セルフホストランナーをインストールするには、Kubernetes クラスタ内でコンテナランナーを使用する方法と、マシン実行環境内でマシンランナーを使用する方法があります。

**Comment by devinmarieb** [comment]
@Mayuko-Sa could you take a look at this! Thank you!

**Comment by Mayuko-Sa** [comment]
@bufferings Sorry for my late reply! will update the translation today or tomorrow, thank you!
