### ISSUE TITLE
Insights snapshot badge docs incorrect for private projects

### ISSUE THREAD

**Issue by Peter-Darton-i2** [circleci/circleci-docs#7531]
Documentation is more "aspirational" than "accurate".

# Locations
https://circleci.com/docs/insights-snapshot-badge/#creating-badges-for-private-repositories

# Details
The docs claims that "you may reuse the same API token".
While this is highly desirable, this isn't correct; the CircleCI WebUI provides no such facility and the documentation doesn't explain how to do it any other way.

This is a screenshot showing the options we have, after creating a status-only token to support a build status badge:
![image](https://user-images.githubusercontent.com/97306111/199550067-04edf141-1415-427a-82c2-644aa8f3890d.png)
 - The WebUI page has a "Add API Token" button, allowing you to create as many _new_ tokens as you like (or, by accident, far more than necessary 😉)
 - ... but there's no option to reuse one - there is no option to select an existing token (no doubt for security reasons) or any means for the user to provide a token/placeholder.

# Suggestion:

Specify the format of the generated badge URL in this documentation.
i.e. effectively provide a functional specification of the WebUI page.

That would mean that, regardless of the WebUI's actual behaviour, a (sufficiently skilled) user could construct a viable URL manually.
...which would allow a user to be able to reuse an existing API token (as originally intended) and/or create a URL for data that hadn't passed through the system yet.
i.e. we go straight from "can't do that" to "can do everything we need without waiting" just with a documentation change.

**Comment by rosieyohannan** [comment]
@Peter-Darton-i2 Thanks so much for pointing this issue out to us. I will check with the engineering team but all being well I should be able to update the docs with templates for adding the various components of the Insights snapshots badge manually, therefore allowing reuse of the Token for status badges, as you suggest 🙏 🎉
