### ISSUE TITLE
Conflicting info on AWS certificate manager setup on Server 4.x Helm values

### ISSUE THREAD

**Issue by kelvintaywl** [circleci/circleci-docs#7614]
# Locations

https://circleci.com/docs/server/installation/phase-2-core-services/#tls

# Conflict Description

Under the **USE AWS CERTIFICATE MANAGER** of TLS section for Phase 2 - Core of the Server 4.x installation,
we mentioned 

> Enable aws_acm and add the service.beta.kubernetes.io/aws-load-balancer-ssl-cert annotation to point at the ACM ARN

However, the example snippet has the `aws_acm.enabled` set to `false`.
<img width="686" alt="Screen Shot 2022-12-05 at 17 55 36" src="https://user-images.githubusercontent.com/2164346/205595685-bac37f37-4750-419f-b47d-9f931caa7783.png">

This can be confusing to the reader, and i _think_ we meant to set the `aws_acm.enabled: true` in this case?

**Comment by rosieyohannan** [comment]
@circleci/server just to double check this ^^

**Comment by ryanwohara** [comment]
@rosieyohannan Can confirm this should be `enabled: true` in this case
