### ISSUE TITLE
Missing minimal permissions to pull images from AWS ECR private repository

### ISSUE THREAD

**Issue by alceufreitas** [circleci/circleci-docs#7634]
# Missing Information
Documentation lacks the minimal AWS IAM permissions to pull images from AWS ECR private repository when creating an user.

# Already Looked
- https://circleci.com/docs/private-images/#aws-ecr

# Potential Locations
I would expect to find a link or brief description of the required permissions that must be configured to the AWS IAM user/role so CircleCI can pull Docker images from a private AWS ECR repository.

**Comment by devinmarieb** [comment]
@alceufreitas thanks I'll take a look at this!
