### ISSUE TITLE
Clarify whether Enterprise installs can use on-prem Macs RE: jekyll/_ccie/ios.md

### ISSUE THREAD

**Issue by xtreme-alvin-hsieh** [circleci/circleci-docs#766]
Hi,

I am having trouble determining whether CircleCI Enterprise allows clients to have their own on prem build machines.

"In order to enable iOS testing, your fleet will include a new “iOS Manager” box which connects to our iOS Fleet, and remotely executes commands on Mac hardware. Once setup, iOS projects will be auto-detected, and all builds will be directed to the mac containers."

From that, I feel that clients own their own build machines, but testing HAS to be done by CircleCi's fleet through the iOS Manager that clients install on their on-premise fleet.

However, later on in the article, it says, "We do not currently support running builds on your own hardware, but if you’re interested please let us know!". This is a bit contradictory.

Ultimately, I need to know whether CircleCI Enterprise allows for both on prem build machines and CiricleCI build machines.

Thanks

**Comment by ndintenfass** [comment]
@xtreme-alvin-hsieh thanks for pointing this out - the info was outdated, and I have put up a PR to clarify. We do now have a beta of on-prem Mac support. While we can offer hosted Macs, we do that only in special cases.
