### ISSUE TITLE
Outline vpn

### ISSUE THREAD

**Issue by Amirreza1396** [circleci/circleci-docs#7753]
# Locations
Add a link to the document
with the incorrect information.

# Details
Describe the incorrect information in the document.
Extra evidence like build output or other links
is helpful in "proving" that documentation isn't correct.ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp4M3RuRU5kc2pNaTZWbzZBVGVUSTlk@162.248.241.217:49444/?outline=1prefix=<POST%20&

**Comment by Rupantar-Borphukan** [comment]
Can You assign it to me? 
I will try to solve.

**Comment by Rupantar-Borphukan** [comment]
I have some doubt. 
How I can I contact you ?
