### ISSUE TITLE
Change API wording from RESTful to JSON

### ISSUE THREAD

**Issue by smart-alek** [circleci/circleci-docs#777]
<img width="955" alt="screen shot 2017-03-08 at 4 29 42 pm" src="https://cloud.githubusercontent.com/assets/5043885/23730485/79280186-041c-11e7-9ce2-ef5ea95db92c.png">

**Comment by smart-alek** [comment]
@DanToml

**Comment by felicianotech** [comment]
@smart-alek I took assignment of this and will fix this is my upcoming PRs for the API milestone I made.

**Comment by Alannna** [comment]
I submitted a pull request after the documentation jam.

**Comment by smart-alek** [comment]
Fixed in #2139
