### ISSUE TITLE
Phase 1 - prerequisites - Section 2 / GKE: Why do we need a service account & credentials?

### ISSUE THREAD

**Issue by paddynewman** [circleci/circleci-docs#7774]
In the following document:

* https://circleci.com/docs/server/installation/phase-1-prerequisites/

In the section:

* 2 Create a Kubernetes cluster
  * GKE
    * 5 Create a service account
    * 6 Retrieve credentials for the service account

The documentation doesn't appear to explain what the service account and credentials are for.

As a result, we don't understand why we need to create it, or what name we should use for it.

Can the documentation clarify what this service account is for, and suggest a suitable name for it?

If it's used later on in the documentation, can it mention where?

Thanks!

**Comment by rosieyohannan** [comment]
@paddynewman Hello! Thanks for getting in touch. First off, can I check which version of CircleCI you are using? Cloud or Server?

The page you are asking about is  only of interest to system administrators looking to install CircleCI server on their own infrastructure.

See more about hosting options here: https://circleci.com/product/#hosting-options

**Comment by paddynewman** [comment]
Hi @rosieyohannan,

We're using CircleCI Server v4.

We use a self-hosted GitHub Enterprise environment so the CircleCI Cloud option is not available to us.

**Comment by paddynewman** [comment]
Hi @rosieyohannan,

Our CircleCI support contact has confirmed that this service is account is required when CircleCI Server v4 is configured to use Workload Identity.

If that's the case, I think these two steps should be moved so that they sit under the _Enable Workload Identity in GKE (optional)_ section:

* 2 Create a Kubernetes cluster
    * GKE
        * Enable Workload Identity in GKE (optional)
            * ...
            * 4 Create a service account
            * 5 Retrieve credentials for the service account

That'll put these two tasks next to this text:

_Follow these links for steps to enable Workload Identity for your Kubernetes service accounts:_

_- Nomad Autoscalar_
_- VM_
_- Object-Storage_

That seems to clearer to me, if I've understood what this service account is for.

**Comment by rosieyohannan** [comment]
Thank you so much @paddynewman! I will get this page updated, I will also get one of the engineers to check the steps once updated during the review. 🎉

**Comment by rosieyohannan** [comment]
@paddynewman so sorry for the delay here, I'm working on clarifying this section now :-D
