### ISSUE TITLE
Improvement proposal for Japanese translation of the project values and variables page

### ISSUE THREAD

**Issue by tokizuoh** [circleci/circleci-docs#7850]
# Location

https://circleci.com/docs/ja/variables/

> 現在のビルドの前回のコミットの SHA1 ハッシュ。

# Explanation

The English version is 

> The SHA1 hash of the last commit of the current build.

The translation "前回" may cause misunderstanding as _previous_. I propose the following alternatives:

- 現在のビルドの最後のコミットの SHA1 ハッシュ。
- 現在のビルドの一番新しいコミットの SHA1 ハッシュ。

**Comment by rosieyohannan** [comment]
This is fixed in #7854 Thank you!
