### ISSUE TITLE
Differenciate more between h2 and h3 / ## and ###

### ISSUE THREAD

**Issue by kenden** [circleci/circleci-docs#786]
Differentiate more between h2 and h3 / ## and ###

On [this page](https://circleci.com/docs/2.0/configuration-reference/), for example, it is not easy to see which headers are steps and which are sub steps.
Is 'command' a step? Is 'deploy' a step?

Update the css to make h2 and h3 header more different.

On github, there is a line 

---
below the steps to differenciate better, but not on the circle site.

**Comment by smart-alek** [comment]
@kenden that's great feedback! We're toying with the idea of tables, but horizontal rules would probably be a good idea too.

**Comment by smart-alek** [comment]
Hey @kenden, we've updated the formatting; mind taking a look and seeing if that improves your experience at all?

**Comment by kenden** [comment]
Hi @smart-alek  Thanks for the update!

I think it's still hard to see the hierarchy of elements in the page:
In this page In https://circleci.com/docs/2.0/configuration-reference/

[Root](https://circleci.com/docs/2.0/configuration-reference/#root)
Has a big font (looks more important) and no bold (less important)

[jobs]https://circleci.com/docs/2.0/configuration-reference/#jobs
Has a smaller font (less important), but is bold (more important)

Both Root and Jobs are h2. Which one is more important / the higher level element?

An upcoming table of content will help. Splitting the page in to smaller page might also help.
I would add even more differentiation between header types too.

Also, [run](https://circleci.com/docs/2.0/configuration-reference/#run) (h4) and [Configuration map](https://circleci.com/docs/2.0/configuration-reference/#configuration-map) look too similar (h5) to me. 
Use indentation?

**Comment by smart-alek** [comment]
@kenden would love any feedback you have for the updated version! :)

**Comment by kenden** [comment]
@smart-alek 
Could we reopen this maybe?
In this page:
https://circleci.com/docs/2.0/configuration-reference/#docker--machine-executor

We have the structure:
![image](https://cloud.githubusercontent.com/assets/480586/25235973/f70003ec-25e6-11e7-88e0-6539c8eb3442.png)

But it's hard to see that jobs:
![image](https://cloud.githubusercontent.com/assets/480586/25238398/988e8e30-25ed-11e7-9e8c-19433044f5ea.png)

 is at a higher level than docker
![image](https://cloud.githubusercontent.com/assets/480586/25238402/9bda301c-25ed-11e7-9f83-b9dde8dd0253.png)

Their style is very similar, but jobs has H3 and docker H2. This makes the page harder to read
