### ISSUE TITLE
The navbar topic says 

### ISSUE THREAD

**Issue by tarun2603** [circleci/circleci-docs#7924]
# Location
[A link to the document that is unclear.](https://circleci.com/docs/deploy-service-update-to-aws-ec2/)
the link says "deploy service update to AWS EC2" but the heading is about ECS. It's sad for me as I was looking to deploy to EC2 :-(
# Explanation

<img width="1129" alt="Screenshot 2023-04-10 at 3 21 21 PM" src="https://user-images.githubusercontent.com/102321585/231010050-4a1428c0-0325-45f1-b825-f3aa567e0122.png">

**Comment by kbatuigas** [comment]
Hi @tarun2603 , thank you for bringing this to our attention! We'll go ahead and publish a correction shortly.

In the meantime, we can try to further assist you in getting the information you need. Does the [Deploy to AWS doc](https://circleci.com/docs/deploy-to-aws/) look relevant? If not, could you give us more details on what you were looking to do?
