### ISSUE TITLE
Installing NPM packages failed

### ISSUE THREAD

**Issue by lsriniwas** [circleci/circleci-docs#7966]
# Description
Package.json file
{
  "dependencies": {
    "@emotion/cache": "11.10.5",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/icons-material": "5.11.0",
    "@mui/material": "^5.12.1",
    "@mui/styled-engine": "5.11.8",
    "@testing-library/jest-dom": "5.16.5",
    "@testing-library/react": "13.4.0",
    "@testing-library/user-event": "14.4.3",
    "chroma-js": "2.4.2",
    "clean": "^4.0.2",
    "clsx": "^1.2.1",
    "flatpickr": "4.6.13",
    "framer-motion": "9.0.2",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "react-circular-progressbar": "^2.1.0",
    "react-copy-to-clipboard": "5.1.0",
    "react-countup": "6.4.1",
    "react-dom": "18.2.0",
    "react-flatpickr": "3.10.13",
    "react-icons": "^4.8.0",
    "react-intersection-observer": "^9.4.2",
    "react-router-dom": "6.8.1",
    "react-scripts": "5.0.1",
    "react-syntax-highlighter": "15.5.0",
    "web-vitals": "3.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
  },
  "proxy": "http://localhost:5000/",
  "lint-staged": {
    "*.{ts,tsx,json}": [
      "prettier --write",
      "npm run lint:fix"
    ]
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "8.33.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-prettier": "8.6.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsx-a11y": "6.7.1",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "prettier": "2.8.4"
  }
}

# Error
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's typescript@5.0.4 does not satisfy typescript@4.9.5
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global]
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/project/node_modules/_logs/2023-04-24T09_59_39_399Z-debug-0.log

Exited with code exit status 1

**Comment by rosieyohannan** [comment]
I'm going to close this issue as there is no supporting information. Feel free to reopen and let use know what issue you have with CircleCI docs, thank you!
