### ISSUE TITLE
Test splitting by timing, when used with pytest requires `junit_family=xunit1` setting

### ISSUE THREAD

**Issue by shaybensasson** [circleci/circleci-docs#8025]
# Missing Information
Articulating why `test splitting by timing` does not work. We got:
```
Error autodetecting timing type, falling back to weighting by name. Autodetect no matching filename or classname.  If file names are used, double check paths for absolute vs relative.
Example input file: "tests/test_example.py"
Example file from timings: ""
```

The reason is highlighted [here](https://stackoverflow.com/a/64796951/1640414):
Basically, circleci expected `junit.xml` to contain `file` attribute for each `testcase` and it is not generated by default on new pytest version.
The solution is to define `junit_family=xunit1` in the `pytest.ini`/`pyproject.toml`.

# Already Looked
- https://circleci.com/docs/parallelism-faster-jobs/
- https://support.circleci.com/hc/en-us/articles/360056636191-Common-test-splitting-issues-with-pytest
- https://discuss.circleci.com/t/test-timings-cant-be-found/33702
- https://github.com/nbialostosky/sample-python-cfd/commit/ebc206cd6fcb9fb4887e6fbe1439be9a3fda0c1f
- https://github.com/CircleCI-Public/circleci-cli/blob/c5d1aee86245d9600d532274097b0a1239b46f09/cmd/tests.go

# Potential Locations
- https://circleci.com/docs/parallelism-faster-jobs/
    - A python pytest example will be useful here.

**Comment by kelvintaywl** [comment]
Hi @shaybensasson 

thanks so much for raising this concern with us here 👍 

I understand we did share this gotcha in our docs under https://circleci.com/docs/troubleshoot-test-splitting/#are-you-setting-the-junit-family-in-your-pytest-ini

I am curious if perhaps it was hard for you to find this section?
this will be useful for us to consider in terms of potential improvements.

**Comment by rosieyohannan** [comment]
@kelvintaywl we could part of the error message to the section where we have this warning, to help people find this through search?

**Comment by kelvintaywl** [comment]
hi @rosieyohannan yes thank you!
I think that is a great idea!
