### ISSUE TITLE
Video referenced in scheduled pipelines is not embedded

### ISSUE THREAD

**Issue by bockets** [circleci/circleci-docs#8050]
The HTML is just dumped to the page

https://github.com/circleci/circleci-docs/blob/e69987679881a905b66a5e3774f1c9ec687e724f/jekyll/_cci2/scheduled-pipelines.adoc?plain=1#L101

![image](https://github.com/circleci/circleci-docs/assets/97627964/f0beda57-5388-4924-927a-e01b211e694a)

**Comment by rosieyohannan** [comment]
@bockets thank you so much for reporting this, fixing now! 🙏
