### ISSUE TITLE
Incorrect URL for Scheduled Pipeline docs

### ISSUE THREAD

**Issue by bockets** [circleci/circleci-docs#8051]
Clicking the link for the "Scheduled Pipelines" docs just goes back to the same page. URL should be https://circleci.com/docs/scheduled-pipelines/

https://github.com/circleci/circleci-docs/blob/e69987679881a905b66a5e3774f1c9ec687e724f/jekyll/_cci2/triggers-overview.adoc?plain=1#L69

**Comment by rosieyohannan** [comment]
Hi @bockets, I can't seem to replicate this issue. Can you send me the URL for the page /section where you're seeing this issue?

**Comment by bockets** [comment]
@rosieyohannan oh sorry about not including that. I cannot replicate this either now.

**Comment by rosieyohannan** [comment]
Thanks @bockets! I'm going to close this but please reopen if you find the broken link 😄
