### ISSUE TITLE
The Collecting Test Data for XCode section references out of date documentation

### ISSUE THREAD

**Issue by KevinSchildhorn** [circleci/circleci-docs#8057]
# Locations
https://circleci.com/docs/collect-test-data/#xcode

# Details
The documentation references a [Third Party Resource](https://medium.com/@warchimede/convert-xcode-plist-test-reports-to-junit-xml-6f0aa8c3fa58) which is out of date. It references test summaries as plists when they are now `XCResult` files, which cannot be made into XML.

**Comment by rosieyohannan** [comment]
@KevinSchildhorn thank you so much for reporting, I'll get this updated 🙏
