### ISSUE TITLE
re-run only failed tests when xargs is not a viable option

### ISSUE THREAD

**Issue by akostadinov** [circleci/circleci-docs#8075]
# Missing Information
Hi, it is not clear what to do when `xargs` approach is not applicable. For example running rake tests like this previously

```
bundle exec rake test:run TEST="${TESTS}" TESTOPTS=--verbose --verbose --trace
```

how to convert this to `circleci tests run`?

I'm trying something like this, hope it will work:
```
circleci tests run --command="cat >> $list" --verbose --split-by=timings
bundle exec rake test:run TEST="$(cat $list)" TESTOPTS=--verbose --verbose --trace
```

# Already Looked
https://circleci.com/docs/rerun-failed-tests-only/

# Potential Locations
https://circleci.com/docs/rerun-failed-tests-only/

**Comment by sebastian-lerner** [comment]
hey @akostadinov i am the PM for this feature.  I've had a couple of other users that fall into a similar bucket as you, so I'll make sure our docs are updated to account for this scenario. 

I think you still want to use `xargs` in your --command.  I believe the following should work:

`circleci tests run --command "xargs echo" --verbose --split-by=timings > files.txt
`
the contents of files.txt reflects either the original file list or the subset of files if it's a rerun

**Comment by sebastian-lerner** [comment]
BTW I've updated the docs to make this more obvious https://github.com/circleci/circleci-docs/pull/8076

**Comment by sebastian-lerner** [comment]
i should add @akostadinov , you will need some kind of glob command before `circleci tests run` to pass in via stdin the test file names on the original job run so that the test splitting can happen.  similar to how the docs show how to do it.

**Comment by akostadinov** [comment]
@sebastian-lerner , thank you for the advise. I think `xargs echo` should be same or similar effect as simply `cat` . I will try that. I didn't realize one can get the output of the whole command.

I don't understand your remark about `glob` though. Isn't `circleci tests run --split-by=timings` already split like `glob` did?

**Comment by akostadinov** [comment]
`cat` seems to work well, much simpler than `xargs echo`. But I see another issue. The `circleci tests run` command appears to output some undesirable lines on stdout. Thus polluting the test list [1].

```
TEST='
	Installing
	circleci-tests-plugin-cli
	plugin.
	circleci-tests-plugin-cli
	plugin
	Installed.
	Version:
	1.0.6601-306bc14
	test/unit/cinstance_test.rb
	test/unit/services/admin/api/cms/template_service_test.rb
	test/unit/simple_layout_test.rb
	test/unit/stats/service_test.rb
	test/unit/account/states_test.rb
....
```

The output that is coming from it is:
```
	Installing
	circleci-tests-plugin-cli
	plugin.
	circleci-tests-plugin-cli
	plugin
	Installed.
	Version:
	1.0.6601-306bc14
```

It should output all such debug info to stderr so that the test output is only what the user command has outputted.

[1] https://app.circleci.com/pipelines/github/3scale/porta/24779/workflows/8c3120c6-985c-4b18-b78d-25935c643c85/jobs/278746/parallel-runs/0?filterBy=ALL

**Comment by akostadinov** [comment]
@sebastian-lerner , ok, that was my original idea. Let me try.

But FYI there is an error in your documentation. It reads:
```
circleci tests glob "src/**/*js" | circleci tests run --command ">files.txt xargs echo" --verbose --split-by=timings > files.txt
```

So the redirection to file is both - inside and outside the command. And it should be only at one place.

btw the spurious stdout lines would better be fixed in future iteration of your tool as this is how cli tools are supposed to work.

**Comment by sebastian-lerner** [comment]
good catch, opened a PR to fix that https://github.com/circleci/circleci-docs/pull/8129.  thank you.

agreed on the stdout, we're working on fixing that.  unfortunately that is coming from a different component, not the test-plugin-cli. but agreed, still something we should resolve.

**Comment by akostadinov** [comment]
Thanks, all should be clear now.

**Comment by akostadinov** [comment]
btw I just spotted another thing in the log:
```
DEBU[2023-06-21T14:15:54Z] starting execution
```
I assume it has to be `DEBUG`. But that's minor cosmetic thing so I'm not going to open an issue.
