### ISSUE TITLE
Add meaningful examples for glob-based parallelism (_cci2/parallelism-faster-jobs.md)

### ISSUE THREAD

**Issue by lukesneeringer** [circleci/circleci-docs#811]
I really want to use glob-based parallelism, but have the file be appended to a command.

For example, if I have directories `foo/nox.py`, `bar/nox.py`, and `baz/nox.py`, it would be nice to be able to do something like:

```
# on three different nodes...
nox -f foo/nox.py
nox -f bar/nox.py
nox -f baz/nox.py
```

This seems like it is _probably_ possible with `circleci tests glob` and `circleci tests split` but it is not even remotely obvious how to do it.

**Comment by lukesneeringer** [comment]
I tried doing [this][1], and it just runs everything on every container.
So...it is not at all clear to me exactly how this command works...

  [1]: https://github.com/lukesneeringer/google-cloud-python/blob/ci/.circleci/config.yml#L19-L21

**Comment by ryanwohara** [comment]
I think you'd need `**/nox.py` but your link is private and your example unclear.
