### ISSUE TITLE
Opt out of parallelism by certain steps in a job

### ISSUE THREAD

**Issue by bc-rajesh** [circleci/circleci-docs#8135]
# Missing Information

It is mentioned in [this circleci documentation page](https://circleci.com/docs/configuration-reference/#parallelism) that "Certain parallelism-aware steps can opt out of the parallelism and only run on a single executor." But there is no information on how this can be achieved. I am trying to find out how certain steps in a circleci job can opt out of parallelism. 

# Already Looked
Above page points to [this page](https://circleci.com/docs/parallelism-faster-jobs). But could not find that information here 

# Potential Locations
I would like that information to be available in any of the above 2 pages i mentioned.

**Comment by kbatuigas** [comment]
Hey @bc-rajesh , thank you for reaching out! I've checked this for you and the "parallelism-aware steps" actually refers to just the [`deploy` step](https://circleci.com/docs/configuration-reference/#deploy-deprecated), which is deprecated.

I'll go ahead and remove that portion in our config reference to prevent further confusion. Thanks!
