### ISSUE TITLE
Inconsistency between Executors and Jobs Linking in CircleCI Documentation

### ISSUE THREAD

**Issue by oussamaessaji** [circleci/circleci-docs#8188]
# Description
In the https://circleci.com/docs/orb-author-intro/ page the Executors links to jobs and vice versa 
# Location
https://circleci.com/docs/orb-author-intro/

# Steps to Reproduce
Visit this link https://circleci.com/docs/orb-author-intro/ under Quick start try to visit Jobs or Executors

**Comment by rosieyohannan** [comment]
Thank you for reporting this @oussamaessaji!
