### ISSUE TITLE
Step-by-step migration instructions from GitHub Actions are missing

### ISSUE THREAD

**Issue by dabrahams** [circleci/circleci-docs#8261]
# Missing Information
A step-by-step guide for the new CircleCI user to get my Github (actions) project building/testing on CircleCI.  I'm looking for a single document that doesn't make me hop around the general getting started guide.  Lowering the bar for people to switch in this way might be the best way to encourage adoption.

# Already Looked
https://circleci.com/docs/migrating-from-github/

# Potential Locations
The above location.

**Comment by rosieyohannan** [comment]
This sounds like a great idea, thanks @dabrahams! I'll update here when this work gets prioritized.
