### ISSUE TITLE
Deploy on FIrebase with FIREBASE_DEPLOY_TOKEN is depriciated

### ISSUE THREAD

**Issue by EhteshamAnwar** [circleci/circleci-docs#8264]
# Locations
https://circleci.com/docs/deploy-to-firebase/

# Details
The Method to deploy on firebase using `FIREBASE_DEPLOY_TOKEN` is depriciated according to official [npm firebase-tools docs](https://www.npmjs.com/package/firebase-tools) unfortunately this is not updated in [firebase google cli docs](https://firebase.google.com/docs/cli) .

Snippet from firebase-tools npm page: 
![image](https://github.com/circleci/circleci-docs/assets/16754151/03b15ba1-723b-4098-8825-9524f86f4073)

For Deploying we need to use Service Account method by setting `GOOGLE_APPLICATION_CREDENTIALS `to .json key file.

Updated workflow code should be: 

`      - run:`
`          name: Deploy on Firebase`
`          command: |`
`            echo $GSA_CREDENTIALS > gcloud.json`
`            GOOGLE_APPLICATION_CREDENTIALS=gcloud.json firebase deploy` 

Set `$GSA_CREDENTIALS`  as an environment variable in circleCI project. Set its value to the Key file generated from Google Service Account with proper permissions.

**Comment by kbatuigas** [comment]
Thanks for bringing this to our attention @EhteshamAnwar , we'll work on getting this updated.
