### ISSUE TITLE
Android and iOS Lacks Documentation

### ISSUE THREAD

**Issue by grndvl1** [circleci/circleci-docs#8311]
# Missing Information
Literally there is almost no documentation on Android or iOS setups for how to do test results, how to do code coverage and report those back.  Everything I have seen is mostly documentation web.  Please consider standardizing on Mobile platforms.

# Already Looked
I have searched like no other for something as simple as how to parse the XML output for UI tests in android and then go through it and update Jira for test cases.  Nothing here on even an XML parser.  Just sad with the level of documents and also simple orbs to help

**Comment by rosieyohannan** [comment]
@grndvl1 Thank you for bringing this to our attention. I'll bring this to the team and get back to you 🙏

**Comment by Shashankpantiitbhilai** [comment]
please assign this to me

**Comment by rosieyohannan** [comment]
Hey @grndvl1 We will consider adding further docs content in this area in future. I've added a note in our backlog. Thank you!
