### ISSUE TITLE
Table contains cloud-only variables but doesn't specify that

### ISSUE THREAD

**Issue by thedoc31** [circleci/circleci-docs#8331]
# Missing Information
Looking at the built-in variables table, there are values listed in the table which are exclusively available on Cloud:
CIRCLE_OIDC_TOKEN
CIRCLE_OIDC_TOKEN_V2
Unfortunately, there is no note which states this and I wasted an entire work day trying to make these work, but support case 138969 confirmed they just don't exist in Server yet. Please make sure to specify exactly which variables are available with which product if they can't be kept in sync.

# Already Looked
https://circleci.com/docs/variables/#built-in-environment-variables
There is nowhere else to look for this information.
This article is tagged with Cloud, Server v4.x, Server v3.x, so as a user I can only assume everything on this page applies to everything listed.

# Potential Locations
There needs to be a column or some kind of visual mark that indicates exactly which of the items on the page are Cloud-only. The two I mentioned above may not be the only items on the page like that.

**Comment by rosieyohannan** [comment]
Hi @thedoc31, thank you for reporting this, and really sorry for the time you ended up wasting. I will get this page updatedm, and look at our internal processes for ensuring Cloud/Server tagging is consistent in future.
