### ISSUE TITLE
What does member and owner mean in orbs permission matrix?

### ISSUE THREAD

**Issue by kporras07** [circleci/circleci-docs#8421]
# Location
[CircleCI Orb permission matrix.](https://circleci.com/docs/orb-author-intro/#permissions-matrix)

# Explanation
What do "owner" and "member" mean in the matrix? 

I'm trying to publish an orb from a Github repo in the organization "myawesomeorg" and keep getting: "Error: User does not have access to publish SemVer orbs in this namespace."

Having admin permissions in the repo is not enough to allow me to publish prod versions of the orb? Should I be an admin/owner in the Github org?

I would really appreciate some clarification on what owner/member mean in this context.

TIA!

**Comment by rosieyohannan** [comment]
Hey @kporras07 I believe these are the GitHub permissions of org owner and member, as documented here: https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#organization-owners

I can update our docs to be more specific.

cc @KyleTryon to check I have this right :-D

**Comment by kporras07** [comment]
Thanks!

That would be too broad of a token to publish a prod version of an orb. If you confirm that's the case, is there any mechanism to submit a feature request to allow maybe repo admins or something else to publish prod versions of existing orbs?

**Comment by KyleTryon** [comment]
This is correct 👍 The permissions are tied to the GitHub equivalents. At this time this will be the only method of authentication for the foreseeable future. I can say though that we are always working on improvements under the hood and we are aware of these limitations.
