### ISSUE TITLE
Link not rendered

### ISSUE THREAD

**Issue by Greg-Smulko** [circleci/circleci-docs#8434]
# Description

Link not rendered:

`see the xref:github-apps-integration#[GitHub App integration page].`

![image](https://github.com/circleci/circleci-docs/assets/26791344/d184f03c-d3de-4fdc-8d56-d8e970b506c9)

# Location
https://circleci.com/docs/using-windows/

**Comment by rosieyohannan** [comment]
Thanks @Greg-Smulko I'll get this fixed!
