### ISSUE TITLE
How can I extend and existing CircleCI Machine Image.

### ISSUE THREAD

**Issue by dopry** [circleci/circleci-docs#8494]
# Missing Information
I'd like to add a few packages to the ubuntu-2204 machine image for my builds. There are plenty of resources that explain how to build an image from scratch or from the cimg/base images, but there is nothing indicating how I would

```Dockerfile
from ubuntu-2204:2023.07.2
apt install ...
```

# Already Looked
https://circleci.com/developer/machine/image/ubuntu-2204
https://circleci.com/docs/custom-images/

# Potential Locations
https://circleci.com/docs/custom-images/

**Comment by rosieyohannan** [comment]
Hello @dopry, thanks for asking. I just had a look and found there is a note in this section, after the code block: https://circleci.com/docs/using-linuxvm/#pre-installed-software ... I realise the section heading doesn't do much to help you find that information! If you could let me know if that answers your question I can update the page to make this clearer. Thanks!

**Comment by dopry** [comment]
I'm realizing now that the machine executor isn't a docker image... I had forgotten that. It isn't something I can use as a base image. I may need to revisit the build process. I was looking to pre-install the dependencies from playwright. At the moment though our build runs on the machine executor so it can leverage our docker compose development environment without having to redeclare it and our various initialization tasks in the config.yaml...
