### ISSUE TITLE
Prerequisites for machine runner on macOS are confusing

### ISSUE THREAD

**Issue by kai687** [circleci/circleci-docs#8554]
# Location

[Install machine runner 3.0 on macOS](https://circleci.com/docs/install-machine-runner-3-on-macos/#prerequisites)

# Explanation

- The prerequisites seem to be the same as on the page for Linux, but the macOS-specific commands just uses homebrew. I don't think, I need to worry about `tar`, `gzip`, and `coreutils` on macOS when using homebrew.  
- The page uses homebrew, yet Homebrew isn't listed as a prerequisite.

**Comment by rosieyohannan** [comment]
@kai687! Thank for letting us know about this, I agree this is confusing. I will work to make some improvements :-D
