### ISSUE TITLE
Broken YAML rendering with NoScript

### ISSUE THREAD

**Issue by tripleee** [circleci/circleci-docs#8619]
# Description

The YAML snippets on https://circleci.com/docs/migrating-from-github/ are completely broken. I cannot copy/paste the code, or easily guess how to correct the syntax if I copy/paste anything off that page.

Bottom line, it is unfortunate that the page requires Javascript to render what should be trivial plain text. There is no indication as to what might be wrong when this happens.

# Location

For example, https://circleci.com/docs/migrating-from-github/#jobs-and-workflows renders like this with NoScript:

![Screenshot 2024-02-20 at 11 20 08](https://github.com/circleci/circleci-docs/assets/2160915/b5173ee0-e618-4222-bf5d-e88a044eee0f)

(Chrome on a Mac)

# Steps to Reproduce

Install and activate the NoScript extension. Visit the page. Struggle to figure out why the formatting is broken (the sources on Github look fine).

# Workaround

Once you understand what's wrong, the workaround is trivial: Permit Javascript from `circleci.com` on the page (perhaps temporarily, if you are paranoid).

**Comment by rosieyohannan** [comment]
Thanks for reporting this and I'm sorry this has been a frustrating experience for you. My understanding is that our syntax highlighter for our code examples required Javascript, and this isn't something we are going to address at this time.

**Comment by tripleee** [comment]
Could you please reconsider this? My request isn't "stop depending on Javascript", it's "ensure a sensible degradation when it's unavailable".
