### ISSUE TITLE
I am looking for an API to stop building a project

### ISSUE THREAD

**Issue by amansharma-eb** [circleci/circleci-docs#8657]
# Location
A link to the document that is unclear.

I looked [here](https://circleci.com/docs/api/v2/index.html#operation/patchProjectSettings:~:text=%F0%9F%A7%AA-,Update%20project%20settings,-%5BEXPERIMENTAL%5D%20Updates) if we have any flag in the  header but could not find any. Also, this is experimental so can it be used? I tried to call the API but getting `404 ("Project not found.")`  

# Explanation
Describe what confused you about the document.
This could be syntax, word choice, sentence length, or something entirely different.

Can we use experimental APIs and any way to call API to stop building a project.

**Comment by rosieyohannan** [comment]
Hi sorry for the delay here, our experimental endpoints can change at any time. It is not advised to use in production because of this reason. More info here: https://discuss.circleci.com/t/project-settings-api-v2-endpoints-now-in-open-preview/49999
