### ISSUE TITLE
Nightly jobs, incorrect docs

### ISSUE THREAD

**Issue by elyasADK** [circleci/circleci-docs#8676]
# Locations
[nightly jobs](https://circleci.com/docs/set-a-nightly-scheduled-pipeline/#set-a-schedule-with-the-api)
with the incorrect information.

# This is incorrect:
            "per_hour": 1,
            // at 01:00 UTC
            "hours_of_day": [1],
            // on the following days of the week
            "days_of_week": ["TUE", "WED", "THU", "FRI", "SAT"]
    
# Correct is:
    
            "per-hour": 1,
            // at 01:00 UTC
            "hours-of-day": [1],
            // on the following days of the week
            "days-of-week": ["TUE", "WED", "THU", "FRI", "SAT"]

**Comment by rosieyohannan** [comment]
Thank you for spotting this, I'll get it updated 👍 👍

**Comment by elyasADK** [comment]
thanks for fixing it 🚀
