### ISSUE TITLE
Overriding dependencies to run Yarn will prevent inference

### ISSUE THREAD

**Issue by kpalmvik** [circleci/circleci-docs#873]
> To use Yarn instead of npm, we override both the `dependencies` and `test` sections.

Please add a note that overriding the `dependencies` section has the [unfortunate side effect of preventing the CircleCI inference](https://circleci.com/docs/1.0/configuration/#phases), for example automatically running `bundle install` in a Rails project.

Moving the `yarn` command to the `pre` section will run both `yarn` (from `pre`) and `npm install` (from inference).

Ideally, switching between `yarn` and `npm` should be a configuration flag, set from the config file, instead of a `yarn` command.

**Comment by felicianotech** [comment]
I wouldn't call it an "unfortunate side effect" as that's exactly what the `override` section is for, to override Inference.

With focus on CircleCI 2.0 which avoids this issue completely, I don't any sort of configuration file flag happening for this.

I'll open a PR to reword that paragraph slightly.

**Comment by kpalmvik** [comment]
> I wouldn't call it an "unfortunate side effect" as that's exactly what the override section is for, to override Inference.

No, it might not be unfortunate in context. Seen from the perspective of the instructions in [Using Yarn (the npm replacement) on CircleCI](https://circleci.com/docs/1.0/yarn/), I was under the impression that it was more of a _override npm by using Yarn_ than _override everything in my project_.

I look forward to CircleCI 2.0, as well as the slightly altered paragraph. 👏 🙇

**Comment by felicianotech** [comment]
@kpalmvik How does this look? https://github.com/circleci/circleci-docs/pull/874

**Comment by kpalmvik** [comment]
> How does this look?

LGTM! 👍

**Comment by felicianotech** [comment]
Awesome, I'll get that merged. Thank you.
