### ISSUE TITLE
RE: jekyll/_cci1/continuous-deployment-with-google-container-engine.md

### ISSUE THREAD

**Issue by arekkas** [circleci/circleci-docs#878]
The following command

```
sudo /opt/google-cloud-sdk/bin/gcloud docker push us.gcr.io/${PROJECT_NAME}/hello
```

yields

```
ERROR: gcloud crashed (ArgumentError): argument DOCKER_ARGS: unrecognized args: push eu.gcr.io/.../hello
```

and when reproducing this locally I was able to track it back to the path ` /opt/google-cloud-sdk/bin` being present - without it the command works as epxected. Any ideas how to resolve this?

**Comment by arekkas** [comment]
Apparently this changed to

```
gcloud docker -- push gcr.io/your-project-id/example-image
```

in recent versions

**Comment by rasekar2000** [comment]
Man.. I spent a day to find why this isn't working . Which worked yesterday but after the gcloud components upgrade .. This is seriously breaking fix for many

**Comment by smart-alek** [comment]
@arekkas @rasekar2000 just following up: looks like this document was updated to include the hyphens, so closing this (almost a year later, yikes!). :)
