### ISSUE TITLE
Please provide a schema for the `config.yml`, in particular version 2.1

### ISSUE THREAD

**Issue by gdubicki** [circleci/circleci-docs#8786]
# Missing Information

I want to use a schema in my IDE for `config.yml` for automatic validation of the syntax of my config.

# Already Looked

My IntelliJ IDEA uses https://www.schemastore.org but it's doesn't have a complete schema, in particular schema for v. 2.1 is missing there, see https://github.com/SchemaStore/schemastore/issues/515.

# Potential Locations

I think it would be best for your users if you would help updating/provide a new schema for v 2.1 in https://www.schemastore.org, as it's a semi-standard way to provide a schema for IDEs such as VS Code or the ones from JetBrains.

**Comment by gdubicki** [comment]
A previous effort for this was in https://github.com/CircleCI-Public/config-preview-sdk/issues/42, but - if I am reading it right - that was in the pre-release phase of v. 2.1.

**Comment by rosieyohannan** [comment]
Hi @gdubicki! Thanks for your message. I'm going to ask our engineering teams about this but first wanted to see if this helps at all: https://circleci.com/docs/vs-code-extension-overview/#open-source-language-server

**Comment by rosieyohannan** [comment]
AFAIK the schema is up to date for 2.1 CircleCI config. Please reopen this issue if you disagree or if I'm misunderstanding. Thanks!
