### ISSUE TITLE
RE: jekyll/_cci1/continuous-deployment-with-amazon-s3.md

### ISSUE THREAD

**Issue by dan-perron** [circleci/circleci-docs#898]
It would be really nice if there was some suggestions on how to properly set content types, cache control, etc.

**Comment by dan-perron** [comment]
ie, for my build:

```
- aws s3 sync build/ s3://our-b
# Write index.html again so we can set the cache control header.
- aws s3api put-object --bucket our-b --key index.html --body build/index.html --cache-control "max-age=300, public"
```

I assume there are some problems / downsides to this.

**Comment by felicianotech** [comment]
My thoughts:

1. We should morph any work for this into a 2.0 doc.
2. This information specifically shouldn't be in this doc. We should link to AWS's: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html

**Comment by smart-alek** [comment]
@felicianotech I think that's a great idea. It probably makes sense to crack the "Deploy" page into a few platform-specific changes. I've already noticed something similar with Google Cloud and how we deploy to that.

So we should break out [this section](https://circleci.com/docs/2.0/deployment-integrations/#aws) into an entirely new document, yeah?

**Comment by felicianotech** [comment]
Yes.

Perhaps just having an integrations category and docs could be "tagged" as deployment. An example would be the new snap doc in PR. It's not totally a deployment doc but it has a "publishing" section which is basically deploying.

**Comment by michelle-luna** [comment]
I would like to leave this as a long document with a TOC for now, but I added the link to the S3 docs as suggested
