### ISSUE TITLE
Configuration guide very hard to read

### ISSUE THREAD

**Issue by ddollar** [circleci/circleci-docs#916]
I spent a couple of days with this document and I felt more confused every time I looked at it. Some suggestions:

* Better explanation of `docker` vs `machine`. The `machine` stanza is never described except in terms of itself. I had to experiment to figure out what made them different.

* More example configuration files. I feel like this doc could actually just be 4-5 good example configs in increasing complexity with a good description of what they do. 

* Better use of YAML hierarchy. The data structure of your YAML configuration does not lend itself to discoverability. Requiring one but not two of certain map keys (`docker`, `machine`) is confusing. You can model this more naturally in YAML so that it's not possible to do it wrong, something like:

```
jobs:
  build:
    executor: docker
```

* Related to the YAML hierarchy, it's strange to have the first element of an array be special (looking at `images:`). It took me a long time to figure out that the first image in the list was special. You could represent this special-ness in the YAML hierarchy so that it's more immediately obvious:

```
jobs:
  build:
    executor: docker
    image: ubuntu:16.04
    sidecars:
      - postgres:9.4.3
      - redis
```

* Adding new vocabulary like "executor" requires a bit more explanation and context. You should consider avoiding it in the first place.

This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>)

**Comment by ndintenfass** [comment]
Thanks for this detailed feedback. We are going to improve this page very soon. 

Your idea about "sidecars" is intriguing -- we will be discussing that internally. 

Clarifying machine vs docker and when to use them is also in the works. 

Keep the feedback coming!

**Comment by technomancy** [comment]
Hi @ddollar! Thanks for the feedback. This page could definitely benefit from links to some other pages where some of the concepts are explained more thoroughly; I've opened #918 for that.
