### ISSUE TITLE
Incorrect code snippet involving multiple Python versions

### ISSUE THREAD

**Issue by smart-alek** [circleci/circleci-docs#921]
The following example did not work for @ryanwohara:

```
machine:
  post:
    - pyenv global 2.7.9 3.4.2
```

This issue is about <https://circleci.com/docs/1.0/language-python/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/language-python.md>)

**Comment by eric-hu** [comment]
This failed because we removed those versions of python with our rolling version window.  This worked:

`pyenv global 2.7.12 3.4.4`

https://circleci.com/gh/eric-hu/support-sandbox/1235
