### ISSUE TITLE
Git LFS support in CircleCI 2.0?

### ISSUE THREAD

**Issue by L8D** [circleci/circleci-docs#926]
Not entirely sure if this is the right place to go for this but I was wondering if/when there will be Git LFS support in CircleCI 2.0? I remember experimenting with 2.0 docker executor builds and they appeared to be checking out the LFS files properly. Now with a machine executor, the `checkout` step is not invoking LFS and is leaving my files unfetched. Perhaps the docker executor I was using happened to have LFS installed so it properly fetched them, and the machine executor doesn't?

Anyways, clarification on how to handle LFS in CircleCI 2.0 would be great to have in the docs! Thanks.

**Comment by ndintenfass** [comment]
This kind of question is definitely better asked in our Discuss forum (and looks like someone already has: https://discuss.circleci.com/t/is-git-lfs-supported-by-circleci-2-0/11283). 

It's true that LFS is not installed on the `machine` - in the case of `docker` executor it would depend on whether it's in the image you chose to use for your job, so you are correct in your guess that it happened to be installed - we are not doing anything magical to include it there. We may add it to the `machine` in the future, and you could always install it as part of your job (not sure how long that will take, though).
