### ISSUE TITLE
How to use phantomjs in circleci 2.0?

### ISSUE THREAD

**Issue by zfben** [circleci/circleci-docs#940]
I have installed phantomjs-prebuilt, but when I run rspec, it will freeze host, and after 10 minutes, console will show `Too long with no output (exceeded 10m0s)`.

**Comment by ndintenfass** [comment]
@zfben unfortunately, issues on our docs repo isn't a good way to get help.  A much more fruitful path is to post this in our Discuss forums: https://discuss.circleci.com/
