### ISSUE TITLE
aws s3 sync always reuploads files

### ISSUE THREAD

**Issue by rubendura** [circleci/circleci-docs#943]
This issue is about <https://circleci.com/docs/1.0/continuous-deployment-with-amazon-s3/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-amazon-s3.md>)

```aws s3 sync``` should only reupload changed files, but when running it on CI it always reuploads all files. 
According to the docs (http://docs.aws.amazon.com/cli/latest/userguide/using-s3-commands.html#using-s3-commands-managing-objects):
``` s3 sync updates any files that have a different size or modified time than files with the same name at the destination```

When CI finishes, all objects' Last Modified is updated, which makes me think that this could be the issue. It is not a major problem, but an annoyance as I have to reupload all files every time even though most of the time I just change one or two files.

Are there any workarounds or ways to solve this?

**Comment by felicianotech** [comment]
I'm not sure. As this isn't an issue with Docs persay, this question should be posted in [CircleCI Discuss](https://discuss.circleci.com).
