### ISSUE TITLE
example 2 to clarify deploy to AWS S3 

### ISSUE THREAD

**Issue by AWattNY** [circleci/circleci-docs#964]
This issue is about <https://circleci.com/docs/1.0/continuous-deployment-with-amazon-s3/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-amazon-s3.md>)
In Example 1: info is either not clear or missing:
for example Install awscli line is missing 
path-to-files: is not clear and took a few tries to guess 
bucket-URL:  is not accurate should be bucket-name 
Following example 2 addresses all the 3 issues above 

Example2: here is a snippet of a circle.yml file that shows how to deploy a static site to AWS s3:

dependencies:
    override:
        - sudo pip install awscli
deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync /home/ubuntu/project-name-here s3://bucket-name-here --delete

**Comment by ryanwohara** [comment]
`awscli` is already installed
