### ISSUE TITLE
Add documentation for configuring elastic search 5.2

### ISSUE THREAD

**Issue by Shwetakale** [circleci/circleci-docs#965]
steps are given [here](https://circleci.com/docs/1.0/installing-elasticsearch/) to configure custom version elastic search is nice but elastic search 5.2 depends on JVM 1.8 and by following only steps on above link is not sufficient for the latest version of elastic search.

Can we also add not about configuring JVM for the latest version in this doc? Let me know if that can be done I will send PR.

**Comment by key88sf** [comment]
👍

**Comment by ryanwohara** [comment]
This is solved on the 2.0 platform.
