### ISSUE TITLE
Deployment to GKE 1.6.0: kubectl falis

### ISSUE THREAD

**Issue by kolov** [circleci/circleci-docs#966]
I can't make `kubectl` work with a 1.6.0 cluster on GKE following instructions on <https://circleci.com/docs/1.0/continuous-deployment-with-google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-google-container-engine.md>)

`gcloud container clusters get-credentials` works, so the consequent `gcloud docker -- push ...` works too, after giving right permissions to the service account. The call to kubctl fails, here's what I get with different versions of gcloud comonents/kubectl:

--version 120.0.0
error: group map[authorization.k8s.io:0xc8203a0bd0 batch:0xc8203a0cb0 componentconfig:0xc8203a0d20 extensions:0xc8203a0d90 rbac.authorization.k8s.io:0xc8203a0e70 authentication.k8s.io:0xc8203a0f50 certificates.k8s.io:0xc8202fc230 :0xc8203a0af0 apps:0xc8203a0b60 autoscaling:0xc8203a0c40 policy:0xc8203a0e00 federation:0xc8203a0a80] is already registered

--version 146.0.0
error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

--version 150.0.0
Unable to connect to the server: error executing access token command "/opt/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exit status 1 output=

**Comment by zzak** [comment]
Hello @kolov,

Would you mind emailing support@circleci.com?

That would be the best place so that we can assist you in resolving your issue with `kubectl`.

Best, Zak

**Comment by kolov** [comment]
Thank you, I did.

**Comment by kolov** [comment]
The solution is posted in https://discuss.circleci.com/t/google-container-engine-deployment-fails/11690/9 It boils down to
