### ISSUE TITLE
Mention the need of export NODE_ENV

### ISSUE THREAD

**Issue by mironov** [circleci/circleci-docs#975]
This issue is about <https://circleci.com/docs/1.0/yarn/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/yarn.md>)

One of the notable differences when switching from `npm` to `yarn` is that the `NODE_ENV`environment variable is not set to `test` anymore.

Without override:
![image](https://cloud.githubusercontent.com/assets/20403/24955041/7b5d2178-1f8a-11e7-9cd7-5fa5ce24c9da.png)

With override:
![image](https://cloud.githubusercontent.com/assets/20403/24955049/894b58cc-1f8a-11e7-8746-a2ddbb210416.png)

That might cause issues in specs. I think we should mention that besides setting the `PATH` in `machine/environment`, people also need to set `NODE_ENV: test`.

**Comment by smart-alek** [comment]
Hey @mironov, thanks for the catch! We'll be sure to call that out in the docs. Thanks for letting us know! :)

**Comment by joshhepworth** [comment]
How should the NODE_ENV and PATH be set? I'm running into issues with this as well.

**Comment by JonathanKolnik** [comment]
Same here! Wondering what NODE_ENV and PATH should be set to.

**Comment by mironov** [comment]
@JonathanKolnik It should be
```yml
machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
    NODE_ENV: test
```

**Comment by JonathanKolnik** [comment]
Thanks for the speedy reply! Just to clarify though, since the example you posted is under machine and the screenshot is under dependencies is there any difference?
