### ISSUE TITLE
RE: jekyll/_docs/language-php.md

### ISSUE THREAD

**Issue by andyg5000** [circleci/circleci-docs#98]
The documentation specifies that the php conf.d is located at ` ~/.phpenv/versions/$(phpenv global)/etc/conf.d` 

In circle.yaml, I had to use `/opt/circleci/php/$(phpenv global)/etc/conf.d` because the documented path threw `bash: line 1: ~/.phpenv/versions/$(phpenv global)/etc/conf.d/timezone.ini: No such file or directory`

**Comment by levlaz** [comment]
@andyg5000 thank you for letting us know, can you confirm that you are using the new Trusty image? I believe that this is an issue with our image where we are installing things into /opt instead of home. (this is also true for node).

**Comment by andyg5000** [comment]
Yes I am using Ubuntu 14.04 (Trusty) build environment.
