### ISSUE TITLE
Dead link in Using Centralized Logging page

### ISSUE THREAD

**Issue by stutefish** [circleci/circleci-docs#986]
This issue is about <https://circleci.com/docs/enterprise/logging/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_ccie/logging.md>)

This page includes the advice: 

"The Services box uses Docker. You can customize tbe Docker daemon to route logs to your desired supported destination. For more details see [the Docker documentation on logging drivers](https://docs.docker.com/engine/reference/logging/overview/)."

This URL is not valid. 

It looks like this URL: 

https://docs.docker.com/engine/admin/logging/overview/

May be the correct page to reference.

**Comment by smart-alek** [comment]
@stutefish This is way overdue, but it looks like this was on Docker's end, and they've added a redirect to that link. It goes to https://docs.docker.com/config/containers/logging/configure/, but that (I think) is actually more specific.

Thanks for catching this! :)
