### ISSUE TITLE
Docs on 2.0 Images could use a little more detail

### ISSUE THREAD

**Issue by aviflax** [circleci/circleci-docs#995]
This issue is about <https://circleci.com/docs/2.0/circleci-images/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/circleci-images.md>)

Specifically, it’d be helpful to see a list of the packages that are available across the board, like git, Docker, etc. I found a list on [this page](https://hub.docker.com/r/circleci/ruby/) which was very helpful; it just seems to me this info belongs in the official and canonical docs page.

Thanks!

**Comment by keybits** [comment]
Thanks for your question. You can do this by creating a file in your project directory and defining the env vars there. Then define `BASH_ENV` as that file's name in config.yml.

More details in this thread: https://discuss.circleci.com/t/injecting-custom-environment-variables-when-running-locally-via-circleci-cli/11234

I've made a note to get this added to the docs.
